### ISSUE TITLE
Certain noteskins in invalid visual states

### ISSUE THREAD

**Issue by PCBoyGames** [TeamRizu/OutFox#1]
While I like having noteskins, certain ones appear to pass into other frames they shouldn't. I don't know why, and I can't quite capture a good split-second frame for a visual demonstration of this in dance mode, but it has bugged me since the latest alpha release. I'm sure someone in our Discord must have seen this and noted it. Can someone look into what causes this?

**Comment by JoseVarelaP** [comment]
In cases, it can be in situations as the texture coordinate, begins to overflow, or go into a invalid area, causing garbage data.

Tested on: THERMOMETHER, Stepfiles Made Horribly 5, Intel HD Graphics 4000, running in GLAD.

![imagen](https://user-images.githubusercontent.com/23246027/82769977-63ce3800-9dfc-11ea-86f3-58ce738b3cbd.png)

**Comment by Scraticus** [comment]
This is due to a texture overflow, which is when the renderer is set to textures at 2048, and the image scales incorrectly to match this. It is a bug, but for now you can fix it by setting your texture size in the graphics menu to 1024.

**Comment by JoseVarelaP** [comment]
The bug has been identified and it is being fixed. This occurs being the dimensions/aspect ratio of the physical screen, as the engine uses Display[Width/Height] and Window[Width/Height], and does improper calculations for defining said aspect ratio. This breaks math when defining a value to obtain said aspect ratio.

**Comment by Scraticus** [comment]
This is fixed as of Commit 74ed43
