### ISSUE TITLE
[BUG] Defaults to Original Judgment while in Advanced Timing

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#101]
**Please give System Info**

OS: *Windows 10 Pro 64-bit*
CPU: *Intel Core 2 Duo E7500 @ 2.93GHz*
GPU: *512MB NVIDIA GeForce 8400 GS*
Storage: *465GB Seagate ST3500413AS ATA Device*

**Please give your StepMania Info**

StepMania Version: *StepMania Outfox Final Alpha 4.8.3 (build 55e328118d)*
Theme: *SoundWaves*

**Describe the problem**
1. Start the game, set your Timing Window to Advanced
2. Go into Save/Preferences.ini
3. Add an invalid mod in ``DefaultModifiers``
4. Start the game and play any chart.
5. An Original Timing Judgment is selected 

**Describe what should happen**

The game should default to an Advanced Timing Judgment.

**Logs and Additional context**

[info.txt](https://github.com/TeamRizu/OutFox/files/5204399/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5204401/log.txt)
Video: https://youtu.be/qV6Gz_0aE5U
![image](https://user-images.githubusercontent.com/58047457/92796820-e5d07580-f387-11ea-977c-cd0fad8d6a11.png)

**Comment by Scraticus** [comment]
Is this still occuring?

**Comment by moruzerinho6** [comment]
Nope, seems to have been fixed.

**Comment by Scraticus** [comment]
Can you close then please?

Thanks for reporting.
