### ISSUE TITLE
[BUG] Changing window size manually doesn't change screen resolution

### ISSUE THREAD

**Issue by Emilovesdoubles** [TeamRizu/OutFox#102]
OS: Windows 7
CPU: i5-3570 
GPU: Nvidia GeForce GTX 1060 6GB
Storage: SSD (for OS files) HDD (for stepmania program) and 16GB RAM

Stepmania 5.3-git-09ae1e4e29 (2020 08 19)
Default Outfox theme

Maximizing the window leaves a lot of blank (black) space. Other versions of stepmania change resolution to match the size of the window when the size of the window is manually adjusted or maximized. 

... Additionally, if I change the settings from Options -> Display & Graphics -> Display and Resolution
So that it is full screen on one of my two monitors, I am unable to go back to windowed mode w/o restarting the client. I believe that

![bug outfox window screen](https://user-images.githubusercontent.com/71107022/92831295-d824eb00-f39b-11ea-9189-4e227c45016d.png)

**Comment by moruzerinho6** [comment]
> Maximizing the window leaves a lot of blank (black) space.

That's because the code to solve that isn't there yet.

> Other versions of stepmania change resolution to match the size of the window when the size of the window is manually adjusted or maximized.

Other version of StepMania are also not in Alpha

**Comment by Scraticus** [comment]
For now, i've removed the option to resize the window so this isn't an issue anymore.

When we get the rest of the RageDisplay code fixed, i'll add it back.
