### ISSUE TITLE
[BUG] Backgrounds not displayed in Beginner/Novice difficulty

### ISSUE THREAD

**Issue by SilentTempest83** [TeamRizu/OutFox#105]
**Please give System Info**

OS: Windows 10 Pro 64-bit

CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60Hz  2.30 GHz

GPU: Intel(R) HD Graphics Family

Storage: SSD | Crucial_CT525MX300SSD1

**Please give your StepMania Info**

StepMania Version: OutFox alpha 4.8.5
Theme: Soundwaves (alpha 4.8) / EKS-D ParaMania

**Describe the problem**

In alpha 4.8.5, backgrounds are not displayed on the Beginner/Novice difficulty, despite having the Beginner Helper option toggled off. The backgrounds are properly displayed on other difficulties on the same chart, but display solid black on Beginner/Novice.

**Describe what should happen**

Backgrounds should be displayed when a chart is loaded for Beginner/Novice difficulty.

**Logs and Additional context**

1. Go into the game folder
2. Open the Logs folder
3. Grab every file in there and post with the issue.
4. Go back to the game folder, if there's an crashinfo.txt then send it too.

[info.txt](https://github.com/TeamRizu/OutFox/files/5251042/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5251043/log.txt)

Add any other context or screenshots here.

**Comment by Scraticus** [comment]
Confirmed. Working on a fix now.

**Comment by Jousway** [comment]
fixed will be in next hf
