### ISSUE TITLE
[Nitpick] Hold/Roll Anchor Incorrect

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#106]
**Give an example of what is wrong**

This nitpick is about the default Outfox noteskins.

When scrolling downward, hold and roll bodies are anchored to the bottom (where the head is), instead of the top (where the rest of the hold is).

Tested and confirmed on `default`, `crystal`, `crystal4k`, and `Delta2019` (rolls only). `paw` did not have patterns on the hold or roll body, but I am assuming that the hold/roll anchor is also incorrect on it.

**Given an example of what it should look like**

![demonstration](https://user-images.githubusercontent.com/8707990/93708443-96edc180-fb79-11ea-84e0-3ad843133477.gif)

Left: How it should look like.

Right: How it looks.

I'm proud to tell you that this is the very first issue of mine that I actually know how to fix. This issue arises because the metric `[NoteDisplay] TopHoldAnchorWhenReverse` is set to 0, even though `FlipHeadAndTailWhenReverse` and `FlipHoldBodyWhenReverse` are set to 1. Adding that value to metrics.ini in `dance/[every default noteskin]` and `global/[every default noteskin]` should fix the issue without messing any noteskins in other modes.

**Comment by Jousway** [comment]
I do consider this a bug, so I fixed it, will be in next hf, thanks for your report
