### ISSUE TITLE
[BUG] Incorrect text encoding in loading window (Windows 10)

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#107]
**Please give System Info**

OS: Windows 10

CPU: *Type the CPU name here*

GPU: *Type the GPU name here*

Storage: HDD + SSD

**Please give your StepMania Info**

StepMania Version: 5.3-git-4f74b16121
Theme: SoundWaves

**Describe the problem**

The loading text is garbled in some languages. For example, here is the Japanese loading text:

![image](https://user-images.githubusercontent.com/8707990/93965875-840c0480-fda6-11ea-9bfb-a073ca5d0bfc.png)

According to a bit of detective work (by which I mean reading [the Wikipedia article for Mojibake](https://en.wikipedia.org/wiki/Mojibake), it seems that text stored in UTF-8 is incorrectly assumed to have been stored in Windows-1252, as evidenced by the string “è¾¼”, which is the letter 込 saved as UTF-8 and loaded as Windows-1252 (0xE8 = è, 0xBE = ¾, 0xBC = ¼).

I tried to confirm my assumption by changing the language to Polish, which has characters that are not the same between UTF-8 and Windows-1252. And sure enough, the “Ł” in “Ładowanie” was stored as UTF-8 and loaded as Windows-1252 (0xC5 = Å, 0x81 = invalid).

![image](https://user-images.githubusercontent.com/8707990/93966595-6cce1680-fda8-11ea-8651-4b1808f2eaf3.png)

**Describe what should happen**

Text should be loaded as a UTF-8 string, instead of a Windows-1252 one.

**Logs and Additional context**
Does not crash the game.

**Comment by Scraticus** [comment]
Fixed in 4.8.6 hopefully! will build a version you can test.
