### ISSUE TITLE
[BUG] Oops! All Downs™

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#108]
**Please give System Info**

OS: Windows 10

CPU: *Type the CPU name here*

GPU: *Type the GPU name here*

Storage: HDD + SSD

**Please give your StepMania Info**

StepMania Version: 5.3-git-4f74b16121
Theme: SoundWaves

**Describe the problem**

Some of my noteskins that work fine for 5.1 appear with all down arrows in 5.3.

![2020-09-23_144428](https://user-images.githubusercontent.com/8707990/93967918-a5bbba80-fdab-11ea-9dee-589995af9175.jpg)

Noteskin in screenshot is `composite4k`, but I've received a report of the same bug on `diva4k`. Both are downloadable through [here](https://2gd4.me/otoge/noteskin).

**Comment by MrThatKid** [comment]
So, I looked through the noteskin and I noticed it fell back onto the `default` noteskin.
The default noteskin changed between SM5.0/5.1 and 5.3, so I tried having it fall back onto `defaultsm5` (what we renamed the SM5.0 default noteskin to) instead, and that got rid of the all downs issue.

To try it yourself, make sure you've got the old SM5 noteskins installed, then edit composite4k's metrics to fall back on `defaultsm5` instead.

If it works, you can have it fall back on that as a quick solution, but in the long term, you may want to make sure your noteskin can work independently of the default noteskin. (Try having it fall back on `common` and work from there.)

**Comment by Jousway** [comment]
fixed in next release by changing the fallback default noteskin to the original sm5 default one resulting in fixing this issue
