### ISSUE TITLE
[Feature Request] Missing Korean character

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#109]
The character 렌 shows up as a ?.  It would be great to get this added to Outfox.  I found a stepchart for the song Siren by Sunmi, but the original Korean title 사이렌 does not work because of the missing character.

Thanks!

**Comment by JapanYoshi** [comment]
Lots of Hangul syllables seem to be missing in `Appearance/Themes/_fallback/Fonts/_korean 24px.ini`. There are 11,172 Hangul syllables in total [according to Wikipedia](https://en.wikipedia.org/wiki/Hangul_Syllables), but only 249 are defined in _korean.ini.

**Comment by Scraticus** [comment]
I have spent the last two days fixing up tje texture font generator and with @hanubeki's help have restored many of the missing korean glyphs.

i will take the time to redo all the fonts as they are woefully out of date, and missing a lot of glyphs that should be in the game.

This issue is fixed in 4.8.6 which will be out shortly. Thanks for reporting and giving me a kick up the backside to finally fix this issue.

**Comment by Scraticus** [comment]
This has been present in sm since 3.x days so its nice to finally be shot of it for now.

**Comment by AngledLuffa** [comment]
Thanks, that will be great!  Years back I made my own pack of glyphs which
could be added as a custom font - it's much easier to have it supported out
of the box

**Comment by Scraticus** [comment]
This is fixed in 4.8.6 and will be out around the middle of next week.

**Comment by AngledLuffa** [comment]
In terms of fonts that might be useful, I have what seems to be some Greek characters in one of my sims:

Ψηλά τακούνια
Κατερίνα τικούδη

If it's easy to add, can we get some or all of the Greek alphabet added as well?

**Comment by Scraticus** [comment]
Already done in 4.9.0 test them though, will be interesting to see.

**Comment by AngledLuffa** [comment]
Love it.  Should I wait and see, or do you have an early access build I can
look at?  Windows 10 if the answer is I can alpha test it.

**Comment by AngledLuffa** [comment]
Got another glyph request - thought piggybacking on an existing issue, even a closed one, would keep things simpler.

How about Armenian?

Թե աղջիկ լինեիր

https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=26514
