### ISSUE TITLE
Access Violation Crash (Alpha 5.3.0)

### ISSUE THREAD

**Issue by GMDParitionhlep** [TeamRizu/OutFox#11]
Log: [log.txt](https://github.com/TeamRizu/OutFox/files/4806949/log.txt)
Crash info: [crashinfo.txt](https://github.com/TeamRizu/OutFox/files/4806958/crashinfo.txt)

[CrashVideo.zip](https://github.com/TeamRizu/OutFox/files/4806966/CrashVideo.zip)
(Sorry for bad quality video and low framerate)

**Comment by GMDParitionhlep** [comment]
> Log: [log.txt](https://github.com/TeamRizu/OutFox/files/4806949/log.txt)
> Crash info: [crashinfo.txt](https://github.com/TeamRizu/OutFox/files/4806958/crashinfo.txt)
> 
> [CrashVideo.zip](https://github.com/TeamRizu/OutFox/files/4806966/CrashVideo.zip)
> (Sorry for bad quality video and low framerate)

**Comment by Scraticus** [comment]
i'm just looking into your logs now

**Comment by Scraticus** [comment]
why have you closed this?
