### ISSUE TITLE
[BUG] Version 4.8.2, file lock not released when song closed

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#110]
OS: Windows 10

**Please give your StepMania Info**

StepMania Version: 4.8.2
Theme: Default

**Describe the problem**

When editing a file with a video, if you stop editing the file, StepMania keeps a lock on the file.  You cannot delete the song folder or move it elsewhere.

**Describe what should happen**

I would like to be able to delete songs I don't like as soon as I try them out and realize I don't like them.

**Comment by Scraticus** [comment]
We'll investigate why files are not being unlocked and get back to you, thanks for the report.

**Comment by Scraticus** [comment]
can you confirm if this is resolved?

**Comment by AngledLuffa** [comment]
Yes!  Works great now.  Thanks
