### ISSUE TITLE
[Nitpick] Editor note colors are wrong

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#111]
This is true as of version 4.8.2, at least

16th notes are now green and 12ths purple in the default noteskin, right?  But if you edit a song and switch to 12th or 16th, the colors on the right and left side of the editor are not the same as the color of the step being placed.

**Comment by ListenerJubatus** [comment]
Fixed by #112 noteskin change.

**Comment by AngledLuffa** [comment]
A very clean 2 for 1!  Thanks for the quick response.
