### ISSUE TITLE
[Nitpick] 24th notes are unreadable

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#112]
Using the default theme, 12th notes are some kind of magenta / purple color, and 24th notes are the exact same shade.  It is really a challenge to read a 24th note snuck into a stream of 12th notes.  The editor shows a much darker purple color for 24th notes.  It would be great to use that color instead of the same magenta used for 12th notes.

Thanks!

**Comment by ListenerJubatus** [comment]
I am changing the default noteskin to use the "note" standard colors.
![Designer_TIaY3LOuBo](https://user-images.githubusercontent.com/6346433/94230951-a8f89880-fec8-11ea-8626-feb4eebd6e20.png)

**Comment by AngledLuffa** [comment]
Sounds great!  Thanks!
