### ISSUE TITLE
[Nitpick] foxchan avatar is not updated

### ISSUE THREAD

**Issue by Joehuu** [TeamRizu/OutFox#115]
**Give an example of what is wrong**

![image](https://user-images.githubusercontent.com/35318437/94350125-ff1c2780-ffff-11ea-911f-13591d8e8da3.png)

**Given an example of what it should look like**

![image](https://user-images.githubusercontent.com/35318437/94350096-a187db00-ffff-11ea-91c2-26c57ab3fad7.png)

**Comment by ListenerJubatus** [comment]
Narumi will be in the next alpha as an option.

**Comment by ListenerJubatus** [comment]
Done.
