### ISSUE TITLE
[BUG] NPS graph appears blank on slow Beginner charts

### ISSUE THREAD

**Issue by jummy0** [TeamRizu/OutFox#116]
**Please give System Info**

OS: Windows 10 Home v1903

CPU: Intel Core i7-7500U

GPU: Intel HD Graphics 620

Storage: 1TB HDD

**Please give your StepMania Info**

StepMania Version: OutFox 5.3 alpha 4.6.5
Theme: Soundwaves alpha 4.8

**Describe the problem**

The NPS (notes per second) graph appears blank (0 NPS) if the chart never has two notes in a second. This applies both in the song select as well as in-game.
 
**Describe what should happen**

The NPS should not be 0 when a note is present.

**Logs and Additional context**

[userlog.txt](https://github.com/TeamRizu/OutFox/files/5308573/userlog.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/5308574/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5308575/log.txt)
timelog.txt was empty.

Add any other context or screenshots here.

Blank NPS graph in song select:
![2020-09-30_171854](https://user-images.githubusercontent.com/4022196/94746826-3746a180-0343-11eb-9d74-7bacd25de656.jpg)

Blank NPS graph in-game:
![2020-09-30_171841](https://user-images.githubusercontent.com/4022196/94746886-56453380-0343-11eb-8858-e6c0f93495be.jpg)

**Comment by JoseVarelaP** [comment]
This is due to the NPS Graph rounding values, We could not perform that if there's the case that the chart overall is not dense at all (Maybe if the chart is less than 4 notes per second at peak).

**Comment by Scraticus** [comment]
Fixed in 4.9.x as we have decimal points on NPS now
