### ISSUE TITLE
[Feature Request] Precision Dance Pad config

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#117]
A Precision Dance Pad 4 panel pad has 6 buttons.  I mapped them using this string:

0300000009d200000115000000000000,Precision Dance Pad,platform:Windows,a:b3,b:b2,x:b4,y:b5,back:b0,start:b1,

My hope is this will be useful to someone else.

**Comment by Scraticus** [comment]
Thanks for the submission, I'll add it to our [database](https://github.com/TeamRizu/SDL_GameControllerDB/commit/610dc05ef7df982e8aab3e8499ef4a16d8319f02).
