### ISSUE TITLE
[BUG] ReverseDrawOrder does nothing

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#119]
**Please give System Info**

OS: Windows 10

CPU: Intel i7

GPU: Nvidia GeForce

Storage: SSD + HDD

**Please give your StepMania Info**

StepMania Version: 5.3 alpha 4.6.5
Theme: This bug is independent of theme

**Describe the problem**

The arrows appear in the incorrect order compared to DDR. Sooner notes appear OVER later notes on all 3 columns except Up, which draws later notes over sooner notes. (Note that this order is dependent on physical direction, not time.)

The metric ReverseDrawOrder, apparently doing nothing but contained in most noteskins, seems to have been a Boolean array that defines this behavior (i.e. it's 1101, 1 for sooner over later, 0 for later over sooner). 

**Describe what should happen**

I don't recommend that ReverseDrawOrder be revived. In the interest of supporting non-4-column game modes, I think it should be defined as a separate metric or something inside a Lua file.

**Logs and Additional context**

This bug happens any time on Dance mode.

**Comment by Jousway** [comment]
ReverseDrawOrder was something the SSC was planning to implement over 8 years ago, but never did

**Comment by Jousway** [comment]
also we have had contact with the japanese comunity about this https://sm.waiei.net/other/oboegaki.html#faq1_arrow and have implemented the way it should be for ddr, we even have a list of how it should look for multiple gametypes

**Comment by Scraticus** [comment]
We will add a metric for draw order, that's already planned in the roadmap.
