### ISSUE TITLE
[Nitpick] Curly apostrophes in song title show up as “を"

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#123]
**Give an example of what is wrong**

![2020-10-07_210944](https://user-images.githubusercontent.com/8707990/95330183-1fdb5b80-08e3-11eb-83cc-ac3f57973247.jpg)
“3y3s (ver. Shufflin’)” shows up as “3y3s (ver. Shufflinを)”. This appears to be an unfortunate result of the very much welcome new Unicode support.

**Comment by JapanYoshi** [comment]
By “curly apostrophes”, I mean the Unicode apostrophe as opposed to the straight ASCII apostrophe. cf. [U+2019 right single quotation mark on Graphemica](https://graphemica.com/%E2%80%99)

Also, what should be an ellipsis is appearing as ゅ. I think it's meant to be [U+2026 horizontal ellipsis](https://graphemica.com/%E2%80%A6). (プロファイル保存中…)
![2020-10-07_213028](https://user-images.githubusercontent.com/8707990/95331264-b3615c00-08e4-11eb-93f6-9d761a104cc6.jpg)

**Comment by hanubeki** [comment]
U+2019 (’) is 0x92 in cp1252, を is U+3092 which matches lower 8-bit.
So it is might be TFG, Font ini or charmap issue.

**Comment by Scraticus** [comment]
Fixed in Texture Font Generator, and OutFox, (And 5.1, 5.0, SM4, 3.95} but who's counting ;)

**Comment by Scraticus** [comment]
[9a96806](https://github.com/TeamRizu/Texture-Font-Generator-2020-Squirrel/commit/9a96806238727642f9c02a57dec8444b7c453644)
