### ISSUE TITLE
[Nitpick] Option names jump between uppercase and lowercase

### ISSUE THREAD

**Issue by JustMoNeko** [TeamRizu/OutFox#124]
StepMania Version: 5.3 A4.9HF
Theme: Soundwaves

**Describe the problem**

After changing settings Display Mode in Display and Resolution, the names of "ASPECT RATIO" "DISPLAY RESOLUTION" and "REFRESH RATE" are displayed in lowercase. 

Normal:
![StepMania Screenshot 2020 10 07 - 15 30 01 60](https://user-images.githubusercontent.com/63615036/95338364-2225c180-08b3-11eb-9598-17110f7d7874.png)

After changing the setting:
![StepMania Screenshot 2020 10 07 - 15 29 37 38](https://user-images.githubusercontent.com/63615036/95338358-205bfe00-08b3-11eb-94f0-7afb0faf7e23.png)

This also happens when selecting timing windows before gameplay:

![StepMania Screenshot 2020 10 07 - 15 31 09 10](https://user-images.githubusercontent.com/63615036/95338368-22be5800-08b3-11eb-9017-9979add26a52.png)

**Describe what should happen**

Option names should stay uppercase.

**Comment by JoseVarelaP** [comment]
Fixed it, required to update `uppercase` so now it can perform an actual uppercase.
