### ISSUE TITLE
[Game Crash] during editing steps

### ISSUE THREAD

**Issue by JavaJeremy** [TeamRizu/OutFox#125]
_1. What you were doing before it crashed and what action made the game to crash._
I was editing simfile steps. 
The crashes do not happen at any specific action, but I only noticed them while editing steps. 
They happened during scrolling through the steps, playing the song back, saving, etc.
_2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)_
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5343432/crashinfo.txt)
_3. Upload the info.txt and log.txt (GameFolder/Logs)_
[info.txt](https://github.com/TeamRizu/OutFox/files/5343441/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5343442/log.txt)

**Explain how we can reproduce the error**

1. Start the game
2. Go to screen 'Edit/Share -> Edit Songs/Steps -> Edit Existing'
3. Start editing steps and after a few minutes
4. Game crashed (every time)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5343434/crashinfo.txt)

**Sreenshots/Videos**
Sorry for the low resolution, but GitHub has a limit of around 10Mb.
The crash happens at about 5min 17sec.
[Crash_low_res.zip](https://github.com/TeamRizu/OutFox/files/5343598/Crash_low_res.zip)

If you recognize this as a "true bug", please give me a "Bug Hunter Achievement" in your Discord, I'm "gogoLgnjry" :wink:

**Comment by Jousway** [comment]
does this also happen for files with no video?, it might be ffmpeg acting up

**Comment by JavaJeremy** [comment]
I removed the video and edited the simfile for over half an hour without any crashes just now.
So I think you're right - it seems to be related to the video.

**Comment by Scraticus** [comment]
Hiya Jeremy, did you try a newer build to see if this problem remains?

**Comment by Scraticus** [comment]
Please open a new issue if this problem remains, but I think it's been fixed since this time. Thanks for reporting!
