### ISSUE TITLE
[BUG] ScreenSelectMusic wheel doesn't remember which edit chart was chosen

### ISSUE THREAD

**Issue by MrThatKid** [TeamRizu/OutFox#128]
**Please give System Info**

OS: Ubuntu 18.04.1, 64-bit

CPU: Intel i7-4770T

GPU: nVidia GeForce GTX 750 Ti

Storage: Samsung SSD 850

**Please give your StepMania Info**

StepMania Version: StepMana 5.3 alpha 4.9.0
Theme: default

**Describe the problem**

When playing on an edit chart of a simfile that has multiple edit charts, the music wheel doesn't remember which chart was selected, and moves you back to the first edit chart.

This also happens on upstream StepMania. I tested with the SM5.1 default and legacy 5.0 default theme.

Here's how to reproduce:
1. Create a simfile file (or edit a pre-existing one), and create more than one edit chart.
2. For each edit chart, give it a distinct name (and difficulty/description/chart artist, optionally)
3. Go to the music wheel and go into gameplay with any edit chart that isn't the first one.
4. Go back to the music wheel and notice that you're back to the first edit chart listed.

**Describe what should happen**

The wheel should remember which edit chart was chosen and one shouldn't have to re-select the chart.

Here's a video that demonstrates the issue: [wheelreset.webm](https://cdn.discordapp.com/attachments/684883542303571973/765755911120748574/wheelreset.webm)

**Comment by Jousway** [comment]
tested and confirmed fixed by mr thatkid, will be in next release
