### ISSUE TITLE
[BUG] Banner videos are not played back in original speed (too quickly) 

### ISSUE THREAD

**Issue by JavaJeremy** [TeamRizu/OutFox#129]
OS: Win10
CPU: AMD Ryzen 5 1600 Six-Core Processor 3.20 GHz
GPU: GeForce GTX 1050 Ti
Storage: Seagate ST2000DM006 HDD Barracuda

StepMania Version: 5.3 (20201007)
Theme: Default

Videos in the banner are played back too fast.
Here's an example simfile you should be able to reproduce it with:
https://zenius-i-vanisher.com/v5.2/download.php?type=ddrsimfilecustom&simfileid=43035

Videos in the banner should be played back in their original tempo, as they were often carefully synced to the preview music.

Here's a direct side by side video of Stepmania 5.1 and 5.3 showing the difference, it works in 5.1.
[Fast banner video playback.zip](https://github.com/TeamRizu/OutFox/files/5388252/Fast.banner.video.playback.zip)

**Comment by Jousway** [comment]
this was an issue with the sprite and screen update calling the decoder too many times, fixed it by adding a ragetimer inside of ffmpeg, fix in next release

**Comment by JavaJeremy** [comment]
Awesome, thanks! 👍 Can't wait for the next release then 🎉
