### ISSUE TITLE
ScreenTextEntry does not respect caps lock

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#13]
**What you're using**

Having Caps Lock enabled or disable does not change the input to upperCase. Using Shift does.

**Expected behavior**

Having Caps Lock enabled should upperCase the input.

**How to reproduce**

1. Go to **Options**
2. Select **Profiles**
3. Select **Create Profile**
4. Enabled Caps Lock and type something.
5. The input is not in uppercase.

Version: StepMania 5.3 Outfox Alpha date-20200619

**Comment by JoseVarelaP** [comment]
A fix has been created and it will be tested. Until there's confirmation, the issue will remain open.

**Comment by JoseVarelaP** [comment]
The engine now supports the key on commit 4fd4cc.
