### ISSUE TITLE
[Game Crash] GAME CRASH

### ISSUE THREAD

**Issue by nikonikokunStepmania** [TeamRizu/OutFox#132]
**Describe how it crashed by giving us those informations:**
Konnichiwa from Japan! I use Deepl translation as I can barely speak English, so please forgive me if my English isn't right:(

1. Staht THe game and crash
[log.txt](https://github.com/TeamRizu/OutFox/files/5432430/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/5432431/info.txt)

3. Upload the info.txt and log.txt (GameFolder/Logs)

1. Start the game

2. Game crashed

**Sreenshots/Videos**

If possible, take screenshots or record the crash happening.

**Additional information**

If there's any information that you think would help us.

**Comment by Scraticus** [comment]
こんにちは！
_Hello!_

ゲームをバージョン4.9.0に更新します
_Update the game to 4.9.0_

GPU用のより良いOpenGLドライバーを確認してください
_Check for an updated GPU Driver for your OpenGL_

4.9.0ではプレイできます
_Alpha 4.9.0 should allow you to play_

あなたはここでアップデートを見つけることができます https://github.com/TeamRizu/OutFox/releases
_You can find the update here_

さらにサポートが必要な場合はお知らせください
_Let me know if you need more help_

頑張って!
_Good Luck!_

**Comment by Scraticus** [comment]
closing as been longer than 3 months and it seems the user's problem was solved
