### ISSUE TITLE
[BUG] [pump] [upstream] Holds combo not counting as perfects/flawless

### ISSUE THREAD

**Issue by SHRMP0** [TeamRizu/OutFox#133]
**What you're using**
If you play a chart with combos during holds (example: https://www.youtube.com/watch?v=i5ZaI9QAacs) the stats panel and results screen looks like this on OutFox:
![2020-10-25_180320](https://user-images.githubusercontent.com/61925574/97119175-2ba18d00-16ed-11eb-89a7-a91b13f0bb7e.jpg)

**Expected behavior**
It should look like this:
![Captura de tela 2020-10-25 175718](https://user-images.githubusercontent.com/61925574/97119160-13ca0900-16ed-11eb-9053-4767ae35e373.png)

**Comment by Jousway** [comment]
https://github.com/stepmania/stepmania/issues/1089 pretty old bug

**Comment by SHRMP0** [comment]
[stepmania/stepmania#102](https://github.com/stepmania/stepmania/issues/102) and [stepmania/stepmania#1975](https://github.com/stepmania/stepmania/issues/1975) are also related to this.

**Comment by SHRMP0** [comment]
Bumping, as requested by @Scraticus

**Comment by Scraticus** [comment]
fixed in 4.15.. finally
