### ISSUE TITLE
A notefield issue from Alpha 4.5.9

### ISSUE THREAD

**Issue by TacvicomGN** [TeamRizu/OutFox#14]
Good night.

Here, we were using the Alpha 4.5.9 version (dated June 15, 2020. Because the administrator was unable to install the 4.6.1, acts like the installer is broken, even downloading various times from the website), and the issue for this case is the following:

We were testing a theme (StepMania Tacvicom Edition v4.0, not finished yet but is perfectly stable in SM 5.1 Beta 2 at its current state) in this current alive laptop, and we found the step field don't show any steps, noteskins, and judgment labels in the How to Play and Demonstration screens (but they appear successfully in the normal gameplay screen).

This current alive laptop use (Acer Aspire 5050 4697):
- AMD Turion 64 (2.20 GHz, 512 Kb L2 cache).
- ATI Radeon Express 1100 using v8.539.100 driver.
- 1 Gb of RAM memory.
- Windows 7 Ultimate SP1.

Thanks!!!

**Comment by Jousway** [comment]
just fixed this, it will be fixed  on next release, thanks for your report

**Comment by Scraticus** [comment]
Fixed as of 4.6.0-RC2
