### ISSUE TITLE
[Nitpick] Mouse cursor show up in fullscreen

### ISSUE THREAD

**Issue by axu2** [TeamRizu/OutFox#141]
When I start up OutFox, the mouse cursor stays on the screen, unlike in 5.0.12

This is a little annoying to move to the side, since the mouse isn't needed, and wanted to put this in as a feature request.

**Comment by moruzerinho6** [comment]
Options > Experimental Options > Show Mouse Cursor

just select disable.

**Comment by axu2** [comment]
Ah, OK, must have missed that!
