### ISSUE TITLE
[Feature Request] Add lua-based volume control

### ISSUE THREAD

**Issue by 48productions** [TeamRizu/OutFox#149]
**Is your feature request related to a problem? Please describe.**

Recently on the Moondance discord, [solsang suggested a feature](https://discord.com/channels/422897054386225173/439809793964769291/772114594395062275) to reduce the volume of the game when not actively playing a song.

There's multiple ways this could be implemented, but my suggestion would be to allow themes to change the game/song volume via Lua. This allows for themes that, for example, dim music previews when in select music, a la *(iirc)* jubeat, or behavior closer to solsang's original suggestion.

---

**Describe the solution you'd like**

Currently, `DimMusic()` can be used to temporarily lower the volume of whatever music is currently playing via `SOUND`, but it only accepts arguments for volume and duration.

I'm suggesting adding additional functions to allow for more freedom with volume control in theming. This could take the form of:
- Expanded/alternate versions of `DimMusic()` with different arguments for controlling music played via `SOUND` (no duration argument for permanent volume changes, fade length control/disabling, etc)
- Directly setting or fading the game's master/attract volumes via Lua (if this isn't already possible) for controlling both music and sound volumes.

---

**Describe alternatives you've considered**

solsang's original suggestion is worth mentioning here as well - they were suggesting some kind of "Theme/Menu" volume option, assumingly alongside the existing master/attract mode volume settings to be used when not playing a song.

---

**Additional context**

[Link to the discussion on the moondance server](https://discord.com/channels/422897054386225173/439809793964769291/772114594395062275)

**Comment by Jousway** [comment]
added in 4.9.5
