### ISSUE TITLE
TNS_PRO_W$ and TNS_W$ seem to be swapped in Options>HideNote Judgement

### ISSUE THREAD

**Issue by EscapeNumber001** [TeamRizu/OutFox#15]
**What you're using**

I switched the HideNote Judgement option to "TNS_W3" and none of the arrows disappeared, even when hit with a Fantastic judgement. I looked in Save>Preferences.ini and found that the HideNote option in the .ini read "TNS_PRO_W3" while the game said "TNS_W3".

**Expected behavior**

The timing was intended to make the note disappear after attaining a Great judgement.

**Comment by JoseVarelaP** [comment]
Dealt with this issue since 4.9.7. Forgot that we didn't close this issue.
