### ISSUE TITLE
[Nitpick] "Exit" button on "Config Key/Joy Mappings" makes a louder noise than usual.

### ISSUE THREAD

**Issue by AppleArcade120** [TeamRizu/OutFox#150]
**Give an example of what is wrong**
When you hit the "Exit" button there, the normal back sound plays, but louder than usual. This is the only place where this happens, and this also happens on previous builds of SM5 and I think it's time for that to change. Make the sound the normal volume again!

**Comment by JoseVarelaP** [comment]
Fixed.

Turns out the sound is played twice as the Exit action has another PlayStartSound, while all actions already play a StartSound when they're called.
