### ISSUE TITLE
[Game Crash] Game crashes when in fullscreen

### ISSUE THREAD

**Issue by TheFireRed** [TeamRizu/OutFox#152]
This issue might be related with my hardware. Tested on another computer and found no problems.

The game crashes everytime I try to switch to fullscreen mode (ALT-TAB) or apply new graphics settings. The only way to get it working again is by modifying or deleting the Preferences.ini file.

I looked into the crash reason (waveOutGetPosition failed) and tried [this workaround](https://github.com/stepmania/stepmania/issues/1104#issuecomment-219252067) with no luck. Using latest Intel drivers too. Hope you guys can cast some light into this!

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5497829/crashinfo.txt)

**Comment by Scraticus** [comment]
can you try switching the renderer to glad? 

And can you post the log.txt, as i need to see what's going on here

**Comment by TheFireRed** [comment]
Sure thing! Switched to glad and here's what came out:
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5541467/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5541468/log.txt)

**Comment by Scraticus** [comment]
Hiya!

This unfortuanately looks like the intel driver issue raising it's head to mess with us again.

Are there any other drivers available for your chip? can you let me know what's in your system?

sorry for all the questions!

**Comment by TheFireRed** [comment]
No problem at all! I'm more than happy to be of help. 😄 

Unfortunately I don't think it has any other drivers. I can try to find old drivers for it though, if that could help somehow.

The machine itself is a [Chuwi Larkbox](https://www.chuwi.com/product/items/Chuwi-LarkBox/specs.html) with a Celeron J4115, 6GB RAM and UHD Graphics 600. Here's a DxDiag and CPU-Z report for reference. 

[DxDiag.txt](https://github.com/TeamRizu/OutFox/files/5541983/DxDiag.txt)
[CPU-Z Larkbox.txt](https://github.com/TeamRizu/OutFox/files/5541984/CPU-Z.Larkbox.txt)

Let me know if you need anything. And thanks so much for taking the time! 😃

**Comment by Scraticus** [comment]
There is an alpha driver for this card, it seems to be having problems deciding what GL version to access.

https://downloadcenter.intel.com/download/29996/Intel-Graphics-BETA-Windows-10-DCH-Drivers?product=126787

can you try this one? it is definitely an Intel Issue here, but can you alt+enter a few times as well? just to see (no alt-tab)

Many thanks

**Comment by TheFireRed** [comment]
Tried it and still crashes. Here's the crashinfo!
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5547399/crashinfo.txt)

I'm guessing there's nothing we can do until Intel fixes this issue, right?

**Comment by Scraticus** [comment]
This, could also be a sounddriver issue, I note your sound card appears to be through the HDMI?

could you post a pic of your device manager, with the 'sound video and game controllers' bit expanded?

It seems your card is running in emulation mode, so StepMania cannot get direct access.

Thanks

**Comment by TheFireRed** [comment]
Sorry for the late response! Yes, it's currently using this "Intel Sound for Displays" driver.

![screenshot](https://user-images.githubusercontent.com/9060830/99871468-327fca80-2bdb-11eb-8f84-e6f8d3c3ccac.png)

**Comment by Scraticus** [comment]
The game just isn't seeing a sound driver it things it can use. I'll have a think on what to do in this regard. I will update shortly.

**Comment by Scraticus** [comment]
Closing as no response for a while, ping us if you need help still

**Comment by TheFireRed** [comment]
Sorry for the late response!

I kid you not, my Chuwi Larkbox outright died days after this and I couldn't keep testing this. After a long battle with the "splendid" after-sale service, I replaced it with a Chuwi Larkbox Pro, which is essentially the same machine but with a slightly more powerful CPU.

The crash is still present. However... I disabled the HDMI audio driver (Intel Sound for Displays) and used its 3.5mm audio output (Realtek High Definition audio). And it worked fine! So something happens when it tries to switch to fullscreen.

**Comment by charredchar** [comment]
I actually have a very similar issue with a very similar Intel NUC that I use as a Home theater PC. Unfortunately I can't just change the audio device since my sound system uses HDMI.
I'd be happy to continue troubleshooting, though, as I tested a little with a maximized window and it runs fine otherwise. It just crashes when I enter Fullscreen Mode.

**Comment by Scraticus** [comment]
This is fixed, you can set your SOUNDDRIVERS= to portaudio or rtaudio and use one of the more saner systems hehe
