### ISSUE TITLE
[BUG] Some modfiles have effects that don't clear after the song ends.

### ISSUE THREAD

**Issue by MrThatKid** [TeamRizu/OutFox#156]
**What you're using**

This was on Outfox alpha 4.9.1

**Expected behavior**

While we were doing a stream on the raspberry pi, we found that some files don't properly set the modifiers, and it makes odd effects that persist beyond the file that set it.
One would expect that it would not persist between songs.
We need to see what files do this and why.

**Comment by ListenerJubatus** [comment]
Suspecting it might have something to do with ApplyGameCommand.

**Comment by Scraticus** [comment]
Fixed in 4.16
