### ISSUE TITLE
[BUG] Bad Banner PNG causes error that cannot be escaped from

### ISSUE THREAD

**Issue by NekoIncardine** [TeamRizu/OutFox#157]
**Please give System Info**

OS: Windows 10

CPU: Intel Core i7-8700

GPU: Nvidia GTX 1080

Storage: Stepmania running on 512GB SSD; song accessed from 1TB traditional drive

**Please give your StepMania Info**

StepMania Version: StepMania 5.3 Alpha 4.9.1 
Theme: Default

**Describe the problem**

While playing in fullscreen, when a song has a bad banner file (the example I ran into this with was "How Much Is The Fish" from DDRei Tournamix 4 - which I recall causing similar issues back in 2003), the error message that appears can be clicked on the first time the error appears on the song select menu. If you then select and clear the song, the error message becomes unclickable - attempting to click on it causes the Stepmania window to minimize, no keyboard input is accepted, and clicking outside the error message gives the standard Windows erroneous-click noise.

When the screen is minimized, I can still operate the computer normally outside of Stepmania - but clicking back into it produces the same results.

**Describe what should happen**

The error should be able to be closed if it crops up a second time, to allow gameplay to continue.

**Logs and Additional context**

1. Go into the game folder
2. Open the Logs folder
3. Grab every file in there and post with the issue.
4. Go back to the game folder, if there's an crashinfo.txt then send it too.

[info.txt](https://github.com/TeamRizu/OutFox/files/5504437/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5504438/log.txt)
(Timelog was empty)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/5504439/userlog.txt)

The error-causing BN file:
![How Much Is the Fish BN](https://user-images.githubusercontent.com/69831665/98434697-87213280-207e-11eb-843c-8e9253a45d59.png)

The error screen that occurred:
![InescapableError](https://user-images.githubusercontent.com/69831665/98434701-8e484080-207e-11eb-8c13-0157f66f7a3c.png)

**Comment by Scraticus** [comment]
This is a valid point - it should be posting the error into user or info.txt. Will get that sorted, as this is silly for cabs.

Thanks for the report!

**Comment by Scraticus** [comment]
This is now fixed. Any bad textures will generate a 'dummy' texture, and report itself to the Info.txt log, so you can address them / fix them.

It will be released in the 4.9.2 build. Many thanks for reporting this.
