### ISSUE TITLE
[BUG] Endless mode not auto generating courses

### ISSUE THREAD

**Issue by ListenerJubatus** [TeamRizu/OutFox#159]
On previous versions of StepMania, the Endless mode contains autogenned courses from the groups in the user's song library. On 5.3 however, it does not seem to be doing this, even if the autogen courses option is on. Behaviour is not theme-specific (confirmed in both Soundwaves and 5.0 legacy theme).

5.3 behaviour:
![StepMania_Kro6bpoeYW](https://user-images.githubusercontent.com/6346433/98468893-24c15280-21a2-11eb-9e9c-95cea9aeb77a.png)

Expected behaviour (5.1):
![StepMania_QRk6TPXSTh](https://user-images.githubusercontent.com/6346433/98468965-7bc72780-21a2-11eb-8504-d4208c0d665e.png)

**Comment by Jousway** [comment]
https://github.com/stepmania/stepmania/commits/5_1-new/src/Course.cpp endless not working was an upstream bug we inhered when we pulled from 5.1-new 2 years ago, seems like it only got fixed in jun on 5.1-new, I fixed it just now, will be in next release
