### ISSUE TITLE
Random song selection in courses is not returning 4 random songs

### ISSUE THREAD

**Issue by selrahc13** [TeamRizu/OutFox#16]
Using https://objects-us-east-1.dream.io/outfox/Windows/StepMania-5.3-Outfox-Alpha-4.6RC2-date-20200623.exe release

Using Fitness Mode, extended on default Outfox theme

I expect 4 random songs to be selected; instead, Outfox is alternating between the same 2 songs
I also created a workout playlist with 20 random songs from a specific group and the results were the same

![Nonrandom 1](https://user-images.githubusercontent.com/1953955/85906724-326ed080-b7dd-11ea-9e21-d8653f7fc728.png)
![Nonrandom2](https://user-images.githubusercontent.com/1953955/85906726-339ffd80-b7dd-11ea-9dd9-5306e0d55087.png)
![Nonrandom3](https://user-images.githubusercontent.com/1953955/85906728-339ffd80-b7dd-11ea-9939-2e9e5c8ab38f.png)

**Comment by selrahc13** [comment]
Example course I tested with, same result:

#COURSE:Workout;
#METER:Regular:4;

#SONG:The Starter Pack of Stamina/*:2:nodifficult;
#SONG:The Starter Pack of Stamina/*:3:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:5:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:3:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:5:nodifficult;
#SONG:The Starter Pack of Stamina/*:6:nodifficult;
#SONG:The Starter Pack of Stamina/*:5:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:3:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:5:nodifficult;
#SONG:The Starter Pack of Stamina/*:6:nodifficult;
#SONG:The Starter Pack of Stamina/*:7:nodifficult;
#SONG:The Starter Pack of Stamina/*:6:nodifficult;
#SONG:The Starter Pack of Stamina/*:5:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:3:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:5:nodifficult;
#SONG:The Starter Pack of Stamina/*:6:nodifficult;
#SONG:The Starter Pack of Stamina/*:5:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:3:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:5:nodifficult;
#SONG:The Starter Pack of Stamina/*:4:nodifficult;
#SONG:The Starter Pack of Stamina/*:3:nodifficult;
#SONG:The Starter Pack of Stamina/*:2:nodifficult;

**Comment by Scraticus** [comment]
This is a weird one! we'll look into what's causing this and get back to you, apologies it's broken your working course

**Comment by selrahc13** [comment]
In the meantime I put every song into my course by hand instead of using the wildcard selector, but I'm definitely looking forward to random not being broken. Thank you!

**Comment by MrThatKid** [comment]
I've made a fix for this, so 4.8.3 should have working random courses again!
