### ISSUE TITLE
[Unexpected Behavior] Editing detailed stats for the first time has wrong default settings highlighted

### ISSUE THREAD

**Issue by Joehuu** [TeamRizu/OutFox#160]
**What you're using**

Default theme:
`Options` -> `Profiles` -> pick a new profile -> `Edit` -> `Edit Detailed Stats`

Saving at this state (i.e. pressing exit) will actually turn these settings off.

![StepMania_P6cydlE82F](https://user-images.githubusercontent.com/35318437/98627536-508b2800-22c9-11eb-8516-d138a7f38152.png)

**Expected behavior**

![StepMania_uWoHQgd2n5](https://user-images.githubusercontent.com/35318437/98627611-76183180-22c9-11eb-986f-bdc99ba4707c.png)

**Comment by JoseVarelaP** [comment]
Oh, yeah, I see what is happening, I'll head on to fix this.

**Comment by JoseVarelaP** [comment]
Fixed on 4.9.9.
