### ISSUE TITLE
game crash:It won't start up.

### ISSUE THREAD

**Issue by Logobot757** [TeamRizu/OutFox#162]

**Comment by Logobot757** [comment]
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5532417/crashinfo.txt)
As soon as I move my songs from old SM, the game literally will not boot up.

**Comment by Scraticus** [comment]
can you provide the log.txt from the folder so I can work out which song is killing it?

many thanks

**Comment by Logobot757** [comment]
[log.txt](https://github.com/TeamRizu/OutFox/files/5605550/log.txt)

**Comment by Scraticus** [comment]
Set your graphics renderer to ``opengl``
``Videorenderer=opengl``
in Preference.ini

You also need to update your Video driver to get the best experience out of the game, as we don't fall back to direct3d anymore.

**Comment by Scraticus** [comment]
Closing this as it's past 3 months old
