### ISSUE TITLE
[Nitpick] Smooth lines are not smooth

### ISSUE THREAD

**Issue by natano** [TeamRizu/OutFox#164]
**Please give System Info**

OS: Linux Mint 20

CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz

GPU: Intel Corporation HD Graphics 620 (rev 02)

Storage: Some SSD

**Please give your StepMania Info**

StepMania Version: 5.3 alpha 4.9.1
Theme: Simply Love ([wip-outfox branch](https://github.com/Simply-Love/Simply-Love-SM5/tree/wip-outfox))

**Describe the problem**

With the latest release smooth lines don't have the rounded corners as they have in SM 5.1. As a matter of fact there are strange rendering artifacts at the corners between segments. On discord Squirrel pointed out the UsePointsandBlending option to me. When enabling that (and disabling smooth lines) the results look very promising. Maybe this could replace the smooth lines option?

**Describe what should happen**

Lines should have smooth corners when the smooth lines option is enabled in the graphics settings.

**Logs and Additional context**

SM 5.1-b2 with smooth lines
![lifeline-sm51-smoothlines](https://user-images.githubusercontent.com/27127/99150854-a419bf00-2697-11eb-836c-4245e5ca1bc7.png)

SM 5.3 with smooth lines
![lifeline-sm53-smoothlines](https://user-images.githubusercontent.com/27127/99150863-b5fb6200-2697-11eb-9ad9-b48c1885092c.png)

SM 5.3 w/out smooth lines
![lifeline-sm53-nosmoothlines](https://user-images.githubusercontent.com/27127/99150855-a4b25580-2697-11eb-8f1b-735e137932cc.png)

SM 5.3 w/out smooth lines, but UsePointsandBlending enabled
![lifeline-sm53-nosmoothlines-usepointsandblending](https://user-images.githubusercontent.com/27127/99150856-a54aec00-2697-11eb-9d12-a6734f2123b8.png)

Logs:
[info.txt](https://github.com/TeamRizu/OutFox/files/5541012/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5541013/log.txt)

**Comment by Scraticus** [comment]
Changed so smoothlines are off, and blending/points are enabled.

Will be active in 4.9.2

**Comment by natano** [comment]
I just wanted to verify that this now works as expected with alpha 4.9.5, but unfortunately I ran into another issue with line rendering: The line width doesn't seem to be applied correctly.

SM 5.3 alpha 4.9.5
![lifeline-SM5 3](https://user-images.githubusercontent.com/27127/100797141-ee35cb00-3421-11eb-87e0-e34eac88de4b.png)

SM 5.1 for reference
![lifeline-SM5 1](https://user-images.githubusercontent.com/27127/100797120-e7a75380-3421-11eb-8bf7-fe2367aaf0da.png)

SL sets the lifeline width to 2.

This issue is probably related to the smooth lines changes, that's why I comment here. Let me know in case you want a separate bug report for this.

**Comment by natano** [comment]
fixed in 4.9.7
