### ISSUE TITLE
[Nitpick] Default texture size

### ISSUE THREAD

**Issue by natano** [TeamRizu/OutFox#166]
**Give an example of what is wrong**

Outfox reduced the default texture size from 2048 to 1024. This causes an issue in the SL theme: The edges of the hearts in the background look fuzzy and pixelated with 1024.

SM 5.3 with default texture size 1024:
![Screenshot from 2020-11-12 19-05-37](https://user-images.githubusercontent.com/27127/99154001-b3efce00-26ac-11eb-82b0-9c48a695f70f.png)

**Given an example of what it should look like**

I'd prefer the default texture size to be 2048 (like in SM 5.1). That way users get crisp graphics by default, but can reduce quality if it is necessary due to hardware reasons.

SM 5.1 with default texture size 2048:
![Screenshot from 2020-11-12 19-03-22](https://user-images.githubusercontent.com/27127/99154000-b2bea100-26ac-11eb-8788-37b00de8e7c1.png)

**Comment by Scraticus** [comment]
'Adjusted' in 4.9.2. I will have to add a note for people on older hardware to adjust it back down.

**Comment by natano** [comment]
Is the adjustment included in alpha 4.9.5? The texture resolution is 1024 when starting SM after removing `~/.stepmania-5.3/`.

**Comment by JoseVarelaP** [comment]
The adjustment is included. We're defaulting at 2048.

**Comment by natano** [comment]
![Screenshot from 2020-12-01 21-24-15](https://user-images.githubusercontent.com/27127/100794084-63eb6800-341d-11eb-825a-1af15493299f.png)
(with a fresh install of alpha 4.9.5)

**Comment by natano** [comment]
With alpha 4.9.6 on Linux I still get 1024 as the default (see screenshot).
![Screenshot from 2021-01-13 16-50-21](https://user-images.githubusercontent.com/27127/104475636-9d3bf980-55bf-11eb-8760-c9c9793f1675.png)
(started after deleting ~/.stepmania-5.3)

I remember there being some discussion on the outfox discord about there being two places where a default is set for the texture resolution. I guess one of them is still set to 1024 instead of 2048?

**Comment by Scraticus** [comment]
This has been fixed in 4.9.7.
