### ISSUE TITLE
[Game Crash] Was doing a jump on a d-force pad

### ISSUE THREAD

**Issue by auzdavines** [TeamRizu/OutFox#171]
**Describe how it crashed by giving us those informations:**

1. What you were doing before it crashed and what action made the game to crash.
Doing a jump on a d-force pad

2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5556850/log.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5556853/crashinfo.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/5556856/info.txt)

3. Upload the info.txt and log.txt (GameFolder/Logs)

**Explain how we can reproduce the error**

1. Start the game
2. Go to screen '...'
3. Select '...'
4. Game crashed

**Sreenshots/Videos**

If possible, take screenshots or record the crash happening.

**Additional information**

If there's any information that you think would help us.

**Comment by Jousway** [comment]
> 06:49.006: OutFox Engine (SDL Input Debug) - Controller Removed 00
> 06:49.201: InputFilter::ButtonPressed: Invalid device 39
it seems when you jump the pad disconnects, does this happen in windows itself when you jump cuz it it does it might be that your pad or the cable of the pad is malfunctioning

**Comment by Scraticus** [comment]
Fixed a while ago, sorry for not replying here ;_;
