### ISSUE TITLE
[BUG] Game does not fallback to image background when video isn't present in a simfile

### ISSUE THREAD

**Issue by SheepyChris** [TeamRizu/OutFox#172]
**Please give System Info**

OS: MX-19.3_x64 patito feo May 31 2020

CPU: Intel Celeron G4900

GPU: Intel UHD Graphics 610

Storage: Samsung SSD PM871b M.2 2280 128GB and Micron MTFDDAK480MBB-1AE1ZA 00AJ366 00AJ369LEN

**Please give your StepMania Info**

StepMania Version: OutFox Alpha 4.9.1
Theme: Soundwaves

**Describe the problem**

When entering a song with a background video defined but not present, the game will not fallback to the background image and will display nothing (black screen).

**Describe what should happen**

The game should fallback to the background image instead.

**Logs and Additional context**

[info.txt](https://github.com/TeamRizu/OutFox/files/5562558/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5562559/log.txt)

The previous version of OutFox (4.9.0) did not have this behavior.

**Comment by Scraticus** [comment]
Fixed in 4.9.5, Thanks for reporting!
