### ISSUE TITLE
[BUG] Characters affected by masking

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#174]
**Give an example of what is wrong**
If you try to apply masking on ScreenGameplay the Characters are affected by it.

_Type here what is wrong or/with pictures._
https://i.imgur.com/g83dtzP.png

**Given an example of what it should look like**
Um, the character should be above the masking or even not affected by it.

A possible suggestion is to zclearbuffer but I don't have a clean picture of what happens in the Characters realm.
Also this is probably an Upstream Bug.

**Comment by JoseVarelaP** [comment]
This seem like the Legacy DancingCharacters does not perform a cleanup of the Z Buffer, so i'll see if i can recreate this to fix.

**Comment by JoseVarelaP** [comment]
Just tested and made a fix, should be on the Hot Fix update!
![](https://cdn.discordapp.com/attachments/727565840060514425/784898861063733258/Captura_de_Pantalla_2020-12-05_a_las_15.47.44.png)
