### ISSUE TITLE
[Feature Request] Can't get Models/Characters through Lua for other themes

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#175]
I can't get the Models in ScreenGameplay. I did see it's possible to get them with Soundwaves.
Any advices to get them?

**Comment by JoseVarelaP** [comment]
The characters in Soundwaves are possible to be obtained as they're being generated on a lua file in ScreenGameplay's background layer. Legacy characters are not possible to be obtained as they are in a separate isolated layer in gameplay and it's not even named, not attached to anything to lua.
