### ISSUE TITLE
[BUG] No inputs registered in fullscreen and started via xinit

### ISSUE THREAD

**Issue by navaroli** [TeamRizu/OutFox#177]
**Please give System Info**

OS: Linux mint 20 x64 MATE

CPU: Intel i3-8145U

GPU: Intel UHD Graphics 620

Storage: Intel 660p 1TB NVME

**Please give your StepMania Info**

StepMania Version: StepMania 5.3 Alpha 4.9.1
Theme: Default

**Describe the problem**

When booting Linux Mint to runlevel 3 (without graphics), and starting stepmania via xinit (eg: xinit stepmania -- :1), it works fine until I change the display options to fullscreen.  After it goes fullscreen, I'm no longer able to provide input to stepmania via keyboard of pad (from maty-taneczne.pl).  However, I can switch to another TTY via Ctrl + F##.

**Describe what should happen**

Similar to fullscreen mode when running Linux Mint typically (runlevel 5): keyboard and pad input should work while in fullscreen.

**Logs and Additional context**
[info.txt](https://github.com/TeamRizu/OutFox/files/5578012/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5578013/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/5578014/userlog.txt)

**Comment by Scraticus** [comment]
There are several issues going on here which need looking at. We have a sound issue too, which will need a plughw command for the sounddevice= option in the prefs.ini

it also seems that XInput is not playing nice with Run Level 3, before you go to fullscreen, can you try the experimental options screen and set 'use old joystick mapping' or set the same in the prefs.ini for the game.

let me know your findings, it's been a while since we've tested the old runlevel 3 mode, so thanks for giving us a kick to do so!

**Comment by navaroli** [comment]
Hi Scraticus,

I cleared the preferences file (to go back to windowed), enabled the experimental old joystick mapping options, then went back to fullscreen.  Unfortunately, it didn't seem to do anything.

Not sure if it helps, but this setup is able to use the keyboard and pads with the 5.1 branch (this is setup as a dedicated computer that boots straight into stepmania, then powers off on exit). If there's any additional debugging logs, would be happy to send for both 5.1 and 5.3 for diffing.

**Comment by Scraticus** [comment]
comparing with 5.1 isn't going to help here, but can you send the logs with oldinputmapping enabled? I am thinking we aren't running the input correctly for Level 3

**Comment by navaroli** [comment]
No problem!  Here are the logs:

[info.txt](https://github.com/TeamRizu/OutFox/files/5593884/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5593885/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/5593888/userlog.txt)

This was using glad; I had same behavior when I switched to opengl (can send those logs too if that helps).

**Comment by Scraticus** [comment]
I'm going to give this some proper testing after alpha 4.9.5 comes out

I have a feeling i know the problem, but will need further investigation. sorry for the delay in resolving this, to be honest, we forgot to ensure this mode was available when ripping out all the ancient code, and i think we've broken it.

I'm going to install mint on a machine myself and debug this week.

**Comment by navaroli** [comment]
No problem; thanks for the update!  Happy to help test as well or provide any additional info!

**Comment by Scraticus** [comment]
We are awaiting some fixes from Upstream SDL on this matter so please bear with us

**Comment by Scraticus** [comment]
We are still working on this one! I haven't forgotten you!

There were bugs in the FBDev driver that our windowing system uses, and this was preventing any type of input being generated. I'm still awaiting the final release of this, and then we can add it to the alpha (it's likely to be 4.9.10, but i will ping you for some development testing when it's ready.) Thanks for your patience on this one, sorry it's taken so long

**Comment by Scraticus** [comment]
This is _somewhat_ fixed on alpha V, you need to use glad as the renderer, but i'll need to do more testing on it

**Comment by Scraticus** [comment]
this is fixed now, let us know if it isn't on your system
