### ISSUE TITLE
source tarballs

### ISSUE THREAD

**Issue by briaguya-ai** [TeamRizu/OutFox#178]
in the [faq](https://projectmoon.dance/faq) 
> As 5.3 is developing at a rapid pace, allowing source code access at this time would allow users to compile their own builds based on incomplete work, which would be difficult for us to debug and support during this phase of development.

i can understand that logic when choosing if you want a repo to be public or private, but not when choosing whether or not to release source tarballs along with the builds

**Comment by Scraticus** [comment]
This issue tracker is for bugs and feature requests. Your opinion of how we run the project is welcomed, but we are not discussing it. 

At the end of the day, it's our project, if we do not wish to release source tars yet, we do not have to.

**Comment by briaguya-ai** [comment]
while i did originally post this hoping that source tarballs could work as a middleground between maintaining a public repo and only releasing binaries, i know that it is your choice.

i guess the reasoning stated in the faq just didn't feel satisfying, but i'll interpret it as, "we don't want to deal with a ton of, 'i can't get it to build on *insert obscure disto/architecture here*' bug reports"

**Comment by Scraticus** [comment]
it is a little bit of a selfish development methodology I appreciate that. 

The SM community is quite passionate about the game, and doing things this way allow us to build a better scaffolding for SM in the future.

It's more of a case of 'this is what we've done, go fork it and then do it your way' so we're not overloading ourselves in suggestions/bugs which would really slow down the progression altogether.

I meant no offence in my reply, a lot of the time I know folks just wish to play with what we've done etc, but I can just see a can of worms opening from that.

Be well

**Comment by briaguya-ai** [comment]
looking forward to poking around the code when you're ready to share!

**Comment by Scraticus** [comment]
for sure, We want to provide a better set of 'barebones' for folks to add to. We're really excited with what the community will add to the game in the future. 

Thanks for your interest and if you have any questions or wish to be part of the testing team, do ping us in the discord.
