### ISSUE TITLE
[Nitpick] IsUsingWideScreen() doesn't recognize 8:3 and 21:9 as widescreen

### ISSUE THREAD

**Issue by natano** [TeamRizu/OutFox#179]
**Give an example of what is wrong**

The `IsUsingWideScreen()` lua function only recognizes 16:10 and 16:9 as widescreen, but no other widescreen aspect ratios.

**Give an example of what it should look like**

8:3 and 21:9 should be recognized as widescreen formats.

I fixed this some time ago for SM 5.1: https://github.com/stepmania/stepmania/commit/6a4551f9589e4dc9e9afcbcf2a8c50e74ea7d427. I think the diff should still apply cleanly as the version in the lastest outfox alpha seems to be the old SM 5.1 version of the function.

**Comment by Scraticus** [comment]
Fixed, will be out in the next build.
