### ISSUE TITLE
Crash to desktop in the middle of a course

### ISSUE THREAD

**Issue by animusyosho** [TeamRizu/OutFox#18]
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/4871923/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/4871924/log.txt)

Crash to desktop in the middle of a course during transition between song 9 and 10. Updated to version OF4.6.0-rc3 earlier today. Have completed this exact course dozens of times now and this is the first time to experience a crash. Will note if it happens again the next time or not.

**Comment by animusyosho** [comment]
It crashed at the beginning of the exact same song, outside of a course. Have done this song many times so must be something incompatable between the song and the new version. Not going to upload song files here of course. But the song in question is Xepher which is part of Ben Spiers Galaxy.

**Comment by animusyosho** [comment]
Rolled back to RC2 and it works fine. Maybe the ffmpeg update?

**Comment by Jousway** [comment]
https://trac.ffmpeg.org/ticket/8747 already fixed by reverting libswscale

**Comment by animusyosho** [comment]
https://github.com/TeamRizu/OutFox/issues/17#issuecomment-653722610

I updated to RC3 again and replaced the mentioned swscale-5.dll and can confirm it eliminated the crash.

**Comment by Scraticus** [comment]
fixed in 4.6.0
