### ISSUE TITLE
[Game Crash] Sending any MIDI Input while transitioning between Screens crashes the game

### ISSUE THREAD

**Issue by Gabrimax98** [TeamRizu/OutFox#180]
**1. What you were doing before it crashed and what action made the game to crash.**

In every screen, whenever i'd be transitioning from a screen to another and i'd send any MIDI signal from my Hercules DJControl Inpulse 200, the game would crash with an Access Violation reason.

This also happens with default Soundwaves theme, as well as SL-Outfox.

**2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)**

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5580166/crashinfo.txt)

**3. Upload the info.txt and log.txt (GameFolder/Logs)**

[log.txt](https://github.com/TeamRizu/OutFox/files/5580169/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/5580170/info.txt)

**Explain how we can reproduce the error**

1. Start the game
2. Send any midi input (i.e. turn knobs on a console)
2a. While doing this, transition to another screen (i.e. press start)
3. Game crashed

*If there's any information that you think would help us.*

I happened to have the PC output set to the console, but that wasn't enough to *not* make it crash as it would still do that with another output set before launching the game.

I also tried replicating the crash in the MidiTest2.exe build Jous gave me the 18th and it did.

**Comment by Scraticus** [comment]
Fixed in 4.9.9 - we only need to adjust screenselect music now, but the major bug this was upset with is solved.
