### ISSUE TITLE
[BUG] DDR Game Energy Pad right/up arrows not registering in 5.3 Alpha 4.9.5 and 4.9.0

### ISSUE THREAD

**Issue by carlshan** [TeamRizu/OutFox#184]
**System Info**

OS: Windows 10 (running on MacOS Bootcamp)

CPU: 2.3 GHz 8-core Intel i9

GPU: Intel UHD Graphics 630 1536 MB

Storage: 120 GB Bootcamp partition

StepMania Version: 5.3 Alpha 4.9.5 (and replicated on the October release)

**Describe the problem**

I recently purchased new soft pads via DDR Game ([link to pads](https://www.ddrgame.com/energypads.html)). In trying to map their controls in Stepmania, however I am seeing the following:

- When mapping, the pad's left arrow gets recognized as "Joy1 RightShoulder" and the right and up arrows don't get mapped at all
- The down arrow gets recognized as "Joy1 LeftShoulder"
- The Start and Select buttons on the pad are responsive and can get mapped.

This has happened on both the 4.9.5 and 4.9.0 builds. 

The last version the of Stepmania it worked on was 4.8.1 (I believe).

**Details**
Previously I had used D-Force Deluxe pads ([Amazon](https://www.amazon.com/D-Force-Deluxe-Dance-Pump-USB/dp/B00H1B9B6A/ref=sr_1_1?dchild=1&keywords=ddr+pad&qid=1606789451&sr=8-1)) without a problem. Their arrows mapped correctly. These pads that worked correctly had a USB prong.

The new DDR Game Energy pads, however, has a multi-prong that can connect to USB, XBox, PS/PS2/PS3 and Wii. I'm wondering if there may be some issue there.

**Comment by ListenerJubatus** [comment]
Have you tried legacy input mode (in experimental options) at all?

**Comment by SheepyChris** [comment]
Considering the way that DDRGame control boxes work, I strongly recommend enabling "Use Legacy Input System" in Experimental Settings. If you still want to use the modern XInput input system, this FAQ page teaches you how to properly map your dance pads to a virtual Xbox controller: https://projectmoon.dance/help/controllers

**Comment by carlshan** [comment]
Got it. Let me try to use the Legacy Input System first and report back whether that worked.

**Comment by carlshan** [comment]
I was able to successfully map the DDR Energy pad using the Legacy Input System settings (after selecting it in Experimental Settings and restarting the game).

That's a good workaround. I'll close this issue now.
