### ISSUE TITLE
[BUG] Stepmania 4.9.5 crashes on MacOS Big Sur (11.0.1)

### ISSUE THREAD

**Issue by carlshan** [TeamRizu/OutFox#185]
**Please give System Info**

OS: MacOS Big Sur v. 11.0.1

CPU: 2.3 GHz 8-Core i9

GPU: Intel UHD Graphics 630

Storage: 1TB

**Please give your StepMania Info**

StepMania Version: Alpha 4.9.5

**Describe the problem**

In trying to reproduce the [bug on Windows via Bootcamp in a previous bug report](https://github.com/TeamRizu/OutFox/issues/184), I tried to download and install 4.9.5 on Mac.

After downloading and installing (+ giving permission for the application to execute), double-clicking on Stepmania results in it briefly opening up and immediately closing/crashing.

No crash log files are generated. However, Apple's crash log has been pasted below.
[stepmania_crash.txt](https://github.com/TeamRizu/OutFox/files/5619964/stepmania_crash.txt)

**Comment by JoseVarelaP** [comment]
The log shows that you have not fully dequarantined the application, thus MacOS will prohibit the app from playing. Only giving it permission for the app to run is not enough. 

Perform the following:
Open a terminal window, and insert the following command:
`xattr -dr com.apple.quarantine /path/to/OutFox` 

It must be the entire folder, not just the application. 

This will add OutFox to the dequarantined zone, allowing it to run.

**Comment by carlshan** [comment]
Thanks, Jose. I'll try that and let you know how it works. For future reference, can you let me know which line in the crash log you looked at to triage this?

**Comment by JoseVarelaP** [comment]
The fact that the log does not report any activity of StepMania at all, but instead MacOS's Kernel Protection check shows that it has stopped it from accessing anything outside of the .app (Only thing reporting is the assigned possible threads for the game). (Also explains why the pathing being registered is in a private sandbox).

**Comment by Famic0m** [comment]
this fix worked a treat thanks for that because i was scratching my head trying to figure this one out
