### ISSUE TITLE
[BUG] [pump] Fake notes doesn't show up correctly

### ISSUE THREAD

**Issue by SHRMP0** [TeamRizu/OutFox#187]
**Describe the problem**
Fake notes (not to be confused with fake regions) are displayed like this on OutFox: [https://imgur.com/a/HVPRjwp](https://imgur.com/a/HVPRjwp)

**Describe what should happen**
Fake notes are meant to look like this: [https://youtu.be/BmlwQUZLfig?t=80](https://youtu.be/BmlwQUZLfig?t=80) (as seen in 1:20 / 2:40)

**Logs and Additional context**
[simfile.zip](https://github.com/TeamRizu/OutFox/files/5628770/simfile.zip)

**Comment by SHRMP0** [comment]
Oops, forgot the logs: [Logs.zip](https://github.com/TeamRizu/OutFox/files/5629072/Logs.zip)

**Comment by JoseVarelaP** [comment]
This was actually because of LiroCode, he forgot to set the correct graphics for the fake arrows. It is now resolved.
