### ISSUE TITLE
[Game Crash] "Assertion 'tn.iDuration != 0' failed"

### ISSUE THREAD

**Issue by AppleArcade120** [TeamRizu/OutFox#188]
**Describe how it crashed by giving us those informations:**

1. What you were doing before it crashed and what action made the game to crash.
Booting the game.

2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5632984/crashinfo.txt)

3. Upload the info.txt and log.txt (GameFolder/Logs)
[log.txt](https://github.com/TeamRizu/OutFox/files/5632985/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/5632987/info.txt)

**Explain how we can reproduce the error**

1. Download a pack of EZ2AC and DJMAX BMS files.
2. Start the game
3. Game crash

**Additional Information**

I have no idea what "tn.iDuration != 0" is

**Comment by Scraticus** [comment]
Should be fixed now, but do open a new issue if you get it. there was a known bug that needed fixing and it also resolved this.
