### ISSUE TITLE
[Nitpick] Rough transitions between random background videos

### ISSUE THREAD

**Issue by navaroli** [TeamRizu/OutFox#189]
**Give an example of what is wrong**

When cycling through random background videos, the transition can be a bit jarring / distracting.  I've attached two examples when this happens below (the 2nd and 5th pictures are the transition frames, which are problematic).

![1a](https://user-images.githubusercontent.com/1111117/101268065-369c0400-3714-11eb-8be0-ec1ba885de75.png)
![1b](https://user-images.githubusercontent.com/1111117/101268069-38fe5e00-3714-11eb-849e-dc5f5ac1ed02.png)
![1c](https://user-images.githubusercontent.com/1111117/101268070-3ac82180-3714-11eb-869b-69120c9b69a7.png)
![2a](https://user-images.githubusercontent.com/1111117/101268073-3c91e500-3714-11eb-87ed-c165dd85c04f.png)
![2b](https://user-images.githubusercontent.com/1111117/101268075-3e5ba880-3714-11eb-9cdb-52808b056d82.png)
![2c](https://user-images.githubusercontent.com/1111117/101268077-40256c00-3714-11eb-9b56-52c0102fd678.png)

**Given an example of what it should look like**

It should be a smooth transition from one video to the next (this is the behavior I see in Stepmania 5.1 branch on the same computer).

System info:
- Linux mint 20 x64 MATE
- Intel i5-6600T
- Intel HD Graphics 530
- Kingston 500GB NVME
- 16GB DDR4 Ram

**Comment by Scraticus** [comment]
This is due to the newer FFMPEG driver, and the way the frames are cached. We'll look into this, thanks for reporting

**Comment by Scraticus** [comment]
We have a fix in testing, that will be out in the next release, sorry for it taking so long!
