### ISSUE TITLE
Mac OS - No Noteskins Available error when launched

### ISSUE THREAD

**Issue by NateLowrie** [TeamRizu/OutFox#19]
1. What you were doing before it crashed and what action made the game to crash.

On Mac OS.
I downloaded the DMG, copied all the files to the Applications folder.
Where I launch the application, I get an error message that says "No Noteskins available." 

2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)

None generated

3. Upload the info.txt and log.txt (GameFolder/Logs)

None generated.

**Explain how we can reproduce the error**

On Mac OS.
I downloaded the DMG, copied all the files to the Applications folder.
Where I launch the application, I get an error message that says "No Noteskins available." 

**Sreenshots/Videos**

![error](https://user-images.githubusercontent.com/45018/86502028-b2141680-bd6c-11ea-96d1-fb52ef5d0d1b.png)

**Additional information**

The file folders are in the same folder as the app. Not sure if it needs to be in a different folder.

**Comment by moruzerinho6** [comment]
https://wiki.projectmoon.dance/books/stepmania-user-guide/page/troubleshooting

Go down to ``MacOS Related Issues``

**Comment by NateLowrie** [comment]
Thanks. That did the trick. For reference, a link to that wiki does not appear anywhere on the main website. I would suggest linking to that page under in the Notices section on the Downloads page.
