### ISSUE TITLE
[BUG] Color-cycling noteskins no longer working

### ISSUE THREAD

**Issue by fluffy-critter** [TeamRizu/OutFox#191]
**Please give System Info**

OS: macOS 10.13

CPU: Intel Core i7 2.7GHz

GPU: AMD Radeon HD 6630M 256MB

Storage: 256GB SSD

**Please give your StepMania Info**

StepMania Version: OutFox 4.9.5 alpha, StepMania 5.3-git-1ced17f540
Theme: Happens both on OutFox and on SimplyLove-outfox-4.9.1

**Describe the problem**

Using the "normal" noteskin from https://github.com/MadkaT182/DDRNoteskins, all arrows are green.

**Describe what should happen**

Arrows should be colored based on their phase within the beat.

This worked correctly on the previous build of Stepmania

**Logs and Additional context**

1. Go into the game folder
2. Open the Logs folder
3. Grab every file in there and post with the issue.
4. Go back to the game folder, if there's an crashinfo.txt then send it too.

Add any other context or screenshots here.

![Screen Shot 2020-12-12 at 6 43 24 PM](https://user-images.githubusercontent.com/347162/102001905-fdcbd400-3cab-11eb-91b0-5f7479454abc.png)
![Screen Shot 2020-12-12 at 6 43 49 PM](https://user-images.githubusercontent.com/347162/102001906-fefd0100-3cab-11eb-8a3d-122f722fd792.png)

**Comment by JoseVarelaP** [comment]
This was addressed immediately after the 4.9.5 version was released. The fix will come on the hotfix.

**Comment by fluffy-critter** [comment]
Ah, good to know, thanks! Sorry for the unnecessary bug report. :)
