### ISSUE TITLE
[Game Crash] Game wont start after set something in "expert settings"

### ISSUE THREAD

**Issue by KaZo75** [TeamRizu/OutFox#193]
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5711799/crashinfo.txt)

If you go to the menu settings/expert settings, the video renderer is 'GLAD', independent fom earlier settings.
If you change someting here (not the renderer), the settings will be saved at path: Save\Preferences.ini (as I see) and the tag "VideoRenderers=glad" will be setted,
The program won't start any more. You should set back "VideoRenderers=opengl" manual in the Save\Preferences.ini to start the program.

**Comment by moruzerinho6** [comment]
Your integrated just doesn't support glad, that's why it won't work with it, check if your drivers are updated, if yes and you still can't use glad then stick with opengl.

**Comment by KaZo75** [comment]
Ok, maybe I was not enough clear, sorry. My system settings is  
Opengl, and yes, my system does not suppot glad. Renderer is set to  
opengl. But when I choose the expert settings menu, I see the renderer  
setting is 'glad'. I mean this is the problem. Durung the  
initialisation/start the renderer setting is not updated in the menu  
(to OpenGL im my case) from Preferences.ini. If I change something  
here (e.g.:size of notes), the system saves the glad, but I do not and  
will not change the renderer. If I restart the Program, it wont start.  
I have to set back 'VideoRenderers=opengl' in the Preferences.ini  
manually. 
If I change something in the expert menu (e.g.:size of notes), and I  
set the renderer to opengl, the program starts correctly, but after  
restart I can see glad as renderer again in the expert menu.

Idézet (zerinho6 <notifications@github.com>):

>  
>
>   Your integrated just doesn't support glad, that's why it won't  
> work with it, check if your drivers are updated, if yes and you  
> still can't use glad then stick with opengl.
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].



Hivatkozások:
-------------
[1] https://github.com/TeamRizu/OutFox/issues/193#issuecomment-747667096
[2]

**Comment by Scraticus** [comment]
We've tweaked this to remove the 4.5 support that's crashing your driver. This is a windows 10 issue, so we'll try to mitigate it so you don't crash in the future.

Thanks for reporting this!
