### ISSUE TITLE
[Game Crash] Crash on first startup

### ISSUE THREAD

**Issue by alexalder** [TeamRizu/OutFox#194]
I downloaded the Alpha 4.9.6 Build, tried starting it from various different folders (home, desktop, applications) and i always get this crash

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5720048/crashinfo.txt)

**Comment by Jousway** [comment]
can you tell me your OS and machine?, is it a mac m1 with big sur, cuz if so are you downloading the M1 build?

**Comment by alexalder** [comment]
Yes of course, the M1 Mini, i downloaded the Stepmania-Outfox-Alpha-4.9.6-MacOS-M1-date-20201216.dmg

**Comment by Jousway** [comment]
its prob the security issue, there is a part about it on our website under FAQ https://projectmoon.dance/faq
here is a short of that text
`If you receive errors such as "No noteskins found" or other unusual behavior, you will have to change macOS security settings in order for Project OutFox to operate correctly. The OS does not trust unsigned applications, and prevents access to external files unless given manual permission by the user.

To do this, open Terminal and run the following command: xattr -dr com.apple.quarantine /path/to/OutFox

Alternatively, you can exclude the path, and drag the folder containing the game executable directly onto the window.`

**Comment by alexalder** [comment]
![image](https://user-images.githubusercontent.com/7947093/102698312-b493fb00-423c-11eb-9ff7-3eb6802bb898.png)
Tried dragging the folder containing the application file and running the command and nothing changed.
The program did ask for approval via the usual Security and Privacy menu before i posted the original crashlog and of course i did approve it from the system preferences

**Comment by SheepyChris** [comment]
It doesn't look like the command was able to grab the directory of the game folder, considering that it's empty in the screenshot after `com.apple.quarantine`. Type in the full path to the folder instead and try again.

**Comment by alexalder** [comment]
Oh! I thought you mean drag it as in "run the command in the folder path" and not "run the command with the folder as argument". My bad.
It now works of course.
I would suggest including a visible readme with this procedure in the installer like in this screenshot, as it's really strange behaviour for a mac app to not work after giving permission in the system preferences but of course it's a beta so it's my fault for not reading the FAQs.
Thank you for the quick answer!
![image](https://user-images.githubusercontent.com/7947093/102698460-bdd19780-423d-11eb-8f0b-c4a8f956fffa.png)
