### ISSUE TITLE
Windows 7: stepmania loadlibrary failed with error 87. Wrong parameter

### ISSUE THREAD

**Issue by eewokee** [TeamRizu/OutFox#196]
**Please give System Info**

OS: Windows 7

CPU: Q9550 2.83ghz

GPU: Ultimarc ArcadeVGA 5000

Storage: SSD Samsung 840

**Please give your StepMania Info**

StepMania Version: 5.3 Alpha 4.9.6
Theme: *Type here the theme name*

**Describe the problem**

Program cannot start-up and Windows 7 gives error: stepmania loadlibrary failed with error 87

**Describe what should happen**

Start the program

**Logs and Additional context**

1. Go into the game folder
2. Open the Logs folder
3. Grab every file in there and post with the issue.
4. Go back to the game folder, if there's an crashinfo.txt then send it too.

Add any other context or screenshots here.

**Comment by Scraticus** [comment]
what build of windows 7 are you on?

**Comment by eewokee** [comment]
Windows 7 Professional SP1

**Comment by Scraticus** [comment]
were there any logs generated? or did it just die?

and could you try the XP build and see if it also dies?

I'd like to help you troubleshoot this one

**Comment by eewokee** [comment]
XP the same issue. 3 logs created. Info, log and userlog.
[info.txt](https://github.com/TeamRizu/OutFox/files/5748586/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5748588/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/5748589/userlog.txt)

**Comment by Scraticus** [comment]
do you have a /save folder in your application directory (if you checked portable mode?) for `preferences.ini`

can you add the following to the line entitled `LastSeenVideoDriver=`

so it looks like: `LastSeenVideoDriver=AMD Radeon HD 5450`

you have the weird bug where sometimes it's not exposed due to a bug in the driver issue

**Comment by eewokee** [comment]
I did....unfortunately the same error.

**Comment by eewokee** [comment]
And the latest logs.


StepMania5.3-git-768a687e88
Compiled 20201218 @ 07:40:02 (build 768a687e88)
Log starting 2020-12-28 21:36:06
WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting
Loading window: sdl
Windows 7
OutFox Engine - Memory Detected: 4094MB Installed, (3050MB Available), 8187MB Swap Memory (7118MB Swap available)
Primary display driver: AMD Radeon HD 5450
WARNING: Couldn't find primary display driver; logging all drivers
Video driver: A [Advanced Micro Devices, Inc.]
              13.13.22.149, 7-13-2016 [pci\ven_1002&dev_68f9&subsys_02810801]
Drive: "Samsung SSD 840 Seri    DXT0" Driver: nvstor64 DMA: N/A
Drive: "WDC WD1500HLFS-01G6U    04.0" Driver: nvstor64 DMA: N/A
Drive: "Hitachi HDP725050GLA    GM4O" Driver: nvstor64 DMA: N/A
Drive: "SAMSUNG HD154UI         1AG0" Driver: nvstor64 DMA: N/A
Drive: "PIONEER BD-ROM  BDC-202 1.01" Driver: nvstor64 DMA: N/A
Drive: "WDC WD7500AAKS-00RBA    30.0" Driver: nvstor64 DMA: N/A
Sound device 0: Luidsprekers (2- High Definitio, 0.0, MID 1, PID 65535 
Sound device 1: Hoofdtelefoon (2- High Definiti, 0.0, MID 1, PID 65535 
Sound device 2: Digitale audio (S/PDIF) (2- Hig, 0.0, MID 1, PID 65535 
WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'default'.
Sound writeahead has been overridden to 4096
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'glad,opengl,gles2'

00:00.034: StepMania5.3-git-768a687e88
00:00.034: Compiled 20201218 @ 07:40:02 (build 768a687e88)
00:00.034: Log starting 2020-12-28 21:36:06
00:00.034:  
00:00.035: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.037: Reading 'Data/Static.ini' failed: No such file or directory
00:00.079: Outfox Engine: SDL Subsystem Initialised.
00:00.079: OutFox Engine: Initializing Discord SDK
00:00.080: OutFox Engine: Core Creation Returned: Failed With Error:  4
/////////////////////////////////////////
00:00.080: WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting
/////////////////////////////////////////
00:00.092: FONT LOADED!
00:00.293: Loading window: sdl
00:00.307: Windows 7
00:00.307: OutFox Engine - Memory Detected: 4094MB Installed, (3050MB Available), 8187MB Swap Memory (7118MB Swap available)
00:00.307: Primary display driver: AMD Radeon HD 5450
/////////////////////////////////////////
00:00.307: WARNING: Couldn't find primary display driver; logging all drivers
/////////////////////////////////////////
00:00.308: Video driver: A [Advanced Micro Devices, Inc.]
00:00.308:               13.13.22.149, 7-13-2016 [pci\ven_1002&dev_68f9&subsys_02810801]
00:00.308: Drive: "Samsung SSD 840 Seri    DXT0" Driver: nvstor64 DMA: N/A
00:00.308: Drive: "WDC WD1500HLFS-01G6U    04.0" Driver: nvstor64 DMA: N/A
00:00.309: Drive: "Hitachi HDP725050GLA    GM4O" Driver: nvstor64 DMA: N/A
00:00.309: Drive: "SAMSUNG HD154UI         1AG0" Driver: nvstor64 DMA: N/A
00:00.309: Drive: "PIONEER BD-ROM  BDC-202 1.01" Driver: nvstor64 DMA: N/A
00:00.309: Drive: "WDC WD7500AAKS-00RBA    30.0" Driver: nvstor64 DMA: N/A
00:00.371: Sound device 0: Luidsprekers (2- High Definitio, 0.0, MID 1, PID 65535 
00:00.373: Sound device 1: Hoofdtelefoon (2- High Definiti, 0.0, MID 1, PID 65535 
00:00.374: Sound device 2: Digitale audio (S/PDIF) (2- Hig, 0.0, MID 1, PID 65535 
00:00.382: Reading 'Data/Static.ini' failed: No such file or directory
/////////////////////////////////////////
00:00.382: WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
/////////////////////////////////////////
/////////////////////////////////////////
00:00.382: WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'default'.
/////////////////////////////////////////
00:00.382: ThemeManager::SwitchThemeAndLanguage: "default", "nl"
00:00.409: Reading 'Appearance/Themes/default/Languages/nl.ini' failed: No such file or directory
00:00.488: Loading "/Scripts/32log.lua" ...
00:00.499: Loading "/Scripts/extend_table.lua" ...
00:00.508: Loading "/Scripts/Timing.lua" ...
00:00.520: Loading "/Scripts/unavailable_functions.lua" ...
00:00.529: Loading "/Scripts/32log.lua" ...
00:00.529: Loading "/Scripts/extend_table.lua" ...
00:00.529: Loading "/Scripts/Timing.lua" ...
00:00.530: Loading "/Scripts/unavailable_functions.lua" ...
00:00.531: Loading "/Appearance/Themes/_fallback/Scripts/00 init.lua" ...
00:00.541: Loading "/Appearance/Themes/_fallback/Scripts/00 lua5.3.lua" ...
00:00.554: Loading "/Appearance/Themes/_fallback/Scripts/01 alias.lua" ...
00:00.570: Loading "/Appearance/Themes/_fallback/Scripts/01 base.lua" ...
00:00.580: Loading "/Appearance/Themes/_fallback/Scripts/01 IniFile.lua" ...
00:00.591: Loading "/Appearance/Themes/_fallback/Scripts/02 Actor.lua" ...
00:00.603: Loading "/Appearance/Themes/_fallback/Scripts/02 ActorDef.lua" ...
00:00.616: Loading "/Appearance/Themes/_fallback/Scripts/02 Branches.lua" ...
00:00.629: Loading "/Appearance/Themes/_fallback/Scripts/02 Colors.lua" ...
00:00.641: Loading "/Appearance/Themes/_fallback/Scripts/02 Debug.lua" ...
00:00.652: Loading "/Appearance/Themes/_fallback/Scripts/02 Enum.lua" ...
00:00.661: Loading "/Appearance/Themes/_fallback/Scripts/02 OptionsMenu.lua" ...
00:00.673: Loading "/Appearance/Themes/_fallback/Scripts/02 Other.lua" ...
00:00.685: Loading "/Appearance/Themes/_fallback/Scripts/02 Serialize.lua" ...
00:00.696: Loading "/Appearance/Themes/_fallback/Scripts/02 Sprite.lua" ...
00:00.707: Loading "/Appearance/Themes/_fallback/Scripts/02 StageMods.lua" ...
00:00.717: Loading "/Appearance/Themes/_fallback/Scripts/02 ThemePrefs.lua" ...
00:00.729: Loading "/Appearance/Themes/_fallback/Scripts/02 ThemePrefsRows.lua" ...
00:00.741: Loading "/Appearance/Themes/_fallback/Scripts/02 Utilities.lua" ...
00:00.754: Loading "/Appearance/Themes/_fallback/Scripts/03 CustomSpeedMods.lua" ...
00:00.766: Loading "/Appearance/Themes/_fallback/Scripts/03 DisplaySpecs.lua" ...
00:00.779: Loading "/Appearance/Themes/_fallback/Scripts/03 Gameplay.lua" ...
00:00.790: Loading "/Appearance/Themes/_fallback/Scripts/03 GamePreferences.lua" ...
00:00.802: Loading "/Appearance/Themes/_fallback/Scripts/03 ModuleSys.lua" ...
00:00.811: Loading "/Appearance/Themes/_fallback/Scripts/03 ThemeAndGamePrefs.lua" ...
00:00.822: Loading "/Appearance/Themes/_fallback/Scripts/03 ThemeLibrary.lua" ...
00:00.833: Loading "/Appearance/Themes/_fallback/Scripts/03 UserPreferences2.lua" ...
00:00.845: Reading 'Appearance/Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:00.845: Loading "/Appearance/Themes/_fallback/Scripts/04 CreditsHelpers.lua" ...
00:00.880: Loading "/Appearance/Themes/_fallback/Scripts/04 LogDisplay.lua" ...
00:00.893: Loading "/Appearance/Themes/_fallback/Scripts/04 NumPadEntry.lua" ...
00:00.905: Loading "/Appearance/Themes/_fallback/Scripts/04 pause_menu_helper.lua" ...
00:00.915: Loading "/Appearance/Themes/_fallback/Scripts/04 SetBGFitHelpers.lua" ...
00:00.927: Loading "/Appearance/Themes/_fallback/Scripts/05. ColumnModAliases.lua" ...
00:00.938: Loading "/Appearance/Themes/_fallback/Scripts/find_missing_lang_strings.lua" ...
00:00.948: Loading "/Appearance/Themes/default/Scripts/Main.lua" ...
00:01.088: Loading "/Appearance/Themes/default/Scripts/Rin_Inspect.lua" ...
00:01.176: Size is now 13 from 1.063750 (855)
00:01.197: Sound writeahead has been overridden to 4096
00:01.253: WaveOut software mixing at 44100 hz
00:01.253: Starting thread: Decode thread
00:01.253: Starting thread: Mixer thread
00:01.253: Sound driver: WaveOut
00:01.253: Starting thread: Music thread
00:01.253: Initializing lights drivers: SystemMessage,Export
00:01.253: Lights driver: SystemMessage
00:01.253: Lights driver: Export
00:01.253: ThemeManager::SwitchThemeAndLanguage: "default", "nl"
00:01.253: Reading 'Save/Keymaps.ini' failed: No such file or directory
00:01.253: Couldn't open mapping file "Save/Keymaps.ini": No such file or directory.
00:01.253: Reading 'Save/Keymaps.ini' failed: No such file or directory
00:01.253: Couldn't open mapping file "Save/Keymaps.ini": No such file or directory.
00:01.268: Reading 'Cache/images.cache' failed: No such file or directory
00:01.327: Attempting to load 1 songs from "Songs/Akire-X"
00:01.353: Loaded 1 songs from "Songs/Akire-X"
00:01.353: Attempting to load 11 songs from "Songs/Dance Dance Revolution 1st Mix"
00:01.539: Loaded 11 songs from "Songs/Dance Dance Revolution 1st Mix"
00:01.539: Attempting to load 23 songs from "Songs/Dance Dance Revolution 2nd Mix"
00:01.921: Loaded 23 songs from "Songs/Dance Dance Revolution 2nd Mix"
00:01.921: Attempting to load 38 songs from "Songs/Dance Dance Revolution 3rd Mix"
00:02.543: Loaded 38 songs from "Songs/Dance Dance Revolution 3rd Mix"
00:02.543: Attempting to load 17 songs from "Songs/Dance Dance Revolution 3rd Plus"
00:02.815: Loaded 17 songs from "Songs/Dance Dance Revolution 3rd Plus"
00:02.815: Attempting to load 49 songs from "Songs/Dance Dance Revolution 4th Mix"
00:03.621: Loaded 49 songs from "Songs/Dance Dance Revolution 4th Mix"
00:03.621: Attempting to load 14 songs from "Songs/Dance Dance Revolution 4th Plus"
00:03.845: Loaded 14 songs from "Songs/Dance Dance Revolution 4th Plus"
00:03.846: Attempting to load 40 songs from "Songs/Dance Dance Revolution 5th Mix"
00:04.492: Loaded 40 songs from "Songs/Dance Dance Revolution 5th Mix"
00:04.493: Attempting to load 42 songs from "Songs/Dance Dance Revolution 6th Mix -Max-"
00:05.158: Loaded 42 songs from "Songs/Dance Dance Revolution 6th Mix -Max-"
00:05.159: Attempting to load 53 songs from "Songs/Dance Dance Revolution 7th Mix -Max2-"
00:05.974: Loaded 53 songs from "Songs/Dance Dance Revolution 7th Mix -Max2-"
00:05.974: Attempting to load 70 songs from "Songs/Dance Dance Revolution 8th Mix -Extreme-"
00:07.072: Loaded 70 songs from "Songs/Dance Dance Revolution 8th Mix -Extreme-"
00:07.072: Attempting to load 18 songs from "Songs/DDR Anime 1st Mix"
00:07.342: Loaded 18 songs from "Songs/DDR Anime 1st Mix"
00:07.342: Attempting to load 20 songs from "Songs/DDR Anime 2nd Mix"
00:07.645: Loaded 20 songs from "Songs/DDR Anime 2nd Mix"
00:07.645: Attempting to load 13 songs from "Songs/DDR Anime 3rd Mix"
00:07.842: Loaded 13 songs from "Songs/DDR Anime 3rd Mix"
00:07.842: Attempting to load 23 songs from "Songs/DDR Anime 4th Mix"
00:08.187: Loaded 23 songs from "Songs/DDR Anime 4th Mix"
00:08.187: Attempting to load 17 songs from "Songs/DDR Anime 5th Mix"
00:08.453: Loaded 17 songs from "Songs/DDR Anime 5th Mix"
00:08.453: Attempting to load 6 songs from "Songs/DDR Video Games 1st Mix"
00:08.538: Loaded 6 songs from "Songs/DDR Video Games 1st Mix"
00:08.538: Attempting to load 13 songs from "Songs/DDR Video Games 2nd Mix"
00:08.718: Song "/Songs/DDR Video Games 2nd Mix/SonicCD/" has no SSC, SM, SMA, DWI, BMS, or KSF files.
00:08.718: Song "/Songs/DDR Video Games 2nd Mix/SonicCD/" has no music file either. Ignoring this song directory.
00:08.718: Loaded 12 songs from "Songs/DDR Video Games 2nd Mix"
00:08.718: Attempting to load 17 songs from "Songs/DDR Video Games 3rd Mix"
00:09.012: Loaded 17 songs from "Songs/DDR Video Games 3rd Mix"
00:09.012: Attempting to load 8 songs from "Songs/DDR Video Games 4th Mix"
00:09.114: Song "/Songs/DDR Video Games 4th Mix/konami/" has no SSC, SM, SMA, DWI, BMS, or KSF files.
00:09.114: Song "/Songs/DDR Video Games 4th Mix/konami/" has no music file either. Ignoring this song directory.
00:09.114: Loaded 7 songs from "Songs/DDR Video Games 4th Mix"
00:09.114: Attempting to load 30 songs from "Songs/DDR4EVER 10th Mix -MAX5-"
00:09.571: Loaded 30 songs from "Songs/DDR4EVER 10th Mix -MAX5-"
00:09.571: Attempting to load 30 songs from "Songs/DDR4EVER 1st Mix"
00:10.031: Loaded 30 songs from "Songs/DDR4EVER 1st Mix"
00:10.032: Attempting to load 30 songs from "Songs/DDR4EVER 2nd Mix"
00:10.543: Loaded 30 songs from "Songs/DDR4EVER 2nd Mix"
00:10.543: Attempting to load 30 songs from "Songs/DDR4EVER 3rd Mix"
00:11.102: Loaded 30 songs from "Songs/DDR4EVER 3rd Mix"
00:11.102: Attempting to load 30 songs from "Songs/DDR4EVER 4th Mix"
00:11.543: Loaded 30 songs from "Songs/DDR4EVER 4th Mix"
00:11.543: Attempting to load 30 songs from "Songs/DDR4EVER 5th Mix"
00:11.987: Loaded 30 songs from "Songs/DDR4EVER 5th Mix"
00:11.987: Attempting to load 30 songs from "Songs/DDR4EVER 6th Mix -MAX-"
00:12.446: Loaded 30 songs from "Songs/DDR4EVER 6th Mix -MAX-"
00:12.446: Attempting to load 30 songs from "Songs/DDR4EVER 7th Mix -MAX2-"
00:12.866: Loaded 30 songs from "Songs/DDR4EVER 7th Mix -MAX2-"
00:12.866: Attempting to load 30 songs from "Songs/DDR4EVER 8th Mix -MAX3-"
00:13.307: Loaded 30 songs from "Songs/DDR4EVER 8th Mix -MAX3-"
00:13.307: Attempting to load 30 songs from "Songs/DDR4EVER 9th Mix -MAX4-"
00:13.732: Loaded 30 songs from "Songs/DDR4EVER 9th Mix -MAX4-"
00:13.732: Attempting to load 1 songs from "Songs/Originals"
00:13.746: Loaded 1 songs from "Songs/Originals"
00:13.746: Attempting to load 3 songs from "Songs/Originals -DM Ashura-"
00:13.791: Loaded 3 songs from "Songs/Originals -DM Ashura-"
00:13.791: Attempting to load 1 songs from "Songs/Outfox"
00:13.803: Loaded 1 songs from "Songs/Outfox"
00:13.803: Attempting to load 3 songs from "Songs/StepMania 5"
00:13.857: Loaded 3 songs from "Songs/StepMania 5"
00:13.873: Found 799 songs in 12.606000 seconds.
00:13.873: Loading courses.
00:13.878: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/ChallengingRandom5.crs") ("Cache/Courses/Courses_Default_ChallengingRandom5.crs")
00:13.909: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/Jupiter.crs") ("Cache/Courses/Courses_Default_Jupiter.crs")
00:13.921: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_01-04.crs") ("Cache/Courses/Courses_Default_MostPlayed_01-04.crs")
00:13.944: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_05-08.crs") ("Cache/Courses/Courses_Default_MostPlayed_05-08.crs")
00:13.965: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_09-12.crs") ("Cache/Courses/Courses_Default_MostPlayed_09-12.crs")
00:13.987: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_13-16.crs") ("Cache/Courses/Courses_Default_MostPlayed_13-16.crs")
00:14.064: Starting thread: Worker thread (MemoryCardWorker)
00:14.069: RageSound: Load "/Appearance/Themes/_fallback/Sounds/MemoryCardManager ready.ogg" (precache: 1)
00:14.090: RageSound: Load "/Appearance/Themes/_fallback/Sounds/_missing.ogg" (precache: 1)
00:14.107: RageSound: Load "/Appearance/Themes/_fallback/Sounds/_missing.ogg" (precache: 1)
00:14.107: RageSound: Load "/Appearance/Themes/_fallback/Sounds/MemoryCardManager disconnect.ogg" (precache: 1)
00:14.121: Starting thread: Worker thread (/@mc1int/)
00:14.121: Starting thread: Worker thread (/@mc2int/)
00:14.130: Profile::LoadAllFromDir( /Save/MachineProfile/ )
00:14.154: Loading /Save/MachineProfile/Stats.xml
00:14.154: Done.
00:14.173: UnlockManager::Load()
00:14.208: Last seen video driver: AMD Radeon HD 5450
00:14.208: Card matches 'Radeon.*R*|Vega*|Navi*'.
00:14.208: Applying defaults for AMD Radeon HD 5450.
00:14.208: Video renderers: 'glad,opengl,gles2'

Song "/Songs/DDR Video Games 2nd Mix/SonicCD/" has no SSC, SM, SMA, DWI, BMS, or KSF files.
Song "/Songs/DDR Video Games 2nd Mix/SonicCD/" has no music file either. Ignoring this song directory.
Song "/Songs/DDR Video Games 4th Mix/konami/" has no SSC, SM, SMA, DWI, BMS, or KSF files.
Song "/Songs/DDR Video Games 4th Mix/konami/" has no music file either. Ignoring this song directory.

**Comment by eewokee** [comment]
And the logs
[info.txt](https://github.com/TeamRizu/OutFox/files/5748729/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5748731/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/5748732/userlog.txt)

**Comment by eewokee** [comment]
Upgraded to Windows 10 and now it runs fine.
