### ISSUE TITLE
[BUG] Framerate Tanks with Background Video

### ISSUE THREAD

**Issue by DinsFire64** [TeamRizu/OutFox#199]
Old Dell.

OS: Arch Linux (Linux itg 5.1.7-arch1-1-itg #1 SMP PREEMPT Wed Jun 5 21:22:35 CDT 2019 x86_64 GNU/Linux)

CPU: Intel i5-660

GPU: GT 640, using nvidia blobs.

Storage: 120gb SSD

StepMania Version: Stepmania-Outfox-Alpha-4.9.6-amd64-date-20201216
Theme: default

**Describe the problem**

Opening a background video absolutely tanks the performance from ~900fps to a little over 60. This causes the entire screen to jitter. Vsync is disabled hovers around 60, enabling it brings it down to 30fps locked (!).

**Describe what should happen**

A frame hit but not a crazy one.

**Logs and Additional context**

Video Recording: https://streamable.com/hm663z
Pack with song in question: https://www.dropbox.com/s/m4hvtzb3to9adb7/Animal%20Crossover.zip?dl=0
[log.txt](https://github.com/TeamRizu/OutFox/files/5792023/log.txt)

Let me know what else I can provide or help with.

Side note the log is *very* angry at my ALSA setup...

**Comment by Scraticus** [comment]
Thanks for the report, still having a lot into this one, try 4.9.7 shortly and let me know what it does

**Comment by DinsFire64** [comment]
Sure thing, whenever it goes live.

Is there a changelog?

**Comment by Scraticus** [comment]
there will be as always aye :) it's a big one this month

**Comment by Scraticus** [comment]
We've tweaked the miniffmpeg driver for the next alpha, would you check when it's released on your system for me Din?

appreciated.

**Comment by Scraticus** [comment]
There have been tweaks with the ffmpeg driver which caused this, and it's been fixed.

If you get time can you confirm?

cheers
