### ISSUE TITLE
Notefield zoomed out on some styles in 480p themes

### ISSUE THREAD

**Issue by ListenerJubatus** [TeamRizu/OutFox#20]
![StepMania_2020-07-04_09-18-37](https://user-images.githubusercontent.com/6346433/86515614-d826ce80-bddf-11ea-9def-0de9af6340de.png)

Something in the new notefield positioning code is not correctly compensating for older 480-resolution themes, causing doubles to not be zoomed correctly. This has been reported by other users as well on SL.

**Comment by Scraticus** [comment]
This is likely to the new scaling code, we'll look into this,

Thanks

**Comment by Scraticus** [comment]
Fixed 4.6 Final
