### ISSUE TITLE
[FIXED][BUG] ALSA Log Spam

### ISSUE THREAD

**Issue by DinsFire64** [TeamRizu/OutFox#200]
Old Dell.

OS: Arch Linux (Linux itg 5.1.7-arch1-1-itg #1 SMP PREEMPT Wed Jun 5 21:22:35 CDT 2019 x86_64 GNU/Linux)

CPU: Intel i5-660

GPU: GT 640, using nvidia blobs.

Storage: 120gb SSD

StepMania Version: Stepmania-Outfox-Alpha-4.9.6-amd64-date-20201216
Theme: default

**Describe the problem**

Attached log shows multiple problems with alsa configuration despite alsa being configured by default.

```
[dance@itg ~]$ cat /etc/asound.conf 
defaults.pcm.card 0
defaults.ctl.card 0
```

**Describe what should happen**

ALSA should be happy with a default config.

**Logs and Additional context**

[log.txt](https://github.com/TeamRizu/OutFox/files/5792023/log.txt)

Ran with legacy amd64 as instructed:

[log.txt](https://github.com/TeamRizu/OutFox/files/5792098/log.txt)

**Comment by DinsFire64** [comment]
...so I was messing around and simply by installing the `pulseaudio` package the spam stops...

So that's an interesting one as I didn't want pulseaudio on this system, just alsa, but the spam goes away once installing it.

Bug or feature? lol

**Comment by Scraticus** [comment]
Fixed in Alpha V, as we don't use the 2002 driver anymore.

**Comment by Scraticus** [comment]
fixed, we had to rewrite it a bit to get it right
