### ISSUE TITLE
[Feature Request] Favorite Songs

### ISSUE THREAD

**Issue by fabb** [TeamRizu/OutFox#201]
**Is your feature request related to a problem? Please describe.**

I have a large library and would like to find my favorite songs quickly.

**Describe the solution you'd like**

It would be cool if songs could be marked as favorite, and later quickly be found with a filter.

**Describe alternatives you've considered**

Currently it's just possible to copy favorite songs to a custom group with a file manager, but that's impractical when playing the game with dance pads in front of the TV.

**Comment by solsang** [comment]
I need this every single time i dance!
*************************************
Made a favorite folder with name "Allfavorites" and an empty song called "Allsilient" so there is no music when i start the game!!

I find myself moving songs back and forth to this folder or wasting time around the folders to find the ones i currently play

**Comment by ListenerJubatus** [comment]
This is something we are working on for a future release
