### ISSUE TITLE
[Game Crash] Not compatible MacOS BigSur

### ISSUE THREAD

**Issue by haneunsuk** [TeamRizu/OutFox#202]
<img width="916" alt="Screen Shot 2021-01-19 at 23 56 18" src="https://user-images.githubusercontent.com/77687209/105067054-edc8c080-5ab1-11eb-9700-18d214d76cfb.png">
<img width="274" alt="Screen Shot 2021-01-19 at 23 56 33" src="https://user-images.githubusercontent.com/77687209/105067095-f7522880-5ab1-11eb-8e1e-4fad63ea032d.png">

**Comment by ListenerJubatus** [comment]
You downloaded the M1 build which is only for the new Arm MacBook and Mini. Download the Intel build here. 

https://github.com/TeamRizu/OutFox/releases/download/OF4.9.6/Stepmania-Outfox-Alpha-4.9.6-MacOS-date-20201216.dmg
