### ISSUE TITLE
[Unexpected Behavior] STARLiGHT theme - Close Group / Difficulty Selection on Song Selection Screen

### ISSUE THREAD

**Issue by xenrohachi** [TeamRizu/OutFox#206]
**What you're using**

When using STARLiGHT theme and 5.3. Closed Group (Up-Down) changes difficulty instead of closing group. Changing difficulty only requires one press of up/down arrow instead of two like usual. Tried multiple themes and only seems to occur on this one. Also went back to 5.0.12 and confirmed no issue there

**Expected behavior**

Difficulty on song selection while using STARLiGHT theme should require 2 presses to change as its causing issues closing sorting groups

**Comment by SheepyChris** [comment]
Did you happen to previously utilize a theme that modified the pad codes? Either way, I would suggest clearing out your `Preferences.ini` file in the Save folder and double check that your game files corresponds to the one provided with the latest installer.

**Comment by JoseVarelaP** [comment]
This is actually because the default wheel type STARLiGHT uses changes the method for changing steps.

It goes like this:
If you're using dedicated buttons, you can use Up+Down to close the folder, as now you use MenuUp+MenuDown to change the difficulty. It seems this wheeltype is the only one that changes steps with a single press.

```lua
function PrevSteps2(self)
	if ThemePrefs.Get("WheelType") == "CoverFlow" then
		return "MenuUp"
	else
		return
	end
end

function NextSteps2(self)
	if ThemePrefs.Get("WheelType") == "CoverFlow" then
		return "MenuDown"
	else
		return
	end
end
```

**Comment by xenrohachi** [comment]
Interesting! Thank you for your help with this. Its strange this only happens with 5.3 and not the older 5.0.12 which is why it lead me to believe that this was a 5.3 issue. I found the code you were referring you and simply changed it to Jukebox since i don't use that wheel type and it fixed it!
Sorry for bringing such a trivial issue to your attention but as the release notes say if there are any issues with older theme releases to report them.

Thanks again!!
