### ISSUE TITLE
[BUG] Segfault on game launch, ATI

### ISSUE THREAD

**Issue by DinsFire64** [TeamRizu/OutFox#208]
Dell, old i5.

OS:
Linux itg 5.10.11-zen2-1-zen #1 ZEN SMP PREEMPT Wed, 27 Jan 2021 23:13:33 +0000 x86_64 GNU/Linux

CPU:
Model name: Intel(R) Core(TM) i5 CPU 660 @ 3.33GHz

GPU: 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos XT [Radeon HD 7470/8470 / R5 235/310 OEM]
[ 5.665] (II) RADEON: Driver for ATI/AMD Radeon chipsets:

Storage: 120gb ssd

StepManiaOutFox-5.3.0-alpha-4.9.7-amd64-date-20210220

StepMania Version: StepManiaOutFox-5.3.0-alpha-4.9.7-amd64-date-20210220
Theme: Default

Describe the problem

Game segfaults right after loading window.

Describe what should happen

Game should launch.

Logs and Additional context

See attached.

Other:
Default user directory, no .stepmania5.3 created.
Issue persists on both legacy and default.

Appears to be GPU/rendering related as my desktop (same packages and versions) runs the game fine with an RX480.

Attempted to override VideoRenderers=opengl with no success in an attempt to bypass glad.

Previous beta runs no issues.

**Comment by Scraticus** [comment]
huh, the default on linux launch should be ``opengl``.

I'm not sure why it's even using glad as default.

However, that crash endpoint is not what I wanted to see... This is what we've been fighting the past 6 weeks. I was not aware it even affected linux, let alone ATI/AMD cards

**Comment by Scraticus** [comment]
I am going to try the fix we used on windows to get rid of this crash, and will ping you when we've done so.

Bear with us

**Comment by DinsFire64** [comment]
Sorry let me be clear in my issue tickets here.

I have the same base image (which you can download here https://dinsfire.com/itgimage) that I have multiple card setups going on, because people have a bunch of old hardware lying around I try and support.

Mmy main card I use on these builds is a Radeon 7xxx series. It straight up segfaults and no rendering window is created. No preferences is created and in an attempt on sideloading one, I can't try and "force" opengl.

I have an nvidia 9500 that I use for testing "not supported by nividia blobs" nouveau. That card has the game freeze on launch, but the rendering window is black. X also hangs pretty hard. You can see the artifacting in the screenshot I posted in the other ticket.

Changing Preferences to opengl does get the game too boot in that situation. So that's probably a glad incompatibility somewhere, but it's hard to say.

I also have an Nvidia GT640 and an RX480. Both of those cards load and run the game fine on the same base image.

So the oddest issue I see is the straight segfault from the Radeon/ATI card. The nouveau issue does appear to have a workaround.

I apologize for the confusion I was trying to diagnose the issue at the same time as trying to report the issues here. I crossed my wires a bit.

**Comment by Scraticus** [comment]
I'm aware of the work you do for the cab and retro community, I use some of your images myself on obscure hardware.

I have identified the segfault cause, and we'll have a new alpha out hopefuly tommorow, as it's 2am here in London.

We do not allow the legacy entrypoints for archiac or older GPU's (It is an upstream SDL2 OpenGL bug). We can revert back to the version in 4.9.6 which will resolve the issue back to how it was. If you are ok with this, I'd like to pass you some tester images so we can keep the older hardware going. If we are missing anything from the build you need, do let us know

Thanks for taking the time to report this, and we'll get a fixed build out ASAP.

cheers Din

**Comment by DinsFire64** [comment]
No worries man, take your time and get some sleep.

<3

**Comment by DinsFire64** [comment]
Fixed with Cube.

Left over code on the GL version being accidentally forced to 3.2.
