### ISSUE TITLE
[BUG] Game freezes on window launch, nouveau

### ISSUE THREAD

**Issue by DinsFire64** [TeamRizu/OutFox#209]
[log.txt](https://github.com/TeamRizu/OutFox/files/6016946/log.txt)
Dell, old i5.

OS: 
`Linux itg 5.10.11-zen2-1-zen #1 ZEN SMP PREEMPT Wed, 27 Jan 2021 23:13:33 +0000 x86_64 GNU/Linux`

CPU: 
`Model name:                      Intel(R) Core(TM) i5 CPU         660  @ 3.33GHz`

GPU: `01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos XT [Radeon HD 7470/8470 / R5 235/310 OEM]`
`f86-video-nouveau 1.0.17-1`

Storage: 120gb ssd

StepManiaOutFox-5.3.0-alpha-4.9.7-amd64-date-20210220

StepMania Version: StepManiaOutFox-5.3.0-alpha-4.9.7-amd64-date-20210220
Theme: Default

**Describe the problem**

Game launches rendering window to black screen and locks.

**Describe what should happen**

Game should launch.

**Logs and Additional context**

See attached.

Other:
Default user directory, no `.stepmania5.3` created.
Issue persists on both legacy and default.

Overriding `VideoRenderers=opengl` in Preferences.ini **does fix this issue**. Perhaps the default renderer for this era of card needs to be `opengl,glad` or perhaps it's a more widespread nouveau issue.

Previous beta runs no issues.

[log.txt](https://github.com/TeamRizu/OutFox/files/6016947/log.txt)
![IMG_20210220_192541](https://user-images.githubusercontent.com/5580979/108612808-961fbc80-73b1-11eb-8f08-32a50c5abd3a.jpg)

**Comment by Scraticus** [comment]
where are the logs chap?

**Comment by DinsFire64** [comment]
Attached, I was writing the ticket while moving over the files.

**Comment by DinsFire64** [comment]
Fixed by forcing `HighResolutionTexures=Auto` rather than the default `ForceOn`
