### ISSUE TITLE
Noteskin randomly not loading 5.3 Alpha 4.6 RC3

### ISSUE THREAD

**Issue by bibusdax** [TeamRizu/OutFox#21]
Stepmania 5.3 Alpha 4.6 RC3 with replaced ffmpeg dll on Windows 10
Stepmania 5.3 Alpha 4.6 RC3 as distributed on Linux (Kubuntu)
Hardware is in both cases an ASUS Barebone with Intel Atom CPU and Nvidia iON Graphics.

It is a Noteskin issue (arrows not appearing) on both systems.
When booting the machine and starting the game the first time, often (randomly) the noteskins do not appear.
When I go back to song selection, the problem persists.
However when I go back to the entry screen (top menu in Stepmania) and start the game, there is a big chance the noteskins do appear.
If they do appear, they appear in all songs from that moment on.

This problem persisted for me through all the pre RC (alpha) versions of Stepmania 5.3.
I did not encounter this problem with RC2 on Windows 10.
With Stepmania 5.3 Alpha 4.6 RC3 this problem exists again and on both, Linux (Minimal Kubuntu) and Windows.

Besides that.
Great work and great support !
Thank you very much and I am looking forward to your release in August.

Best regards,

Patrick

**Comment by Scraticus** [comment]
hiya, 

can you check this is on both the `glad` and `opengl` renderer?

Moving to ffmpeg4.3 has caused a few regressions we are currently ironing out, so thanks for this report

**Comment by Scraticus** [comment]
Fixed in the next release, Thanks for taking the time to report and I hope you continue to enjoy the game.
