### ISSUE TITLE
[Game Crash] Calibrate Audio Sync crashes on pump

### ISSUE THREAD

**Issue by SHRMP0** [TeamRizu/OutFox#210]
Game crashes when trying to open the `Input & Calibration » Calibrate Audio Sync` screen on pump gamemode (Auto Sync works if triggered via F6 anywhere else).

[log.txt](https://github.com/TeamRizu/OutFox/files/6017100/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/6017103/userlog.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6017104/crashinfo.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/6017105/info.txt)

**Comment by Kaede573** [comment]
The same thing seems to happen in dance mode, and _only_ when using the Simply Love theme (I used an older copy, but behavior is the same with the up-to-date release branch). No crash on audio sync after switch back to the default 5.3 theme. I haven't tested other themes.
I have checked Stepmania-Outfox-Alpha-4.9.6-amd64-date-20201216 and it worked okay.

I can reproduce the crash with pump (and beat, haven't tested the others) also, so am providing logs for both below.

[pump_info.txt](https://github.com/TeamRizu/OutFox/files/6017815/pump_info.txt)
[pump_log.txt](https://github.com/TeamRizu/OutFox/files/6017817/pump_log.txt)
[pump_userlog.txt](https://github.com/TeamRizu/OutFox/files/6017818/pump_userlog.txt)
[dance_SL_info.txt](https://github.com/TeamRizu/OutFox/files/6017819/dance_SL_info.txt)
[dance_SL_log.txt](https://github.com/TeamRizu/OutFox/files/6017821/dance_SL_log.txt)
[dance_SL_userlog.txt](https://github.com/TeamRizu/OutFox/files/6017822/dance_SL_userlog.txt)

**Comment by Scraticus** [comment]
Fixed in 4.9.7GG, give Jose some love
