### ISSUE TITLE
[Game Crash] Crash right after load screen on Raspberry Pi 4 64 bit Os

### ISSUE THREAD

**Issue by eudes** [TeamRizu/OutFox#211]
**How it crashed:**

The latest build (4.9.7) crashes right after the load screen finishes loading songs.
On Raspberry Pi 4, Raspberry OS 64 bit.
With mesa-git 21.1.0-devel.
Using a new (empty) Saves folder and using a Saves folder from 4.9.6, with previously working Preferences.ini.

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6018121/crashinfo.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/6018122/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6018123/log.txt)

**Steps to reproduce:**
1. Start the game.

**Sreenshots/Videos**
https://www.dropbox.com/s/rkakdqpoykymksp/20210221_170552.mp4?dl=0
The start loop is due to my LXDE config, not inherent to Outfox.

**Comment by Scraticus** [comment]
Fixed in 4.9.7GG. Thanks for reporting
