### ISSUE TITLE
[BUG] In Guitar mode, lowering Note Field Zoom % pushes the receptors up the screen

### ISSUE THREAD

**Issue by shockdude** [TeamRizu/OutFox#212]
**Please give System Info**

OS: Windows 10 20H2

CPU: Intel i7-4720HQ

GPU: Nvidia GTX 860M

Storage: 1GB SSD

**Please give your StepMania Info**

StepMania Version: Alpha 4.9.7HF
Theme: Default

**Describe the problem**

In Guitar Mode, lowering the Note Field Zoom % unexpectedly pushes the receptors higher up the screen.

**Describe what should happen**

The receptors should stay at the bottom of the screen

**Logs and Additional context**

Screenshot of 50% note field zoom
![image](https://user-images.githubusercontent.com/27760396/108640694-0b41cf00-7450-11eb-8bd5-1f12d83ef5a4.png)

**Comment by ListenerJubatus** [comment]
I've seen something similar happen in beat mode too.

**Comment by shockdude** [comment]
Fixed in OF4.9.8
