### ISSUE TITLE
[BUG] Stats.xml over 10Mb is not parsed - 0 songs played, no scores in game

### ISSUE THREAD

**Issue by kellykato** [TeamRizu/OutFox#215]
OS: happened on both  Windows 7 and Linux Mint 20.1

CPU: Intel i7 3770k 

GPU: NVIDIA GTX 770

Storage: WD 500Gb HDD for Windows, WD 500Gb SSD for Linux

**Please give your StepMania Info**

StepMania Version: StepMania 5.3 Alpha 4.9.6; happened on 4.9.7 too. Logs are for 4.9.6.
Theme: Digital-Dance [0.9.6](https://github.com/Hayoreo/Digital-Dance)

**Describe the problem**
I've been playing Stepmania for some years, so I have a pretty huge Stats.xml file and I back the whole Save folder up occasionally.
Latest backup was on Feb, 13 with Stats.xml being 9.9 Mbs, and number of total songs played was almost 9700 .
I played around 40 songs on Feb 21. Today, Feb 23, I booted my PC, started Stepmania and saw that it shows 0 songs played on profile select screen and no local profile scores from earlier. Local profile folder was in place, Stats.xml was a little bit above 10 Mbs.
Looks like it was not parsed correctly. Maybe because of file size.

**Describe what should happen**

Game should handle Stats.xml and today I should've seen something like "9740 songs played" on profile select screen, and local profile scores should present on the songwheel screen as well.

**Logs and Additional context**

Logs:
[info.txt](https://github.com/TeamRizu/OutFox/files/6029738/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6029739/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/6029742/userlog.txt)

Screenshots and Local Profile with 9 and 10Mb Stats file.
With 9Mb Stats file:
![2021-02-23_173141](https://user-images.githubusercontent.com/79508110/108860340-2868d000-75ff-11eb-9b92-994bea8b4d93.jpg)
![2021-02-23_173218](https://user-images.githubusercontent.com/79508110/108860378-2ef74780-75ff-11eb-8d0e-7854e5f044bf.jpg)
[Local_Profile_With_9Mb_Stats.zip](https://github.com/TeamRizu/OutFox/files/6029604/Local_Profile_With_9Mb_Stats.zip)

With 10Mb Stats file:
![2021-02-23_173406](https://user-images.githubusercontent.com/79508110/108860526-53532400-75ff-11eb-96c9-86f7e0069d3d.jpg)
![2021-02-23_173432](https://user-images.githubusercontent.com/79508110/108860534-551ce780-75ff-11eb-8565-9ed04bf4bcf6.jpg)
[Local_Profile_With_10Mb_Stats.zip](https://github.com/TeamRizu/OutFox/files/6029614/Local_Profile_With_10Mb_Stats.zip)

**Comment by Scraticus** [comment]
Wow i thought we'd made this a bit bigger than 10MB, you are quite correct, it is 10,240,000 bytes as the maximum.

I will increase the maximum for 20MB, as that's the reasonable limit of Lua (and would make the game a bit unstable)

I'll update this before we release the GG hotfix patch, so you won't need to wait a month for the release.

**Comment by Scraticus** [comment]
This one is fixed in 4.9.7GG Hotfix, which will be out shortly. Will close when released 

Thanks for your report!
