### ISSUE TITLE
[BUG] Song played using Portal does not return to the Portal Selection after Song completion

### ISSUE THREAD

**Issue by JavaJeremy** [TeamRizu/OutFox#217]
Current State:
After I play a song through the new "Portal" option, the selection changes to that song instead of staying at the "Portal" selection.
Same goes for the old "Random" option.

Suggestion:
To me it's more logical if the selection is not changed after a song is finished.

**Comment by ListenerJubatus** [comment]
We're looking into this idea cause it actually makes sense

**Comment by JoseVarelaP** [comment]
This is now fixed on Alpha-V pre-041.
