### ISSUE TITLE
[Nitpick] Soundwaves: Song preview line in the NPS graph can extend outside the graph

### ISSUE THREAD

**Issue by 48productions** [TeamRizu/OutFox#218]
_Extremely_ nitpicky bug on ScreenSelectMusic in soundwaves, reporting it anyways :P

I noticed that on the NPS graph in select music, the line that shows where the preview audio happens in the simfile can extend past the boundaries of the graph.

![image](https://user-images.githubusercontent.com/57228987/108958163-d1c7ba00-762f-11eb-8e96-fb4b4efadf3e.png)

This bug seems to occur when a song's preview happens past the end of the notes in a simfile, and reproducing this issue is pretty self-explanatory. Create a new stepchart for a song with only a few notes in it, then set the song's preview to happen after the notes end.

**Comment by Scraticus** [comment]
This is actually as designed for songs that do not use the song within the NPS Graph. - however, we should likely look at hiding it if it is outside of the player boundaries.

**Comment by JoseVarelaP** [comment]
Fixed by making the limit the possible step limit, so anything further from the area will be stopped.
