### ISSUE TITLE
SuperShuffle/Blender is capable of deleting notes randomly

### ISSUE THREAD

**Issue by PCBoyGames** [TeamRizu/OutFox#22]
[In this example](https://youtu.be/Jdyj5KZqT1E), I applied note addition modifiers, then Blender on the left field only. Both use the same base song, note additions, and difficulty (MD13 to Thinking Of You from SPEEDCORE 3), yet the Blender field has notes missing. For example, right away at 0:11, there is a missing note in a jump and a missing 16th not too long after.

The Flawless counter on the top of either side represents the amount of rows with notes of any count (“Single note” jumps are not taken into account, only missing rows can separate the gap.) that have passed at any given time per their side.

Upon seeing 0:11, Kid suspected notes missing in jumps are a double random to the same column, but when I asked him of the 16th after, he had no idea. At least we’re making speculations.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PCBoyGames** [comment]
Further investigation has been done. StepMania 5.1 does not face this problem. I have not yet tested 5.0.12 for this.

However, on the latest 5.3, a song that with the note additions would have summed up to 654 rows on the baseline run ended up in three test runs with 611 rows the first, 618 the second, and 560 the third. No changes were made to the note addition mods used nor the song or difficulty used in testing this, only SuperShuffle was added in for the three non-baseline runs.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Scraticus** [comment]
Fixed in 4.9.7... finally!!
