### ISSUE TITLE
[Unexpected Behavior] RATE - mismatch between audio and background video playback speeds

### ISSUE THREAD

**Issue by SilentTempest83** [TeamRizu/OutFox#220]
In all versions newer than Alpha 4.9.0 [2020-10-07], adjusting the RATE option will adjust the playback rate of the music, but does not adjust the playback rate of background videos.  This behavior appears to be present when using any theme (Soundwaves or 3rd party themes).  Behavior performs as expected in Alpha 4.9.0 [2020-10-07] and earlier.

**What you're using**
RATE option under SONG MODIFIERS.  Behavior tested using options 0.5 / 0.8 / 1.5

**Expected behavior**
Both audio and background video will play at the same RATE set in SONG MODIFIERS.  ie: if rate is set to 0.5, both song and background video will play at half of normal speed / if rate is set to 1.5, both song and background video will play at one and a half times normal speed / and so on...

**EXAMPLE:**

https://user-images.githubusercontent.com/68167805/109235801-ffc60f00-7793-11eb-85a6-59952a4b64ea.mp4

**Comment by SilentTempest83** [comment]
Tested this behavior on the following versions on 2 separate Windows 10 machines (1 using NVIDIA Graphics, the other using Intel HD Graphics):

(Unexpected Behavior) v5.3.0-alpha.4.9.7GG
(Unexpected Behavior) Alpha 4.9.6 +Windows HF
(Unexpected Behavior) Alpha 4.9.5
(Unexpected Behavior) Alpha 4.9.1
(Expected Behavior) Alpha 4.9.0HF
(Expected Behavior) Alpha 4.8.5 Final
(Expected Behavior) Alpha 4.8.2 Final

**Comment by Jousway** [comment]
fixed, will be in next release, thanks for report, the issue was old SM code and I changed the way the DeltaTime works for videos.

**Comment by Scraticus** [comment]
Fixed in 4.9.7.3
