### ISSUE TITLE
[BUG] Python23IO Inuput not recognized on Program initialization, Causing program hangs

### ISSUE THREAD

**Issue by geoff10e** [TeamRizu/OutFox#222]
**Please give System Info**
OS: *Windows 7*
CPU: *i5-6500*
GPU: *R7 240*
Storage: *500gb sdd*

**Please give your StepMania Info**
StepMania Version: *StepMania5.3-git-768a687e88*
Theme: *Default*

**Describe the problem**
 SM 5.3 hangs after launch with input drivers set to use the SuperNova Betson Cabinet Python2.

**Reproduction Steps**
1. Make the following changes in ./Saves/Preferences.ini
> InputDrivers=Python23IO
> Python23IO_HDXB_DEV_ID=3
> Python23IO_HDXB_PORT=
> Python23IO_Mode=SDP2IO
> Python23IO_P2IO_EXTIO=1
2. Start Stepmania 5.3
3. Program loads until Arcade button is used, then program hangs and stops responding.

**Describe what should happen**
Stepmania should perform similarly to SM 5.1 Starworlds(the package that the Python23IO libraries were adapted from) in that after making the changes above to the Preferences.ini, lights and at the very least arcade inputs are recognized and usable by the game.

**Logs and Additional context**
Attached are logs and preferences from both Outfox(SM5.3) and Starworlds(SM5.1)
[log-outfox.txt](https://github.com/TeamRizu/OutFox/files/6051910/log-outfox.txt)
[log-starworlds.txt](https://github.com/TeamRizu/OutFox/files/6051913/log-starworlds.txt)
[Preferences-starworlds.ini.txt](https://github.com/TeamRizu/OutFox/files/6051918/Preferences-starworlds.ini.txt)
[Preferences-outfox.ini.txt](https://github.com/TeamRizu/OutFox/files/6051919/Preferences-outfox.ini.txt)

**Comment by Scraticus** [comment]
This is a bug in the loader we use for libusb, investigating a solution

**Comment by Scraticus** [comment]
This should be fixed in 4.9.8, please read the changelog on how it works.
