### ISSUE TITLE
[BUG] Soundwaves: the NPS graph can go out of bounds (on the top)

### ISSUE THREAD

**Issue by Kaede573** [TeamRizu/OutFox#227]
It seems to be more common/pronounced on charts with low NPS.

![2021-03-06_215748](https://user-images.githubusercontent.com/18552062/110220628-158bb080-7ec7-11eb-85c0-4a76ffd901f1.jpg)
^ dance

![soundwaves_nps_oob](https://user-images.githubusercontent.com/18552062/110220632-1d4b5500-7ec7-11eb-8ffa-cfe9b3d8e50a.jpg)
^ pump. Simfile: [Memories of You (ATLUS Meguro Remix).ssc.txt](https://github.com/TeamRizu/OutFox/files/6096105/Memories.of.You.ATLUS.Meguro.Remix.ssc.txt)

Attached logs but I think they don't show anything.

[log.txt](https://github.com/TeamRizu/OutFox/files/6096104/log.txt)

**Comment by JoseVarelaP** [comment]
Fixed for the next version.
<img width="1192" alt="Captura de Pantalla 2021-03-27 a la(s) 11 43 08" src="https://user-images.githubusercontent.com/23246027/112729427-a4ea1980-8ef1-11eb-86a5-e2bd10bf8a91.png">
