### ISSUE TITLE
"Center 1 Player" option set to ON overlaps note fields for player 1 and player 2 in 2-player mode

### ISSUE THREAD

**Issue by SilentTempest83** [TeamRizu/OutFox#24]
When the `Center 1 Player` option is toggled `ON` in settings with the game type set to `para`, and the user enters 2 Player mode, the note fields for both players (P1 & P2) are overlapped in the center of the screen.  This behaviour was not present in the RC1 build from 2020/06/19 and earlier, but is present in RC2 (2020/06/23) and RC3 (2020/07/01).  The issue shows up in both the theme my group is working on, as well as the default theme (Soundwaves) or when using different noteskins, so the issue does not appear to be theme or noteskin specific.  Screenshots have been provided for reference.

**RC1: Custom Theme**
![RC1 - Custom Theme](https://user-images.githubusercontent.com/68167805/87234403-1438d100-c396-11ea-8dd8-e1c6cccc200c.jpg)
**RC1: Default (Soundwaves) Theme**
![RC1 - Soundwaves Theme](https://user-images.githubusercontent.com/68167805/87234411-2b77be80-c396-11ea-8e4d-637f5adcf749.jpg)

**RC2: Custom Theme**
![RC2 - Custom Theme](https://user-images.githubusercontent.com/68167805/87234412-2fa3dc00-c396-11ea-844a-9e052396623a.jpg)
**RC2: Default (Soundwaves) Theme**
![RC2 - Soundwaves Theme](https://user-images.githubusercontent.com/68167805/87234414-32063600-c396-11ea-9725-76b7fc313587.jpg)

**RC3: Custom Theme**
![RC3 - Custom Theme](https://user-images.githubusercontent.com/68167805/87234415-3599bd00-c396-11ea-8886-2fc710ed03aa.jpg)
**RC3: Default (Soundwaves) Theme**
![RC3 - Soundwaves Theme](https://user-images.githubusercontent.com/68167805/87234417-392d4400-c396-11ea-8dca-6390220ffa43.jpg)

**Comment by JoseVarelaP** [comment]
We have identified the issue, but it will take time to fix it, so we will push it for Alpha 5 or sooner.

**Comment by JoseVarelaP** [comment]
The issue has now been fixed on commit 9b158c.

**Comment by moruzerinho6** [comment]
Hello @SilentTempest83 

Project Moondance Discord Moderator here, a while ago we created a bug hunter system, users who make issue on this repository gain points and can be rewarded in our discord, so I'm here to ask, are you in Project Moondance discord?

If not, you can join using this link: https://discord.gg/3DgsbSg

If you don't wish to join, that's okay. Please be sure to contact any moderator if you join.
