### ISSUE TITLE
FPS down from ~60fps to ~30fps 4.6 RC3 and 4.6.0 with GLAD

### ISSUE THREAD

**Issue by LightningSkunk** [TeamRizu/OutFox#25]
5.3 Alpha 4.6 RC3 and 5.3 Alpha 4.6.0
Intel Core i5-2400
NVIDIA GeForce 210
8GB RAM
128GB SSD
Windows 10 1909 x64

glad rendering
wait for vertical sync: No
SoundDevice=WaveOut

I had skipped installing RC3 until now to verify, but my FPS has dropped from about 59fps to about 31fps in-game with versions 4.6 RC3 and 4.6.0. This does not happen in RC2 or earlier. I also made sure that I am on the latest GPU drivers.

However, I am able to render in ~65-70fps when switching to "OpenGL" from GLAD in 4.6.0

My preferences files are in the attached zip as is a system hardware summary screenshot for a bit more detail if needed. 

Thank you for all the great work you are doing!

[preferences.zip](https://github.com/TeamRizu/OutFox/files/4908785/preferences.zip)
![systemSummary](https://user-images.githubusercontent.com/68192874/87250852-bd82d400-c435-11ea-9a64-30d844a9fc00.png)

**Comment by moruzerinho6** [comment]
This is weird, I think that's some NVIDIA global setting that I also have to deal with sometimes.

Go into NVIDIA Control Panel
![image](https://user-images.githubusercontent.com/58047457/87251124-c11b5880-c43f-11ea-8890-0ab006df399a.png)

Select the 2° Option in 3D Settings
![image](https://user-images.githubusercontent.com/58047457/87251143-d6908280-c43f-11ea-8a9e-39cdd3bab1f4.png)

Select the 2° Tab "Program Configuration"
![image](https://user-images.githubusercontent.com/58047457/87251157-f1fb8d80-c43f-11ea-815e-2b7aa555ebae.png)

Click Add and **see if the newest version of stepmania that you have installed and is having issues with is here**
![image](https://user-images.githubusercontent.com/58047457/87251175-0f305c00-c440-11ea-8f90-7ab0054087b6.png)

**If not**, click Search and select the StepMania.exe inside the Program folder
![image](https://user-images.githubusercontent.com/58047457/87251192-3129de80-c440-11ea-956a-1ef235a3a4f5.png)

Now that you have Stepmania selected, go down into the last options or try to find one that relates to "Max FPS"
![image](https://user-images.githubusercontent.com/58047457/87251212-54548e00-c440-11ea-9a07-b7fd818e61c0.png)

Select Off
![image](https://user-images.githubusercontent.com/58047457/87251223-65050400-c440-11ea-9d4f-b9124ef9b61f.png)

Now click Apply.

Restart the game, disable Vsync (F3 + 7, be sure to be ``off``) and enable stats (F3 + 6 be sure to be ``on``)

Tell me if it works!

**Comment by LightningSkunk** [comment]
Thanks. It was not there in NVIDIA control panel. I added it, then set "Vertical Sync" to Off, and hit apply. 
I checked the F3 menu. VSync is off and rendering stats are on (that's how I could tell my fps before).

Sadly, it made no difference.

:::switches back to OpenGL:::

**Comment by moruzerinho6** [comment]
Oh, it's only when using GLAD?

**Comment by LightningSkunk** [comment]
Yes.

**Comment by moruzerinho6** [comment]
Well............................................................................................that's unexpected.

**Comment by LightningSkunk** [comment]
lol, um, surprise!? 

Tbh. I only started using OpenGL today in trying stuff and that seems to work. 

I choose to blame triangles :-P

**Comment by LightningSkunk** [comment]
Logs from config with GLAD

[log_4.6.0_GLAD.txt](https://github.com/TeamRizu/OutFox/files/4942217/log_4.6.0_GLAD.txt)
[log_4.6RC2_GLAD.txt](https://github.com/TeamRizu/OutFox/files/4942219/log_4.6RC2_GLAD.txt)

**Comment by Scraticus** [comment]
Done some corrections and worked through this with Lightning in the Discord, closing as it's fixed in the next release. 

Thanks for reporting!
