### ISSUE TITLE
Crash when trying to play "Can't Stop the Feeling" from SPEIRMIX

### ISSUE THREAD

**Issue by torinjacobson** [TeamRizu/OutFox#26]
Get this this song/simfile: https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=29458
In OutFox, Game Start -> Single -> Normal
Find "Can't Stop the Feeling"
Change difficulty to Hard
OutFox 5.3 reliably crashes every time before any arrows arrive. Other songs work great.

**Comment by torinjacobson** [comment]
The log:
[log.txt](https://github.com/TeamRizu/OutFox/files/4910841/log.txt)

**Comment by torinjacobson** [comment]
Appears to be fixed in 4.6.0 final

**Comment by torinjacobson** [comment]
Root cause appears to have been the video file. Removing the video fixed it in RC3. Works with video in 4.6.0 final.

**Comment by moruzerinho6** [comment]
Yeah, this versions comes with a fix for the dependence used in videos. Thanks for reporting anyway
