### ISSUE TITLE
[BUG] Default keybinds reset themselves, override custom keybinds on same keys

### ISSUE THREAD

**Issue by Areldyb** [TeamRizu/OutFox#278]
**System and StepMania info**

OS: Observed on Win10 and Linux
StepMania Version: v5.3.0-alpha.4.9.7GG, may also have been present on 4.9.7 but I no longer have it to confirm
Theme: Soundwaves

**Describe the problem**

When setting a custom keybind on a key that already has a default keybind, the default keybind reappears after restarting the game. Both the custom and default keybinds are listed on the Config Key/Joy Mappings screen, but only the default keybind has an effect and the custom keybind does nothing.

Example: Set the arrow keys to P2 instead of P1, save your key mappings to disk, then restart the game and check the key mappings. Keybinds for the arrow keys will be shown under both P1-default and P2-primary, and will only affect P1 instead of P2 as assigned.

**Describe what should happen**

Default keybinds should not take precedence over custom keybinds. I typically set P1 to WASD and P2 to the arrow keys, so this is a real pain.

**Comment by SHRMP0** [comment]
Thanks for your report, but this bug was already identified and fixed a few days ago. There'll be a new release soon with this correction soon.

**Comment by Areldyb** [comment]
Good to know, sorry I missed that one.
