### ISSUE TITLE
Text input forces US QWERTY

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#28]
## Before doing such issue, please make sure you're using the latest version of the game.

**What you're using**

When I input text in any text field, it ignores the current keyboard layout that I'm using (Dvorak, Colemak, QWERTZ, AZERTY, Bépo, ...) and forces QWERTY. This also breaks entry of any language using any character outside ASCII, including Spanish, German, Italian, Portuguese, French, Polish, Japanese, Chinese, Korean, Vietnamese, Russian, Arabic, ...

**Expected behavior**

When I press a key, it should enter the corresponding character *in the selected keyboard layout*.

Related to Issue #13 - Likely caused by the same underlying problem: outdated/limited text input handlers.

**Comment by Scraticus** [comment]
I have added the beginnings of support for new input layouts in outfox.

Will update when this is further along.
