### ISSUE TITLE
MacOS Big Sur crash at startup

### ISSUE THREAD

**Issue by Gustiviy** [TeamRizu/OutFox#281]
![image](https://user-images.githubusercontent.com/79268434/111189950-4783cd80-85bf-11eb-81e5-d6d2c4a79d37.png)

When i open it it just closes with no error or anything

**Comment by SHRMP0** [comment]
Did you change your macOS security settings to allow OutFox, [as described on the website's FAQ page](https://projectmoon.dance/faq)? Also, please make sure you downloaded the correct version for you system architecture (Apple M1 builds won't work on Intel/x86 Macs)
