### ISSUE TITLE
[Game Crash] Windows 10 Fresh Update

### ISSUE THREAD

**Issue by LionHardt544** [TeamRizu/OutFox#282]
1. I was in another window trying to figure out how to make my PPP controller work.  As far as I could tell, no specific action was taken that triggered the crash.  I was pressing the start button on my brand new PPP controller, testing if the program would respond, but I had hit start several times already without incident
2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6145463/crashinfo.txt)

3. Upload the info.txt and log.txt (GameFolder/Logs)
[info.txt](https://github.com/TeamRizu/OutFox/files/6145465/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6145466/log.txt)

1. Start the game
2. Stay on opening menu screen. Either stay alt-tabbed for a few minutes or press start on a brand new controller.  Not sure what caused it.
4. Game crashed

I had just swapped from XInput to HIDAPI on the Old Joystick Mapping option.  When I first set up the game, HIDAPI was selected by default and my controller still didn't work.  Switching to XInput didn't fix my controller, as one might expect, and then switching back again didn't work.  The issue could lie in the switching back and forth maybe.  I'm not sure but I wanted to be as helpful as possible.

**Comment by Scraticus** [comment]
you need to ensure the ppp pad is connected at the beginning of the game.

it is _not_ mapped by default, so you need to map it in the input mapping screen, as some like to use the controller buttons but most dont (when they are on the floor!)

we've not seen this crash before, so it looks like you've found some really weird behaviour likely with the para theme.

We'll check it out for sure.

**Comment by Scraticus** [comment]
This bug is fixed on 4.9.9. Sorry for the delay in response, it was a tricky one!
