### ISSUE TITLE
When a video in BGChanges is called more than once, it does not restart properly the 2nd time and onward

### ISSUE THREAD

**Issue by TheT113** [TeamRizu/OutFox#283]
I feel like I heard about this issue a long time ago, predating Outfox, but I just got back into StepMania and found it still be the case, even on the most recent version 4.9.7gg. EDIT: additional note, I am on Windows 10. Not sure if any other info is needed.

What occurs is: if you create a BGChanges script that uses the same videos multiple times, each time a video plays again, it starts off by playing what looks to be either the last frame of where it left off the last time, before jumping back to the start of it's video. This causes video sequences to look extremely jumpy and disorienting.

Intended behavior: When it starts playing the video again the next time, it should start from the beginning, not play a half-second of where it left off and then jump back to the beginning.

I will paste an excerpt of the script:
23.750=blackhole1.avi=1.000=1=1=1,
27.750=bunny1.avi=2.000=0=1=1,
29.750=bunny2.avi=1.000=0=1=1,
31.750=blackhole1.avi=1.000=0=1=1,
35.750=bunny1.avi=2.000=0=1=1,
37.750=bunny2.avi=1.000=0=1=1,

I brought it up on the Discord but it didn't fully seem like it was a known issue, so I figure I better bring it up here.

Thanks for all ya'll do!

**Comment by Scraticus** [comment]
Can you confirm is this is still a problem or not?

**Comment by Scraticus** [comment]
Closing as no response, do open a new issue if you find it again!
