### ISSUE TITLE
[Unexpected Behavior] Fatal Error

### ISSUE THREAD

**Issue by xTHECONNORx** [TeamRizu/OutFox#289]
Well, when I was playing your SM 5.3 Theme, it was behaving as normal when all of a sudden...

![Fatal Error 01](https://user-images.githubusercontent.com/81449746/112703667-04461c00-8e55-11eb-9f8d-92be70e17b1b.png)

When I clicked abort, I got this:

![Fatal Error 02](https://user-images.githubusercontent.com/81449746/112703688-16c05580-8e55-11eb-9b1f-64e51f4b7e4b.png)

**Comment by SheepyChris** [comment]
This error is more related to the theme utilized, made by a community member, and not OutFox itself. If you press the Ignore button or run the game in dedicated fullscreen mode, the error should be skipped. I would recommend further submitting similar bugs reports to the theme repository located here: https://github.com/Nepumi/MusicMemories

**Comment by ListenerJubatus** [comment]
The issue tracker is not for reporting bugs with third-party content _unless_ it is a bona fide bug with the software that is exposed by the theme.
