### ISSUE TITLE
[Nitpick] ScreenJukebox background BGA's sprites not being animated

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#294]
ScreenJukebox background BGA's sprites are not being animated.
On 4.9.7.
Also I noticed this happens on 5.1 too. It could be an old thing.
Please check ScreenDemonstration too just in case.

**Comment by MrThatKid** [comment]
Would you be willing to elaborate on this?

**Comment by EngineMachiner** [comment]
All the gameplay BGA's background layer sprites didn't animate in that version. I tried checking with 0.4.14.1 but I'm getting a hard crash at the ScreenJukebox screen. :l
[log.txt](https://github.com/TeamRizu/OutFox/files/8767541/log.txt)

**Comment by EngineMachiner** [comment]
Confirmed that still happens in 4.15.1.

**Comment by EngineMachiner** [comment]
This could have been on my side and I've tested on a recent test build so it's not happening anymore.
