### ISSUE TITLE
[Unexpected Behavior] Outfox not reading .SSC file?

### ISSUE THREAD

**Issue by DracoOfZeradaith** [TeamRizu/OutFox#295]
I seem to be having trouble opening .SSC files in Stepmania Outfox 5.3. I just downloaded and installed the newest version today. It claims that the song is missing a music file. I didn't realize that there were any other file extensions other than .sm and .dwi, so I'm kinda at a loss as to what to do about this one. Can anyone assist the ignorant? <3
![Screenshot 2021-04-01 115911](https://user-images.githubusercontent.com/81766346/113327371-de06fd00-92e8-11eb-851f-1ad6a8ab47b4.jpg)

**Comment by Scraticus** [comment]
Can you check on whether the SSC does actually list a song file?
 
 We have had no reports of issues before, so could you check the logs and see? they usually contain helpful information.

**Comment by DracoOfZeradaith** [comment]
Thanks so much for responding! So, I found this in the logfile:

/////////////////////////////////////////
00:03.635: WARNING: Main title or music file for '/Songs/Fanmade Stepfiles/Sonic Mania VOCAL THEME/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
/////////////////////////////////////////
00:03.644: Song '/Songs/Fanmade Stepfiles/Sonic Mania VOCAL THEME/' points to a music file that doesn't exist, found music file '?MANIA? -Sonic Mania VOCAL THEME-.mp3'
/////////////////////////////////////////
00:03.644: WARNING: Sound file /Songs/Fanmade Stepfiles/Sonic Mania VOCAL THEME/?MANIA? -Sonic Mania VOCAL THEME-.mp3 couldn't be opened: Invalid argument. Please check it is not corrupted and redownload the file.
/////////////////////////////////////////
00:03.644: Graphic file "/Songs/Fanmade Stepfiles/Sonic Mania VOCAL THEME/?MANIA? -Sonic Mania VOCAL THEME-.png" couldn't be loaded: Invalid argument

I have spoken with the stepfile's creator. He has reuploaded the files and I have downloaded them again to no avail. I have tested the MP3 and it opens just fine.

**Comment by Scraticus** [comment]
This is a problem with non-unicode friendly characters used in the song title. delete whatever is either side of 'MANIA' in the song title, and the game can find it.

This is a long running issue which requires a pretty hefty rewrite of the file serving system within the game, and we've only been able to tackle it in stages at the moment.

A quick fix is to just delete whatever is making the ? on the filename for the banner and song, and it should work, you may need to edit the .ssc to do the same (or ask the simfile author to do this for you, as it's a unicode to UTF issue)

I'll leave this open as it is a bug, but it will take a while to fix completely.

**Comment by DracoOfZeradaith** [comment]
That totally resolved it! Thanks again for all your help!! :D
