### ISSUE TITLE
[Game Crash] Crash upon booting title screen, complete fresh installation on 4.9.7, Windows

### ISSUE THREAD

**Issue by christianyvdo** [TeamRizu/OutFox#296]
OS: Windows 10
CPU: AMD Ryzen 7 3700x 8-Core 3.6GHZ
GPU: AMD Radeon RX 5700

I wanted to switch from Stepmania 5.3 to Stepmania Outfox 4.9.7 since, I read OutFox had native MIDI support. I completely uninstalled and deleted Stepmania 5.3, downloaded and installed OutFox-5.3.0-alpha-4.9.7GG-Win32-date-20210224, ran the executable, saw the game window briefly (~0.5 sec), the game crashed. Game crashes similarly every time I try to run the exe.

[info.txt](https://github.com/TeamRizu/OutFox/files/6247431/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6247433/log.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6247428/crashinfo.txt)

I am running a lot of other audio devices as seen in the log. I still to see how well the MIDI runs on Outfox since I wasn't successful trying to bodge MIDI input into base Stepmania 5.3 , so hopefully this is a simple fix :(

**Comment by Scraticus** [comment]
There is a bug at the moment if a lot of midi input is received on screen changes, it can cause a crash. Our MIDI input works fine, but this is the only known bug at the moment. Do check your device is not sending lots of midi signals when going through screens. We are investigating a fix for this one.

**Comment by christianyvdo** [comment]
I disabled my other devices, except the current audio input and output and my Nektar Impact GX61 MIDI controller and the game runs fine! I just did the same with my Alesis Strike Multipad, and it turns out it had a "Global Sync" setting that kept sending MIDI program changes. I just shut it off and things are working smoothly! Thanks for helping me out!

**Comment by Scraticus** [comment]
Thanks for letting me know! 

I will keep this open as a reminder while we fix the issue over the coming months if that's ok with you!

**Comment by christianyvdo** [comment]
Yup! That's fine!

**Comment by Scraticus** [comment]
We have a new midi driver coming in 4.9.9 which should fix some of the issues you have with this, we no longer crash on boot with midi installed.

Please ensure you read the new changelog about it as there are a few important bits to note
