### ISSUE TITLE
[BUG] Player joining in song select shows the default avatar

### ISSUE THREAD

**Issue by Joehuu** [TeamRizu/OutFox#297]
**Give an example of what is wrong**

The player doesn't show its set avatar after joining in song select. Going to other screens will fix it.

https://user-images.githubusercontent.com/35318437/113380643-a2dcec00-9331-11eb-9353-dfcfab4b32a0.mov

**Given an example of what it should look like**

It should be the set one, not default.

**Comment by Scraticus** [comment]
Likely a tweak in the playerjoined() code is required, thanks for reporting!

**Comment by JoseVarelaP** [comment]
Just fixed this.

https://user-images.githubusercontent.com/23246027/113383532-60231000-9341-11eb-9ab3-98da6321d0f5.mov
