### ISSUE TITLE
[Nitpick] There's still cmd in the fallback theme

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#298]
While most cmd code has been removed from OutFox, there are still some calls of it in fallback, which can slowdown the game for everyone on every theme.

Proper testing will be required so no theme is affected after the changes and everything behaves the same.

**Comment by moruzerinho6** [comment]
Fixed, a test package has been generated and being tested by our alpha testers.

**Comment by Scraticus** [comment]
Fixed in 4.9.8
