### ISSUE TITLE
[BUG] Native PIUIO support not working on Windows

### ISSUE THREAD

**Issue by Gabrimax98** [TeamRizu/OutFox#299]
**Please give System Info**

OS: Windows 7 Embedded x64, Windows 10 build 19041

**Please give your StepMania Info**

Outfox Version: Outfox Alpha 4.9.7GG
Theme: Any

**Describe the problem**

My PIUIO (EZ-USB FX2) is not getting recognized as an input, no matter if i leave the device without a driver or i install libusb-win32/WinUSB via Zadig.
Tested behaviour on both Windows 7 and Windows 10, exact same issue. The IO does work if programs like _piuio2vjoy_ or _io2key_ are installed.

As a test, i tried editing **gamecontrollerdb.txt** to include Windows in the _platform_ section of PIUIO Input, but still won't work.

**Describe what should happen**

The IO should get recognized by the Joystick subsystem as "PIUIO input", but logs show no sign of it being recognized.

**Logs and Additional context**
[log.txt](https://github.com/TeamRizu/OutFox/files/6252405/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/6252406/userlog.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/6252408/info.txt)

**Comment by Scraticus** [comment]
After spending a few days on this, and speaking with Din, i think the benefits versus the options for the PIUIO native support would be a waste of time to implement, when there are known solutions, (and tbh, you should be using linux for this pad!)

I'll have a muse over whether or not it's worth the development time to conclude and add it to outfox.

**Comment by Gabrimax98** [comment]
It's totally fine! Worst case scenario I'll recommend his piuio2vjoy solution whenever people ask for it, as it isn't really that hard to install and get running, and apart from his program required to be opened before playing. Don't lose too much time on making it native as it was more a completion fact rather than a complete lack of support.

**Comment by Scraticus** [comment]
This one is way too niche, and as we found out, it's for a version of the board which runs better under linux as it is. Will close this as we've run the course of investigating.
