### ISSUE TITLE
Switching languages doesn't update all strings

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#3]
**Most constant way to reproduce**
1° Start the game
2° Go to Options
3° User Experience
4° Appearence Options
5° Select any other language
6° Exit the screen and go to theme options
7° Now you'll see that many lines are still with the strings of the old language.

**Solution for now**
Restart the game.

**Video example**
Switching languages: https://youtu.be/-m8t6NmGEC8
Restart to fix: https://www.youtube.com/watch?v=sNzvnj_bQpQ

Doing F2 + Shift (reload metrics) before step 7° doesn't not fix the issue.

The theme options screen is not the only affected, both me and Moneko (another translator) have reported more screens with strings not updating, but theme options seems to be the most consistent one.

**Comment by JoseVarelaP** [comment]
Most reasonable explanation for this is that the Lua hook is not updating when switching languages, but only metrics data. We would need to update the lua globals to ensure proper updates.

**Comment by Jousway** [comment]
apparently I did a commit on Feb 18, 2023 thats called,
5660611 Updateluaglobals on language change. 
this should have fixed this issue, can you check if it still happens @moruzerinho6

**Comment by moruzerinho6** [comment]
The issue is fixed.

**Comment by Jousway** [comment]
tnx bud
