### ISSUE TITLE
[Bug?? Maybe Not???] Audio gets louder as time progresses

### ISSUE THREAD

**Issue by AppleArcade120** [TeamRizu/OutFox#301]
(I haven't made an issue in forever so I don't know what I'm doing)
I'm not on the latest build of OutFox (and I should be to be honest. I'm highly sure updating will fix this issue even though I've never had this happen before [I think I'm on 4.9]).
The audio gets louder as time goes on, but when I switch songs it gets quiet and then does the same thing??
Attached are 2 videos (through Google Drive, because they are way bigger than 10MB. Thanks, phone camera!) For some reason, it's not noticeable in the first video but it's very very noticeable in person, and it's slightly noticeable in the second video...?
[First Video (not very noticeable)](https://drive.google.com/file/d/1ro0IZrfgaKmyL0hMjnqRdFol9L2JX8Fz/view?usp=sharing)
[Second Video (more noticeable, but still not that much)](https://drive.google.com/file/d/17ndlWRO8RnPbJLlcHorcl2TqV3EO40Ap/view?usp=sharing)

**Comment by SHRMP0** [comment]
Can you test again on the latest build (4.9.7GG)?

**Comment by AppleArcade120** [comment]
Yup! Will do later today, and then I'll report back.

**Comment by AppleArcade120** [comment]
Tested a few days ago (sorry for keeping you waiting!), and it turns out it's just an issue with my TV... nice.
