### ISSUE TITLE
[BUG] Background videos are not played back in original speed (too quickly)

### ISSUE THREAD

**Issue by JavaJeremy** [TeamRizu/OutFox#304]
OS: Win10
CPU: AMD Ryzen 5 1600 Six-Core Processor 3.20 GHz
GPU: GeForce GTX 1050 Ti
Storage: Seagate ST2000DM006 HDD Barracuda

StepMania 5.3 Outfox Alpha date-20210224
Theme: Default

In "Endless"-Mode the background video ist played back too fast sometimes.
Once it happens, the videos of all following songs are also played back too fast.

I don't know exactly how to reproduce it, because sometimes the video starts playing back too fast starting at the 2nd song, and sometimes it happens later. 
I thought it had something to do with the filetype of the video but I couldn't find a correlation yet: 
It happened to me in the following cases:
- 1st case:
1. Song (background video type: .mp4) - normal speed
2. Song (background video type: .mpg) - too fast

Here is a screen recording I made of this problem - you can see the first song finishing with the background video running at normal speed and then the second song starting with the background video being too fast:
https://user-images.githubusercontent.com/7582225/114309884-1082d800-9ae9-11eb-8506-391eaa03320c.mp4
- 2nd case:
1. Song (background video type: .mpg) - normal speed
2. Song (background video type: .mpg) - normal speed
3. Song - same as first Song (background video type: .mpg) - too fast

Maybe it has something to do with the same issue that caused [a similar problem with the banner videos](https://github.com/TeamRizu/OutFox/issues/129)?

**Comment by moruzerinho6** [comment]
> StepMania 5.3 Outfox Alpha date-20210220

Based on your build date, you're using [4.9.7OF](https://github.com/TeamRizu/OutFox/releases/tag/OF4.9.7), can you check if this issues still exists while using [4.9.7GG](https://github.com/TeamRizu/OutFox/releases/tag/OF4.9.7GG)?

**Comment by JavaJeremy** [comment]
yes, I just updated it and unfortunately the problem still exists. 
It happened again around the 5th song in endless mode:
before was a song with .mp4 bg-video and that problem was with an .mpg bg-video

**Comment by moruzerinho6** [comment]
Can you test if this still happen while using the latest build 4.9.8?

**Comment by JavaJeremy** [comment]
Yes, the problem still exists (the file I'm opening in Windows is called "StepMania 5.3 Outfox Alpha date-20210425") and I'm slowly starting to wonder if I'll just be asked if it works now every new version without it actually being fixed lol
It happened again in endless mode after a few songs, and the video was .mpg again - so my sample size is growing and I'm getting more and more sure it must have something to do with that .mpg file type.

**Comment by Scraticus** [comment]
Your sarcasm is not welcome when we are actually trying to solve these issues. Keep that out of posting here, because it berates the team and makes you look a bit of an ass.

We have fixed several of the rate issues in the last build, but we will need these mpg files, which i bet are ancient, and could be encoded into a format that is modern.

So instead of trying to be sarcastic, provide logs, and a link to the MPG files in question, please.
