### ISSUE TITLE
[BUG] Not switching from fullscreen to window mode correctly on Linux

### ISSUE THREAD

**Issue by eliasYFGM** [TeamRizu/OutFox#306]
**Please give System Info**

OS: Xubuntu 18.04 64-bits

CPU: Intel Core i3-4160

GPU: Intel HD Graphics 4400

Storage: 1 TB SATA III Toshiba PC P300

**Please give your StepMania Info**

StepMania Version: v5.3.0-alpha.4.9.7GG
Theme: Soundwaves (default, but it happens with all themes)

**Describe the problem**

StepMania OutFox doesn't switch from fullscreen to window mode correctly. Instead, it stays on fullscreen and only makes the game screen smaller, usually occuping only the bottom-left part of the entire screen, and the rest of the screen is only black.

This occurs both in "Exclusive mode" and "Borderless window" modes.

**Describe what should happen**

Switch to window mode completely, without leaving a huge black space on the screen.

**Logs and Additional context**

1. Go into the game folder
2. Open the Logs folder
3. Grab every file in there and post with the issue.
4. Go back to the game folder, if there's an crashinfo.txt then send it too

[info.txt](https://github.com/TeamRizu/OutFox/files/6315269/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6315270/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/6315271/userlog.txt)

![Captura de pantalla_2021-04-14_23-28-08](https://user-images.githubusercontent.com/17137552/114817044-ed715600-9d7e-11eb-8e40-21c27b1821a5.png)
This is after I tried switching from a fullscreen 1280x1024 mode to a 1024x768 window mode.

**Comment by concubidated** [comment]
After you switch the resolution, if you exit, and reopen, does it display correctly?

**Comment by JustMoneko** [comment]
I can replicate the same behaviour on Windows 10 with Nvidia's 1050Ti card. In my case after lowering resolution in settings and then changing from fullscreen to windowed mode, it still remains fullscreen. Using Alt+Enter actually switches from fullscreen to windowed and vice versa.

**Comment by eliasYFGM** [comment]
> After you switch the resolution, if you exit, and reopen, does it display correctly?

Yes it does. I have to restart OutFox so that it can restore to window mode completely.

> I can replicate the same behaviour on Windows 10 with Nvidia's 1050Ti card. In my case after lowering resolution in settings and then changing from fullscreen to windowed mode, it still remains fullscreen. Using Alt+Enter actually switches from fullscreen to windowed and vice versa.

In my case, using Alt+Enter actually switches to window mode, but the window does not revert back to the internal resolution (output resolution) that I'm using and it has the same size as my desktop resolution, again, with the game screen occuping only the bottom-left part of the window:

![Captura de pantalla_2021-04-15_15-18-54](https://user-images.githubusercontent.com/17137552/114933464-4e8c3e80-9dfe-11eb-9637-1255d2a00381.png)

**Comment by Scraticus** [comment]
Long Time, but this is fixed in 4.9.9.

Thanks for reporting it!
