### ISSUE TITLE
[BUG] some notes are invisible on gh charts if using autogen steps on other gamemodes

### ISSUE THREAD

**Issue by arceuss** [TeamRizu/OutFox#308]
already mentioned it in the discord
its essentially just autogen doesnt know about gh

**Comment by arceuss** [comment]
![image](https://user-images.githubusercontent.com/28229451/115101254-b1193380-9eff-11eb-8db3-27b150b43858.png)
example if needed

**Comment by Jousway** [comment]
> its essentially just autogen doesnt know about gh
no its not, absolutly not, its because the noteskins dont support hopo's and gems so they arnt shown, I dont consider this a bug cuz you shouldnt use hopo's and gems on dance, but I'm open for opinions from other members.

**Comment by arceuss** [comment]
> 
> 
> > its essentially just autogen doesnt know about gh
> 
> no its not, absolutly not, its because the noteskins dont support hopo's and gems so they arnt shown, I dont consider this a bug cuz you shouldnt use hopo's and gems on dance, but I'm open for opinions from other members.

interesting

**Comment by Scraticus** [comment]
Fixed
