### ISSUE TITLE
[BUG] Hold body texture does not scale properly with zoom-related modifiers like Tiny.

### ISSUE THREAD

**Issue by MrThatKid** [TeamRizu/OutFox#31]
**What you're using**

This is tested with current in-dev versions, the Tiny modifier, a chart with holds, and a noteskin with a distinct start and end point in the hold body texture.

For this, I used Jousway's Cel3D noteskin, and GPOP's "My Story" chart.

I recall this being an issue since at least StepMania 5.1

**Expected behavior**

I'd expect the hold body to properly scale the texture so that the bottomcap does not look visibly out of place. I am unsure how this works with the topcap of a hold.

Here's what it does, and notice how the bottomcap's texture doesn't line up with the body in at least 100% and -100% Tiny.

100% Tiny:

![tiny_bad_small](https://user-images.githubusercontent.com/18648486/87590273-5c5c3a00-c69b-11ea-81f3-ab9cac8707ed.png)

-100% Tiny:

![tiny_bad_large](https://user-images.githubusercontent.com/18648486/87590733-1fdd0e00-c69c-11ea-8836-d3c4d6a1dcc7.png)

**Comment by Jousway** [comment]
Fixed, as confirmed with @MrThatKid, pushed commit up.
