### ISSUE TITLE
[BUG] Proper support for more than 2 letters language files

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#311]
**Please give System Info**

_Not required_

**Please give your StepMania Info**

StepMania Version: 4.9.7GG
Theme: default

**Describe the problem**

Most language files use 2 letters naming such as `en.ini`, `de.ini`... and such files can have their naming defined inside of their own values, such as `en.ini` showing as `English` on the themes. However, if the language file has more than 2 letters, let's say `pt-BR.ini`, it's not possible to show its correct naming on the theme.

**Describe what should happen**

It should be possible to show the language correct name.

**Comment by moruzerinho6** [comment]
A good standard to follow when this is fixed is [ISO 639-X](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

**Comment by Scraticus** [comment]
this is in engine, but needs some other work done first so will close, and then poke you when you can use them.
