### ISSUE TITLE
[BUG] [PMS] / [BMS] Song parser does not recognise LR2 style files

### ISSUE THREAD

**Issue by PachiSystems** [TeamRizu/OutFox#312]
**Please give System Info**

OS: macOS Big Sur 11.2.3 

CPU: Intel i7 Quad-core 1.7GHz

GPU: Intel Iris Plus 645

Storage: 256Gb SSD

RAM: 16Gb LPDDR3 @ 2133MHz

**Please give your StepMania Info**

StepMania Version: Outfox Alpha 4.9.8
Theme: Defualt

**Describe the problem**

Loading LR2 style files results in them not being recognised in popn mode. popn5, 7 and some 9s do not show in song select. Can view them in beat and dance.

**Describe what should happen**

Songs should be playable in popn mode. Squirrel suggested making the bug report. Something about LM2 channels?

**Comment by Scraticus** [comment]
Indeed, confirmed bug.

I mistakenly added channel 12 as the starter, so anything with channel 11-> is missed by the parser. I've fixed this, there is a test build we can sort you with, just ping us in the server :)

**Comment by Scraticus** [comment]
Will be fixed in 4.9.9. Thanks for taking the time to report this and I hope this improves your gameplay. remember to remove your cache when the next build is released, so it can make the new files.
