### ISSUE TITLE
[BUG] A very short Hold/Roll judgement is unnatural

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#315]
**Please give System Info**

OS: Windows10 Pro

CPU: i5-7500 3.4GHz

GPU: GeForce GTX 1060 6GB

Storage: SSD

**Please give your StepMania Info**

StepMania Version: Project OutFox 5.3 Alpha 4.9.8
Theme: Soundwaves(Default)

**Describe the problem**

A very short Hold (or Roll) will result in a MISS if the response is even slightly delayed
If the Tail is reached before the Head is judged, it seems to be a MISS

https://youtu.be/lEt_26J-ORI

**Describe what should happen**

The Judgement width of the Head should be the same regardless of the length of the Body

**Logs and Additional context**

[log.txt](https://github.com/TeamRizu/OutFox/files/6409266/log.txt)

![image](https://user-images.githubusercontent.com/8708955/116777898-ca96af80-aaa9-11eb-8ba3-ec9253b3c731.png)

**Comment by Sudospective** [comment]
An issue related to this problem; notes right after the tail of a hold or roll are near impossible to hit.

**Comment by Scraticus** [comment]
Fixed in 4.9.9, but leaving this open while it's tested

**Comment by Scraticus** [comment]
Confirmed solved in the release candidates, thank you both for letting us know
