### ISSUE TITLE
[Game Crash] yuv720p to rgba issue on arm64 with 4.9.8

### ISSUE THREAD

**Issue by bibusdax** [TeamRizu/OutFox#320]
**Describe how it crashed by giving us those informations:**

The problem is in the included version of the encoding library.
there seems to be a problem with yuv720p to rgba recoding.

In 4.9.7 I could mitigate it by installing a dev-library, but with 4.9.8 on Ubuntu for Arm64 it does not work.

1. What you were doing before it crashed and what action made the game to crash.
The game loads correctly.
A song with video can be selected and run
After the song ends the game crashes and has an error about the library and video conversion.
2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
3. Upload the info.txt and log.txt (GameFolder/Logs)

**Explain how we can reproduce the error**

1. Start the game
2. Play "24K Magic" from SPEIRMIX GALAXY
3. When the music ends: game crashes

**Sreenshots/Videos**

If possible, take screenshots or record the crash happening.

**Additional information**

If there's any information that you think would help us.

You may need to find a better version of the encoding library in the root folder of 4.9.8.
It does not work with SPEIRMIX GALAXY and always crashes at the end of a song with video.

**Comment by Scraticus** [comment]
Could you upload the log files requested please?

Thanks

**Comment by Scraticus** [comment]
Any updates?

**Comment by Scraticus** [comment]
Closing for now, please open a new issue to report this if you still have it
