### ISSUE TITLE
[BUG] Inconsistent Letter Grades In 4.9.8

### ISSUE THREAD

**Issue by germaniums** [TeamRizu/OutFox#321]
**Please give System Info**

OS: Windows 10

CPU: i5-6500

GPU: GTX-1070

Storage: Samsung 970 EVO NVMe

**Please give your StepMania Info**

StepMania Version: 4.9.8
Theme: Soundwaves (Default)

**Describe the problem**

Letter grades are inconsistent despite same percentages.

**Describe what should happen**

In previous Outfox releases, a percentage score mapped 1-to-1 to a letter grade. For example, with my setup, 90% would always be A, 94% would be AA-, etc. With 4.9.8 there is a lot of inconsistency. See example below, songs both played for the first time back to back with near-identical percentage scores have wildly different letter grades. The D- grade I intentionally missed a lot whereas the C+ was a lot of goods/greats, seems like it's being weighed differently under the hood to determine the letter grade despite the same percentage score in the end?

**Logs and Additional context**

My setup is: Judge: 4 (Original); Life difficulty: 3; Flawless score disabled; Game/grading type: DDR

[info.txt](https://github.com/TeamRizu/OutFox/files/6424469/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6424462/log.txt)

![70% C+](https://user-images.githubusercontent.com/7546991/117083485-56bc0780-ad34-11eb-9e90-aa5618a4a0e9.jpg)
![70% D-](https://user-images.githubusercontent.com/7546991/117083499-5f144280-ad34-11eb-9777-ef18f98e860d.jpg)

**Comment by alex-ong** [comment]
> Game/grading type: DDR
Classic DDR (8 ish) is scored differently to pure % based (ITG/modern ddr  style); so that might be related.

**Comment by MrThatKid** [comment]
Hey, could you please re-check this to see if it's still an issue?

**Comment by Scraticus** [comment]
Please reopen if this is still an issue
