### ISSUE TITLE
[Game Crash] (MacOS) Game crashes on startup if it can't load songs/courses within about half a second, (?) requiring the game to be launched multiple times to play.

### ISSUE THREAD

**Issue by StardustAlpha** [TeamRizu/OutFox#325]
**Describe how it crashed by giving us those informations:**

1. What you were doing before it crashed and what action made the game to crash.
opening the game???
2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
I don't see a crashinfo.txt file. Maybe the game didn't get far enough to generate one? (and just to make sure: it should be in the same folder as stepmania.app, right?)
Launching the executable through terminal and experiencing a crash makes terminal say this: [Github Gist Link](https://gist.github.com/StardustAlpha/d4732f5066bec32d431b64a69c00946a)
3. Upload the info.txt and log.txt (GameFolder/Logs)
I don't seem to have a logs folder.

**Explain how we can reproduce the error**

1. Install a bunch of songs. (i have ~480 songs)
2. Open an app or two. (i have three firefox tabs, OBS, system preferences and terminal open. also archive utility)
3. Open OutFox. If the game loads successfully, select Exit and open it again. (try opening more apps or adding more songs if it refuses to crash)
4. OutFox will begin loading songs, but crash before it finishes.
5. Launch OutFox a few more times. It should work after 2 to 5 launches.

**Sreenshots/Videos**

[Youtube video of the thing happening](https://youtu.be/S0cwOf-H_d4)

System Specs:
MacOS High Sierra 10.13.3
Mac mini (Late 2014)
Processor: 2.8 GHz Intel Core i5
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel Iris 1536 MB

**Comment by JoseVarelaP** [comment]
Also, worth pointing out:

> I don't see a crashinfo.txt file. Maybe the game didn't get far enough to generate one? (and just to make sure: it should be in the same folder as stepmania.app, right?)

in MacOS, they're located on the system logs folder.
`~/Library/Logs/StepMania 5.3/`

**Comment by StardustAlpha** [comment]
[info.txt](https://github.com/TeamRizu/OutFox/files/6461415/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6461416/log.txt)
timelog.txt is empty, so i cant upload it
[userlog.txt](https://github.com/TeamRizu/OutFox/files/6461417/userlog.txt)
no crashinfo.txt sadly.

**Comment by Scraticus** [comment]
It seems your mac mini is failing due to the initialisation system used in Metal (it sometimes happens, we aren't perfect ;_; ) but we have changed the way this is done in the next alpha, so 4.9.9 should work as expected.

Will leave open for the moment until we get clarification

**Comment by Scraticus** [comment]
Have you tried again on this? We have a new version coming out really shortly (4.9.9HF4) so this may be better for your mac

**Comment by StardustAlpha** [comment]
I downloaded 4.9.9HF3b, and it seems to work. No more crashes during startup. However, I did update my Mac's operating system (10.13.3 -> 10.13.6) between first reporting this and now, which may have something to do with it.
