### ISSUE TITLE
Severe display corruption on Intel 620

### ISSUE THREAD

**Issue by Chaz6** [TeamRizu/OutFox#33]
installed Stepmania 5.3 Alpha 4.6 RC3 and this is the result when it runs:-

![image](https://user-images.githubusercontent.com/12680/87860171-4072c580-c933-11ea-937d-14399f30d63e.png)

Please let me know if there is any more information I can provide that would be helpful.

**Comment by moruzerinho6** [comment]
log.txt in Logs/log.txt if possible.

**Comment by Scraticus** [comment]
Indeed, we need to know your pc specifics and the logs so we can help identify your problem

**Comment by Chaz6** [comment]
[log.txt](https://github.com/TeamRizu/OutFox/files/4948551/log.txt)

Please see the log file attached. System information follows.

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       LENOVO
System Model:              20LES0GT00
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1910 Mhz
BIOS Version:              LENOVO N25ET54W (1.40 ), 01/07/2020
Total Physical Memory:     16,222 MB
Available Physical Memory: 10,324 MB
Virtual Memory: Max Size:  18,654 MB
Virtual Memory: Available: 11,729 MB
Virtual Memory: In Use:    6,925 MB
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB4565627
                           [02]: KB4537759
                           [03]: KB4557968
                           [04]: KB4560366
                           [05]: KB4561600
                           [06]: KB4566785
                           [07]: KB4565503
```

**Comment by Scraticus** [comment]
are you using a usb video device to display the game on? 

I have not seen a log with a 'displaylink usb device' before, can you elaborate on the use of that for me?

cheers!

**Comment by Chaz6** [comment]
My monitor is connected to a Lenovo dock connected by USB as my laptop does not have a native graphics ouput port. Thanks!

**Comment by moruzerinho6** [comment]
Hello @Chaz6 

Project Moondance Discord Moderator here, a while ago we created a bug hunter system, users who make issue on this repository gain points and can be rewarded in our discord, so I'm here to ask, are you in Project Moondance discord?

If not, you can join using this link: https://discord.gg/3DgsbSg

If you don't wish to join, that's okay. Please be sure to contact any moderator if you join.

**Comment by Scraticus** [comment]
This was a confirmed issue with the intel driver - 8356-8522, and it's not helping with the way microsoft are forcing users onto the DCH based drivers. We sadly cannot fix it as it's a driver issue.

**Comment by Scraticus** [comment]
Just to update if anyone is searching and finding this issue:

If you have a 4th generation Intel CPU to 6th Generation CPU: drivers prior to 8220 work fine, and greater than 8600 seem to work fine.
if you have a 7th generation Intel CPU to 8th Generation CPU(HD 500/HD 600/UHD 600 series): drivers around 8429 work, and greater than 8700 work fine.
If you have a 9th+ generation Intel CPU (UHD 620 etc) higher than 8600 work fine.

**Comment by Scraticus** [comment]
The Iris Pro require 8800+or less than 8200 in version. Remember this is for windows only, linux/mac are not affected by this driver issue.

**Comment by Chaz6** [comment]
Thank you for the useful information!
