### ISSUE TITLE
[BUG] Removing hold notes leaves behind a hold note end that is invisible in the chart editor yet the Autoplay gets it

### ISSUE THREAD

**Issue by jack5github** [TeamRizu/OutFox#331]
**Please give System Info**

OS: Microsoft Windows 10 Home 10.0.19042 Build 19042

CPU: Intel i7-9700F Eight Core CPU

GPU: NVIDIA GeForce GTX 1660 Driver version 466.27

Storage: C: 287/930GB free, E: 1.21TB/1.81TB free, 16GB RAM, 18.3GB Virtual Memory

**Please give your StepMania Info**

StepMania Version: StepMania 3.5-git-58ac2bb65c
Theme: Soundwaves

**Describe the problem**

Upon deleting a hold note in the chart editor, an invisible note is left behind at the end of where the hold note was, and persists upon saving. It is noticeable enough to trigger the AutoPlay to play it, although it doesn't affect player scores as far as I'm aware.

**Describe what should happen**

Deleting a hold note should completely remove all traces of the note. You might also want to automatically remove remnants of hold notes when a chart is opened, because I can imagine there will be a lot of charts now made using Outfox that have this problem.

**Comment by JoseVarelaP** [comment]
This has been resolved on the alpha-V editor branch, and making a cherrypick to include it for Alpha 4.11.

https://user-images.githubusercontent.com/23246027/141054181-541ab160-40f1-4a7d-8500-d434b8722395.mp4

**Comment by Scraticus** [comment]
Fixed in 4.11.0 - Happy Charting!
