### ISSUE TITLE
[Game Crash] App crashes on startup

### ISSUE THREAD

**Issue by Tosche** [TeamRizu/OutFox#332]
I downloaded the alpha, installed the StepMania folder to the Applications folder. Upon my first launch with nothing else installed (after approving the app in the System Preferences of course), the app bounced for several seconds in the dock and crashed. The ini files mentioned in the crash info do not exist indeed.

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6469627/crashinfo.txt)

**Comment by JoseVarelaP** [comment]
Looks like you've forgot to apply the quarantine command (it's not performed on System Preferences), which can be followed here: https://outfox.wiki/#/install?id=macos

**Comment by Tosche** [comment]
Thanks! Sorry this was rather embarrassing.
