### ISSUE TITLE
[BUG] 'beat' charts saved as .ssc are parsed inconsistently between editor and gameplay

### ISSUE THREAD

**Issue by oyakawa** [TeamRizu/OutFox#336]
**Please give System Info**

OS: Windows 10

CPU: Intel i5-7600K

GPU: NVIDIA GeForce GTX 1080

Storage: 16GB RAM

**Please give your StepMania Info**

StepMania Version: StepMania5.3-git-58ac2bb65c (also happening on 5.1)
Theme: Soundwaves

**Describe the problem**
In the editor, a bm-single7 .ssc chart has its columns parsed as, in order:
1-Scratch
2-Key 1
3-Key 2
4-Key 3
5-Key 4
6-Key 5
7-Key 6
8-Key 7

However, the same chart in gameplay is parsed as:
1-Key 1
2-Key 2
3-Key 3
4-Key 4
5-Key 5
6-Key 6
7-Key 7
8-Scratch

As a result, charts created using SM's editor do not play as intended by the author.

**Describe what should happen**
I expect both the editor and gameplay to parse the chart the same way.

**Logs and Additional context**

In-editor video:
https://streamable.com/b9u67s

Gameplay video:
https://streamable.com/zx26ut

**Comment by concubidated** [comment]
Was able to reproduce, only happens when its an ssc chart.When the file is .sm everything appears to work correctly.

**Comment by Scraticus** [comment]
Fixed in 4.9.9
