### ISSUE TITLE
Windowed game runs unlimited fps when another window is fully above it on MBA M1

### ISSUE THREAD

**Issue by Joehuu** [TeamRizu/OutFox#337]
**Please give System Info**

OS: macOS Big Sur 11.3.1

CPU: Apple M1

GPU: Apple M1

Storage: 512 GB

**Please give your StepMania Info**

StepMania Version: OutFox-alpha.4.9.8
Theme: Soundwaves (alpha 4.9.8)

**Describe the problem**

I have vsync on and it's windowed. When I fully cover the game window with another window, say Chrome, it runs unlimited and makes my MBA hot.

**Describe what should happen**

It should stay at 60 fps.

**Logs and Additional context**

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6481237/crashinfo.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/6481238/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6481239/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/6481240/userlog.txt)

https://user-images.githubusercontent.com/35318437/118333108-0117f580-b4c0-11eb-817a-c7fd54c8fe38.mp4

**Comment by Scraticus** [comment]
This is actually a bug with the metal surface layer we use, If an app overlays it which changes the base FPS, we jump up to whatever that app uses. 

I will see if there has been any changes in the 11.4 beta, but as of 11.3 it still is weird

**Comment by Scraticus** [comment]
Ah, yes, it is still doing so on my Mini M1 on the latest beta of MacOSX 11.4

I am hoping it will go away when we finallly get our renderer finished. 

I will leave this issue open to remind me, thanks for taking the time to report this issue!

**Comment by Scraticus** [comment]
Just to update this one, i've forced the renderer to 'give up' cycles on the next release, when that comes let me know if it still happens. (My M1 is busy rendering so cannot test it right now)

**Comment by Joehuu** [comment]
I just noticed that disabling `Displays have separate Spaces` under `Mission Control` in the System Preferences fixes the problem for me in the current release.

Will check again with it enabled in the next release.

**Comment by Scraticus** [comment]
Thanks for the update. We've also forced the renderer to give up cycles when the app is no longer focused, which should also let metal know we're in the background. 4.9.9 isn't that long away, we're just cleaning up little bugs now.

Will leave this open until 4.9.9 is released.

**Comment by Joehuu** [comment]
Still happens with `Displays have separate Spaces` enabled.
![Kapture 2021-07-31 at 13 41 57](https://user-images.githubusercontent.com/35318437/127752003-742897d4-f4cd-4ea2-9cd7-cba5b83d794d.gif)

**Comment by rullinoiz** [comment]
im also having this issue, the game uncaps whenever it loses focus which ramps up the gpu to 100% and it gets toasty. also on an M1

**Comment by Scraticus** [comment]
This has been patched in 4.11.0, can you check when you're ready? Closing, but let me know if it still happens

**Comment by Joehuu** [comment]
This still happens to me in 4.11.0 on macOS 12.0.1. Apart from a bug on macOS 12 where VSync is 2x the refresh rate, the original report reproduction is still the same (`VSync` on, `Windowed`, `Displays have separate Spaces` enabled, and another window fully covering the game).

In the past, I couldn't reproduce the fullscreen case as @rullinoiz said, but now I can in the latest build. In this case, it doesn't matter what `Displays have separate Spaces` is. I noticed that the behavior changed when unfocusing while fullscreen, it minimizes now instead of showing a black screen.
