### ISSUE TITLE
[BUG] MIDI Release Not Working

### ISSUE THREAD

**Issue by Avxnt** [TeamRizu/OutFox#341]
OS: Windows 10 Pro 2002
CPU: Intel Core i5-7600K
GPU: Nvidia Geforce RTX 2060 Super
Storage: Samsung 860 EVO 250GB

StepMania Version: Stepmania 5.3-git-58ac2bb65c (20210425) and has happened in older releases as well
Theme: Default

I have a Midi Fighter 64 that I am trying to use with Stepmania since I learned that it had MIDI support, but the thing is that when I hit any button on the controller, _mapped or not,_ Stepmania **doesn't recognize when it releases, making it always pressed down.**

It should be able to recognize when it releases since I'm able to look at the hexes for button state, number, and velocity. 

Just putting it here in case it helps at all, here's how my Midi Fighter 64 sends a note:
WX YY ZZ

W will either be 9 when on or 8 when off, **here is where I suspect something is up since it doesn't detect this**
X is the MIDI channel it sends on, ranging from 1 to 13, _I've tested multiple MIDI channels for the controller and this isn't it_
YY is the button number, _the game recognizes it all perfectly_
ZZ is the velocity (which as a side note could be a good idea to add a slider for button sensitivity if one likes)

I am not versed in how MIDI is sent in general at all, I just know how the Midi Fighter sends its data thanks to its' log, but hopefully what I've explained can help a bit with making sure this is fixed.

**Comment by Avxnt** [comment]
The only parts of the log that involves MIDI in any parts are this:
`00:07.979: MIDI Button detected: Type: 144
00:08.046: MIDI Button detected: Type: 128`

I hit 2nd Player Enter and then 2nd Player Menu Up in that order, afterwards I closed the game. Not sure if that's any help.

**Comment by Scraticus** [comment]
Hiya!, Sorry for the delay in writing a reply, we were on annual leave. You are quite right, there is a bug with the return() code from upstream that tells the game the button is off/released.

We'll crack on with this and hopefully a fix will be done soon.

**Comment by Scraticus** [comment]
Ok, confirmed fixed, thanks for taking the time to test the build for me.

Closing as will be in 4.9.9
