### ISSUE TITLE
[Nitpick] Fix pump/piu menu inconsistencies on Soundwaves

### ISSUE THREAD

**Issue by SHRMP0** [TeamRizu/OutFox#343]
Although Soundwaves is going to be replaced in a few months, the navigation on pump/piu needs to be fixed ASAP.

**Give examples of what is wrong**
- the yellow visual indicator is cool but there's still the same problem as before: once the game awaits you to hit again before proceeding, you can still change difficulties with upleft/upright and the only way to cancel is pressing back, which will throw you out of select music back into the main menu
- menu buttons scroll one chart at a time after you select the song, but gameplay buttons skip one chart while scrolling
- change difficulty tip doesn't reflect properly how it's currently working for pump on sw (on menu buttons, you just need to press up or down once, plus it only works after you click a song) (see image below)
![image](https://user-images.githubusercontent.com/61925574/119689845-93ed5400-be1f-11eb-8f36-cab1b8e57347.png)

**Proposed QoL fixes for `pump/piu`**
- toggle to switch between gameplay buttons tips or menu buttons tips
- toggle to make menu buttons behave as gameplay buttons (for cabs with 45-degree rotated 5-button boards)

- shortcuts/codes
> for gameplay buttons
> - `upleft` + `upright`: close current group
> - `upleft` » `upright` » `upleft` » `upright`: opens mode menu
> - `downleft` + `downright`: change sort
> - holding `upleft` + `upright` for 2 seconds if no group is currently selected: go back to main menu
>
> for menu buttons
> - `up` + `down`: close current group
> - `up` » `down` » `up` » `down`: opens mode menu
> - `left` + `right`: change sort
> the current behavior while holding `select` is fine

- menu navigation option 1 (preferred) (hybrid)
> for song scrolling
> - `downleft` / `downright` / `left` / `right`: previous/next song
> - `upleft` / `upright` / `up` / `down`: previous/next group
> - `center` / `start`: selects song
> 
> after song is selected
> - `downleft` / `downright` / `left` / `right`: previous/next difficulty
> - `upleft` / `upright` / `up` / `down` / `back`: back to song scrolling
> - `center` / `start`: goes to gameplay or player/song options 

- menu navigation option 2 (dance-like)
> for song scrolling/selecting
> - `downleft` / `downright` / `left` / `right`: previous/next song
> - `upleft` / `upright` / `up` / `down` 2x: previous/next difficulty
> - `center` / `start`: selects song and goes to gameplay or player/song options

**Comment by SHRMP0** [comment]
Paging @ListenerJubatus and @JoseVarelaP as requested

**Comment by Scraticus** [comment]
This one is mainly going to be archived as the theme is being replaced with a pump-centric design for alpha V. If liro/sheepy has time, they'll update the community version in the future.
