### ISSUE TITLE
[Game Crash] regression: startup crash on Linux since alpha 4.9.7 (Ubuntu 20.04 LTS, NVIDIA NVS 5100M)

### ISSUE THREAD

**Issue by rxhfcy** [TeamRizu/OutFox#347]
**Describe how it crashed by giving us those informations:**

1. What you were doing before it crashed and what action made the game to crash.
didn't do anything: tried launching the game, crashes on startup

2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
didn't find crashinfo.txt anywhere

3. Upload the info.txt and log.txt (GameFolder/Logs)
I'll attach info.txt, log.txt and console output from 4.9.6 (no crash), 4.9.7 (first version that crashes) and 4.9.8 (still crashes)

[no-crash-4.9.6-console-output.txt](https://github.com/TeamRizu/OutFox/files/6600742/no-crash-4.9.6-console-output.txt)
[no-crash-4.9.6-info.txt](https://github.com/TeamRizu/OutFox/files/6600743/no-crash-4.9.6-info.txt)
[no-crash-4.9.6.log.txt](https://github.com/TeamRizu/OutFox/files/6600744/no-crash-4.9.6.log.txt)

[crash-4.9.7-console-output.txt](https://github.com/TeamRizu/OutFox/files/6600755/crash-4.9.7-console-output.txt)
[crash-4.9.7-info.txt](https://github.com/TeamRizu/OutFox/files/6600756/crash-4.9.7-info.txt)
[crash-4.9.7-log.txt](https://github.com/TeamRizu/OutFox/files/6600757/crash-4.9.7-log.txt)

[crash-4.9.8-console-output.txt](https://github.com/TeamRizu/OutFox/files/6600758/crash-4.9.8-console-output.txt)
[crash-4.9.8-info.txt](https://github.com/TeamRizu/OutFox/files/6600759/crash-4.9.8-info.txt)
[crash-4.9.8-log.txt](https://github.com/TeamRizu/OutFox/files/6600760/crash-4.9.8-log.txt)

**Explain how we can reproduce the error**

0. delete ~/.stepmania-5.3 folder, everything straight from the factory, no customizations whatsoever, "first startup ever"
1. Start the game
2. Game crashed

**Sreenshots/Videos**

I've included console output from 4.9.6 (no crash), 4.9.7 and 4.9.8
4.9.7 and 4.9.8 say this at the bottom:
Fatal: crash from within the crash signal handler
Fatal: crash from within the crash signal handler

**Additional information**

4.9.6 doesn't crash and works perfectly, 4.9.7 and 4.9.8 crash on startup.

I also tried explicitly only allowing opengl (not glad) and forcing high-res textures off, didn't help, can't think of anything else to try (if you have any suggestions, I'm happy to try them)

The laptop is old, from the year 2010 (HP EliteBook 8540p)
Ubuntu 20.04.2 LTS (Focal Fossa) (fully updated)
old NVIDIA GPU, "GT216M [NVS 5100M]" so probably this: https://www.techpowerup.com/gpu-specs/nvs-5100m.c1466
the driver package is nvidia-340 (340.108) (legacy, but the latest version I believe)
Linux kernel version 5.4.0-74-generic (nvidia-340 won't support anything after 5.4), x86_64

**Comment by Scraticus** [comment]
Hiya, thanks for the bug report!

We were having our annual leave break, so apologies for the delay in responding to your issue.

It looks like the Nvidia Driver is unable to create a window in 4.9.7/4.9.8, which is the source of the crash.

I'll have our linux developer do some testing on the fix i've written, and hopefully we can squash this annoying bug!

**Comment by rxhfcy** [comment]
Thanks! If it helps, I can also try running test/debug builds. Just let me know if I can help somehow.

**Comment by Scraticus** [comment]
Are you able to join our discord?

**Comment by rxhfcy** [comment]
Sure, I've joined there, just tell me what to do next! Can I message you there?

**Comment by Scraticus** [comment]
send a message to Squirrel in one of the channels, so i can see it, just ping me

**Comment by rxhfcy** [comment]
I can't reproduce this crash anymore with 4.9.9HF, so this is fixed at least for me!

**Comment by rxhfcy** [comment]
...just double-checked with 4.9.9HF2, no crash there either. Thanks for caring about old hardware!

**Comment by rxhfcy** [comment]
Pretty sure this is fixed now. Please reopen if necessary. Thanks!
