### ISSUE TITLE
[BUG] "Preferred Meter" option isn't working properly

### ISSUE THREAD

**Issue by KirbyJoe** [TeamRizu/OutFox#349]
**Please give System Info**

OS: Windows 10 Pro 20H2 (OS Build 19042.985) (64bit)

CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz

GPU: NVIDIA GeForce GTX 1080

Storage: C (SSD): 38.5GB/224GB free, D (HDD): 11.3GB/1.81TB free, F (HDD): 1.48TB/1.81TB free, 16.0 GB RAM

**Please give your StepMania Info**

StepMania Version: StepMania5.3-git-58ac2bb65c
Theme: Soundwaves

**Describe the problem**

There is an option to change meter threshold to mark "boss songs" in red text. When I try to change the option, the meter threshold persists into "DDR" while the option is saved correctly, making most of charts with DDR X meter as "boss songs".

**Describe what should happen**

The meter threshold should apply correctly. Also add support for [Group.ini/lua](https://github.com/waiei/Group.ini-lua) (which adds multiple per-folder features, including per-folder meter type) if possible.

**Logs and Additional context**

Here's what FIXED project charts (which uses DDR X meter) look like in OutFox:

![2021-06-07_092008](https://user-images.githubusercontent.com/20151551/120944909-ed377a80-c771-11eb-873a-ea35448384b7.jpg)

**Comment by ListenerJubatus** [comment]
Should be fixed now
![StepMania_GHMS0tM6R1](https://user-images.githubusercontent.com/6346433/126736186-88fb104e-a4ec-4e31-9349-d941343fbd0a.jpg)

**Comment by ListenerJubatus** [comment]
Fixed in Alpha 4.9.9
