### ISSUE TITLE
[Unexpected Behavior] Game opens with a blank, white screen

### ISSUE THREAD

**Issue by Gabriel-minceraft** [TeamRizu/OutFox#354]
**What you're using**
Hello Team Rizu,
My name is Gabriel-minceraft, I am a player of Stepmania since 2019, I make packs and stepcharts.
I have recently taken a break from Stepmania for some months, and then I returned.
I opened the game, and saw a blank, white screen...
Note: the game was working, however the screen is white.
![stepmania blank moment](https://user-images.githubusercontent.com/76697916/122849647-4828b000-d2e2-11eb-9a9b-04eb0b4f9ebf.PNG)

I am using a Windows 7 Home Premium, DirectX 11. 

**Expected behavior**

I was actually expecting Stepmania to actually open correctly, but as I said, the game opens with a white screen.

For any more info tell me.
Gabriel-minceraft, 2021

**Comment by Scraticus** [comment]
Hiya! 

We need the log files that will be in the /logs folder. Then we will be able to assist you further.

thanks a lot!

**Comment by Scraticus** [comment]
any update?
