### ISSUE TITLE
[Game Crash] This Should Be 2 Player Pop'n Music Here.

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [TeamRizu/OutFox#355]
**Describe how it crashed by giving us those informations:**

When i tried to play battle mode, the game crashed.

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6698789/crashinfo.txt)

**Explain how we can reproduce the error**

1. Start the game
2. Play WIth Style "popn"
3. Join 2 Players
4. As Music Select Appears, Game crashed

**Additional information**

https://www.youtube.com/watch?v=97NatSWUMj8

**Comment by Scraticus** [comment]
Thanks for reporting this one, I can confirm it was a debug check left behind that wasn't caught before release. We've fixed this and made the 2p pop'n mode a lot more stable on the next alpha. (it also supports all po-mu modes, 3/4/5/7/9)

Proper battle mode will come in the future, but you can now at least play 2 players.

Again, thanks for taking the time to report this and letting us know.
