### ISSUE TITLE
[Game Crash] Some part of Random Attacks crashes the game

### ISSUE THREAD

**Issue by cpguy5089** [TeamRizu/OutFox#356]
In short, I put random attacks on for the fun of it, and early on in the first song I tried it crashed. Assuming it was a random bug I just restarted, turned random attacks on again, and kept playing. Two songs later it crashed midway through.

**How you can reproduce the error**

1. Enable random attacks under Modifiers - Only tested on Dance, no idea if other modes have (random) attacks
2. Play any song(s)
3. The game will, at some point, crash (Note: it's not common, generally every 2-3 songs or so it happens)

I want to note that I don't know if it's random attacks trying to do something it isn't able to, or if there's specific attack(s) that are known to crash. (I looked in issues + the discord search bar, couldn't find any other complaints about this)

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6699056/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6699058/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/6699059/info.txt)

**Comment by Scraticus** [comment]
Hiya! Sorry for the delay in response.

Does the game crash while the song is playing, or at the end of the track?

I'm currently investigating this now, so it would be helpful if you can let me know when it crashes, so we can investigate the attacks for you.

**Comment by Scraticus** [comment]
I've ran through 27 songs back to back in 4.9.9rc-1 and it seems to be better, i have not had a single crash. I'll leave this open for your reply, but i think this has been resolved now :)

**Comment by cpguy5089** [comment]
The song was crashing while it was playing, usually at different points through the song (I did test the same songs multiple times, and it was a different point each time if/when it did crash)

If it's magically been fixed in a newer version maybe I'll have to update then.

**Comment by Scraticus** [comment]
Indeed, grab the new alpha when it's released. Can confirm there _was_ a bug in attacks we've fixed, so it wasn't magically done. 

Thanks for the Report! - Closing as fixed in 4.9.9
