### ISSUE TITLE
Add error handling to RageFileDriverDirect

### ISSUE THREAD

**Issue by ArcticFqx** [TeamRizu/OutFox#36]
Bug discovered when it caused a crash on shutdown:
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/4950578/crashinfo.txt)

**Comment by Scraticus** [comment]
This is due to an open file or handle preventing closure of the logfile.

It does have another potential bug within it on the TextureDestroy function that warrants a look.

**Comment by Scraticus** [comment]
Fixed in 4.13
