### ISSUE TITLE
[BUG] IniFile.ReadFile function from the _fallback theme checks for sections anywhere inside a line

### ISSUE THREAD

**Issue by japareaggae** [TeamRizu/OutFox#360]
## System Info

* OS: Arch Linux x86_64
* CPU: AMD Ryzen 5 3600X
* GPU: AMD Radeon RX 5500 XT
* Storage: WD SN500 NVMe SSD

## StepMania Info

* StepMania Version: 5.3.0-alpha-4.9.8
* Theme: Simply Love

## Describe the problem

The IniFile.ReadFile function from the _fallback theme (defined in Scripts/01 IniFile.lua) uses a regex to determine when to create sections, however, this regex does not check if the starting bracket is on the beginning of the line. This causes issues whenever a key or a value has brackets.

## How to reproduce

1. Install and enable Simply Love (since this theme uses IniFile.ReadFile heavily)
2. In Options > Simply Love Options, change settings as desired (for a quick example, turn on Rainbow Mode), then quit the game
3. Open the Save/ThemePrefs.ini file, create a dummy value right below the `[Simply Love]` header:

```
[Simply Love]
DummyKey=please [ignore] this
AllowDanceSolo=false
AllowFailingOutOfSet=true
AllowScreenEvalSummary=true
```
4. Open the game and notice how all your settings have been reset
5. Go back to Options > Simply Love Options, change settings again and exit
6. Open the Save/ThemePrefs.ini file again and notice how it has two sections now: `[Simply Love]` and `[ignore]`

## Describe what should happen

The IniFile.ReadFile function should only create sections if the line starts with a left bracket. Which means the regex should be:

`local sec = str:match( "^%[(.+)%]" )`

Instead of:

`local sec = str:match( "%[(.+)%]" )`

## Additional context

This bug is also present in StepMania 5.1-new and 5.0.12. A pull request to fix it has been opened there: https://github.com/stepmania/stepmania/pull/2127

This bug was found while creating this pull request for the Simply Love theme: https://github.com/Simply-Love/Simply-Love-SM5/pull/330

**Comment by Scraticus** [comment]
Thanks for reporting this! 

I can confirm this will be corrected in time for our next alpha release.
