### ISSUE TITLE
[Game Crash] Game thinks `techno` noteskin doesn't exist?

### ISSUE THREAD

**Issue by ValVoice** [TeamRizu/OutFox#364]
**Describe how it crashed by giving us those informations:**

1\. What you were doing before it crashed and what action made the game to crash.

I tried to play Technomotion mode, but it crashed upon trying to start the song. The last line of the log said "WARNING: Someone set a noteskin that doesn't exist.  Good job."

2\. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6799505/crashinfo.txt)

3\. Upload the info.txt and log.txt (GameFolder/Logs)
[info.txt](https://github.com/TeamRizu/OutFox/files/6799508/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6799509/log.txt)

**Explain how we can reproduce the error**

1. Delete all noteskins except for the default one for every mode, except for Global; leave 2 noteskins there.
2. Play `techno` mode
3. Select one of the two available noteskins in the song menu
4. Game crashed

**Sreenshots/Videos**

If possible, take screenshots or record the crash happening.

[Video recording](https://streamable.com/mf005j) (also shows weirdness of menu in `techno` mode)

**Additional information**

In case this issue is caused by the noteskins themselves (because I tried modifying one of the noteskins), here is my `NoteSkins\global` folder.
[global.zip](https://github.com/TeamRizu/OutFox/files/6799538/global.zip)

**Comment by ListenerJubatus** [comment]
What version are you on? There is a default techno noteskin that redirects to broadhead-columns in Global.

**Comment by ListenerJubatus** [comment]
Because the techno default noteskin is actually a pointer to one of the Global noteskins, broadhead-columns. Is there any particular reason why you did this?
