### ISSUE TITLE
[BUG] ParaParaParadise PS2 Controller doesn't work on macOS

### ISSUE THREAD

**Issue by Casuallynoted** [TeamRizu/OutFox#366]
OS: macOS Big Sur 11.4

CPU: Apple M1

GPU: Onboard M1 APU

Storage: 256GB Apple SSD

**Please give your StepMania Info**

StepMania Version: OutFox Alpha 4.9.8
Theme: EKS-D Paramania

**Describe the problem**

When I have the PPP controller plugged in via USB, it is detected and listed by both the Mac and StepMania. However, no button presses actually seem to produce a response in any joystick configuration application, including StepMania

**Describe what should happen**

The controller should be able to be used with all four buttons and five motion inputs on macOS

**Logs and Additional context**

I tried to find logs but could not find any in the game's folders.

**Comment by Scraticus** [comment]
Hiya!

Thanks for reporting this, I'll get on fixing this for MacOS, seems we had a regression on our end from the fix we added. the PPP driver was only ever windows only.

**Comment by Casuallynoted** [comment]
Awesome, thank you so much! I can't wait to be able to try out the Para pad with Stepmania!

**Comment by Casuallynoted** [comment]
This may or may not already be known, but I just tested out the controller with Linux (x64 non-legacy) and this bug seems to apply to that as well.

**Comment by Scraticus** [comment]
Thanks for letting us know, i'll add it to the todo list

**Comment by PicoPico40** [comment]
I've been getting into para as well. Are there any updates on this? running on Linux. As of the latest build it isn't picking up the controller.

**Comment by YurgenJurgensen** [comment]
I'm in the same boat.  There's definitely people who care about Parapara Paradise controller support.

**Comment by Scraticus** [comment]
are any of you guys in our discord? I'd like to throw you a test build

**Comment by Scraticus** [comment]
Awaiting results of your testing, then we can mark this closed

**Comment by MrThatKid** [comment]
Fixed in 4.14
