### ISSUE TITLE
[BUG] Assets missing for gh mode

### ISSUE THREAD

**Issue by Casuallynoted** [TeamRizu/OutFox#368]
**Please give System Info**

OS: macOS Big Sur

CPU: Apple M1

GPU: Integrated M1 GPU

Storage: Apple 256GB SSD

**Please give your StepMania Info**

StepMania Version: Outfox Alpha 4.9.8
Theme: All themes

**Describe the problem**

When trying to load the songs list in gh mode, it presents multiple errors related to missing noteskin assets.

**Describe what should happen**

Noteskins should be present and used to enter the game mode.

**Logs and Additional context**

The NoteSkin element "Down StrumNote" could not be found in any of the following directories:
Appearance/NoteSkins/gh/modern-2d/, Appearance/NoteSkins/common/common/ 

The NoteSkin element "_RES/_Up mat.txt" could not be found in any of the following directories:
Appearance/NoteSkins/gh/default/, Appearance/NoteSkins/common/common/

**Comment by Casuallynoted** [comment]
Not exactly the same issue, but I've also noticed that gh is the only mode which doesn't autogen files from other modes (when that feature is enabled).

**Comment by ListenerJubatus** [comment]
Did you run the quarantine process for macOS? See https://outfox.wiki/user-guide/setup/install/ for details

**Comment by Casuallynoted** [comment]
> Did you run the quarantine process for macOS? See https://outfox.wiki/user-guide/setup/install/ for details

When I try to do this, I get:

xattr: [Errno 9] Bad file descriptor: '/Applications/StepMania/StepMania.app/Contents/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Applications/StepMania/StepMania.app/Contents/MacOS'
xattr: [Errno 9] Bad file descriptor: '/Applications/StepMania/StepMania.app/Contents/Resources'
xattr: [Errno 9] Bad file descriptor: '/Applications/StepMania/StepMania.app/Contents/Libs'
xattr: [Errno 9] Bad file descriptor: '/Applications/StepMania/StepMania.app/Contents'
xattr: [Errno 9] Bad file descriptor: '/Applications/StepMania/StepMania.app'

**Comment by JoseVarelaP** [comment]
This is fixed in 4.9.9, where you don't have to worry about the permissions.
