### ISSUE TITLE
[Fixed][Unexpected Behavior] Mod "Hide Judgment" has inconsistent behavior.

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#37]
**What you're using**

Stepmania 4.6 OF (with backers special symbols build git-2b972eef18)

Right now we have 2 ways to enable "Hide Judgment" mod.

The first one being by going into Song Modifiers screen, going down to "Hide" row and selecting Hide Judgment.
![image](https://user-images.githubusercontent.com/58047457/88115876-9773d700-cb8d-11ea-83ae-8dd9f76c3b39.png)

The second one being by going into Song Modifiers > Additional Options, going down to Judgment Items and selecting Hide Judgment.
![image](https://user-images.githubusercontent.com/58047457/88115848-84f99d80-cb8d-11ea-8baa-fa3f35bb5851.png)

### Inconsistent behavior

The first one disappears, after going back to the menuTitle or exiting the game, *even if you have a profile*. **It doesn't work when playing modfiles**

![image](https://user-images.githubusercontent.com/58047457/88115918-b70aff80-cb8d-11ea-92f4-07368e957865.png)

The second one does not disappears after going back to the menuTitle or exiting the game(atleast when you have a profile which is a expected behavior). It works when playing modfiles.

**Expected behavior**

There should only be one Hide Judgment in Song Modifiers, it should not disappear if you're using a profile and it should work with mods.

**Comment by Scraticus** [comment]
I'll leave this one to @ListenerJubatus and @JoseVarelaP to look into. Thanks for your report!

**Comment by Scraticus** [comment]
Referenced in #50

**Comment by Jousway** [comment]
> Expected behavior
> 
> There should only be one Hide Judgment in Song Modifiers, it should not disappear if you're using a profile and it should work with mods.
I 100% agree, sorry it took like 3 years.

![image](https://github.com/TeamRizu/OutFox/assets/4059058/c21da4be-5e6e-452f-8d73-c945fb9be238)

Removed as requested.
