### ISSUE TITLE
[BUG] Game maps any Arduino to StepManiaX controller

### ISSUE THREAD

**Issue by SugoiFactory** [TeamRizu/OutFox#374]
OS: Windows 10

CPU: Core i5-9300H

GPU: NVIDIA GeForce GTX 1650

Storage: 256GB NVMe SSD

**Please give your StepMania Info**

StepMania Version: Project OutFox 5.3 Alpha 4.9.8
Theme: Simply Love v5.0.1

**Describe the problem**

When plugging in an Arduino, the game recognizes it as a StepManiaX controller and only allows for certain inputs to be valid, which will then be mapped to "DPad Up", "DPad Left", etc. instead of as individual button numbers. Any inputs that are not pre-mapped for a StepManiaX controller are ignored and not allowed to be set in options.

**Describe what should happen**

This greatly reduces possible usage of custom controllers using an Arduino for sending inputs. Earlier versions of StepMania simply recognized an Arduino as an Arduino and mapped all these inputs as "B11", "B12", etc. and it would be preferable if something like that functionality were preserved, or if there was an option to NOT recognize it as a StepManiaX controller.

**Comment by Scraticus** [comment]
What input system are you using? XInput or Legacy? and can you provide your logs please?

**Comment by SugoiFactory** [comment]
The logs don't seem to be producing anything when I configure or test my inputs. How do I check or set my input system?

**Comment by Scraticus** [comment]
Not what I asked for, but ok. 

Can you post them so I can actually help you?

**Comment by SugoiFactory** [comment]
[info.txt](https://github.com/TeamRizu/OutFox/files/6912210/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6912211/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/6912212/userlog.txt)

**Comment by Scraticus** [comment]
Ok, you're using XInput, so it's likely the SMX pads are using a similar device structure to the Arduino.

You can fix this by going to the experimental options and selecting 'legacy' it'll give you back the freedom to tinker.

I also tried one of my arduinos, and this code came up for that as well, so they must be using the common HID library which is sending a known PID/VID

**Comment by SugoiFactory** [comment]
I can confirm that legacy input works with the Arduino as expected.
