### ISSUE TITLE
[BUG] Offset is not applied when loading .chart files

### ISSUE THREAD

**Issue by SockHungryClutz** [TeamRizu/OutFox#376]
**Please give System Info**

OS: Windows 10
CPU: Ryzen 7 5800X
GPU: RTX 2080Ti
Storage: SSD

**Please give your StepMania Info**

StepMania Version: Outfox 4.9.9 (latest release today)
Theme: default

**Describe the problem**

Loading a .chart file that has an offset will not have the offset be applied. No matter the offset in the .chart file, the song will always have a beat 0 offset of 0

**Describe what should happen**

The beat zero offset should be set according to the offset parameter, IIRC it should be set to -1 * (offset)

Test song with copyright free audio of me imitating the opening attached.

Add any other context or screenshots here.
![image](https://user-images.githubusercontent.com/37255977/127752655-81ab5308-fcd0-4006-b60c-8870858917cd.png)
[Example.zip](https://github.com/TeamRizu/OutFox/files/6911841/Example.zip)

**Comment by Scraticus** [comment]
This is now fixed for .chart files.

Seems when we were looking at the methodology used for the parser from your implementation for 5.2, the offset is not actually even calculated or configured correctly, and we missed it.

Thanks for the report, and I can happily report this is fixed now.

![image](https://user-images.githubusercontent.com/11047768/131968863-7ffa7064-f12c-4134-86d8-c979a892df23.png)

![image](https://user-images.githubusercontent.com/11047768/131968934-fec8aab2-cd08-4d91-b7f7-905a9b2b0d29.png)


using your example as a testbed.

![image](https://user-images.githubusercontent.com/11047768/131969115-bb4a6a97-d0e4-42d4-b846-d413d1356cbf.png)

Fix will be added to the next release, but will be available in a nightly shortly.

Cheers for letting us know!
