### ISSUE TITLE
[BUG] Soundwaves game mode selection bypass

### ISSUE THREAD

**Issue by Kaede573** [TeamRizu/OutFox#377]
OutFox-5.3.0-alpha-4.9.9-amd64-date-20210731

When first started, StepMania will prompt for game mode selection.
However pressing ESC will bypass that screen.
After that, "Current Gametype" displays "SelectGameMode". It is possible to start a game in that state, but everything is broken (can't select difficulty or change chart) and selecting a chart to play will crash the game, understandably.

**Comment by MrThatKid** [comment]
Should be fixed as of alpha 4.9.9's upcoming hotfix. Thank you for pointing it out!
