### ISSUE TITLE
[Unexpected Behavior] GAMESTATE:GetGameSeed isn't random

### ISSUE THREAD

**Issue by JustinLove** [TeamRizu/OutFox#38]
**What you're using**

GAMESTATE:GetGameSeed()

Always returns 8365 on the first game after starting the program.

**Expected behavior**

Seed is will be different every time you "Game Start", and remain the same until "Game Over". E.g. when you return to song selection between songs, the seed can be used to produce a consistent random sequence for that game, but each game will have a different seed.

**Comment by Scraticus** [comment]
Hiya!

thanks for this report! It appears neither the Game seed or the stage seed actually had a 'seed' being generated at the beginning of the game, so it always reported the same number from the rand() call. 

We have added an actual seed generation call before these are set and now it works as designed.

The fix will be out the next release.

Thanks again!

![gameseed](https://user-images.githubusercontent.com/11047768/88317294-fada4200-cd10-11ea-8dcc-55d451759e9b.png)

**Comment by moruzerinho6** [comment]
Hello @JustinLove  

Project Moondance Discord Moderator here, a while ago we created a bug hunter system, users who make issue on this repository gain points and can be rewarded in our discord, so I'm here to ask, are you in Project Moondance discord?

If not, you can join using this link: https://discord.gg/3DgsbSg

If you don't wish to join, that's okay. Please be sure to contact any moderator if you join.

**Comment by JustinLove** [comment]
@moruzerinho6 wondible on discord, though I don't keep up very well.
