### ISSUE TITLE
[Unexpected Behaviour] Graph width set incorrectly if failed too early in Course Mode

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#383]
**What you're using**

The following happens on any theme on either course mode with set multiple songs (Extended/Nonstop/Marathon & Oni/Survival):
Just fail the first song and the graph for the first song takes up the entire width. Every subsequent song has the same width and eventually goes off the screen, showing splits at positions they weren't meant to be.
The widths seems to be only calculated once a new song has been reached.

The following depicts a 5-song-course in Oni/Survival Mode.
The image displays what happens if one fails on each song (starting with the 1st).
The last snippet shows what happens if one skips a(ll) song(s).
It seems that skipping songs doesn't move the life meter towards the next segment (the GainSeconds spikes happen way before the song split marker) but are being displayed at which time they occured.

![CourseMode](https://user-images.githubusercontent.com/83576877/128324232-80de29d7-3281-465b-8767-efc9c6e0e4b6.png)

Note: Even if the screenshots were made on 4.9.8, this behavior still occurs in 4.9.9

**Expected behavior**

Set graph width to course's entire duration instead of length of all cleared songs.

**Comment by JoseVarelaP** [comment]
Update: I found out what the bug is, and now i'm in the process of a fix.

**Comment by JoseVarelaP** [comment]
The fix in testing, seems to look fine, now the widths are enclosed to its proper boundries.
This is being shown with the first reproduction case, which is failing a song early on at the beginning of the course.

![Captura de Pantalla 15](https://user-images.githubusercontent.com/23246027/130488080-5751f17a-5322-408e-b3c2-c5f6e66aaf5a.png)

**Comment by DarkBahamut162** [comment]
But we aren't done yet!
As I had thought, rates haven't been fully accounted for:

This shows a course with a bunch of songs with the "3.0xmusic" modifier.
The upper graph is being displayed correctly (I've also tested the failed case and everything was in line).
But the combo graph haven't been adjusted fully (or have been adjusted too much?).
![2021-08-28_100134](https://user-images.githubusercontent.com/83576877/131211438-5aecb81a-1e90-4034-bac5-7c6c2db83f03.jpg)

The same could be said with "Haste".
![2021-08-28_100831](https://user-images.githubusercontent.com/83576877/131211487-1fb73173-996f-4f29-9495-87014c2bb0fa.jpg)
However: I wasn't able to test the haste course normally on 4.9.10/HF4 and had to do `SoundUseOldResampler=1` to get it to work. And this has it's own flaws (which might need a seperate issue?).

I could have screenshot the same thing in SoundWaves4.9.9HF4 (?) but the 3.0xmusic course didn't work initially over there but on my ITG3Encore theme. Upon reloading a bunch betweet the two, it's no longer the case... I should have turned it off and on again.

**Comment by Scraticus** [comment]
Fixed in 4.11.0
