### ISSUE TITLE
[Unexpected Behaviour] Invisible CPU Player in 1 Player Rave/Battle Mode

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#384]
**What you're using**
This happens on any theme which still has Rave/Battle Mode available.
The CPU Player is there but invisible (see the bars on top two).

**Expected behavior**
CPU Player should be visible (see bottom two).

**Video**
http://y2u.be/SDwHosTDb-4

Top Left: OutFox (ITG3Encore)
Top Right: OutFox (Legacy)
Bottom Left: NotITG/OpenITG (ITG3Encore)
Bottom Right: SM SSC (Default)

**Comment by JoseVarelaP** [comment]
Fixed in Alpha 4.19. Adding this to alpha-V, realized it is not on that branch.
