### ISSUE TITLE
[Unexpected Behavior] ScreenSelectMusic shows both .sm & .dwi difficulties

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#386]
**What you're using**
Go to old any songs with .sm and .dwi in folder.
Both difficulties are being shown.
![2021-08-06_212322](https://user-images.githubusercontent.com/83576877/128561581-32f507b1-bf04-4141-954f-af561cccbc3c.jpg)

**Expected behavior**
Don't show duplicates (have file prioritisation)

**Comment by ListenerJubatus** [comment]
We now load all simfiles files that exist in a folder and not just one. However, on Alpha 4.9.9 HF2, we have changed the behaviour back to not loading DWI files if there is an SM file.
