### ISSUE TITLE
[BUG] Navigation sounds are louder (playing twice?) on edit profile screen

### ISSUE THREAD

**Issue by Joehuu** [TeamRizu/OutFox#390]
**Please give your StepMania Info**

StepMania Version: 4.9.9HF2
Theme: Default

**Describe the problem**

When navigating (top to bottom) on this specific screen, the sounds are unusually louder than the rest of the game.

**Describe what should happen**

It should conform with the rest of the game.

Add any other context or screenshots here.

![image](https://user-images.githubusercontent.com/35318437/128622956-d5faa8bf-f63f-44e3-96cb-ecc55fa2622d.png)

**Comment by Sudospective** [comment]
Confirming, also found the volume on the profile select screen is louder as well.

**Comment by JoseVarelaP** [comment]
Yeah, they're ignoring the EffectVolume value.

**Comment by DarkBahamut162** [comment]
And I found out a similar sound loudness issue during ScreenGameplay: Playing as two player makes the selected song's audio do that as well.

**Comment by MrTwinkles47** [comment]
> And I found out a similar sound loudness issue during ScreenGameplay: Playing as two player makes the selected song's audio do that as well.

Today, I ran into this problem. When there are two players, during gameplay the song volume is much louder. At the music wheel the song preview plays at the correct volume. 

My quick workaround was to decrease SoundVolume to 80%.

**Comment by Scraticus** [comment]
Fixed in 4.16, thanks for reporting!
