### ISSUE TITLE
[BUG] In-Game syncing returns ScreenPrompt to ScreenGameplay instead of ScreenSelectMusic*

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#395]
**Please give System Info**

OS: Windows 10 Home 64-bit (21H1)
CPU: Intel Core i7 2600 @ 3.40GHz
GPU: ATI Radeon RX 580 Series 8GB
Storage: HDD

**Please give your StepMania Info**

StepMania Version: Project OutFox 5.3 Alpha 4.9.9HF3(b)
Theme: doesn't matter, happens everythere

**Describe the problem**

Self-explanatory. Happens no matter if I pick "Yes" or "No" to the prompt.

**Describe what should happen**

Whatever options I picked in the pause menu before on where it should bring me, I guess...

**Logs and Additional context**

I don't see anything in the logs, but here is a [video](http://y2u.be/DJSAwXh6S1A)

**Comment by JoseVarelaP** [comment]
Found the issue, there's no case for GoToPrevScreen in the new case system we did for ScreenGameplay, so it never performed the screen change method when going back, but it'll still do it when going foward (like ending the song).
