### ISSUE TITLE
[Game Crash] Crash on audio sync calibration, even in dance gametype

### ISSUE THREAD

**Issue by bcdefg123** [TeamRizu/OutFox#396]
**Describe how it crashed by giving us those informations:**

OutFox 4.9.9HF3 crashes after attempting to exit the sync screen (the screen where you press left and right repeatedly to calibrate the offset). This was originally reported by Sevish on Discord and replicated by me.

Sevish reported this happening on Ubuntu and didn't mention whether he/she was using the dance gametype or not.
This happens for me on Raspberry Pi OS 64-bit, and I am using the dance gametype, which is supposed to work.

[info.txt](https://github.com/TeamRizu/OutFox/files/6983319/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6983320/log.txt)

I cannot find a crashinfo.txt. Never seen one, which is odd because there's been a lot of crashes...

**Explain how we can reproduce the error**

1. Start the game
2. Options > Input & Calibration > Calibrate Audio Sync
3. Go for a round of syncing
4. Hold escape to finalize the offset
5. Press yes  to save offset, game crashes.

I have also had this happen while selecting 'no', IIRC.

Video: https://youtu.be/PxdCk6Pp_wM

**Comment by DDRMANIAC007** [comment]
This also happens to me on Windows 10. I don't even need to try to sync. Just exiting the mode without trying to change anything also results in a crash.

**Comment by aryoadhi** [comment]
Same issue here on Ubuntu 21.04. I guess it's not OS-dependent issue?

**Comment by TheNathannator** [comment]
Same issue on my end. Probably worth noting that the new offset still saves as normal if you select Yes.
Looking through other issues, could this be related to #395 in some way?

Here's my logs:
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7002041/crashinfo.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/7002066/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7002068/log.txt)

**Comment by Scraticus** [comment]
This one is fixed in Hotfix 4, we had a weird one where an ancient upstream bug crept up and bit us

**Comment by Scraticus** [comment]
Thanks for reporting!
