### ISSUE TITLE
[Game Crash] Game crashes after building a partial song cache due to theme out of memory error

### ISSUE THREAD

**Issue by MrTwinkles47** [TeamRizu/OutFox#397]
Windows 10 LTSC (1809)
Intel i3-3240
Nvidia GTX660 2GB
4GB RAM
Outfox 4.9.9HF3b

After ~9,600 songs are cached, the game crashes. Outfox uses about 1.7GB of RAM right before the crash. If I restart the game after the crash, the cache is deleted and it happens again. This issue has existed since Outfox 4.9.7 for me (I have not used Outfox <4.9.7). I have a library of about 15.6k songs.

My workaround is to remove the song packs beyond the 9,600 song "limit" and let Outfox build the song/course cache. I then add the remaining song packs back to the `/Songs` folder and restart the game. All 15.6k songs will be successfully cached after that. I also have tried deleting `Preferences.ini` and `/Cache` to no avail. Also, because of this workaround, I can't use the "reload songs/courses" without the crash happening again.

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6985531/crashinfo.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/6985533/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6985534/log.txt)

**Comment by MrTwinkles47** [comment]
I can confirm this issue still exists in 4.9.10

**Comment by Scraticus** [comment]
Apologies for the delay on replying to this one, but it is actually a bug in how we do our parsing, I was running a profile on an older machine, and I had a crash which matches this.

I'm still working out what we can do to fix it, but thank you for taking the time to report this

**Comment by Scraticus** [comment]
can you try 4.11.0?

Many thanks

**Comment by rxhfcy** [comment]
(Not the original reporter but I think I'm seeing the same exacy bug, and 4.11.0 didn't fix it for me. The default theme works much better: using Simply Love during building the cache uses much more memory. So one way to work around this seems to be switching the theme temporarily.)

**Comment by Scraticus** [comment]
Can you try 4.13 when we release it this week?

**Comment by Scraticus** [comment]
reopen a new bug report if you get a crash, as this is a pretty old one now.

**Comment by rxhfcy** [comment]
I'm seeing this too, I don't think anything has changed here. Can this be reopened?
