### ISSUE TITLE
[Nitpick] StretchPaused doesn't pause

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#399]
**Give an example of what is wrong**

The problem is the GainFocusCommand: `GainFocusCommand=cmd(play);`

**Given an example of what it should look like**

If should be like this: `GainFocusCommand=cmd(pause);`

Its `OnCommand` has `:pause()` but it gets overwriten by the GainFocus' `play()`

**Comment by MrThatKid** [comment]
Funnily enough, this seems to be an upstream bug, with the commands being put into the BackgroundEffects in February of 2007.
This should be fixed in the next hotfix! I'm leaving this open for now, so please re-test when the hotfix releases.

**Comment by DarkBahamut162** [comment]
I checked and it now seems to work as intended out of the box (as well as the "no cmd in code" in both Background folders) so this can be closed now.
