### ISSUE TITLE
Theme icon from old theme persists after theme switch

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#4]
## How to reproduce

1° Start the game with one theme, in my case, I'm using DanceDanceRevolution XX -STARLiGHT-
2° Switch to another theme.

----------- Mini-issue -----------
When going from DanceDanceRevolution XX -STARLiGHT- to SoundWaves, the starlight theme music still plays after the change until you get to the title screen.
----------- Mini-issue -----------

3° Trigger an error that can be handled
4° See the old theme icon in the error window

Video example: https://youtu.be/LqmOO8CuRtQ

At 0:09 you can see the mini-issue, at 0:36 you can see the main issue.

**Comment by Scraticus** [comment]
There seems to be a problem with the 'themechanged' code that isn't freeing the music.

as for the icon, that _may_ not be fixable due to the way the windows are drawn, I'll look into it more.

**Comment by MrThatKid** [comment]
At this point, the app & window icon is the OutFox icon, and no theme can change that afaik.
Closing this, since it doesn't seem relevant anymore.
