### ISSUE TITLE
[Feature Request] Allow early dismissal of the input keybind warning.

### ISSUE THREAD

**Issue by MrThatKid** [TeamRizu/OutFox#40]
**Is your feature request related to a problem? Please describe.**

Squirrel and the beta testers have experienced frustration relating to this warning to not override certain inputs.

It takes a noticeably long time before one can dismiss the warning.

**Describe the solution you'd like**

Either set the timer for dismissal lower, or allow for immediate dismissal.

**Comment by JoseVarelaP** [comment]
Just fixed, you are now able to hit enter at any point during the warning to dismiss the message.
