### ISSUE TITLE
[BUG] Inconsistent graph between song selection and gameplay with too many warps and fakes

### ISSUE THREAD

**Issue by aryoadhi** [TeamRizu/OutFox#400]
**Version**

StepMania Version: 5.3 Alpha 4.9.9HF3b
Theme: Soundwaves (Default Alpha 4.9.9)

**Describe the problem**

The density graph between song selection and gameplay is inconsistent. Easily reproduceable with files with a lot of warps and fake notes (attached below). Happens with mini density graph and full-sized one.

**Describe what should happen**

The density graph should be consistent between song selection and gameplay.

**Logs and Additional context**

![Cuplikan layar dari 2021-08-17 19-36-25](https://user-images.githubusercontent.com/5029654/129727376-05679956-68bc-4eee-a8b1-aa5cf3097f70.png)

![Cuplikan layar dari 2021-08-17 19-36-10](https://user-images.githubusercontent.com/5029654/129727493-6af9e819-b89d-49b0-a9f7-02d2fce886c6.png)

![Cuplikan layar dari 2021-08-17 19-41-02](https://user-images.githubusercontent.com/5029654/129727524-d2795dc9-3f89-43eb-aabd-4430ef5beb37.png)

[Sample chart here.](https://r-sei.s-ul.eu/GVlF8Rze)

**Comment by JoseVarelaP** [comment]
Found out the issue, the graph creation from Gameplay graphs is tied to song timing, so depending on what it assigned to, it could go offcourse, but it's fixed now.

<img width="1192" alt="Captura de Pantalla" src="https://user-images.githubusercontent.com/23246027/129741436-17b080bb-e333-4064-bc2c-58eb8bcea048.png">
