### ISSUE TITLE
[Game Crash] Pump Mode - Extended, Oni, and Endless modes cause crash

### ISSUE THREAD

**Issue by notnola** [TeamRizu/OutFox#406]
I am not sure if this is actually a bug, or just that my simfiles are not "compatible"?
Anyway - Simple select one of those modes and the game crashes.  

[log.txt](https://github.com/TeamRizu/OutFox/files/7027484/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/7027485/info.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7027486/crashinfo.txt)

**Comment by Jousway** [comment]
this was an issue with the experimental autokeysound loader in dev alpha builds, this isnt a public release issue, and has already been fixed, and will be fixed in the next public release
