### ISSUE TITLE
[Game Crash] Consistent Crash While Loading Z-I-v Battle Royale\Ohayo!

### ISSUE THREAD

**Issue by animusyosho** [TeamRizu/OutFox#408]
Version 5.3.0.499. This did not happen on the previous version I was using (5.3.0.460)

1. Z-I-v Battle Royale\Ohayo! starts to load either as part of a course or a regular song play in Dance.
2. Silent CTD.

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7042034/crashinfo.txt)

**Comment by aryoadhi** [comment]
Mind to link me the simfile? I need to try it myself and see if it also crashes.

**Comment by animusyosho** [comment]
Sure thing, this one here:
https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=40328

**Comment by aryoadhi** [comment]
Doesn't crash on me. I think it's your custom theme causing the crash.

**Comment by Scraticus** [comment]
Fixed,  but reopen if you crash again.
