### ISSUE TITLE
Game says to turn it off cuz it thinks its crashed

### ISSUE THREAD

**Issue by Redline676767** [TeamRizu/OutFox#409]
OS: Ubuntu Hursuit hippo 

CPU: intel i3

GPU: intergrated

Storage: kingston ssd

**Please give your StepMania Info**

StepMania Version: 4.9.9 hf3 
Theme: default

**Describe the problem**

everytime I open it which i do by double clicking the ./stepmania file or running ./stepmania on the cdl it says to turn it off cuz its unresponsive but other then that it works fine 

**Describe what should happen**

A clear and concise description of what you think should happen.

**Logs and Additional context**

1. Go into the game folder
2. Open the Logs folder
3. Grab every file in there and post with the issue.
4. Go back to the game folder, if there's an crashinfo.txt then send it too.

Add any other context or screenshots here.

**Comment by aryoadhi** [comment]
Related/duplicate to #226 ?
