### ISSUE TITLE
[Unexpected Behavior] It's not clear if Esc should exit the test Input screen.

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#41]
**What you're using**

Stepmania 5.3 (4.6 OF special build git-555b3668ce)

Go into the Test Input screen and look at what the screen says:
![image](https://user-images.githubusercontent.com/58047457/88346860-c4f08a00-cd1f-11ea-8065-f03e15cd68f6.png)

It says that you can use BACK or ENTER to exit the screen, **that's not true**, you can only use ENTER to exit the screen. 

This is also included with most if not all translations since the en.ini itself(which is what translators uses as base to translate content) contains this text.

**Expected behavior**

The text should only include ENTER or make BACK also exit the screen.

**Comment by JoseVarelaP** [comment]
Fixed, now you can hold the back or start buttons to exit the screen.
