### ISSUE TITLE
[BUG] Multiple Access Violations for Techno

### ISSUE THREAD

**Issue by VEGGIM** [TeamRizu/OutFox#412]
**Please give System Info**

OS: *Windows 10*

CPU: *Intel core i7-8750h*

GPU: *GTX 1060M*

Storage: *WD blue 1tb SSd*

**Please give your StepMania Info**

StepMania Version: *Project Outfox 5.3 ver.4.9.10 *
Theme: *Personal Theme called technogroove(modified version of soundwaves)*

**Describe the problem**
I decided to try modes other than standard just for curiosity for techno and now there's an huge issue. It looks like for techno any mode that isn't standard or easy will get access violations. This can cause headaches for anyone who wants to run this in an arcade.

**Describe what should happen**

Techno should be able to get into endless Oni and extended. I got no theme or graphical errors so those aren't exactly the cause. In this case it might be the same thing as how stepmania is flawed with multi mode steps.

**Logs and Additional context**

[5.3 AV LOGS.zip](https://github.com/TeamRizu/OutFox/files/7070860/5.3.AV.LOGS.zip)
CR is the crash reason texts. the mode which the error is about is in the name.

Add any other context or screenshots here.

**Comment by JoseVarelaP** [comment]
What are the contents of your `ScreenGameplay out` file? It contains elements not present on Soundwaves at all. And given it's trying to read contents from a course, and courses don't give out Song objects directly, so that would fail.

```
/////////////////////////////////////////
188:51.822: WARNING: Lua runtime error: ...TechnoGroove/BGAnimations/ScreenGameplay out/default.lua:185: attempt to index a nil value (local 'song')
188:51.822: WARNING: /Appearance/Themes/TechnoGroove/BGAnimations/ScreenGameplay out/default.lua:185: main(dt = 1.235,song = (null),t = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = 0,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = FileType_Bitmap,(*temporary) =  (local 'song'),(*temporary) = attempt to index a nil value (local 'song'))
/////////////////////////////////////////
```

I also notice a huge ammount of timing errors, given the new changes to the timing system in 4.9.10 (which allow function-specific timings), but also the fact that the timing window you're trying to use is not present? Have you checked is still there? This can lead to crashes if its uncapable to reaching a timing window to use.

```
WARNING: [Options.ReturnCurrentTiming] Current Timing 'TechnoGroove' is not present on TimingWindows, using 'Original' instead.
```

As for all of these errors on ScreenTimingAdjust decorations, its again because of the new timing system and how it has to return data, so your screen in this ocassion will not return the correct values, nor even reach valid data.
```
WARNING: Error playing command:...noGroove/BGAnimations/ScreenTimingAdjust decorations.lua:53: attempt to index a function value (field 'Timings')
WARNING: /Appearance/Themes/TechnoGroove/BGAnimations/ScreenTimingAdjust decorations.lua:53: unknown(s = (null),param = (null),sm = (null),(*temporary) = (null),(*temporary) = TapNoteScore_W1,(*temporary) = W1,(*temporary) = (null),(*temporary) = (null),(*temporary) = Selected,(*temporary) =  (field 'Timings'),(*temporary) = attempt to index a function value (field 'Timings'))
```

To fix these ones, just add the following line on that screen's lua, after the `local sm = local sm = TimingWindow[param.choice]()` line.

```lua
local sm = TimingWindow[param.choice]()
sm.Timings = LoadModule("Gameplay.UseTimingTable.lua")(sm) -- Add this
if sm.Timings[ "TapNoteScore_"..JudgNames[i] ] then
```

**Comment by JoseVarelaP** [comment]
As for the Access Violations, it could be related on the first segment of the research, which is the invalid 'Song' object, or the timing set being non-existant, however, i'm trying to replicate the bugs but it lets me run techno on nonstop and endless.

In Nonstop
<img width="1280" alt="Captura de Pantalla" src="https://user-images.githubusercontent.com/23246027/132071645-e8407950-4d57-4750-89ea-cddad46adb21.png">

In Endless
<img width="1280" alt="Captura de Pantalla" src="https://user-images.githubusercontent.com/23246027/132071675-d8f9c397-cd65-4147-b516-60ca8cb357db.png">

In Oni
<img width="1280" alt="Captura de Pantalla 6" src="https://user-images.githubusercontent.com/23246027/132071724-65002cce-425b-4bc9-8009-b144e03348bb.png">

**Comment by Scraticus** [comment]
There was also a bug with styles switching difficulties between different songs. As we've not heard anything, i'll be closing this. if you have more issues, you can reopen the issue.
