### ISSUE TITLE
[BUG] -nan(ind) RadarValues in Stats.xml high score records

### ISSUE THREAD

**Issue by MrTwinkles47** [TeamRizu/OutFox#414]
**Please give System Info**

OS: Windows 10 LTSC (1809)

CPU: Intel i3-3240

GPU: GTX 660 2GB

Storage: SSD

**Please give your StepMania Info**

StepMania Version: 4.9.10
Theme: Simply Love 5.01

**Describe the problem**

A value of `-nan(ind)` is appearing for "air" and "freeze" RadarValues in profile Stats.xml files. 

**Describe what should happen**

The value should be a number.
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7092724/crashinfo.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/7092725/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7092726/log.txt)
[Stats -nan(ind) eample.txt](https://github.com/TeamRizu/OutFox/files/7092727/Stats.-nan.ind.eample.txt)

**Logs and Additional context**

1. Go into the game folder
2. Open the Logs folder
3. Grab every file in there and post with the issue.
4. Go back to the game folder, if there's an crashinfo.txt then send it too.

Add any other context or screenshots here.

**Comment by concubidated** [comment]
```<RadarValues>
<Stream>0.934109</Stream>
<Voltage>0.310611</Voltage>
<Air>-nan(ind)</Air>
<Freeze>1.000000</Freeze>
<Chaos>0.906845</Chaos>
<Notes>512.000000</Notes>
<TapsAndHolds>512</TapsAndHolds>
<Jumps>0</Jumps>
<Holds>83</Holds>
<Mines>4</Mines>
<Hands>0</Hands>
<Rolls>0</Rolls>
<Lifts>0</Lifts>
<Fakes>0</Fakes>
</RadarValues>```

Definitely an issue!

**Comment by concubidated** [comment]
You shared a crash log with a GL_OUT_OF_MEMORY issue (have you already resolved this?), also looks like you may have some permission issues.

```
WARNING: X:\Development\StepmaniaOutfox\src\RageFileDriverDirect.cpp:364: Error renaming "D:/StepMania 5.3 Outfox/Save/LocalProfiles/00000000/new.Stats.xml.new" to "D:/StepMania 5.3 Outfox/Save/LocalProfiles/00000000/Stats.xml" (Access is denied.)
WARNING: X:\Development\StepmaniaOutfox\src\RageFileDriverDirect.cpp:364: Error renaming "D:/StepMania 5.3 Outfox/Save/new.Interaction.txt.new" to "D:/StepMania 5.3 Outfox/Save/Interaction.txt" (Access is denied.)
WARNING: X:\Development\StepmaniaOutfox\src\RageFileDriverDirect.cpp:364: Error renaming "D:/StepMania 5.3 Outfox/Save/LocalProfiles/00000001/new.Stats.xml.new" to "D:/StepMania 5.3 Outfox/Save/LocalProfiles/00000001/Stats.xml" (Access is denied.)
WARNING: RageSoundDriver::GetHardwareFrame: too many tries
WARNING: X:\Development\StepmaniaOutfox\src\RageFileDriverDirect.cpp:364: Error renaming "D:/StepMania 5.3 Outfox/Save/LocalProfiles/00000000/new.Stats.xml.new" to "D:/StepMania 5.3 Outfox/Save/LocalProfiles/00000000/Stats.xml" (Access is denied.)
```

**Comment by MrTwinkles47** [comment]
I have not resolved the GL_OUT_OF_MEMORY issue yet, but that particular crash and log happened during the same session as the -nan(ind) bug.

**Comment by concubidated** [comment]
Okay, I was unable to reproduce the -nan(ind) using the same chart, i'll see if someone on windows can reproduce.

**Comment by JoseVarelaP** [comment]
Managed to replicate with a song that has no jumps.
```
Result of RadarCat_Air: nan (nan)
```
It seems that the calculation of Air does not care if there is no value at all (given in this case, the value of the Air category is 0, and just divides by 0.

**Comment by concubidated** [comment]
air should be jumps / seconds though, cant see where we have any divide by zeros.

**Comment by MrTwinkles47** [comment]
Here's another snippet for a chart you may be familiar with: 

```
<Song Dir='Songs/OutFox Serenity Volume 1/spirai project -drazil- - synthborn lovebirds/'>
<Steps Difficulty='Challenge' StepsType='dance-single'>...
<RadarValues>
<Stream>0.766355</Stream>
<Voltage>0.149973</Voltage>
<Air>-nan(ind)</Air>
<Freeze>0.984615</Freeze>
<Chaos>0.724352</Chaos>
<Notes>303.000000</Notes>
<TapsAndHolds>303</TapsAndHolds>
<Jumps>0</Jumps>
<Holds>64</Holds>
<Mines>0</Mines>
<Hands>0</Hands>
<Rolls>0</Rolls>
<Lifts>0</Lifts>
<Fakes>0</Fakes>
</RadarValues>

**Comment by concubidated** [comment]
we figured it out, will have a fix for the next update, thanks for reporting!
