### ISSUE TITLE
[Game Crash] System freeze on exit in exclusive fullscreen

### ISSUE THREAD

**Issue by bcdefg123** [TeamRizu/OutFox#417]
**Describe how it crashed by giving us those informations:**

Whenever I try to exit OutFox 4.9.10 either through the menu or via alt+f4, with the game running in exclusive fullscreen (borderless windowed is fine), the game will basically freeze and be unresponsive - the only solution I know of is to cut the power to my Raspberry Pi and start again. Alt+F4 doesn't work, nor does alt+tab if I remember correctly.

I am running the arm64v8 build on a Raspberry Pi 4B with 4GB of RAM.

[info.txt](https://github.com/TeamRizu/OutFox/files/7108980/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7108982/log.txt)

**Explain how we can reproduce the error**

1. Start the game
2. Select exclusive fullscreen in graphic options, exit the menu to save
3. Exit the game through either the main menu or alt+f4. It will freeze.

**Sreenshots/Videos**

Video of exclusive working, then borderless not working: https://youtu.be/VhfhdYTRq-Q

**Additional information**

This hanging behavior was also present in 4.9.9HF3, but I wanted to wait until the 4.9.10 update for Linux ARM came out to report the bug as the builds for other platforms were already out. 
With 4.9.9, this freeze was particularly painful as game performance in exclusive mode was significantly better than borderless windowed. Now in 4.9.10 borderless windowed performance seems great, so I can avoid this.

**Comment by Scraticus** [comment]
can you confirm if this is still an issue for me?

**Comment by bcdefg123** [comment]
Did some testing today, no hanging/crashing in 0.4.14.1.
