### ISSUE TITLE
[FIXED] [BUG]Lyrics do not scroll at the correct speed when Rate is adjusted

### ISSUE THREAD

**Issue by SilentTempest83** [TeamRizu/OutFox#422]
**What you're using**

Lyrics from LRC files do not scroll at the appropriate speed during game play when Rate is set to values other than 1.0x
Lyrics scroll slower than expected and lines fail to complete scrolling before advancing to the following line when rate is adjusted downward, whereas lyrics scroll too quickly and lines complete scrolling before corresponding audio when rate is adjusted upward.
Issue is present in all builds newer than Alpha 4.9.0 up to current version Alpha 4.9.10.  Issue has been tested on Windows builds on 2 separate machines.

**Expected behavior**

Lyrics will scroll at the same speed as the Rate that is set so that properly timed lyrics will remain in sync with audio at whatever Rate value is set.

VIDEO EXAMPLE OF BEHAVIOR:
[https://youtu.be/KFAvApKxtVg](https://youtu.be/KFAvApKxtVg)

**Comment by DarkBahamut162** [comment]
I checked it myself on my own theme and can confirm it to be the case.
It seemed almost like in #411 (mentioned in Speed Oddities) how the rate gets applied twice over. But this time, it happens to everythere (SampleRates don't seem to matter here this time, Tested with 48kHz & 44.1kHz songs, Couldn't find anything lower to check if their effects are worse or not)

**Comment by Scraticus** [comment]
A workaround fix will be added in a17 of 042, but will be fixed in the main release of Alpha V 042.

Thanks for reporting guys

**Comment by Scraticus** [comment]
fixed in 042
