### ISSUE TITLE
[BUG] Techno error with different modes.

### ISSUE THREAD

**Issue by VEGGIM** [TeamRizu/OutFox#423]
**Please give System Info**

OS: *Windows 10*

CPU: i7-8750h

GPU: *gtx 1060 mobile*

Storage: *1tb ssd*

**Please give your StepMania Info**

StepMania Version: *5.3 4.9.10*
Theme: Own theme called TechnoGroove
**Describe the problem**

This is more of  a thing that has been happening since sm5 i thought of putting it here so it should be easier. to track. What's happening is that there is access violations any time you have 2 different modes. ex 4 and 5 when there's 2 players.  

**Describe what should happen**

What would happen is that 4 and 5 step would play together,  and other modes like 5 and 9 step /4 and 8 step, etc. would work. It happened some time before strangely. Not sure because of luck or just something else 

**Logs and Additional context**

1. Go into the game folder
2. Open the Logs folder
3. Grab every file in there and post with the issue.
4. Go back to the game folder, if there's an crashinfo.txt then send it too.

These logs are for 4 and 5 mode. the same thing will occur for anything else.
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7187853/crashinfo.txt)

[log.txt](https://github.com/TeamRizu/OutFox/files/7187856/log.txt)

Add any other context or screenshots here.
![4 step and 5 step](https://user-images.githubusercontent.com/89358434/133838347-834527f8-37e6-432f-aacb-dbb2ae5d5698.png)

**Comment by VEGGIM** [comment]
Correction, it looks like it works if player 1 step count is higher than 2 players. 5 and 4/ 9 and 5 for example. But if vise versa is done it crashes.

**Comment by Scraticus** [comment]
We will lock the styles for Techno for now to remove this crash, but this is low priority until after Alpha V. We will be doing the work on the styles per player in the new year.

Thanks for reporting
