### ISSUE TITLE
[BUG] Windows: stuttering display with some simfiles

### ISSUE THREAD

**Issue by Kaede573** [TeamRizu/OutFox#424]
**Please give System Info**

OS: Windows 10

GPU: Radeon R9 Fury.
Radeon Software Version 21.5.2 (Software Version 2021.0511.1352.24954, Driver Version 21.09.03.08-210511a-368456C-RadeonSoftware, 2D Driver Version 8.1.1.1634, Direct3D® Version 9.14.10.01494, OpenGL® Version 29.20.11000.14831)

**Please give your StepMania Info**

StepMania Version: latest
Theme: the default one

**Describe the problem**

I have found a simfile (attached) that makes display (arrows scrolling) stutter ... but only on Windows, and with Vsync on only. I have tested with VRR on and off, it makes no difference. I am using exclusive fullscreen.
I could not reproduce this stutter issue on Linux. With _pulse_ I do have some stutter, but that stutter I have with other simfiles as well (at least _to the eye_, it looks exactly the same) and is a known, global issue (https://github.com/TeamRizu/OutFox/issues/181). With ALSA this simfile plays 100% smooth.
There are both ssc and sm files in the folder, I'm not sure which StepMania picks by default, so I have included both.

[SXU258 - Energy Night.ssc.txt](https://github.com/TeamRizu/OutFox/files/7190525/SXU258.-.Energy.Night.ssc.txt)
[SXU258 - Energy Night.sm.txt](https://github.com/TeamRizu/OutFox/files/7190526/SXU258.-.Energy.Night.sm.txt)
The simfile is from the STEPMAKERS X UNIVERSE pack.

Maybe this is just the known issue reported in https://github.com/TeamRizu/OutFox/issues/181 ? I was bit puzzled to notice stutter on only one specific simfile after playing dozens of other ones, which is why I have opened this report.

**Comment by Kaede573** [comment]
I did some more testing.
Went back to alpha 4.0 and there is no stuttering on it. No stuttering on old StepMania 5.1 beta 2 either.
After testing, it looks like the stutter was "introduced" (at least on my system) either in alpha 4.2 or 4.3 (there is no 4.2 available for Windows so I couldn't test it). I have tested a few recent releases and did not find one that didn't exhibit the stutter, but I haven't tested them all (far too many to test).

I have identified a few more simfiles that exhibit the same issue, so I am attaching them to this ticket.
"The most crazy video" is the chart I used for testing previous releases. "Energy Night" I have also tested on 4.0 and 4.3.
[THE MOST CRAZY VIDEO.sm.txt](https://github.com/TeamRizu/OutFox/files/7192150/THE.MOST.CRAZY.VIDEO.sm.txt)
[2 Phut Hon (KAIZ Remix).sm.txt](https://github.com/TeamRizu/OutFox/files/7192148/2.Phut.Hon.KAIZ.Remix.sm.txt)
[2 Phut Hon (KAIZ Remix).dwi.txt](https://github.com/TeamRizu/OutFox/files/7192152/2.Phut.Hon.KAIZ.Remix.dwi.txt)
[SPARKS.sm.txt](https://github.com/TeamRizu/OutFox/files/7192149/SPARKS.sm.txt)
[USSEEWA.sm.txt](https://github.com/TeamRizu/OutFox/files/7192151/USSEEWA.sm.txt)

**Comment by Scraticus** [comment]
can you test alpha 4.4.1? that was the finalisation of the new window code, so i'm interested if this regression was fixed but broken again

Cheers

**Comment by Kaede573** [comment]
It have just checked, it does stutter on 4.4.1 too.

**Comment by Scraticus** [comment]
thanks for the update, i know where the bug is, so will work on it this week.

**Comment by Scraticus** [comment]
It is related to #181 but not the same bug. So will keep this open while i work on it.

**Comment by Scraticus** [comment]
I'm going to close this as we discovered it was an encoding issue. I am considering adding a 'legacy' option for older FFPMEG which can still support some of those ancient videos/encoding methods, i'll let you know.

Thanks for reporting

**Comment by Kaede573** [comment]
There really aren't many files that recent FFMPEG do not like (they are rare) so here is another candidate if it might be useful for later: Love Dramatic from Ben Speirs' SPEIRMIX GALAXY.
