### ISSUE TITLE
LUA files doesn't like "../" on file inputs

### ISSUE THREAD

**Issue by SDB13** [TeamRizu/OutFox#425]
OS: Windows 10

CPU: Intel i7-8700K

GPU: Asus Nvidia 1080ti

Storage: Intel SSD 705D 

StepMania Version: Project OutFox 5.3 Alpha 4.9.10 
Theme: default

When "../" is inputed to change file folder in .lua files, it reads it as part of the file name instead. It should be changing folders instead.

I have trouble finding the logs on this issue because this is not a typical glitch.

**Comment by Scraticus** [comment]
This is part of the sandbox, and we do not allow escaping the folder in this manner.

what are you trying to do that requires folder switching?
