### ISSUE TITLE
Stamp On The Ground makes OutFox to crash on Ubuntu 20.04

### ISSUE THREAD

**Issue by CuriousCat618** [TeamRizu/OutFox#430]
Today I felt the urge to play a StepMania version of the song Stamp on the Ground. I played it in Outfox since Stepmania doesn't run on my machine. I've never had problems with OutFox before, but when I downloaded a step file for Stamp on the Ground, the game crashed. I tried downloading a different map, and multiple different maps from different sources, but none of them worked. I've attached the crash report and a link to the latest of the step files. Any help would be appreciated, since this song will be stuck in my head for the foreseeable future.
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7248464/crashinfo.txt)
https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=15374

**Comment by JoseVarelaP** [comment]
Do also attach the log.txt file as it will provide more info about what OutFox attempted to do with the file itself.
Already analyzing the crashinfo however indicates that it could not find a music file on the chart. However, I assume you haven't touched anything from the file?

**Comment by CuriousCat618** [comment]
> However, I assume you haven't touched anything from the file?
Yep. I didn't touch anything.

**Comment by concubidated** [comment]
```
WARNING: RageSound::Load: error opening sound "/Songs/StepMania 5/Stamp On The Ground/Stamp on the Ground.ogg": No such file or directory
```
Does the file exist, and if so, do you have read permissions on it?

**Comment by CuriousCat618** [comment]
@Jousway, I checked again, and yeah, the file's been untouched.
