### ISSUE TITLE
[BUG] (CRASH|BLACKSCREEN|FREEZE) Extreme BPMs makes game unusable

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10 Home (21H1)

### CPU

Intel Core i7 2600 @ 3.40GHz

### GPU

8192MB ATI Radeon RX 580 Series

### Storage

2 x 1863GB Western Digital WDC WD2003FZEX-00SRLA0 ATA Device (SATA )

### Game Version

4.10.0

### Describe the problem

The following simfile result in a crash/blackscreen in the current Soundwaves theme while trying to get into GamePlay but freezes on other themes during GamePlay upon reaching said BPM change

x-Aria (今宵、あなたのPCは試される ～ベンチマークdwi～)
x-Aria (Tonight, your PC will be tested ~ benchmark dwi ~)

Reason for the freeze:
18'446'744'073'709'552'000 BPM (eighteen quintillion) on beat 2047

ALSO: During testing I found out that Soundwaves first crashed and then blackscreened after switching themes to one where the simfile was accessable but would then freeze at said BPM change.

### Describe what should happen

As said down below in [Additional Content]:
Like an earlier version of SM5 (anything newer than 2014 would presumably produce this, as the video was created in 2019):

Check for crashable BPMs and lower them to a more manageable state,
The reason for this might be that the game sees this BPM as an invalid warp (more down in [Logs].

### Relevant Log output

[Logs]
No helpful logs possible in all cases, except for the following related to this simfile within "userlog.txt"

`Song file "x-Aria" has an invalid Warp at beat 2047.000000, BPM -44739244.000000.`

[Additional Content]
There are several things with this:

This (and SM3.9.X) - Freezes after reaching said BPM
SM SSC - Cuts said BPM out entirely, makes simfile last longer as last BPM was "4"
Early SM5 builds (unspecified 2014 build shown down below) - Lowers it to a still high but manageable BPM for the game (somewhat seen in the video down below???)
I don't know/remember if SM4 was fine or not... Sorry...

[Old Video using Waiei Theme](https://www.youtube.com/watch?v=JvG15YoaHyg)
[Direct Download Link to the offending simfile](https://www.mediafire.com/file/75o5y9gxyin9bsi/X-Aria.zip/file)

**Comment by Sudospective** [comment]
Sounds like an overflow, which is expected with that massive of a number. I don't know what is exactly planned for this, but personally I feel like this crash is intentional, since this overflow causes a return of a negative BPM and that was patched in favor of proper warps.
