### ISSUE TITLE
[Game Crash] Freezes After Leaving Gameplay

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [TeamRizu/OutFox#434]
### Describe the crash

So... Leaving po-mu causes this program to hang, essentially freezing stepmania.

### How can you reproduce the error?

Install 4.10.0 Windows 32-bit
Play Any po-mu Song.
Leave.
Game Crashed

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/40109698/136178803-26a70f96-b6fc-48fa-a6c5-b0cadd139dda.png)

**Comment by Scraticus** [comment]
Hiya!

thanks for the report, we need the logs the game provided so we can research this further. can you upload them please?

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
[info.txt](https://github.com/TeamRizu/OutFox/files/7293295/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7293296/log.txt)

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
well it's awkward

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
well, i think this crash occur randomly if game is 32bit but windows is 64bit, so this is not a bug. 🤪

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
add windows 64bit variant of 4.10.0 installer, triple check before releasing the tags.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
it does not happen on 4.11.0 so i closing it

**Comment by Scraticus** [comment]
Thanks for letting us know!
