### ISSUE TITLE
[Game Crash] macOS startup crash if when the disk image was originally mounted / verified, only apps downloaded from App Store were allowed

### ISSUE THREAD

**Issue by rxhfcy** [TeamRizu/OutFox#435]
### Describe the crash

On macOS, the game crashes on startup if when the disk image was originally mounted / verified, only apps downloaded from App Store were allowed

### How can you reproduce the error?

1. System Preferences / Security & Privacy / General / Allow apps downloaded from: App Store [only]
2. download OutFox-5.3.0-alpha-4.10.0-MacOS-HF1-date-20211001.dmg
3. mount (and verify) the disk image (right click in Finder / Open / Open)

now, before installing and/or launching, let's allow apps from identified developers too:

4. System Preferences / Security & Privacy / General / Allow apps downloaded from: App Store *and* identified developers

5. copy OutFox from the disk image to /Applications
6. open /Applications/OutFox/OutFox.app (right click in Finder / Open)

what happens:
nothing (the game crashes immediately)

7. delete /Applications/OutFox
8. unmount the OutFox volume / disk image

9. mount the disk image again, copy OutFox to /Applications again

OutFox.app still crashes (!)

10. delete /Applications/OutFox again
11. unmount the OutFox volume / disk image again
12. delete the file you originally downloaded (OutFox-5.3.0-alpha-4.10.0-MacOS-HF1-date-20211001.dmg)

13. re-download the file
14. mount and install again

now the game finally starts up normally

**Comment by Scraticus** [comment]
This is defined expected behaviour. If you only wish to use App Store applications via the setting then that is user choice. As we are not on the store at this time we will not be working on or coding around this. We have to follow a strict set of rules on the Mac system, and what you see/have to do is correct for the settings you have applied. 

We are not on the app store at this time because we are still alpha.

**Comment by rxhfcy** [comment]
> No, it will fail to open because Gatekeeper puts the app into quarantine (It actually does this after you finish downloading the file, because at that point, Gatekeeper will prevent you from opening the DMG file, saying its not from the store). This is the reason why you have to _Right Click -> Open -> Open_ process.

For me, it doesn't seem to matter what the preference is set to when downloading the dmg file (with Safari), or when installing or launching the app, the only time it matters is when the image was first mounted.

I still genuinely think there's a real problem here, which is why I'll try to make my point one more time.

You guys seem to be saying that technically it can be argued that there's no bug here per se, but that doesn't change the fact that for normal users who happen to have this preference set to App Store only (a perfectly normal setting that has never caused me problems with any other app I've ever installed from the web and I pretty much never use the actual App Store), the installation experience is *very* weird and unexpected and results in a completely locked and unusable OutFox installation that can never be launched and always silently dies whatever you do, without any hints about what went wrong, unless you happen to know the right exact spell (both re-download the dmg *and* also figure out which preference setting you should change)

So in my steps above, if you follow them *very* exactly, in step 4, before installing or running the app, the user even changes his mind and explicitly sets the preference to also allow apps from identified developers, but still everything goes south because the preference was "from App Store only" in the previous step 3. So depending on what the preference happened to be in step 3, the app can then either permanently die whatever you do, even when all apps are allowed, or always launch just fine even when only apps from the App Store are allowed.

So can you please at least warn about this in the release notes and even better, warn the user and let them know what to do instead of silently dying, if this can't be fixed otherwise?

**Comment by JoseVarelaP** [comment]
We can add a warning about this, and I'll write up an explanation to the wiki in a few hours.

**Comment by rxhfcy** [comment]
> I dunno which other apps you are talking about but do they require access to external files

I'm talking about any other app I've ever installed on macOS, they all install fine regardless of the "allow from" setting after some light right clicking, but I think the vast majority of apps might access external files in a more standard way: documents, desktop, downloads etc after first having to get permission from the OS.

A release note might well be enough if a "real" warning takes too much time or resources away from other more important things, but I just wanted to point out that this bug is ugly and pretty serious (no way to start up the game) if it happens to hit you. I mean honestly I was very surprised you had modern macOS (let alone arm64) support at all.

Thanks for considering this though!
