### ISSUE TITLE
[Game Crash] Song Restart ScreenGameplay from Operator Menu crashes Outfox

### ISSUE THREAD

**Issue by LightningSkunk** [TeamRizu/OutFox#44]
**Describe how it crashed by giving us those informations:**

1. Start playing a song
2. Enter the operator debug menu F3 + F6 + 3 to restart screen gameplay
3. Game crash.

[F3+F6+3 Menu song restart crashlog.txt](https://github.com/TeamRizu/OutFox/files/4976723/F3%2BF6%2B3.Menu.song.restart.crashlog.txt)

[info.txt](https://github.com/TeamRizu/OutFox/files/4976724/info.txt)

![2020-07-25 18_20_16-StepMania OutFox](https://user-images.githubusercontent.com/68192874/88467297-a74c2d80-cea3-11ea-99c9-b4585bb3cfef.png)
![2020-07-25 18_18_54-New Issue · TeamRizu_OutFox and 11 more pages - Profile 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/68192874/88467298-a915f100-cea3-11ea-99c2-af3271f7ca18.png)

**Comment by PCBoyGames** [comment]
This seems to be a re-report of #23 but I’m glad you found it too.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Scraticus** [comment]
this is a duplicate, will close this one. Continue the conversation on [#23](https://github.com/TeamRizu/OutFox/issues/23)
