### ISSUE TITLE
[Game Crash] the full/normal amd64 Linux version crashes on startup (legacy version works)

### ISSUE THREAD

**Issue by rxhfcy** [TeamRizu/OutFox#444]
### Describe the crash

1. What you were doing before it crashed and what action made the game to crash.
didn't do anything: game crashes on startup

2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7347413/crashinfo.txt)

3. Upload the info.txt and log.txt (GameFolder/Logs
[info.txt](https://github.com/TeamRizu/OutFox/files/7347416/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7347422/log.txt)

### How can you reproduce the error?

1. Start the game
2. Game crashed

### Additional Information

The legacy version without discord doesn't crash and works normally (OutFox-5.3.0-alpha-4.10.0-HF1-amd64-legacy-date-20211001.tar.gz)

The crashing version is OutFox-5.3.0-alpha-4.10.0-HF1-amd64-date-20211001.tar.gz

Is this line in crashinfo.txt relevant?
WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting

Here's information about the computer:
The laptop is old, from the year 2010 (HP EliteBook 8540p)
Ubuntu 20.04.2 LTS (Focal Fossa) (fully updated)
old NVIDIA GPU, "GT216M [NVS 5100M]"
the driver package is nvidia-340 (340.108) (legacy, but the latest version I believe)
Linux kernel version 5.4.0-88-generic (nvidia-340 won't support anything after 5.4), x86_64

**Comment by rxhfcy** [comment]
Yes. The normal non-legacy version still crashes (OutFox-LTS-0.4.18.0-rc6a).

Here's what was in ~/.project-outfox/Logs:
[ProjectOutfox.Crash.2022-10-07--13.19.21.log](https://github.com/TeamRizu/OutFox/files/9733130/ProjectOutfox.Crash.2022-10-07--13.19.21.log)
[ProjectOutfox.MainLog.2022-10-07--13.19.21.log](https://github.com/TeamRizu/OutFox/files/9733132/ProjectOutfox.MainLog.2022-10-07--13.19.21.log)
[ProjectOutfox-default.ThemeLua.2022-10-07--13.19.22.log](https://github.com/TeamRizu/OutFox/files/9733136/ProjectOutfox-default.ThemeLua.2022-10-07--13.19.22.log)

(I deleted the .project-outfox directory before testing, so default settings, songs etc)

**Comment by rxhfcy** [comment]
Didn't find crashinfo.txt anywhere. Here's the console output after the crash:
[console-output.txt](https://github.com/TeamRizu/OutFox/files/9733438/console-output.txt)

**Comment by Scraticus** [comment]
thanks for this, we can confirm the bug and will work on a fix. appreciate the time to reply.

**Comment by Scraticus** [comment]
can you try 6b as we've adjusted the crashlog so we can confirm the func causing the issue

cheers

**Comment by rxhfcy** [comment]
OutFox-alpha-0.4.18.0-rc6b: still couldn't find a crashinfo.txt, here's the console output and log files

[console-output2.txt](https://github.com/TeamRizu/OutFox/files/9739809/console-output2.txt)
[ProjectOutfox.Crash.2022-10-08--19.42.03.log](https://github.com/TeamRizu/OutFox/files/9739812/ProjectOutfox.Crash.2022-10-08--19.42.03.log)
[ProjectOutfox.MainLog.2022-10-08--19.42.03.log](https://github.com/TeamRizu/OutFox/files/9739813/ProjectOutfox.MainLog.2022-10-08--19.42.03.log)

**Comment by Scraticus** [comment]
thank you so much for this, I can confirm the bug and will sort out a fix in the morning!

with this we can release I think now.

awesome

**Comment by Scraticus** [comment]
> OutFox-alpha-0.4.18.0-rc6b: still couldn't find a crashinfo.txt, here's the console output and log files
> 
> [console-output2.txt](https://github.com/TeamRizu/OutFox/files/9739809/console-output2.txt) [ProjectOutfox.Crash.2022-10-08--19.42.03.log](https://github.com/TeamRizu/OutFox/files/9739812/ProjectOutfox.Crash.2022-10-08--19.42.03.log) [ProjectOutfox.MainLog.2022-10-08--19.42.03.log](https://github.com/TeamRizu/OutFox/files/9739813/ProjectOutfox.MainLog.2022-10-08--19.42.03.log)

Outfox doesn't use 'crashinfo.txt' anymore, you provided it's new crashlog in the '.Crash' file above :)

**Comment by Scraticus** [comment]
can you test rc7 when i've finished building it?

**Comment by rxhfcy** [comment]
rc7 and rc8 both still crash, here are the logs:
[RC7-ProjectOutfox.Crash.2022-10-10--11.16.15.log](https://github.com/TeamRizu/OutFox/files/9744277/RC7-ProjectOutfox.Crash.2022-10-10--11.16.15.log)
[RC7-ProjectOutfox.MainLog.2022-10-10--11.16.15.log](https://github.com/TeamRizu/OutFox/files/9744278/RC7-ProjectOutfox.MainLog.2022-10-10--11.16.15.log)
[RC8-ProjectOutfox.Crash.2022-10-10--11.16.57.log](https://github.com/TeamRizu/OutFox/files/9744279/RC8-ProjectOutfox.Crash.2022-10-10--11.16.57.log)
[RC8-ProjectOutfox.MainLog.2022-10-10--11.16.57.log](https://github.com/TeamRizu/OutFox/files/9744280/RC8-ProjectOutfox.MainLog.2022-10-10--11.16.57.log)

**Comment by Scraticus** [comment]
would you be ok to come into the discord and help us troubleshoot?

**Comment by rxhfcy** [comment]
Alright, rc10 no longer crashes. Thanks!
