### ISSUE TITLE
[Game Crash] Shaders are not supported by this driver.

### ISSUE THREAD

**Issue by nickmainville** [TeamRizu/OutFox#445]
Game crashes while booting up from unsupported driver.
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7358474/crashinfo.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/7358475/userlog.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/7358476/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7358477/log.txt)

**Comment by Scraticus** [comment]
can you try 4.11.0 please?

**Comment by Scraticus** [comment]
any update on this? I'm going to close if we don't get an answer in a few days, 4.12 also has this fix

**Comment by Scraticus** [comment]
Going to close this as not heard a reply. Please open a new issue if you still have problems!
