### ISSUE TITLE
[BUG] Scores played on edit charts are written to non-unique entries in Stats.xml

### ISSUE THREAD

**Issue by Kaede573** [TeamRizu/OutFox#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

W10

### Game Version

4.10.0

### Describe the problem

If a simfile offers multiple _edit_ charts, then after playing one, the score gets displayed on every edit chart for that simfile. It seems like this is because stats.xml uses the difficulty as an identifier, and doesn't distinguish between edit charts (it distinguishes singles against doubles etc. thanks to StepsType though).

### Describe what should happen

Individual 'edit' scores should be saved and displayed properly.

**Comment by Scraticus** [comment]
This will be fixed in 4.13

**Comment by Kaede573** [comment]
As mentionned in Discord, I have tested this on rc6 (Windows build) and it is working for me. Thank you Scraticus !
