### ISSUE TITLE
[Game Crash] Unhandled C++ Expectation On Song Parser

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [TeamRizu/OutFox#448]
It's Not a Lua error, but an Unhandled C++ Expectation.

----

Looking at your logs there seems to be a Lua error.

Just to confirm, you did uninstall the old version and reinstall 4.10.0 and not just copy/overwrite the folder right?

I'll wait for the team to see what the error is and get back to you.

_Originally posted by @Scraticus in https://github.com/TeamRizu/OutFox/issues/434#issuecomment-936097590_

**Comment by Sudospective** [comment]
`WARNING: Error playing command:/Appearance/Themes/_fallback/Graphics/Player judgment.lua:124: attempt to index a nil value (field '?')`
This was in your log. Do you have that `Player judgment.lua` file that I could look at if you're still having this problem?

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
not related to this problem, but it's related to music parser or core game

**Comment by Sudospective** [comment]
If it was the music parser, I should be able to reproduce the issue you're having, since it wouldn't matter what song it's parsing. I can't reproduce the issue you're having at all, popn mode seems to work just fine for me. It must be something else, and judging by the logs you're getting, it looks theme related. Even if you're 100% sure it's unrelated, please send the `Player judgment.lua` in your install's `_fallback` theme. It should be in `Appearanve/Themes/_fallback/Graphics`.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
[Player judgment.txt](https://github.com/TeamRizu/OutFox/files/7531013/Player.judgment.txt)

**Comment by Sudospective** [comment]
Do you know which type of chart you were playing when this happened? For example, 5-key? 7-key? 9-key?

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
anywhere

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
and outside of popn

**Comment by Scraticus** [comment]
Can we have a new set of logs and crashlogs please?

I cannot replicate this anymore so I think it's fixed in 4.11.0 (the upcoming release) but another log may help us solve this

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
i think songs prematurely end can crash game
[info.txt](https://github.com/TeamRizu/OutFox/files/7587977/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7587978/log.txt)

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
bro, what the heck it's error spazzing with self:false()?
/////////////////////////////////////////
02:54.763: WARNING: Compiling "return function(self)
02:54.763: WARNING: 	self:false()
02:54.763: WARNING: end
02:54.763: WARNING: ": [string ""]:2: <name> expected near 'false'
/////////////////////////////////////////

**Comment by Jousway** [comment]
what is BetterSolo?

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
my theme that i working on
[BetterSolo.zip](https://github.com/TeamRizu/OutFox/files/7588055/BetterSolo.zip)

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
it does not happen on 4.11.0 so i closing it
