### ISSUE TITLE
[Game Crash] When Start This Game and i Have a Game Crash

### ISSUE THREAD

**Issue by DJPilouDevelopersandmore** [TeamRizu/OutFox#449]
### Describe the crash

Here is!
[log.txt](https://github.com/TeamRizu/OutFox/files/7428607/log.txt)

And This!
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7428614/crashinfo.txt)

### How can you reproduce the error?

When Start This Game, The Game is Crashed

### Screenshots/Videos

![Captura de pantalla (2559)](https://user-images.githubusercontent.com/91300652/139130460-ab9dfce4-659c-44bd-a18a-0512e1ec0dd7.png)

### Additional Information

help with game crash when start this game.

**Comment by Sudospective** [comment]
Looking over your `log.txt`, it looks like your GPU drivers are not installed correctly. Do you know your graphics vendor?

**Comment by Scraticus** [comment]
Moving this to a GPU bug as it's the 'Intel GPU has no drivers as I'm using a dedicated GPU for my games' we inherited from upstream
