### ISSUE TITLE
[Unexpected Behavior] USB Joystick Adapter - not showing up in devices - osx Catalina

### ISSUE THREAD

**Issue by cmhoneycutt343** [TeamRizu/OutFox#45]
**What you're using**

macOS Catalina Version 10.15.5

Running the Latest Build [5.3 Alpha 4.6] (though I did not get this to function properly otherwise).

Running "Stepmania.app" after giving permissions using "xattr -dr com.apple.quarantine /Applications/Stepmania-Outfox-Alpha-4.6.0-MacOS-date-20200711/StepMania.app"

**Expected behavior**

Outfox ought to recognize USB controller adapter as it does others, but fails to populate "Test Input" menu. 

**Current behavior**

Terminal debug window displays message acknowledging USB controller connect; also does not recognize button inputs in Mapping Menu / Test Input Menus. Debug window outputs message when controller is plugged in:

"OutFox Engine (SDL Input Debug) - Joystick Added For Mapping 02 (DragonRise Inc. Generic   USB  Joystick  )"

My USB controller (Reyann Zero Delay Arcade USB Encoder https://www.amazon.com/gp/product/B00UUROWWK/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1).

Program Registers / accepts inputs from other USB joysticks fine; other programs recognize input from "Reyann" Controller fine (why i figured this qualified as a bug and not a tech support issue).

This is my first bug - forgive me if I need to make some sort of correction in reporting etiquette / standards.

**Comment by Scraticus** [comment]
You will need to use the SDL Tool and add a mapping for the controller before it can work on Mac OSX. You do not have a bad device, but the _mapping_ is likely wrong for your pad.

If you need help on mapping the pad, or have any other questions, join our discord and ping Squirrel and I'll help you. I will leave this open until Alpha 5.0.0.

**Comment by moruzerinho6** [comment]
Hello @cmhoneycutt343 

Project Moondance Discord Moderator here, a while ago we created a bug hunter system, users who make issue on this repository gain points and can be rewarded in our discord, so I'm here to ask, are you in Project Moondance discord?

If not, you can join using this link: https://discord.gg/3DgsbSg

If you don't wish to join, that's okay. Please be sure to contact any moderator if you join.

**Comment by Scraticus** [comment]
This one was fixed with the user in Discord, Glad you're able to enjoy the game!
