### ISSUE TITLE
[BUG] SetTextureFiltering not functional on BitmapText actors

### ISSUE THREAD

**Issue by ChocoboGamer** [TeamRizu/OutFox#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10 home

### Game Version

4.9.10

### Describe the problem

When using the actor method SetTextureFiltering on a BitmapText actor. It does not actually affect how the actor draws unlike every other actor type.

### Describe what should happen

When using SetTextureFiltering on BitmapText actors, Faldo should properly disable filtering, while true leaves it enabled.

**Comment by Scraticus** [comment]
This is fixed in 4.13, with setexture being restored. Thanks for reporting!
