### ISSUE TITLE
[Feature Request] Add a function to load font

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#451]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

Maybe use the function if it's possible instead of creating different BitMapTexts.

**Comment by JoseVarelaP** [comment]
Experimenting a bit with it, would a function like this work?

https://user-images.githubusercontent.com/23246027/140582374-ae9f299b-e480-48ab-87ac-76fe9bcc21c0.mp4

**Comment by EngineMachiner** [comment]
That's it!

**Comment by Scraticus** [comment]
Fixed in 4.11
