### ISSUE TITLE
[Game Crash] WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting on windows 10

### ISSUE THREAD

**Issue by SDB13** [TeamRizu/OutFox#452]
### Describe the crash

[log.txt](https://github.com/TeamRizu/OutFox/files/7456682/log.txt)
It was loading songs until this error message keeps popping up every time I load the program.  I tried optimizing the files (.PNG, .FLAC, etc) but it still crashes at the same point.

### How can you reproduce the error?

Just start the program and let it run.  It crashes at around "Love is Dreaminness".  II think the size of the program might have something to do with it.

### Additional Information

The size of the program on my machine is over 40G
![size](https://user-images.githubusercontent.com/15899935/139756242-660cea3e-b935-4528-85dc-f2f2d9a55d81.png)
B

**Comment by SDB13** [comment]
I forgot to mention it was working before the last releases.

**Comment by Sudospective** [comment]
Do you also have your `crashinfo.txt` that you can share here? If you have that, that would help us even more.

**Comment by Scraticus** [comment]
could you run this again and provide the crashlog as well? cheers

**Comment by Scraticus** [comment]
no reply, but we have fixed several of the parsing crashes in 4.13, reopen if you find this bug again
