### ISSUE TITLE
[Feature Request] PlayMode_Course/Both

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#454]
### Is your feature request related to a problem?

For example, in Mungyodance 3, there is an Extra Mode, which is pretty much the only course mode it has and is being set as `playmode,oni`
This makes it impossible to play nonstop courses in that mode or both in one at all.

### Describe the solution you'd like

A mode that combines both nonstop and oni with one another.
A differentiation between them should be easy as oni courses have `GAINSECONDS` / `LIVES` and nonstop courses have `TIME`.

### Describe alternatives you've considered

There is no alternative. Not that I know of...

**Comment by Scraticus** [comment]
Another great feature request. Converting to discussion so we can archive and add it to the road map.
