### ISSUE TITLE
[Unexpected Behavior] X-PAD PROFI Version Dance Pad is not automatically recognised

### ISSUE THREAD

**Issue by Gladstone2412** [TeamRizu/OutFox#46]
**What you're using**

My Czech DDR.cz X-PAD PROFI Version Dance Pad (Red one when you google it) is not automatically recognised as a controller. When I try to map Dance buttons to xbox controller (last option "Map controller"), it is recognised, but when i try to set buttons in controlls it does not recognises all buttons (tipically it recognises only one of this buttons left/right, down/up)

**Expected behavior**

Automatically recognise of X-PAD PROFI Version Dance Pad. In Stepmania 5.1 and bellow, it was automatically recognised.

**Comment by JapanYoshi** [comment]
I had the same problem, albeit with a different controller. The solution involved just not mapping the controller in the ingame menu in the first place.

Can you try using your dance pad on [this](https://gamepad-tester.com/) and see if it recognizes it? If it does, can you press each button and see how it appears on the page?

**Comment by Scraticus** [comment]
We do not use Direct Input anymore as it is going to be removed. Hell Microsoft are already killing a lot of the pads we supported before.

You will need to use the SDL Tool and add a mapping for the controller, or wait until the next major release which will have a temporary fix for the legacy pads.

This is actually an operating system issue, which we have to add work arounds for.

If you need help on mapping the pad, or have any other questions, join our discord and ping Squirrel and I'll help you. I will leave this open until Alpha 5.0.0

**Comment by moruzerinho6** [comment]
Hello @Gladstone2412 

Project Moondance Discord Moderator here, a while ago we created a bug hunter system, users who make issue on this repository gain points and can be rewarded in our discord, so I'm here to ask, are you in Project Moondance discord?

If not, you can join using this link: https://discord.gg/3DgsbSg

If you don't wish to join, that's okay. Please be sure to contact any moderator if you join.

**Comment by Scraticus** [comment]
Fixed in 4.8.0
