### ISSUE TITLE
[Game Crash] Fatal: crash from within the crash signal handler

### ISSUE THREAD

**Issue by PhracturedBlue** [TeamRizu/OutFox#461]
### Describe the crash

Fresh install in Debian Bullseye x86_64
ran ./stepmania

No crashinfo file generated
[info.txt](https://github.com/TeamRizu/OutFox/files/7592525/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7592528/log.txt)

### How can you reproduce the error?

./stepmania

**Comment by SheepyChris** [comment]
Try to run the game with the following command:
`MESA_GL_VERSION_OVERRIDE=3.1COMPAT ./stepmania`
There is currently an issue with Mesa reporting the wrong OpenGL version, which causes the game to crash attempting to access features from said version that aren't there.

**Comment by PhracturedBlue** [comment]
Thanks for the fast support.  That indeed did resolve the issue and get me to the main screen.  I have other issue to resolve before I can actually try playing the game, so I can't test everything, but at least I can now enter the game.

**Comment by Scraticus** [comment]
Hiya PhracturedBlue!

The next alpha will force a lower GL context which will not require the MESA command. 

Feel free to join the discord if you need help as well.

Will be closing this one, as it's fixed in 4.11.0 (this one comes out on the 14th)
