### ISSUE TITLE
[BUG] i keep getting program error

### ISSUE THREAD

**Issue by Callmechristian74** [TeamRizu/OutFox#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

windows 7

### Game Version

4.10.0

### Describe the problem

Whenever i open stepmania 5.3 i get a error called program crash and i can't play, How do you fix it?

### Relevant Log output

00:00.019: StepMania5.3-git-b2eada2de1
00:00.019: Compiled 20211001 @ 18:21:27 (build b2eada2de1)
00:00.020: Log starting 2021-12-10 23:08:35
00:00.020:  
00:00.020: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.020: Reading 'Save/Preferences.ini' failed: No such file or directory
00:00.020: Reading 'Save/Preferences.ini' failed: No such file or directory
00:00.020: Reading 'Data/Static.ini' failed: No such file or directory
00:00.177: Outfox Engine: SDL Subsystem Initialised.
00:00.177: OutFox Engine: Initializing Discord SDK
00:00.179: OutFox Engine: Core Creation Returned: Failed With Error:  4
/////////////////////////////////////////
00:00.179: WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting
/////////////////////////////////////////
00:00.180: Font Loaded
00:00.252: Loading window: sdl
00:00.276: Windows 7
00:00.276: OutFox Engine - Memory Detected: 1978MB Installed, (836MB Available), 8230MB Swap Memory (6429MB Swap available)
00:00.277: Video driver: Mobile Intel(R) 45 Express Chipset Family (Microsoft Corporation - WDDM 1.1) [Intel Corporation]
00:00.277:               8.15.10.1749, 5-6-2009 [pci\ven_8086&dev_2a43]
00:00.278: Drive: "ATA     TOSHIBA MK2035GS2A" Driver: iaStorA DMA: N/A
00:00.278: Drive: "hp      DVDRAM GT30L    mP04" Driver: iaStorA DMA: N/A
00:00.308: Sound device 0: Speakers (High Definition Audio, 0.0, MID 1, PID 65535 
00:00.309: Memory changed from 0 to 1978; settings changed
00:00.353: Reading 'Data/Static.ini' failed: No such file or directory
/////////////////////////////////////////
00:00.353: WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
/////////////////////////////////////////
/////////////////////////////////////////
00:00.353: WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'default'.
/////////////////////////////////////////
00:00.354: ThemeManager::SwitchThemeAndLanguage: "default", "en"
00:00.381: Loading "/Scripts/32log.lua" ...
00:00.381: Loading "/Scripts/extend_table.lua" ...
00:00.382: Loading "/Scripts/Timing.lua" ...
00:00.383: Loading "/Scripts/unavailable_functions.lua" ...
00:00.383: Loading "/Scripts/32log.lua" ...
00:00.384: Loading "/Scripts/extend_table.lua" ...
00:00.384: Loading "/Scripts/Timing.lua" ...
00:00.386: Loading "/Scripts/unavailable_functions.lua" ...
00:00.387: Loading "/Appearance/Themes/_fallback/Scripts/00 init.lua" ...
00:00.387: Loading "/Appearance/Themes/_fallback/Scripts/00 lua5.3.lua" ...
00:00.388: Loading "/Appearance/Themes/_fallback/Scripts/01 alias.lua" ...
00:00.389: Loading "/Appearance/Themes/_fallback/Scripts/01 base.lua" ...
00:00.390: Loading "/Appearance/Themes/_fallback/Scripts/01 IniFile.lua" ...
00:00.390: Loading "/Appearance/Themes/_fallback/Scripts/02 Actor.lua" ...
00:00.392: Loading "/Appearance/Themes/_fallback/Scripts/02 ActorDef.lua" ...
00:00.392: Loading "/Appearance/Themes/_fallback/Scripts/02 Branches.lua" ...
00:00.393: Loading "/Appearance/Themes/_fallback/Scripts/02 Colors.lua" ...
00:00.395: Loading "/Appearance/Themes/_fallback/Scripts/02 Debug.lua" ...
00:00.395: Loading "/Appearance/Themes/_fallback/Scripts/02 Enum.lua" ...
00:00.396: Loading "/Appearance/Themes/_fallback/Scripts/02 OptionsMenu.lua" ...
00:00.397: Loading "/Appearance/Themes/_fallback/Scripts/02 Other.lua" ...
00:00.397: Loading "/Appearance/Themes/_fallback/Scripts/02 Serialize.lua" ...
00:00.398: Loading "/Appearance/Themes/_fallback/Scripts/02 Sprite.lua" ...
00:00.398: Loading "/Appearance/Themes/_fallback/Scripts/02 StageMods.lua" ...
00:00.399: Loading "/Appearance/Themes/_fallback/Scripts/02 ThemePrefs.lua" ...
00:00.399: Loading "/Appearance/Themes/_fallback/Scripts/02 ThemePrefsRows.lua" ...
00:00.400: Loading "/Appearance/Themes/_fallback/Scripts/02 Utilities.lua" ...
00:00.402: Loading "/Appearance/Themes/_fallback/Scripts/03 CustomSpeedMods.lua" ...
00:00.403: Loading "/Appearance/Themes/_fallback/Scripts/03 DisplaySpecs.lua" ...
00:00.405: Loading "/Appearance/Themes/_fallback/Scripts/03 Gameplay.lua" ...
00:00.406: Loading "/Appearance/Themes/_fallback/Scripts/03 GamePreferences.lua" ...
00:00.406: Loading "/Appearance/Themes/_fallback/Scripts/03 ModuleSys.lua" ...
00:00.407: Loading "/Appearance/Themes/_fallback/Scripts/03 ThemeAndGamePrefs.lua" ...
00:00.408: Loading "/Appearance/Themes/_fallback/Scripts/03 ThemeLibrary.lua" ...
00:00.408: Loading "/Appearance/Themes/_fallback/Scripts/03 UserPreferences2.lua" ...
00:00.409: Reading 'Appearance/Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:00.409: Loading "/Appearance/Themes/_fallback/Scripts/04 CreditsHelpers.lua" ...
00:00.412: Loading "/Appearance/Themes/_fallback/Scripts/04 LogDisplay.lua" ...
00:00.413: Loading "/Appearance/Themes/_fallback/Scripts/04 NumPadEntry.lua" ...
00:00.414: Loading "/Appearance/Themes/_fallback/Scripts/04 pause_menu_helper.lua" ...
00:00.415: Loading "/Appearance/Themes/_fallback/Scripts/04 SetBGFitHelpers.lua" ...
00:00.416: Loading "/Appearance/Themes/_fallback/Scripts/05. ColumnModAliases.lua" ...
00:00.416: Loading "/Appearance/Themes/_fallback/Scripts/find_missing_lang_strings.lua" ...
00:00.418: Loading "/Appearance/Themes/default/Scripts/Main.lua" ...
/////////////////////////////////////////
00:00.440: WARNING: [Options.ReturnCurrentTiming] Current Timing 'false' is not present on TimingWindows, using 'Original' instead.
/////////////////////////////////////////
/////////////////////////////////////////
00:00.444: WARNING: [Options.ReturnCurrentTiming] Current Timing 'false' is not present on TimingWindows, using 'Original' instead.
/////////////////////////////////////////
00:02.473: Loading "/Appearance/Themes/default/Scripts/Rin_Inspect.lua" ...
00:02.572: Size is now 13 from 1.063500 (854)
00:02.608: Sound writeahead has been overridden to 4096
00:02.684: WaveOut software mixing at 44100 hz
00:02.684: Starting thread: Decode thread
00:02.686: Starting thread: Mixer thread
00:02.686: Sound driver: WaveOut
00:02.687: Starting thread: Music thread
00:02.687: Initializing lights drivers: SystemMessage,Export
00:02.687: Lights driver: SystemMessage
00:02.687: Lights driver: Export
00:02.688: ThemeManager::SwitchThemeAndLanguage: "default", "en"
00:02.688: Reading 'Save/Keymaps.ini' failed: No such file or directory
00:02.688: Couldn't open mapping file "Save/Keymaps.ini": No such file or directory.
00:02.688: Reading 'Save/Keymaps.ini' failed: No such file or directory
00:02.688: Couldn't open mapping file "Save/Keymaps.ini": No such file or directory.
00:02.690: Reading 'Cache/index.cache' failed: No such file or directory
00:02.690: Cache format is out of date.  Deleting all cache files.
00:02.691: Reading 'Cache/images.cache' failed: No such file or directory
00:02.701: Attempting to load 1 songs from "Songs/Outfox"
00:02.743: Song::SaveToSSCFile('Cache/Songs/Songs_Outfox_Credits')
00:02.757: Loaded 1 songs from "Songs/Outfox"
00:02.757: Attempting to load 3 songs from "Songs/StepMania 5"
00:02.790: Song::SaveToSSCFile('Cache/Songs/Songs_StepMania 5_Goin' Under')
00:02.822: Song::SaveToSSCFile('Cache/Songs/Songs_StepMania 5_MechaTribe Assault')
00:02.881: Song::SaveToSSCFile('Cache/Songs/Songs_StepMania 5_Springtime')
00:02.953: Loaded 3 songs from "Songs/StepMania 5"
00:02.964: Found 4 songs in 0.273000 seconds.
00:02.964: Loading courses.
00:02.970: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/ChallengingRandom5.crs")
00:03.082: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/Jupiter.crs")
00:03.082: Course file "/Courses/Default/Jupiter.crs" contains an invalid #METER string: "Medium"
00:03.125: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_01-04.crs")
00:03.177: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_05-08.crs")
00:03.177: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST5 with only 4 songs installed. This entry will be ignored.
00:03.177: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST6 with only 4 songs installed. This entry will be ignored.
00:03.177: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST7 with only 4 songs installed. This entry will be ignored.
00:03.227: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_09-12.crs")
00:03.229: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST8 with only 4 songs installed. This entry will be ignored.
00:03.229: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST9 with only 4 songs installed. This entry will be ignored.
00:03.229: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST10 with only 4 songs installed. This entry will be ignored.
00:03.229: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST11 with only 4 songs installed. This entry will be ignored.
00:03.229: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_13-16.crs")
00:03.229: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST12 with only 4 songs installed. This entry will be ignored.
00:03.230: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST13 with only 4 songs installed. This entry will be ignored.
00:03.230: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST14 with only 4 songs installed. This entry will be ignored.
00:03.230: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST15 with only 4 songs installed. This entry will be ignored.
00:03.252: Starting thread: Worker thread (MemoryCardWorker)
00:03.255: RageSound: Load "/Appearance/Themes/_fallback/Sounds/MemoryCardManager ready.ogg" (precache: 1)
00:03.260: RageSound: Load "/Appearance/Themes/_fallback/Sounds/_missing.ogg" (precache: 1)
00:03.266: RageSound: Load "/Appearance/Themes/_fallback/Sounds/_missing.ogg" (precache: 1)
00:03.266: RageSound: Load "/Appearance/Themes/_fallback/Sounds/MemoryCardManager disconnect.ogg" (precache: 1)
00:03.272: Starting thread: Worker thread (/@mc1int/)
00:03.273: Starting thread: Worker thread (/@mc2int/)
00:03.275: Profile::LoadAllFromDir( /Save/MachineProfile/ )
00:03.391: SaveStatsXmlToDir: /Save/MachineProfile/
00:03.507: X:\Development\StepmaniaOutfox\src\RageFileDriverDirect.cpp:179: remove 'C:/Games/StepMania 5.3 Outfox/Save/MachineProfile/Edits/newdir.temp.newdir'
00:03.594: X:\Development\StepmaniaOutfox\src\RageFileDriverDirect.cpp:179: remove 'C:/Games/StepMania 5.3 Outfox/Save/MachineProfile/EditCourses/newdir.temp.newdir'
00:03.634: X:\Development\StepmaniaOutfox\src\RageFileDriverDirect.cpp:179: remove 'C:/Games/StepMania 5.3 Outfox/Save/MachineProfile/Screenshots/newdir.temp.newdir'
00:03.671: X:\Development\StepmaniaOutfox\src\RageFileDriverDirect.cpp:179: remove 'C:/Games/StepMania 5.3 Outfox/Save/MachineProfile/Rivals/newdir.temp.newdir'
00:03.673: UnlockManager::Load()
00:03.698: Last seen video driver: 
00:03.698: Card matches '(unknown card)'.
00:03.698: Applying defaults for Mobile Intel(R) 45 Express Chipset Family (Microsoft Corporation - WDDM 1.1).
00:03.698: Video renderers: 'opengl,glad,gles2'
00:03.700: GL MAJOR = 0
00:03.714: Requested GL Version Context: 4.1
00:03.714: Got GL Version Context: 4.1
00:03.714: Got Context Profile Mask: 2 (2 = compatibility)
00:03.716: OutFox Engine: You are using a modern GL Context: 4.1
00:03.716: RageDisplay_Legacy::RageDisplay_Legacy()
00:03.716: LowLevelWindow_SDL::TryVideoMode called
00:03.716: Renderer Found By SDL: direct3d
00:03.716: Renderer Found By SDL: direct3d11
00:03.716: Renderer Found By SDL: opengl
00:03.716: Renderer Found By SDL: opengles2
00:03.716: Renderer Found By SDL: software
00:03.733: OutFox Serene: OpenGL context created successfully
00:03.734: Outfox SDL Reported Variables:
00:03.734: Outfox Engine: SDL compiled version: 2.0.15
00:03.734: Outfox Engine: SDL linked version: 2.0.15
00:03.734: GL_UNSIGNED_SHORT_1_5_5_5_REV failed (GL_INVALID_ENUM), disabled
/////////////////////////////////////////
00:03.734: WARNING: Vertex shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.734: WARNING: Vertex shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.734: WARNING: Vertex shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.734: WARNING: Vertex shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.734: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.734: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.734: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.734: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.734: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.736: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.736: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.736: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.736: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:03.736: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
00:03.739: 0.27 FPS, 1.00 av FPS, 0 VPF, 25 MB, OpenGL
00:03.740: Graphics Manager:  OpenGL Vendor: Microsoft Corporation
00:03.740: Graphics Manager:  OpenGL Renderer: GDI Generic
00:03.740: Graphics Manager:  OpenGL Version: 1.1.0
00:03.740: Graphics Manager:  OpenGL Max texture size: 1024
00:03.740: Graphics Manager:  OpenGL Texture units: 1
00:03.740: Graphics Manager:  OpenGL Extensions:
00:03.740:   GL_EXT: bgra, paletted_texture
00:03.740:   GL_WIN_swap_hint
00:03.740: OpenGL Line width range: Min=0.00, Max=0.00
00:03.740: OpenGL Point size range: Min=0.50, Max=10.00
00:03.740: OpenGL Windowed 854x480 32 color 32 texture 60Hz Vsync NoSmoothLines
00:03.740: RageInput::RageInput()
00:03.747: Outfox Engine: Input subsystem - Screen Keyboard Support: 0
00:03.747: Outfox Engine: Joystick subsystem - Legacy Mode Set, Initialising Old Mappings
00:03.759: Outfox Engine: Legacy Joystick subsystem - Found 0 joysticks

**Comment by Scraticus** [comment]
can you try the new alpha and see if that resolves your problem?

**Comment by Scraticus** [comment]
No reply, is a driver issue on the computer, do ping us in the discord if you need any further help
