### ISSUE TITLE
[BUG] L-Tek Dance Pad not detected on Linux x86_64

### ISSUE THREAD

**Issue by PhracturedBlue** [TeamRizu/OutFox#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Linux

### CPU

x86_64

### GPU

Haswell internal graphics

### Storage

SSD

### Game Version

4.10.0

### Describe the problem

I'm actually using 4.11.0

This seems to be a regression between 4.10.0 and 4.11.0

With 4.10.0, I see:
OpenGL Windowed 1280x720 32 color 32 texture 60Hz Vsync NoSmoothLines
Outfox Engine: Legacy Joystick subsystem - Found 1 joysticks
Outfox Engine: Legacy Joystick subsystem - Joy device added
Outfox Engine: Legacy Joystick subsystem -  0: 'www.l-tek.pl L-TEK Dance Pad PRO' axes: 0, hats: 0, buttons: 12

With 4.11.0, I see:
OpenGL Windowed 1366x768 32 color 32 texture 60Hz Vsync NoSmoothLines
Outfox Engine: Legacy Joystick subsystem - Found 0 joysticks

And the Ltek pad doesnt work (I also have Ps2 pads which work in both 4.10 and 4.11, but they aren't plugged in in the above logs)

I have tried using XInput and HIDAPI modes.  I have tried adding my pad to Data/gamecontrollerdb.txt, and I've tried using
 export SDL_GAMECONTROLLERCONFIG="03000000eb0300004180000010010000,www.l-tek.pl L-TEK Dance Pad PRO,a:b0,b:b1,x:b4,y:b3,back:b10,start:b11,leftshoulder:b6,rightshoulder:b7,lefttrigger:b8,righttrigger:b9"

I have tried configuring it inside Outfox, but buttons are not detected in the Input Test or in the Controller mapping

The dancepad is properly detected by jstest as /dev/input/js0

### Relevant Log output

[4.10-info.txt](https://github.com/TeamRizu/OutFox/files/7776409/4.10-info.txt)
[4.10-log.txt](https://github.com/TeamRizu/OutFox/files/7776410/4.10-log.txt)
[4.11-info.txt](https://github.com/TeamRizu/OutFox/files/7776411/4.11-info.txt)
[4.11-log.txt](https://github.com/TeamRizu/OutFox/files/7776412/4.11-log.txt)

**Comment by Scraticus** [comment]
Hiya Phractured, this was a bug in SDL's kernel code that has been fixed in 4.11.1, we're still working on a few bits of it at the moment, but if you're in our discord you can ping for an RC build which you can use in the meantime.

**Comment by Scraticus** [comment]
This has been fixed in 4.12, please update from the RC build when you're ready mate. Thanks for reporting this.

**Comment by jsravn** [comment]
I'm having this issue on 0.4.16. Should I reopen? The only workaround I've found is to force SDL not to use evdev, via `SDL_JOYSTICK_DEVICE=/dev/input/js0` before running.

**Comment by Scraticus** [comment]
> I'm having this issue on 0.4.16. Should I open a new one? The only workaround I've found is to force SDL not to use evdev, via `SDL_JOYSTICK_DEVICE=/dev/input/js0` before running.

was this bug present in 4.15?

**Comment by jsravn** [comment]
> > I'm having this issue on 0.4.16. Should I open a new one? The only workaround I've found is to force SDL not to use evdev, via `SDL_JOYSTICK_DEVICE=/dev/input/js0` before running.
> 
> was this bug present in 4.15?

Hmm it's not working there, nor in 4.12 which I just tried. evdev-joystick shows it fine though, also my dualsense controller is picked up without an issue. Not sure why it's stopped working for me.

```
$ steam-run evdev-joystick --l
/dev/input/by-id/usb-www.laser-tek.pl_Mata_taneczna_L-TEK-event-joystick

$file /dev/input/by-id/usb-www.laser-tek.pl_Mata_taneczna_L-TEK-event-joystick
/dev/input/by-id/usb-www.laser-tek.pl_Mata_taneczna_L-TEK-event-joystick: symbolic link to ../event27

$ steam-run ./OutFox
Outfox Engine: Legacy Joystick subsystem - Found 0 joysticks

$ SDL_JOYSTICK_DEVICE=/dev/input/js0 steam-run ./OutFox
Outfox Engine: Legacy Joystick subsystem - Found 1 joysticks
Outfox Engine: Legacy Joystick subsystem - Joy device added
Outfox Engine: Legacy Joystick subsystem -  0: 'www.laser-tek.pl Mata taneczna L-TEK' axes: 0, hats: 0, buttons: 12

$ SDL_JOYSTICK_DEVICE=/dev/input/event27 steam-run ./OutFox
Outfox Engine: Legacy Joystick subsystem - Found 0 joysticks
```

Just seems to not work w/ evdev at all.

**Comment by Scraticus** [comment]
can you join our discord server to help test this?

**Comment by Scraticus** [comment]
Closing this as we enabled the /JS and /DEV support in 4.18
