### ISSUE TITLE
[BUG] song rate defaults to 0.05x

### ISSUE THREAD

**Issue by Brodan** [TeamRizu/OutFox#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

macOS Monterey 12.0.1

### CPU

Apple M1 Pro

### Game Version

~4.10.0~ 4.11.0

### Describe the problem

NOTE: I am on version `5.3 Alpha 4.11.0` but the dropdown didnt have an option for it.

I am using the Waterfall v0.7.0 theme. This seems to only be an issue when using that theme.

When i load up the game and choose a song, the default song rate is 0.05x. I have to change this in the song options before playing begins.

additionally, I can't adjust the song rate to a flat `1.0x`, it only lets me select `0.999999x`

![screenshot](https://i.imgur.com/X2P6Gdo.png)

### Describe what should happen

the song rate should default to 1.0x

**Comment by JoseVarelaP** [comment]
Check out the new 4.12 release, we addressed this issue with lua numbers.

**Comment by Kaede573** [comment]
I have just noticed the same issue using latest public release (4.12 / git a8015adee6 / 20211213).
