### ISSUE TITLE
[BUG] Bone is not applied correctly in the initial display of MilkShape 3D models

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows10 Pro

### CPU

i5-7500 3.4GHz

### GPU

GeForce GTX 1060 6GB

### Storage

SSD

### Game Version

4.12.0

### Game Mode

dance

### Theme

Inheriting the default theme and displaying Def.Model in ScreenTitleMenu
```Lua
-- ScreenTitleMenu overlay.lua
SCREENMAN:SystemMessage('override theme')
local file = 'ball_anime.txt'
return Def.ActorFrame({
    FOV = 60,
    Def.Quad({InitCommand = function(self) self:Center():zoomto(400, 400):diffuse(0, 0, 0, 0.5) end}),
    Def.Model({
        Meshes = file,
        Materials = file,
        Bones = file,
        InitCommand = function(self)
            self:Center():zoom(100)
            self:rate(0)
        end,
    }),
})
```

### Describe the problem

When I used OutFox to display the model that was output in "MilkShape 3D ASCII" format, the display was momentarily distorted, so I checked and found that Bone was not applied at the 0th frame (initial display)
The attached image shows the display of each version when the animation was not moved at rate(0)
Also, when the animation is looped, Bone is not applied at the moment of the loop

![model_init](https://user-images.githubusercontent.com/8708955/147896145-620d1e07-3eff-4915-b07f-0e41d0f7af09.jpg)
The model file is here https://firestorage.com/download/c92026c29a49c5e231510ad8e7bfb109ce86f4d5

Supplement:
This model file was output using the Export function of MilkShape3D 1.8.4
My guess is that the frame count for Bone starts at 1.000000, so Bone is not being applied at a timing less than 1
To test this, I rewrote the text file directly and changed the frame count to 0.000000, which eliminated the display collapse at the moment of looping
However, the initial display at rate(0) is still broken

### Describe what should happen

Bone is applied even when the animation has not started at rate(0)
Also, Bone should always be applied during loop playback

**Comment by JoseVarelaP** [comment]
Could you reupload the model file? Firestorage has removed the file.

**Comment by waiei** [comment]
It seems that the uploader has expired.
I tried to attach the file directly. 
[ball_anime.txt](https://github.com/TeamRizu/OutFox/files/7934413/ball_anime.txt)

**Comment by Jousway** [comment]
just fixed this, will be in next release.
