### ISSUE TITLE
[Game Crash] TAB+INSERT crashes game in editor

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#473]
### Describe the crash

I straight went into the editor did this button combination mentioned below and made it crash.
There is no crashinfo.txt (and all other logs didn't even went far enough to say anything about it).

### How can you reproduce the error?

1. Start the game
2. Go into Edit Mode
3. Select the beginning of an area via TAB
4. Try to insert a beat row in the notefield (aka move it downwards)
5. ?????????
6. Profit (aka crash)

### Screenshots/Videos

"If possible"? More like: "If nessessary"
http://y2u.be/4kNa2euL12w

### Additional Information

I went into SMX* mode and tried it there (*after doing it in dance mode).
So this happens in all game modes (apparently)

**Comment by JoseVarelaP** [comment]
Fixed for 4.13.
