### ISSUE TITLE
[Nitpick] "Paste At Current Beat/Begin Marker" missing in Editor's "Alter Menu"

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#474]
### Give an example of what is wrong

See Title, else see [Video](http://y2u.be/NBBVZdGqEdU) (first half | using current OutFox)
Also, this is the editor (and I've now check it in be-mu as well). So it would then be the following:
Game Mode: All of the above!

### Give an example of what it should look like

See Video mentioned above (the second half | NOT using OutFox)

**Comment by JoseVarelaP** [comment]
Has been readded back for 4.13.
