### ISSUE TITLE
[Game Crash] Game doesn't load, splash screen just disappear (Dec. 31st 2021 build)

### ISSUE THREAD

**Issue by Lebon14** [TeamRizu/OutFox#476]
### Describe the crash

So, when you start the game, the songs will start loading / caching. A little bit halfway through, the splashscreen just disappear and the software can't be found running at all.

### How can you reproduce the error?

1. Have a lot of songs (maybe all official charts from arcades / console / etc.)
2. Attempt to start the game.
3. Should crash around 40%

### Screenshots/Videos

Of course, I have uploaded a video on the Discord server already.
https://cdn.discordapp.com/attachments/527732010714923019/931021012710096947/PXL_20220113_030328781.mp4

The log is also attached to this part of the issue form.
[log.txt](https://github.com/TeamRizu/OutFox/files/7867595/log.txt)
.

### Additional Information

Well, everything works fine in October 1st 2021 build. I really don't know what changed during that build and the newest one.

Besides that, I don't have much else to day besides that no songs in my folder using any fancy scripts / mods. Just regular charts in .sm, mp3s or ogg and some of the official charts have their videos in recognized formats.

So, yeah.
Cheers.

**Comment by Scraticus** [comment]
We're working on a fix for this, thanks for taking the time to bring it to our attention!

**Comment by Scraticus** [comment]
Fixed in 4.13, thanks for your report
