### ISSUE TITLE
[Game Crash] linux64bit-legacy version 4.12.0 crashes on startup

### ISSUE THREAD

**Issue by rxhfcy** [TeamRizu/OutFox#478]
### Describe the crash

1. What you were doing before it crashed and what action made the game to crash.
didn't do anything: tried to launch the legacy version of 4.12.0, game crashes on startup (non-legacy crashes too)

2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/7880453/crashinfo.txt)

3. Upload the info.txt and log.txt (GameFolder/Logs
(info.txt was empty)
[log.txt](https://github.com/TeamRizu/OutFox/files/7880461/log.txt)

### How can you reproduce the error?

1. Start the game (4.12.0 legacy Linux version)
2. Game crashed

### Game Mode

dance

### Additional Information

4.11.0 (legacy version) used to work, so this seems to be a new crash.

Here's information about the computer:
The laptop is old, from the year 2010 (HP EliteBook 8540p)
Ubuntu 20.04.2 LTS (Focal Fossa) (fully updated)
old NVIDIA GPU, "GT216M [NVS 5100M]"
the driver package is nvidia-340 (340.108) (legacy, but the latest version I believe)
Linux kernel version 5.4.0-94-generic (nvidia-340 won't support anything after 5.4), x86_64

**Comment by jose1711** [comment]
Same issue on Arch 64bit (both legacy and standard version)

**Comment by Scraticus** [comment]
Thanks for reporting this for us you two, I have identified the crash, and we're working on a fix.

It's just a little thing Linux likes to do on us from time to time! ;_;

**Comment by Scraticus** [comment]
This is fixed in 4.13, you can ping me on the discord for a pre-alpha 12.1 build to play 12.x if you wish, thanks you two for reporting
