### ISSUE TITLE
[Feature Request] 2P Solo Mode

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [TeamRizu/OutFox#479]
### Please Select the game mode your feature request is about.

dance

### Is your feature request related to a problem?

I'm always frustrated when I want to play solo with 2 players, it's missing
single, double, versus, solo, threepanels is here but I want to have 2 players fighting against solo mode.

### Describe the solution you'd like

add soloversus (versus + solo), threeversus (versus + threepanels)

### Additional context

There's 4 Player For DDR Solo, but it's running on different cabinets, but I want to play Solo mode On the Same Cabinet.

**Comment by Scraticus** [comment]
Done, this will be in 4.13 out this weekend. Thanks for the request
