### ISSUE TITLE
[BUG] Simfiles with Only a .ssc File Break the Notes

### ISSUE THREAD

**Issue by SupraGL** [TeamRizu/OutFox#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 7

### CPU

Intel Core i7-4710MQ

### GPU

NVIDIA Quadro k1100M

### Game Version

4.12.0

### Game Mode

dance

### Theme

- DDR XX STARLiGHT TWOpointZERO v2.0.2
- Default

### Describe the problem

I can't select the 4.13.0 version of OutFox for the bug, but this is the version I have.

When I play a simfile with only a .ssc file, various behaviors happen, no matter the noteskin I choose, such as:
- Notes not appearing;
- Tap explosions not playing at the right time or randomly (happens with autoplay);
- Autoplay or AutoplayCPU not playing during the song anymore and missing all the notes.

Any or all of those issues happen with ACE FOR ACES, Chaos (Terror-Tech Mix) and brokenHeart resurrection ~estelle~.

### Describe what should happen

- All the notes should appear;
- All the tap explosions should appear when the note is tapped;
- Autoplay or AutoplayCPU should not fail notes.

**Comment by Scraticus** [comment]
Hiya! this doesn't sound very good at all :( could you upload the log from the /log folder (specifically log.txt/userinfo.txt) so we can see if there are any issues the parser tells us.

thanks!

**Comment by EtienneGL** [comment]
Here are the logs I got for just loading the game and playing ACES FOR ACES on Challenge with Autoplay.
[info.txt](https://github.com/TeamRizu/OutFox/files/8045082/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/8045084/log.txt)

**Comment by JoseVarelaP** [comment]
Noticing that the AI weights are not being read, did they reset back again to TNS and not TNS_PRO?
This would explain why Autoplay isn't hitting notes.
```
WARNING: AI weight for TNS_PRO_W5 in "Skill0" section not set.
WARNING: AI weight for TNS_PRO_W4 in "Skill0" section not set.
WARNING: AI weight for TNS_PRO_W3 in "Skill0" section not set.
WARNING: AI weight for TNS_PRO_W2 in "Skill0" section not set.
WARNING: AI weight for TNS_PRO_W1 in "Skill0" section not set.
WARNING: AI weight for TNS_PRO_W5 in "Skill1" section not set.
WARNING: AI weight for TNS_PRO_W4 in "Skill1" section not set.
WARNING: AI weight for TNS_PRO_W3 in "Skill1" section not set.
WARNING: AI weight for TNS_PRO_W2 in "Skill1" section not set.
WARNING: AI weight for TNS_PRO_W1 in "Skill1" section not set.
WARNING: AI weight for TNS_PRO_W5 in "Skill2" section not set.
WARNING: AI weight for TNS_PRO_W4 in "Skill2" section not set.
WARNING: AI weight for TNS_PRO_W3 in "Skill2" section not set.
WARNING: AI weight for TNS_PRO_W2 in "Skill2" section not set.
WARNING: AI weight for TNS_PRO_W1 in "Skill2" section not set.
WARNING: AI weight for TNS_PRO_W5 in "Skill3" section not set.
WARNING: AI weight for TNS_PRO_W4 in "Skill3" section not set.
WARNING: AI weight for TNS_PRO_W3 in "Skill3" section not set.
WARNING: AI weight for TNS_PRO_W2 in "Skill3" section not set.
WARNING: AI weight for TNS_PRO_W1 in "Skill3" section not set.
WARNING: AI weight for TNS_PRO_W5 in "Skill4" section not set.
WARNING: AI weight for TNS_PRO_W4 in "Skill4" section not set.
WARNING: AI weight for TNS_PRO_W3 in "Skill4" section not set.
WARNING: AI weight for TNS_PRO_W2 in "Skill4" section not set.
WARNING: AI weight for TNS_PRO_W1 in "Skill4" section not set.
WARNING: AI weight for TNS_PRO_W5 in "Skill5" section not set.
WARNING: AI weight for TNS_PRO_W4 in "Skill5" section not set.
WARNING: AI weight for TNS_PRO_W3 in "Skill5" section not set.
WARNING: AI weight for TNS_PRO_W2 in "Skill5" section not set.
```

**Comment by EtienneGL** [comment]
I was not aware that Pro Weights were a new thing in OutFox, and I overwrote the file with a version that I used in StepMania to allow the AutoplayCPU to only hit Marvelous.
I reinstalled OutFox and manually edited the AI.ini file this time. For the Pro Weights, it automatically puts 0. No matter if I leave them to 0 or modify the values, it does not fix the problem.
[info.txt](https://github.com/TeamRizu/OutFox/files/8045699/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/8045700/log.txt)
[AI.txt](https://github.com/TeamRizu/OutFox/files/8045704/AI.txt) (changed from .ini to .txt for sharing here)

**Comment by EtienneGL** [comment]
Update: the problems only happen when Autoplay or AutoplayCPU are enabled. None of them happens when they are disabled, which allows me to score on them.

**Comment by DarkBahamut162** [comment]
The _notefield_ and the _autoplayer_ **both use different TimingData**.
I figured it out by checking the mentioned simfiles and noticing them on both:

**Chaos (Terror-Tech Mix)** on Challenge has some more stops than the others.
**ACE FOR ACES** has more stuff everywhere above the first two difficulties.

I've recorded something to make this very noticeable (example song is from PUI Pro 1/2):
**Left Side:** What the player gets _(uses TimingData from Steps)_
**Right Side:** What the autoplayer gets _(uses TimingData from Song | changed to .sm to remove different TimingData for this example)_

**Video:** http://y2u.be/ebrN93gwtCA

This explains those early/random tap explosions _(when the player is behind the autoplayer)_ and/or the "missing all the notes" part _(when the player is ahead of the autoplayer)_.

**Comment by JapanYoshi** [comment]
I'm also having the same problem with a different simfile. I can't give you the simfile though, since it's a WIP and confidential, but I'm getting the exact same issue where StepsTiming is not getting respected by AutoPlay.

The Stops earlier in the chart don't seem to desync the chart at all. There were also some scroll gimmicks before the desync, but it doesn't cause any issues, probably because the overall scroll speed is the same as SongTiming.

**Comment by Scraticus** [comment]
Can you check the upcoming 4.15, as we cannot replicate this anymore

**Comment by SupraGL** [comment]
I can check when the time comes.
