### ISSUE TITLE
[Game Crash] Trying to edit stepstage chart and crash.

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [TeamRizu/OutFox#488]
### Describe the crash

I'm trying to make stepstage chart, but it crashed. Even with the fresh install.
[info.txt](https://github.com/TeamRizu/OutFox/files/8054912/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/8054913/log.txt)

### How can you reproduce the error?

1. Try to edit Any map (twin)
2. Crash

### Game Mode

stepstage

### Additional Information

stepstage bug report - UPDATE THE ISSUE FORM.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
In Free (one-lane) Mode: 123 ▷ YBR
In Basic (twin) Mode: 123456 ▷ YBR|RBY

**Comment by MrThatKid** [comment]
Fixed in 4.14
