### ISSUE TITLE
[Unexpected Behavior] Possible to softlock Soundwaves profile select

### ISSUE THREAD

**Issue by Kaede573** [TeamRizu/OutFox#49]
Using Stepmania-Outfox_Alpha-4.6-amd64-date-20200711 (on Linux).

Steps to reproduce:

1. Start from Outfox main menu
2. Press start (Game Start)
3. Press enter to validate caution screen.
4. Press enter a second time, before the caution screen fades to black entirely. The timing is a bit strict.
5. => profile select is softlocked. Up/down arrows to select a profile don't do anything. At that point, if you press ESC once you take control back

I have recorded a short video, but since I didn't include an input overlay, it doesn't show much, except the fact I have to press ESC once too much: https://youtu.be/Hwm-oaEqVFk

(ps. I'm Kaede on Discord btw)

**Comment by Scraticus** [comment]
Thanks for this, we'll fix the input issue on the theme.

**Comment by Kaede573** [comment]
It looks like this is now fixed (fixed back in Stepmania-Outfox-Alpha-4.8.1-amd64-date-20200814, it seems).

Thanks !
