### ISSUE TITLE
[BUG] (.wav specific?) Keysounding in a dance chart plays sounds weirdly.

### ISSUE THREAD

**Issue by cpguy5089** [TeamRizu/OutFox#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### CPU

AMD Ryzen 7 PRO

### GPU

512MB ATI AMD Radeon Graphics

### Storage

476GB Western Digital WDC PC SN730 SDBQNTY-512G-1001

### Game Version

4.13.0

### Game Mode

dance

### Theme

Whichever Soundwaves comes with 4.13.0

### Describe the problem

A song is playing keysounds weirdly. Specifically, it sounds like a broken NES trying to crunch out the crazy bus theme.
https://i.uguu.se/ueCkhHOv.mp4

The keysounds are all .wav files.
For reference, the song in question Happy Century from UPS 4.

Not all the sounds are broken however, there are still a lot which work fine, it's just whatever is used for most of the song is broken.

### Describe what should happen

The sounds should be playing normally and not getting crusted out.

It _should_ sound like this: https://www.youtube.com/watch?v=zSkkWdwyUGI
However, as linked above, it ends up sounding like this: https://i.uguu.se/ueCkhHOv.mp4

### Relevant Log output

[info.txt](https://github.com/TeamRizu/OutFox/files/8057149/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/8057150/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/8057151/userlog.txt)

**Comment by Scraticus** [comment]
fixed in 4.15, as we're reverting to the legacy sampler.
