### ISSUE TITLE
[BUG] [pump] BPM-based warps will turn real notes into fakes in charts

### ISSUE THREAD

**Issue by SheepyChris** [TeamRizu/OutFox#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

MX Linux 21

### CPU

Intel Core i5 8400

### GPU

NVIDIA GeForce GT1030

### Storage

Kingston 128GB + 480GB SSDs

### Game Version

4.13.0

### Game Mode

pump

### Theme

Soundwaves, Infinitesimal etc

### Describe the problem

The conversion of high BPM changes to StepMania-like warps currently turns any notes at the beginning of the effect into fakes, breaking a substantial amount of charts.

### Describe what should happen

The notes at the beginning of each warp should not be modified.

**Comment by DarkBahamut162** [comment]
I would like to chime in on that.
I don't think that it's only a pump issue but an everywhere issue as I noticed that on dance as well.
My ℵ0 (Full Version) simfiles has several of those "warps", especially at the beginning, and those beginning steps were also skipped on AutoPlay/CPU.

**Comment by Sudospective** [comment]
> My ℵ0 (Full Version) simfiles has several of those "warps"
And these "warps" were done either with negative BPM or very high BPM, correct? This may have to do with how the game will register those as actual warps rather than a BPM change, since negative BPM is no longer valid and extreme BPMs can be unstable and effectively become warps at a certain point.

**Comment by Scraticus** [comment]
Fixed in 4.15, fixed the bpm overflow. Was an _ancient_ sm3.x era bug
