### ISSUE TITLE
[BUG] [pump] Some songs do not have correct length stats

### ISSUE THREAD

**Issue by SheepyChris** [TeamRizu/OutFox#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

MX Linux 21

### CPU

Intel Core i5 8400

### GPU

NVIDIA GeForce GT1030

### Storage

Kingston 128GB + 480GB SSDs

### Game Version

4.13.0

### Game Mode

pump

### Theme

Soundwaves, Infinitesimal etc

### Describe the problem

Some songs currently do not have their proper length duration stats (example: Jogging from The Resistance's PIU XX song pack). This has been fixed in gameplay in previous builds and made several songs playable, however none of the chart stats have been corrected yet, which affects:
- Time length;
- NPS graph;
- Amount of stages/hearts the song should take.

### Describe what should happen

The length stats should be matching accordingly to the real duration of the song.

**Comment by Scraticus** [comment]
Fixed in 4.15 ... finally
