### ISSUE TITLE
[Nitpick] Uninstaller doesn't remove all files added from the installer

### ISSUE THREAD

**Issue by Joehuu** [TeamRizu/OutFox#498]
### Give an example of what is wrong

These are the files that are left over after immediately uninstalling:

| ![image](https://user-images.githubusercontent.com/35318437/155068553-b76654d2-e98b-41eb-b135-beace13dcd13.png) | ![image](https://user-images.githubusercontent.com/35318437/155068567-0cd99da5-5f4d-4fee-95aa-aa5926a0a8df.png) | ![image](https://user-images.githubusercontent.com/35318437/155068604-7ec294d5-d826-419b-bc47-858d36ef9091.png) |
| --- | --- | --- |

I know the files from the first image were added after https://github.com/TeamRizu/OutFox/issues/115, but the uninstaller didn't get updated to include those files.

### Give an example of what it should look like

I tested with the StepMania 5.0.12 installer and immediately uninstalled. It removed all the files including the `StepMania 5` folder. I expect it to be the case here also.

**Comment by MatthewDog42** [comment]
It leaves those files on purpose. It deletes and reinstalls them after reinstalling the game again.

**Comment by Joehuu** [comment]
I don't think so, because the other preset avatars do get removed after uninstalling.

**Comment by Scraticus** [comment]
Fixed in 4.14, Liro missed these on the installer script. Thanks for reporting.

**Comment by Joehuu** [comment]
Checking again in the new update, the newly added judgments and an empty folder are not removed.

| ![image](https://user-images.githubusercontent.com/35318437/160220023-84cda8da-5c56-470d-a6aa-ecda925c11a7.png) | ![image](https://user-images.githubusercontent.com/35318437/160220034-c83773f0-6c51-4407-a34a-26eaf3f7fdfe.png) |
| --- | --- |

**Comment by Jousway** [comment]
well when you uninstall the new version they will be, because the uninstaller is set up using the current installed version
