### ISSUE TITLE
[BUG] Model spheremaps visually scale weirdly

### ISSUE THREAD

**Issue by MrThatKid** [TeamRizu/OutFox#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Ubuntu 20.04.3

### CPU

Intel i7-4770T

### GPU

nVidia GeForce GTX 750 Ti

### Game Version

4.13.0

### Game Mode

dance

### Theme

default and legacy

### Describe the problem

Models in noteskins can have spheremaps, but they aren't consistent across theme resolutions. What may work in 480p themes won't look the same in 720p themes.

This also happens in SM5.1, so it's an upstream bug.

I used a spheremap test noteskin that R.O.B.-Bot made to show the difference. You can grab that here to see for yourself: [SphereTEST.zip](https://cdn.discordapp.com/attachments/602373897832103936/945534151346495538/SphereTEST.zip)

Here's what it looks like in 480p (legacy):
![2022-02-21_205906](https://user-images.githubusercontent.com/18648486/156469655-f7b3bc28-58b2-4280-a657-f303ea188fca.png)

And here's what it looks like in 720p (default):
![2022-02-21_205756](https://user-images.githubusercontent.com/18648486/156469705-1be32609-3daa-4b5f-835c-788875e88254.png)

P1 has a zoom of `2*(SCREEN_HEIGHT/480)` and a rotationx of `30`, while P2 is on the default setup.

### Describe what should happen

I'd expect the spheremaps to look the same across all theme resolutions.

**Comment by Scraticus** [comment]
can you give an update on this?

**Comment by MrThatKid** [comment]
As of yesterday, I believe I have fixed this by having the model normals be scaled.
Testing with normal notefields, AFTs and ASTs appears to be consistent with how I expect them to behave.
I also tried with a pad model that uses spheremaps outside of AFTs and they looked alright.
Marking this as closed and fixed.
