### ISSUE TITLE
Issue with Startup

### ISSUE THREAD

**Issue by TacvicomGN** [TeamRizu/OutFox#5]
Hello developers.

I was having the same issue with all the alphas released up today: When I launch OutFox, loads all songs, and when the main window appear, get a crash.

Here, the contents of the crash info document got will be attached.

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/4740114/crashinfo.txt)

StepMania5.3-git-c3092fe12d crash report (build c3092fe12d, 20200531 @ 20:47:04)
--------------------------------------

Crash reason: Access Violation

Thread: main
        RageFileDriverDirectHelpers.cpp:229 C:/Games/StepMania 5.3 Outfox/Appearance/Themes/default/Other/*
        RageFileDriverDirectHelpers.cpp:229 C:/Games/StepMania 5.3 Outfox/Appearance/Themes/_fallback/Other/*
        RageFileDriverDirectHelpers.cpp:229 C:/Games/StepMania 5.3 Outfox/Data/Shaders/*
        RageFileDriverDirectHelpers.cpp:229 C:/Games/StepMania 5.3 Outfox/Data/Shaders/GLSL/*
        RageFileDriverDirectHelpers.cpp:229 C:/Games/StepMania 5.3 Outfox/Data/Shaders/*
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
016a0688: StepMania!01300000
77ca2b77: ntdll!RtlAllocateHeap [77c50000+52966+211]
77ca2a12: ntdll!RtlAllocateHeap [77c50000+52966+ac]
015430da: StepMania!01300000
67a96f99: OPENGL32!wglChoosePixelFormat [67a50000+4651b+a7e]
77ca2b77: ntdll!RtlAllocateHeap [77c50000+52966+211]
01956be5: StepMania!SDL_wcsstr [01300000+4fb6a0+15b545]
0138d08c: StepMania!01300000
016a4d65: StepMania!01300000
01931fae: StepMania!SDL_wcsstr [01300000+4fb6a0+13690e]
0138ec7a: StepMania!01300000
016a44a2: StepMania!01300000
67a8a6c8: OPENGL32!wglSwapMultipleBuffers [67a50000+3a2ad+41b]
016a64d1: StepMania!01300000
77ca2b77: ntdll!RtlAllocateHeap [77c50000+52966+211]
77ca2b77: ntdll!RtlAllocateHeap [77c50000+52966+211]
77ca2a12: ntdll!RtlAllocateHeap [77c50000+52966+ac]
01956be5: StepMania!SDL_wcsstr [01300000+4fb6a0+15b545]
0138d08c: StepMania!01300000
016a351f: StepMania!01300000
01535475: StepMania!01300000
77a6c5a4: kernel32!HeapFree [77a20000+4c590+14]
01940adb: StepMania!SDL_wcsstr [01300000+4fb6a0+14543b]
01956be5: StepMania!SDL_wcsstr [01300000+4fb6a0+15b545]
01931fae: StepMania!SDL_wcsstr [01300000+4fb6a0+13690e]
0138ec7a: StepMania!01300000
016a72f1: StepMania!01300000
0169f746: StepMania!01300000
0169f782: StepMania!01300000
0139146a: StepMania!01300000
77ca2878: ntdll!RtlFreeHeap [77c50000+527fa+7e]
77ca2878: ntdll!RtlFreeHeap [77c50000+527fa+7e]
77a6c5a4: kernel32!HeapFree [77a20000+4c590+14]
01956b8f: StepMania!SDL_wcsstr [01300000+4fb6a0+15b4ef]
0153460c: StepMania!01300000
01397873: StepMania!01300000
77ca6350: ntdll!wcsnicmp [77c50000+556dc+c74]
77ca6386: ntdll!wcsnicmp [77c50000+556dc+caa]
75a3761c: KERNELBASE!GlobalFree [75a30000+75f1+2b]
01965a95: StepMania!SDL_wcsstr [01300000+4fb6a0+16a3f5]
019659e5: StepMania!SDL_wcsstr [01300000+4fb6a0+16a345]
019332c9: StepMania!SDL_wcsstr [01300000+4fb6a0+137c29]
77cb35df: ntdll!RtlInitializeExceptionChain [77c50000+6351d+c2]

Static log:
StepMania5.3-git-c3092fe12d
Compiled 20200531 @ 20:47:04 (build c3092fe12d)
Log starting 2020-06-05 20:47:18
WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting
Loading window: win32
Windows 7
Memory: 958mb total, 2388mb swap (609mb swap avail)
Video driver: ATI Radeon Xpress 1100 [ATI Technologies Inc.]
              8.332.0.0, 1-8-2007 [pci\ven_1002&dev_5975&subsys_010f1025]
WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (El sistema no puede encontrar el archivo especificado.)
Sound device 0: Altavoces (Dispositivo de High , 0.0, MID 1, PID 65535 
Sound device 1: Audio digital (S/PDIF) (Disposi, 0.0, MID 1, PID 65535 
WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'default'.
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'glad,opengl,gles2'
GL_UNSIGNED_SHORT_1_5_5_5_REV failed (GL_INVALID_ENUM), disabled
Language: English
Current renderer: OpenGL
Theme: default

Partial log:
00:01.047: Renderer Found By SDL: software
00:01.126: Outfox SDL Reported Variables:
00:01.126: Outfox Engine: SDL compiled version: 2.0.12
00:01.126: Outfox Engine: SDL linked version: 2.0.12
00:01.126: Outfox Engine: GL_VENDOR   : Microsoft Corporation
00:01.126: Outfox Engine: GL_RENDERER : GDI Generic
00:01.126: Outfox Engine: GL_VERSION  : 1.1.0
00:01.126: Outfox Engine: GLSL version: (null)
00:01.138: GL_UNSIGNED_SHORT_1_5_5_5_REV failed (GL_INVALID_ENUM), disabled
00:01.139: Compiling shader Data/Shaders/GLSL/Texture matrix scaling.vert

-- End of report

Thanks!!!

**Comment by ListenerJubatus** [comment]
Go to Preferences.ini

What is ImageCache set to?

**Comment by moruzerinho6** [comment]
Update your video drivers and hope for the god it works because jesus that card is almost older than me.

**Comment by TacvicomGN** [comment]
ListenerJubatus, by default was Off and didn't work, change to On, and equally don't work.

moruzerinho6, did that, and nothing.

The same issue happens when try in another PC, with Core i3, 2Gb of RAM and Intel HD Graphics...

**Comment by moruzerinho6** [comment]
Can you give more details about that other pc with a Intel HD Graphics? And what driver you installed? (in both machines)

**Comment by TacvicomGN** [comment]
1- Sure. Is a laptop with Core i3, 2 Gb of RAM, Intel HD Graphics. Brand: VIT (Venezolana de Industria Tecnológica), Model: M2400, Year: 2011, Screen: 1366x768 60Hz.
2- I don't have the driver of that VIT laptop at hand (it died again), and this laptop use an ATI Radeon Express 1100, driver v. 8.332 (as read in the contents of the crash info. I don't own a desktop).

**Comment by moruzerinho6** [comment]
Does older versions of stepmania work in that PC?

**Comment by TacvicomGN** [comment]
Perfectly. The two laptops are currently running StepMania 5.1 Beta 2, and that version is too stable to be a Beta.

**Comment by moruzerinho6** [comment]
Okay, I was talking with the devs. That issue is fixed for the next alpha and you should be able to play when it comes, on the intel pc atleast.

**Comment by Scraticus** [comment]
This is fixed and will be released on Sunday 14th June. Your renderer HAS to be set to opengl or it will not work. GLAD is not an openGL 1.1 compatible renderer on Stepmania 5.3
