### ISSUE TITLE
[FIXED] [BUG] Mods that add/remove stuff aren't shown correctly but are invisible

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10 Home 64-bit (21H2)

### CPU

Intel Core i7 2600 @ 3.40GHz

### GPU

8192MB ATI Radeon RX 580 Series

### Storage

2x 1863GB Western Digital WDC WD2003FZEX-00SRLA0 ATA Device

### Game Version

4.13.0

### Game Mode

dance

### Theme

any because this is a course problem

### Describe the problem

Any mods applied that adds or removes stuff is not being shown at all... Well... Kinda...
The shown chart is the unaffected chart.
But there is the actual and invisible chart in the background that should have been the one being shown.

The video below shows the following in course/marathon mode:

- No Mines: They are still there but they don't actually exist (aka Fake Mines).
- Super Shuffle: Visible chart is fake, invisible is the correct one. Noticeable on holds.
- Shuffle: Same as above (but was behaving differently on stream where left&right were the same but up/down were inverted)
- Mines: Same as "No Mines" but the mines are actual arrows which the AutoPlayer still misses them.

Video: http://y2u.be/vMEuAkiOWQg

Not shown are anything like little/wide and what else but act like the shuffles.

### Describe what should happen

Either use or refresh the actual chart while course play.

### Relevant Log output

none

**Comment by MrThatKid** [comment]
May I know how you're setting up these mods?

**Comment by DarkBahamut162** [comment]
I failed again to mention that this seems to be a course mode only problem:
But still, the mods have been set up the following way:
```
#SONG:In The Groove/Vertex:Hard:1.2xmusic, nomines, flat;
#SONG:In The Groove/Disconnected:Normal:supershuffle;
#SONG:In The Groove/Euphoria:Hard:shuffle, 0.9xmusic;
#SONG:In The Groove/Pandemonium:Hard:reverse, boomerang, mines, flat;
```

**Comment by Scraticus** [comment]
fixed in 043
