### ISSUE TITLE
[Feature Request] granularity of stops to be deeper than 0.02

### ISSUE THREAD

**Issue by mendel-lee** [TeamRizu/OutFox#511]
### Please Select the game mode your feature request is about.

All Game Modes

### Is your feature request related to a problem?

a loooong time ago in SM i wrote a chart that experimented with a manual 'stutter' effect:

eighth note stream at 200bpm converts to sixteenth note stream at 400bpm with stops on the 32nd note in between all 16ths

The step timing remains the same, but the latter has a visual stutter.

this conversion can be seen here: https://youtu.be/WzKLO7Gd2b0 where original tempo happens at 1'35" and conversion happens at 1'41"

Stops can only be incremented at a grain of 0.02s, and that has always felt odd to me when the offset can be incremented at a grain of x.xxx (at least). Normally this doesn't matter, but the amount of stops I had to put in was enough that it created noticeable sync drift.

I attempted to create a finer grain by manually editing the stops in the .ssc file, but i'm fairly certain that SM would round to the nearest hundredth or lop off anything past it.

### Describe the solution you'd like

Code in more precision in stop timing.

Allow for users to type in exact stop timing in a text field with at least a grain of ms. Alternatively since this is such a niche thing, allow for direct .ssc edits for stop timing to reflect accurately in execution of the OutFox engine.

### Describe alternatives you've considered

I started working on (but never finished) a brute force method of achieving no sync drift:

1. Create version of stepchart template with no BPM changes
2. Make note of the exact time of each beat down to the ms
3. Create copy of stepchart template and add in BPM changes
4. Add stops. Make note of times from the template, microadjust stops to compensate for drift. Most of my stops were 0.16s, i occasionally had to change some to 0.18s, this still ended up creating some imprecision

**Comment by JoseVarelaP** [comment]
> Allow for users to type in exact stop timing in a text field with at least a grain of ms. 

You can already perform this by opening up the Timing Menu, with the F4 key. Simfiles save up to 6 decimal precision, however do note some other editors can truncate this back to 3 (Given that was the original behavior before we changed it on OutFox).

**Comment by mendel-lee** [comment]
awesome. apologies for not diving deeper and assuming this was an issue when it's not.

**Comment by JoseVarelaP** [comment]
That is understandable. There's a lot of features in the editor that went unnoticed because there's no writing on them.
