### ISSUE TITLE
[BUG] Two-Player toasties not working properly

### ISSUE THREAD

**Issue by DanielRotwind** [TeamRizu/OutFox#52]
**What you're using**

I am using two toasties in versus mode. Using AppleArcade120's "Mario's a Tire"-Toasty for early triggering at 25.
Video link: [https://streamable.com/wfebye](url)

**Expected behavior**

Each toasty is ment to be triggered by the respective player's combo reaching a certain milestone or multiple of said milestone.

instead

After being activated from reaching the specified combo milestone, the toasty gets triggered on each note until the combo breaks.
if "Iterate=true", it will trigger the other player's toasty on the second multiple of the value in "ShowAt", with the same "trigger on every note" bug.
Either player's toasty randomily is the first to trigger, it doesn't matter which player gets the specified milestone, it will always prioritize one or the other.

**Comment by Jousway** [comment]
looked into this, seems I forgot to local a function, optimized the code a bit, should work now, check next test build.
