### ISSUE TITLE
Intel driver version causes green line distortion on screen

### ISSUE THREAD

**Issue by swiau** [TeamRizu/OutFox#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

windows

### CPU

Intel(R) Celeron(R) N4020 CPU @ 1.10GHz   1.10 GHz

### Storage

45.4 gb

### Game Version

4.14.0

### Game Mode

dance

### Theme

version 4.14.0 and default theme

### Describe the problem

just trying to play the game but its being funny and i don't know why
![image_2022-03-29_173449](https://user-images.githubusercontent.com/102613651/160661505-a68f818d-1c01-46d8-865f-a478fe657ccb.png)

### Describe what should happen

when you open the game itself, it should look normal and readable (this screenshot is from a video i found)
![image](https://user-images.githubusercontent.com/102613651/160673777-00bd8f31-b7ef-4f05-802d-ebb5ed7af214.png)

### Relevant Log output

[info.txt](https://github.com/TeamRizu/OutFox/files/8373801/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/8373802/log.txt)

**Comment by MrThatKid** [comment]
Seems like your graphics driver is messed up. Your logs show a bunch of shader errors.
You may want to try following the steps listed in this FAQ entry
https://outfox.wiki/user-guide/meta/faq/#q-i-have-an-ancient-intel-card-and-the-game-does-nothing-but-crash

**Comment by Scraticus** [comment]
Closing as was a driver issue from Intel, and can be solved by updating your driver. Please open up a new issue if you still have problems, or reach out to us on our discord for help
