### ISSUE TITLE
[BUG] Mines ignore ComboIsByRow

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#53]
**What you're using**

With the metric `[Gameplay] AvoidMineIncrementsCombo` set to `true`, each mine increments the combo by 1, even if `[Gameplay] ComboIsPerRow` is set to `true`.

**Expected behavior**

Each row of mines should only increment the combo by 1.

**Suggested solution**

Add a metric called `[Gameplay] AvoidMineComboIsPerRow`, which is `false` by default

**Comment by Jousway** [comment]
Added so that when ComboIsPerRow is active, it does it only once for avoided mines on same row.
It also does the same when MissComboIsPerRow for HitMines on same row.
