### ISSUE TITLE
[BUG] LIFT passes through the receptor

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows10 Pro

### CPU

i5-7500 3.4GHz

### GPU

GeForce GTX 1060 6GB

### Storage

SSD

### Game Version

4.14.0

### Game Mode

dance

### Theme

Theme:
Soundwaves (Alpha 0.4.14)
(Occurs regardless of theme)

NoteSkin:
outfox-note
(Occurs regardless of noteskin)

### Describe the problem

If you get a W1-W3 decision with a normal TAP, the arrow disappears without passing through the decision area, but with Lift, it does not disappear, but passes right through
However, since it is not a Miss judgment, the combo will not be broken
Only the appearance is abnormal
In 5.0 and 5.1, it disappears just like a normal TAP
I thought maybe the specs had changed, but when I tried it in autoplay, it disappears just like in 5.0
It also disappears when Lift and Tap are placed at the same time

https://user-images.githubusercontent.com/8708955/162432450-135acfcf-1d2c-418a-8e85-8650e0b9e077.mp4

### Describe what should happen

I would like it to disappear as in the previous version, because if it passes through the judgment area, I feel as if I have made a Miss

**Comment by Scraticus** [comment]
fixed in 4.15
