### ISSUE TITLE
[BUG] Long Mine and same timing TAP become HoldHead

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows10 Pro

### CPU

i5-7500 3.4GHz

### GPU

GeForce GTX 1060 6GB

### Storage

SSD

### Game Version

4.14.0

### Game Mode

dance

### Theme

Theme:
Soundwaves (Alpha 0.4.14)
(Occurs regardless of theme)

NoteSkin:
[YA_Solo 6+](https://sm.waiei.net/other/ya_solo.html#yasolo6p)
(Occurs in NoteSkin with DrawHold(Roll)HeadForTapsOnSameRow=1)

### Describe the problem

When playing note data with a Tap placed in a position that is the same as the start of the Long Mine, using a NoteSkin with DrawHold(Roll)HeadForTapsOnSameRow=1, the HoldHead design is being applied

https://user-images.githubusercontent.com/8708955/162574843-8d751dbc-d159-496e-b8a1-e089209ca9d6.mp4

### Describe what should happen

I don't think the HoldHead design should be applied in the case of simultaneous long Mine, since the indication implies a TAP to be stepped on at the same time as the long note
However, if a long Mine, Hold/Roll, and Tap come on three lines at the same time, it would be more natural to apply it

**Comment by JoseVarelaP** [comment]
Here's a look into a fix for it.

https://user-images.githubusercontent.com/23246027/167500254-4c2c49fc-191a-4ebf-8d65-43343e027c51.mov

**Comment by Scraticus** [comment]
Fixed in 4.15
