### ISSUE TITLE
[BUG] GH mode: Not all audio stems are loaded correctly

### ISSUE THREAD

**Issue by TheNathannator** [TeamRizu/OutFox#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows

### Game Version

4.14.0

### Game Mode

gh

### Theme

Soundwaves

### Describe the problem

OutFox does not load/cache the following audio stems:

- `drums_2` - Drums audio for the snare drum, plus tom and cymbal audio if 3 and 4 are not present
- `drums_3` - Drums audio for toms, plus cymbal audio if 4 is not present
- `drums_4` - Drums audio for cymbals
- `vocals_2` - Backing/harmony vocals
- `keys` - Keys audio
- `crowd` - Background crowd noise/singing audio

This affects both .chart and .mid files.

In addition to this, some .chart files do not get all of their audio files loaded/cached. Can't figure out a concrete cause, will keep looking into it and update if I find something.

### Describe what should happen

Any stems not specified by a `gh` chart should be searched for by these file names:
- `preview` - Audio to play as the song preview
- `song` - Background audio that never gets muted by gameplay, or the whole song as a single audio file
- `guitar` - Lead Guitar audio, or the whole song as a single audio file if no other audio files are present
- `rhythm` - Rhythm Guitar audio
- `bass` - Bass Guitar audio
- `keys` - Keys audio
- `drums` - Drums audio as a single stem
- `drums_1` - Drums audio for the kick drum, plus snare, tom, and cymbal audio if 2-4 are not present
- `drums_2` - Drums audio for the snare drum, plus tom and cymbal audio if 3 and 4 are not present
- `drums_3` - Drums audio for toms, plus cymbal audio if 4 is not present
- `drums_4` - Drums audio for cymbals
- `vocals` - Vocals as a single stem
- `vocals_1` - Main vocals
- `vocals_2` - Backing/harmony vocals
- `crowd` - Background crowd noise/singing audio

Nearly all modern customs from the GH community use these specific names for audio files, and those who make .chart files don't always use the .chart metadata tags deliberately for specifying the audio in the chart.

### Relevant Log output

Log files from after deleting my cache and starting the game:
[info.txt](https://github.com/TeamRizu/OutFox/files/8458653/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/8458654/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/8458655/userlog.txt)

[A couple charts I made to test this issue, along with the cache files generated for them](https://drive.google.com/file/d/1nMVVqmt6baqweSCCt-p64swHZVskMiqA/view?usp=sharing)
(note: the audio can get a bit grating after a while, you may want to turn down your volume a bit)

**Comment by Scraticus** [comment]
Fixed in 4.15
