### ISSUE TITLE
[BUG] be-mu's noteskins permanent metric lane position when using wrong values

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#536]
This happened while I was trying to make a be-mu noteskin.

On 4.14.0, putting wrong values for metrics like `Single5LaneLocation` or any LaneLocation metric can make all be-mu noteskins break and puts the game in a state that it can't load any other metrics (even when reloading them) with the only option to set the right values for the metric and restart the game. (Also it doesn't error)

**Comment by MrThatKid** [comment]
Jous replaced the LaneLocation system with a better one where you can set the actual x position of the columns.
