### ISSUE TITLE
[BUG] Scores not being written to Stats.xml file in some cases

### ISSUE THREAD

**Issue by MrTwinkles47** [TeamRizu/OutFox#537]
### Is there an existing issue for this?

- [x] I have searched the existing issues and none matched.

### Operating System

Windows 10

### Game Version

4.14.0

### Game Mode

dance

### Theme

Simply Love 5.1.1

### Describe the problem

I discovered a weird bug/odd behavior with either OutFox, Simply Love, and/or GrooveStats Launcher while playing ITL. I am running OF 4.14.1 with SL 5.1.1 and GS 1.3.1. I noticed that most scores were not showing on the songwheel for songs in the ITL pack, after a restart of the game. I checked my profile's Stats.xml file and did not see score/played entries for songs I know I've played previously. All GS/ITL integration stuff seems to be working as expected. 

Here's what I tested with GS running:
- Played an ITL chart -> score submitted -> stats file timestamp modified, but no entry
- Played an ITL chart that I know is in another pack on my machine -> score submitted -> stats file entry written
- Played non-ITL GS-ranked chart -> score submitted -> stats file entry written
- Played non-ITL, non-ranked chart -> no score submitted (expected) -> stats file entry written

Additional notes: 
- ITG game mode
- OF logs didn't show anything odd in relation to profile saving and no errors showed up on screen with "toggle errors" enabled. 
- I did not test what happens with GS **not** running.
- The machine profile stats was not updated in the same situations that the profile stats was not updated. The highscores "upload" directory; however, did have new .xml files for every song I played that session
- OF 4.12 works fine in every case.

### Describe what should happen

Functionally, there should be no difference between GS running and not running when it comes to saving scores in the profile.

**Comment by concubidated** [comment]
I think I solved this. Will send you a test build on discord

**Comment by concubidated** [comment]
Closing this as others have reported it solved.
