### ISSUE TITLE
[Nitpick] Installing 20220327 over an existing install

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#538]
### Game Mode

None

### Give an example of what is wrong

Installing Project OutFox Alpha date-20220327 over an existing install ignores the old install.

Unless I'm misremembering and I had chosen the name myself, the old default install dir on Windows was `Games\\StepMania 5.3 Outfox`.  The new default is `Games\\Project Outfox`  Installing to the default directory ignores the existing installation, including user profiles & updates to preferences

### Give an example of what it should look like

Ideally the game would have known about the existing songs directories, preferences, etc

**Comment by Scraticus** [comment]
Yea, I appreciate the change in naming conventions wasn't fun for everyone, but we won't be changing the name or locations (except for the steam version) in the future.
