### ISSUE TITLE
[BUG] Visual weirdness when closing in borderless window

### ISSUE THREAD

**Issue by bcdefg123** [TeamRizu/OutFox#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Raspberry Pi OS 64 bit

### CPU

Raspberry Pi 4B 4GB

### Storage

SD card

### Game Version

4.14.0

### Game Mode

dance

### Theme

Soundwaves 4.14.0 (or 4.14.1, whichever one comes with 0.4.14.1)

### Describe the problem

This is either an OutFox issue or maybe even an OS issue, not sure.

When exiting the game in Borderless Window setting, a few odd behaviors have been observed. The game for me runs in 720p and the TV/Pi output outside of the game is in 1080p. The first odd behavior is that I see the desktop in a smaller size which doesn't take up the entire TV window, it looks smaller like the size the game was in relative to 1080p output (not describing it well, but you can see what I mean in the video below). Right clicking seems to bring things back to normal, although that's not shown in the video.

The second odd behavior shown (which also happens after exiting) is where the game window stays on the screen but is unresponsive. The Pi OS taskbar can be seen, mostly. The game window does not respond, and right clicking anywhere immediately makes that 'ghost game' window disappear.

See the video of both the things above here: https://www.youtube.com/watch?v=pVbzB0ydk7k

### Describe what should happen

The game should close cleanly without any odd artifacts such as described above.

### Relevant Log output

[info.txt](https://github.com/TeamRizu/OutFox/files/8750408/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/8750409/log.txt)

**Comment by Scraticus** [comment]
I will fix this for 4.16, as we need to update one of the internal libraries we use for this one.

Thanks for reporting, and we'll keep this open till the work is done

**Comment by Scraticus** [comment]
fixed in alpha V 042, will look at a backport, but you need to use the glad renderer and have the 'opengl driver' enabled in raspiconfig
