### ISSUE TITLE
[Feature Request] Better camera debug

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#55]
**Is your feature request related to a problem? Please describe.**

Problem: Right now you can't really control the camera debug how you want, it goes depending of the resolution and you can't go left/up/right/down/zoom more/zoom less

**Describe the solution you'd like**

Add advanced camera control so we can use the camera to go left/up/right/down/zoom more/zoom less

**Describe alternatives you've considered**

Maybe enable a options where you move the mouse to move/look around.

Right click = Goes right
Left click = Goes left
scroll wheel up= Goes up
scroll wheel down = Goes down
Moving the mouse = Moves where the camera is looking

**Additional context**

Being able to append a custom key to move the camera would be good.

**Comment by Scraticus** [comment]
Added in 4.9.7
