### ISSUE TITLE
[BUG] Lift passes through receptor during autoplay

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows10 Pro

### CPU

i5-7500 3.4GHz

### GPU

GeForce GTX 1060 6GB

### Storage

SSD

### Game Version

4.15.0

### Game Mode

dance

### Theme

Soundwaves (Alpha 0.4.15)

### Describe the problem

During autoplay, if a Lift exists on the rightmost side of the column when viewed in rows, it is determined to be Flawless, but it passes by the receptor without disappearing
For example, a simultaneous press that includes Lift will be processed normally if Lift is on the left side, but if Lift is on the right side or only Lift, this phenomenon will occur
However, it seems to work correctly for simultaneous presses of Head and Lift on long notes

https://user-images.githubusercontent.com/8708955/173837290-b920c912-b3d5-4226-92f2-50b464a9e41d.mp4

### Describe what should happen

When Flawless decision is made, it disappears with Receptor as in normal play

**Comment by Jousway** [comment]
also just fixed it, thanks for your report :)
