### ISSUE TITLE
[Game Crash] Enabling ShowBoard with the default theme crashes when loading into dance charts.

### ISSUE THREAD

**Issue by Buic** [TeamRizu/OutFox#559]
### Describe the crash

I was redoing some minor edits to the default theme after the latest update, and noticed the metric ShowBoard=true now crashes the game without an error message when loading dance charts. This did not happen prior to the update, and was required for other useful accessibility tweaks.

I tested this on a fresh install of the latest version and got the same result. 
I also tested this on a fresh install of the prior version with no issue. 

No crashinfo file was generated.

Following files are from the fresh install test, although they do not appear useful. 
[log.txt](https://github.com/TeamRizu/OutFox/files/8918323/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/8918324/info.txt)

Files from the old version.
[log.txt](https://github.com/TeamRizu/OutFox/files/8918412/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/8918414/info.txt)

### How can you reproduce the error?

From a fresh install, set the metric ShowBoard to true in the default theme. Launch the game and attempt to play a dance chart without touching any other settings.

### Screenshots/Videos

New version, crashes.
https://drive.google.com/file/d/1dUigm4Qk4Cterr92ddn5mjeGS2UQGWGn/view?usp=sharing

Old version, functions as expected.
https://drive.google.com/file/d/1wLvY8EK1YrQrpyg-0j9s6dNfgRkbpQ0L/view?usp=sharing 

### Game Mode

dance

### Additional Information

If you look into this, could you also make the board and beat bars rotate with the note field when using the x and z rotation options? They currently do not.

**Comment by JoseVarelaP** [comment]
Fixed for the next alpha, you've hit a state where no board was selected, reaching an invalid `nil` texture.
