### ISSUE TITLE
[BUG] Crashing in the second stage of the course mode

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows10 Pro

### CPU

i5-7500 3.4GHz

### GPU

GeForce GTX 1060 6GB

### Storage

SSD

### Game Version

4.15.0

### Game Mode

dance

### Theme

Soundwaves (Alpha 0.4.15)

### Describe the problem

When certain conditions are met in Course Mode, the crash occurs at the timing when the game switches to STAGE 2
This phenomenon occurs regardless of the music played or Difficulty of Steps

`Occurrence Conditions`
- ShowBeginnerHelper in Preferences.ini is set to 1
- Bones of BeginnerHelper and Model of DancePad exist in Characters folder
- DancePad file names are "DancePad.txt" and "DancePads.txt"
  - Not "DancePad-DDR.txt" and "DancePads-DDR.txt

`List of files in the Characters folder at the time of the occurrence`
```
default
Arrow-Blue.png
Arrow-Red.png
BeginnerHelper_step-down.bones.txt
BeginnerHelper_step-jumplr.bones.txt
BeginnerHelper_step-left.bones.txt
BeginnerHelper_step-right.bones.txt
BeginnerHelper_step-up.bones.txt
DancePad.txt
DancePads.txt
Instructions.txt
MetalPanel.png
```

- It occurs regardless of the character's display status
- It also occurs for other than Novice score
- The crash does not occur if the DancePad file name has "-DDR" in it
  - DancePad.txt" and "DancePads.txt" are officially supported file names as written in Instructions.txt

### Describe what should happen

OutFox should not crash in the middle of course mode

### Relevant Log output

[userlog.txt](https://github.com/TeamRizu/OutFox/files/8918424/userlog.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/8918425/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/8918426/log.txt)

**Comment by JoseVarelaP** [comment]
Fixed for the next alpha. Thanks for the report!
