### ISSUE TITLE
[BUG] Chart Editor Song Options Menu has selection reticle for Player 2

### ISSUE THREAD

**Issue by Zyl9393** [TeamRizu/OutFox#565]
### Is there an existing issue for this?

- [x] I have searched the existing issues and none matched.

### Operating System

Windows 10 x64

### Game Version

4.15.0

### Game Mode

dance

### Theme

Default, but happened too on [this port of CSLA](https://github.com/Casuallynoted/CSLA-5.3)

### Describe the problem

When going into the song options in the chart editor, a selection reticle is displayed for player 2, preventing me from making changes to xmod and playback speed without moving player 2's selection to the exit button. One can still exit the menu with Escape, but then changes will not be applied (though the UI state remains the same when opening the menu again).

![2022-07-03_160127](https://user-images.githubusercontent.com/41211819/177043275-e75bed0e-5df2-43cf-8409-0e61bb85408a.jpg)

### Describe what should happen

By my reckoning, chart editing is not multiplayer. Only player 1 should be able to select things and be able to confirm the selection by himself.

### Relevant Log output

[info.txt](https://github.com/TeamRizu/OutFox/files/9034917/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/9034918/log.txt)
[timelog.txt](https://github.com/TeamRizu/OutFox/files/9034920/timelog.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/9034921/userlog.txt)

**Comment by JoseVarelaP** [comment]
Duplicate of #467.

**Comment by Zyl9393** [comment]
Closing since I failed to think of "Edit/Practice" in addition to "Chart Editor" when searching for existing issue.

**Comment by JoseVarelaP** [comment]
That is understandable, internally the editor/practice are the same thing, just with different flags to determine their functionality.
