### ISSUE TITLE
[BUG] Beat bars and backplates zoom/rotation

### ISSUE THREAD

**Issue by Buic** [TeamRizu/OutFox#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### Storage

External HDD

### Game Version

4.15.0

### Game Mode

dance

### Theme

Default theme, latest with minor edits.

### Describe the problem

This is a 4.15.1 issue, which seems to be absent from this form's dropdown. 

Backplates and beat bars, when enabled in dance, pump, smx, or techno; do not follow note field X/Y rotation, but do match rotation with perspectives. The backplate also seems to bee slightly too thin in pump and techno (possibly in smx as well, but the lanes are messed up so I can't tell [possibly a related issue? Happens a little bit in pump as well.])

![extreme example](https://cdn.discordapp.com/attachments/540706498159050762/996592661370769448/unknown.png)

In addition, beat bars desynchronies from notes when note field zoom % is not 100.

![out of synch](https://cdn.discordapp.com/attachments/540706498159050762/996593304571478036/unknown.png)

### Describe what should happen

Ensure all parts of the note field move together.
Correct plate width, possibly also lane spacing.
Adjust beat bar offset relative to note field zoom %.

### Relevant Log output

Nothing relevant appears in the logs.

**Comment by Buic** [comment]
Misclicked, whoops.

Anyways, additional screenshots:

smx lanes
![smx lanes](https://cdn.discordapp.com/attachments/540706498159050762/996609917651779635/unknown.png)

pump lanes and plate width
![pump lanes and plate width](https://cdn.discordapp.com/attachments/540706498159050762/996610908400910366/unknown.png)

**Comment by Buic** [comment]
Would also be appreciated to make the backplate usable for upscroll players.

**Comment by Scraticus** [comment]
This is fixed in 4.16,  thanks for reporting! Please reopen if there are any other issues with this!

Backplates were not originally designed for use outside of gh, but Jous has added new code to allow this to happen
