### ISSUE TITLE
[BUG] Wrong song length

### ISSUE THREAD

**Issue by Sameth** [TeamRizu/OutFox#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 11

### Storage

SSD

### Game Version

4.15.0

### Game Mode

dance

### Theme

Soundwaves (Alpha 0.4.15)

### Describe the problem

The game incorrectly infers the duration of certain .ogg songs. So far, I've only stumbled upon songs where it infers 1:45 as the duration, whereas the audio file is usually much longer. An example is "Bad Apple!!" from "Dragon Files I" pack (https://search.stepmaniaonline.net/pack/id/726). When trying to play the song, it just cuts off after 1:45, not playing the rest of the song and not allowing me to tap the arrows that are still going.

Now the difficult part: Project Outfox is not the only program that gets it wrong. For example, the Windows Media Player also gets it wrong in the same way, though it continues to play the song beyond 1:45. VLC is able to get the song duration correctly. However, there are songs that Outfox gets right, that MediaPlayer doesn't. Yikes.

Please note that Stepmania 5.0.12 does get the .ogg duration right. I would swear that Outfox 0.4.14.1 also got it right, but there's a slight chance I haven't tried to play any of the broken songs; now I have no way to verify that since I can't download older versions.

### Describe what should happen

Outfox correctly infers the length of the song and plays it in its entirety. Or at least doesn't stop when there's more music to play and arrows to tap.

### Relevant Log output

00:03.641: Attempting to load 39 songs from "/AdditionalSongs/Dragon Files I"
00:03.643: OutFox Engine: Float Value Index Out of Range.
00:03.646: OutFox Engine: Float Value Index Out of Range.
00:03.647: OutFox Engine: Float Value Index Out of Range.
00:03.648: OutFox Engine: Float Value Index Out of Range.
00:03.654: OutFox Engine: Float Value Index Out of Range.
00:03.655: OutFox Engine: Float Value Index Out of Range.
00:03.657: OutFox Engine: Float Value Index Out of Range.
00:03.660: OutFox Engine: Float Value Index Out of Range.
00:03.667: OutFox Engine: Float Value Index Out of Range.
00:03.670: OutFox Engine: Float Value Index Out of Range.
00:03.683: OutFox Engine: Float Value Index Out of Range.
00:03.687: OutFox Engine: Float Value Index Out of Range.
00:03.694: OutFox Engine: Float Value Index Out of Range.
00:03.696: OutFox Engine: Float Value Index Out of Range.
00:03.702: OutFox Engine: Float Value Index Out of Range.
00:03.704: OutFox Engine: Float Value Index Out of Range.
00:03.704: Loaded 39 songs from "/AdditionalSongs/Dragon Files I"

---------------------
I found the above in the log, and the number of "Float Value Index Out of Range" seems to match the number of songs with incorrectly inferred duration.

**Comment by concubidated** [comment]
A little context, these files have the headers patch to get around song length limits on itg r21 cabinets. So that's why they are all 1:45

**Comment by Scraticus** [comment]
Thanks for the report, this is fixed in 4.16 coming this week:

![image](https://user-images.githubusercontent.com/11047768/181119055-236fb309-ba11-40c1-a7c8-6779c1064d11.png)
