### ISSUE TITLE
[BUG] SongMovies folder does not work

### ISSUE THREAD

**Issue by SheepyChris** [TeamRizu/OutFox#572]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

MX Linux 21.1

### CPU

Intel Core i5 8400

### GPU

NVIDIA GeForce 1030

### Storage

120GB + 480GB SSD

### Game Version

4.15.0

### Game Mode

pump

### Theme

Infinitesimal (latest commit as of writing)

### Describe the problem

Songs that utilize BGCHANGES to display their background videos are unable to load them if they are located in SongMovies. If the video is stored in the same folder as the song files, it will be loaded properly. The scenario here is that SongMovies are being stored in the game's User folder and the songs are being loaded from AdditionalSongFolders.

### Describe what should happen

The videos should be able to load fine during gameplay.

### Relevant Log output

Movie located in SongMovies (non functional):
[log.txt](https://github.com/TeamRizu/OutFox/files/9205064/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/9205066/info.txt)

Movie located in song folder (functional):
[log.txt](https://github.com/TeamRizu/OutFox/files/9205068/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/9205069/info.txt)

**Comment by Scraticus** [comment]
Fixed in 4.18, thanks for reporting
