### ISSUE TITLE
[BUG] Short long notes hitting themselves without user interaction

### ISSUE THREAD

**Issue by SheepyChris** [TeamRizu/OutFox#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

MX Linux 21.1

### CPU

Intel Core i5 8400

### GPU

NVIDIA GeForce 1030

### Storage

120GB + 480GB SSD

### Game Version

4.15.0

### Game Mode

pump

### Theme

Infinitesimal (latest as of writing)

### Describe the problem

Long notes that are shorter than the CheckpointHit timing window/release threshold limit will be automatically hit at the end without any user interaction: https://streamable.com/cy7e26

### Describe what should happen

The long notes should miss entirely when not hit.

### Relevant Log output

Test song from video linked above: 
[Credits (Long Note Test).zip](https://github.com/TeamRizu/OutFox/files/9205189/Credits.Long.Note.Test.zip)

[log.txt](https://github.com/TeamRizu/OutFox/files/9205191/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/9205192/info.txt)

**Comment by Scraticus** [comment]
Fixed in 4.18, thanks for reporting!
