### ISSUE TITLE
[BUG] [Windows] Tabbing out and back in while in exclusive fullscreen makes the game become a black screen

### ISSUE THREAD

**Issue by TheNathannator** [TeamRizu/OutFox#576]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### CPU

Intel Pentium Dual-Core E6300

### GPU

AMD Radeon HD 6850

### Storage

N/A

### Game Version

4.15.0

### Game Mode

gh

### Theme

Soundwaves (default)

### Describe the problem

(NOTE: This is actually on 4.16.0, for some reason it's not in the selection yet)
Tabbing/clicking out and back in will make the game become a black screen permanently until you restart the game.

### Describe what should happen

The game should display properly once tabbing back in.

### Relevant Log output

[info.txt](https://github.com/TeamRizu/OutFox/files/9228161/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/9228162/log.txt)
[timelog.txt](https://github.com/TeamRizu/OutFox/files/9228163/timelog.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/9228164/userlog.txt)

https://user-images.githubusercontent.com/29052821/182012881-70368571-ee72-4c36-b0b1-af5ebb9aded4.mp4

**Comment by Scraticus** [comment]
Well spotted! This one I... may have not coded how to handle the redraw when one ALT-TABs

cough

Thanks for reporting, will add this to all the windows handlers, and push for the hotfix.


![raw-417463595](https://user-images.githubusercontent.com/11047768/182041142-52498a8b-f65a-447b-afe9-d0a53222d6b4.gif)
