### ISSUE TITLE
[Feature Request] Expose DebounceCoinInputTime to ScreenOptionsMasterPrefs

### ISSUE THREAD

**Issue by SheepyChris** [TeamRizu/OutFox#580]
### Please Select the game mode your feature request is about.

All Game Modes

### Is your feature request related to a problem?

This is a not well known feature of the engine due to it being completely hidden in game, only existing through its definition in Save/Preferences.ini. In turn, arcade operators are not aware that this feature exists to help resolve issues such as multiple coins being registered with the insertion of a single one.

### Describe the solution you'd like

Have a config option exposed and available for themes to be used aside the already existing InputDebounceTime preference.

**Comment by Scraticus** [comment]
Good issue, I've implemented it into Alpha V and will backport for the next release of Alpha 4.

![image](https://user-images.githubusercontent.com/11047768/183251691-dc00785c-f553-4897-a6c4-f97e9e77fc4d.png)


Thanks for reporting!
