### ISSUE TITLE
[Game Crash] selecting reverse with bothatonce active crashes the game

### ISSUE THREAD

**Issue by Ralexiia** [TeamRizu/OutFox#581]
### Describe the crash

With a fresh start of the game i activated the second player, activated BothAtOnce from the f3 menu, went into the options menu, hit advanced options, and activated the Reverse mod, game crashed immediatly
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/9275862/crashinfo.txt)

### How can you reproduce the error?

Start the game
Activate BothAtOnce with the debug menu
Select a song and open the options menu
Go into Advanced Modifiers
Activate Reverse
Game crashes immediatly

### Game Mode

dance

**Comment by Scraticus** [comment]
This could have been one of two potential bugs we have fixed for the next alpha, could you try 4.17 when it comes out the weekend?

**Comment by Scraticus** [comment]
Fixed in 4.18, thanks for your patience and for reporting!
