### ISSUE TITLE
[Game Crash] Game not starting up properly Raspberry Pi 4

### ISSUE THREAD

**Issue by marti693** [TeamRizu/OutFox#584]
### Describe the crash

I have a Raspberry Pi 4 with 8gb ram, and I am trying to run OutFox on it.
It is running an image of RetroPie, which might be a part of the problem.
I followed the official tutorial to install the game, and ensured I have every library required.
When I run the executable, I get this message, and nothing else:
`OutFox0.4-git-223b7a4a58`
`Compiled 20220801 @ 18:30:26 (build 223b7a4a58)`
`Log starting 2022-08-19 19:15:28`

And then the program stops, and nothing else happens. No crash logs exist, and no save file was ever made. All other logs only contain the information that was printed to the command line.
I know I must be missing something in the installation, but I have looked at every tutorial I can find, and I can't figure out what I've done wrong.

### How can you reproduce the error?

Just running the executable will cause this chain of events. I have tried to run OutFox version 4.9.10 and version 4.16

**Comment by Scraticus** [comment]
We have adjusted the init system for linux, so can you try 4.17 on sunday for me?

Sorry about the issues ;_;

**Comment by marti693** [comment]
That was the problem!! I downloaded a desktop environment (RetroPie has one easily download in its configs), and ran OutFox. It ran perfectly first time.

I knew I was missing something silly. Thanks for the help

Now just to figure out how script loading the desktop and then loading outfox right after
