### ISSUE TITLE
SuperShuffle focuses too heavily on left-most receptors

### ISSUE THREAD

**Issue by PCBoyGames** [TeamRizu/OutFox#59]
While working on discovering further details into issue #22, this same modifier also has an extra unexpected behavior: most of the notes that are shuffled are on the left-most columns. [I sent this image in voice context](https://media.discordapp.net/attachments/586285188158586881/742203481884065923/left.PNG) that demonstrated an example of this behavior.

Unlike issue 22, SM5.1 faces this problem just the same. Per the Comprachicos tests I ran to test 5.1 for that issue (lucky me, it doesn’t seem to face 22), this unexpected behavior appeared with counts of 343 on left, 320 on down, 249 on up, and 124 on right.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Scraticus** [comment]
Fixed in 4.9.7 - Finally!!!!
