### ISSUE TITLE
[Game Crash] Game crashes when memory hits about 530~550MB.

### ISSUE THREAD

**Issue by christinowong** [TeamRizu/OutFox#592]
### Describe the crash

Game crashes when memory hits about 530~550MB. (I have enough memory to run this game, but it still crashed.)

### How can you reproduce the error?

In dance mode, holding the arrow key to scroll songs list. When memory hits about 530~550MB, choose a black cover song, the game closes without any message.

### Game Mode

dance

### Additional Information

- All songs contain video background. songs pack: [https://mega.nz/#F!JIwAwLaL!cFBC123xg4ZY1WUI7rjkEQ](https://mega.nz/#F!JIwAwLaL!cFBC123xg4ZY1WUI7rjkEQ), form the blog: [http://exc19910627.blog.fc2.com/](http://exc19910627.blog.fc2.com/)
- skin: CSLA-5.3, skin source: [https://github.com/Casuallynoted/CSLA-5.3](https://github.com/Casuallynoted/CSLA-5.3)
- log.txt:[https://github.com/christinowong/Outfox-error-log/blob/main/log.txt](https://github.com/christinowong/Outfox-error-log/blob/main/log.txt)

**Comment by Scraticus** [comment]
This is likely a bug that was fixed in the testing for 4.17, can you test on saturday when we release the next one please?

**Comment by christinowong** [comment]
> This is likely a bug that was fixed in the testing for 4.17, can you test on saturday when we release the next one please?

Sure. I will test it when it release. Thanks for your reply!

**Comment by christinowong** [comment]
> 

Game running perfectly now, thanks a lot!
