### ISSUE TITLE
[Game Crash] Dance: Crash when joining after the first song

### ISSUE THREAD

**Issue by DesktopMan** [TeamRizu/OutFox#595]
OutFox: Alpha 0.4.16 HF2
OSes tested: Windows 11 and Xubuntu 22.04. Crash occurs on both. Logs from Windows 11.

Options changed: Event mode off

2. Play a song as player 1
3. Join as player 2
4. Play songs until the credit is used up
5. Game crashes after the credit summary

Logs:
[timelog.txt](https://github.com/TeamRizu/OutFox/files/9437998/timelog.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/9437999/userlog.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/9438000/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/9438001/log.txt)

**Comment by DesktopMan** [comment]
Crash still occurs with OutFox-alpha-0.5.0.0-pre014-Win64-date-20220826. Logs from that version are attached.

[ProjectOutfox.Crash.2022-09-02--22.19.05.log](https://github.com/TeamRizu/OutFox/files/9480921/ProjectOutfox.Crash.2022-09-02--22.19.05.log)
[ProjectOutfox.MainLog.2022-09-02--22.19.05.log](https://github.com/TeamRizu/OutFox/files/9480922/ProjectOutfox.MainLog.2022-09-02--22.19.05.log)
[ProjectOutfox-default.ThemeLua.2022-09-02--22.19.05.log](https://github.com/TeamRizu/OutFox/files/9480923/ProjectOutfox-default.ThemeLua.2022-09-02--22.19.05.log)

**Comment by DesktopMan** [comment]
Crash still occurs with OutFox-LTS-0.4.17.0f-Win64-date-20220902. Logs from that version are attached.

[ProjectOutfox.MainLog.2022-09-02--22.32.15.log](https://github.com/TeamRizu/OutFox/files/9480969/ProjectOutfox.MainLog.2022-09-02--22.32.15.log)
[ProjectOutfox-default.ThemeLua.2022-09-02--22.32.16.log](https://github.com/TeamRizu/OutFox/files/9480970/ProjectOutfox-default.ThemeLua.2022-09-02--22.32.16.log)
[ProjectOutfox.Crash.2022-09-02--22.32.15.log](https://github.com/TeamRizu/OutFox/files/9480971/ProjectOutfox.Crash.2022-09-02--22.32.15.log)

**Comment by Scraticus** [comment]
Fixed in 4.18.0
