### ISSUE TITLE
[Feature Request] Vietnamese characters (maybe just on Windows?)

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#596]
### Please Select the game mode your feature request is about.

dance

### Is your feature request related to a problem?

Got a simfile of `Bống Bống Bang Bang`, but the diacritics over the `o` don't show up.

### Describe the solution you'd like

Ideally, that character and others in Vietnamese would be part of the font system.

### Describe alternatives you've considered

The transliteration fields work well enough for now.

**Comment by AngledLuffa** [comment]
Also not handled: `Người Lạ Ơi`

**Comment by Scraticus** [comment]
![image](https://user-images.githubusercontent.com/11047768/191140505-2d89d7e7-28e4-4e12-88e2-200b6d313635.png)

Added to the texture generator, and the game, so will be in 4.18.

Thanks for reporting!

**Comment by AngledLuffa** [comment]
Excellent, ty!  Looking forward to seeing it.

**Comment by Scraticus** [comment]
no worries, I have added it to the generator as well for other themes of they need them.

thanks for the report!

**Comment by AngledLuffa** [comment]
Looking at the image in this post makes me wonder: is the D with a dash covered elsewhere in the generator?

https://en.wikipedia.org/wiki/D_with_stroke

such as for example in this song title (in case anyone ever DDRifies it):

https://www.youtube.com/watch?v=JAhdeizXpaQ

The "e" as well.  `Để` are both not present in the above image

Thanks!

**Comment by Scraticus** [comment]
you can grab a release candidate from the discord server to test it right
now to see what it does, the new glyph set is in.

many thanks
