### ISSUE TITLE
[BUG] alt-enter no longer goes from full screen to windowed

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 11

### CPU

i7

### GPU

Intel UHD Graphics 630

### Game Version

4.16.0HF

### Game Mode

dance

### Theme

No theme

### Describe the problem

I used alt-enter to go from a small window to fullscreen.  After doing that, alt-enter does not go back to windowed mode.

### Describe what should happen

In previous versions, pressing alt-enter would go from fullscreen to windowed

### Relevant Log output

[info.txt](https://github.com/TeamRizu/OutFox/files/9441257/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/9441258/log.txt)
[timelog.txt](https://github.com/TeamRizu/OutFox/files/9441259/timelog.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/9441260/userlog.txt)

**Comment by AngledLuffa** [comment]
Updates: if it starts in fullscreen mode, *then* it doesn't switch back and forth.  However, if I hit alt-enter once when it starts in fullscreen mode, the next time it will start in non-fullscreen.

**Comment by Scraticus** [comment]
can you confirm this is still an issue?

**Comment by AngledLuffa** [comment]
It is still an issue, actually.  The following pattern on Windows causes 4.18.1 to get stuck in full screen mode.  If I start from a non-full-screen mode, I can switch it back and forth just fine.  However, if I make it full screen and exit while in full screen mode, the next time around, it will not go to windowed mode with alt-enter.  However, pressing alt-enter while stuck in full screen mode will then make it so the next time after that, it loads in windowed mode and can be switched back & forth.
