### ISSUE TITLE
[Game Crash] Game is unable to launch if Logs folder is missing from game folder

### ISSUE THREAD

**Issue by SheepyChris** [TeamRizu/OutFox#601]
### Describe the crash

[terminaloutput.txt](https://github.com/TeamRizu/OutFox/files/9497938/terminaloutput.txt)

### How can you reproduce the error?

Install a fresh copy of Alpha 0.4.17 LTS Linux (amd64) and run it.

**Comment by Scraticus** [comment]
Fixed in latest RC, and will be out in 4.17.1. Was a mac oopsie that slipped through. Thanks for reporting!
