### ISSUE TITLE
[BUG] Song rate gets reset to 1.0 after restarting the song

### ISSUE THREAD

**Issue by kubik369** [TeamRizu/OutFox#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Tested on Windows and Linux

### CPU

Tested on i7-2600 and Ryzen 4750G

### GPU

iGPU

### Game Version

4.16.0HF

### Game Mode

dance

### Theme

The default theme

### Describe the problem

While playing a song, going to the pause menu and restarting the song, the song restarts, but with the rate reset to 1x so e.g. if I am playing a song on 0.75x speed and I restart, the song starts playing with 1x speed. 

### Describe what should happen

After restarting a song, the song should start with the same settings as previously

### Relevant Log output

N/A
I was not able to find any relevant logs :/

**Comment by Scraticus** [comment]
Fixed in 4.18.0
