### ISSUE TITLE
[BUG] FailAtEnd is being applied for no reason

### ISSUE THREAD

**Issue by kubik369** [TeamRizu/OutFox#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Linux

### CPU

i7-2600

### GPU

iGPU

### Game Version

4.16.0HF

### Game Mode

dance

### Theme

Both default and tinyfoxes

### Describe the problem

At some point after creating a profile, I have noticed that I am not failing when I should be failing inside of a song. After letting it run through, it failed me at the end. I have checked all the settings I know of, Song options fail type was set to Immediate, same in the Options-System Settings - Gameplay Settings, no fail option was set in the Stats.xml of the profile (you can find it in discord [0]). I should add that I don't recall ever setting FailAtEnd, only Immediate or Off, but I might be wrong.

If I changed a profile to a freshly made one, it was working fine. Swapping back to the first one didn't help, same behaviour. After trying whether Sudden death works, which worked, after reverting the Sudden death setting, it started failing me properly and it is doing it since then. Another user encountered a similar issue a few days before me, so the possibility of it being some oversight on my part is slightly decreased (user is Hamiltron#0077 , date 2022-09-05).

Possibly related, but only some modifier settings are being stored in the profile. At least from the settings I tend to change, Speedmod type, speedmod value and Judgement font are saved, but Hide Targets and Hide Background is not. Also for months, nothing was being saved, so I am not sure whether it should be working or not.

[0] https://discord.com/channels/422897054386225173/439809793964769291/1017899261612011580

### Describe what should happen

The fail type modifier settings should be honoured.

### Relevant Log output

N/A

**Comment by Scraticus** [comment]
Fixed in 4.18.0 test the preview to confirm for me!

**Comment by kubik369** [comment]
I will try to check, but I still have to come up with steps to reproduce it 😅 I have encountered it on another PC today, so I will try to pin it down. Could you tell me what did you fix?
