### ISSUE TITLE
Attempted to load a non-existing mod for the Player. Ignoring. I don't get it...

### ISSUE THREAD

**Issue by KevRub** [TeamRizu/OutFox#604]
### Is there an existing issue for this?

- [x] I have searched the existing issues and none matched.

### Operating System

Windows 10

### Game Version

4.16.0HF

### Game Mode

dance

### Theme

DDR A3 (Inori)

### Describe the problem

Noteskins that I copied and modified are not loading outside of Soundwaves. and this is shown in the log: Attempted to load a non-existing mod 'Noteskin Name' for the Player. Ignoring. Any solution for this issue? Please let me know as soon as possible.

### Describe what should happen

Noteskins should load properly.

### Relevant Log output

06:43.976: Attempted to load a non-existing mod 'ddr kids modern note' for the Player. Ignoring.
06:43.977: Attempted to load a non-existing mod 'ddra cel' for the Player. Ignoring.
06:43.977: Attempted to load a non-existing mod 'ddra cel_shock-arrows' for the Player. Ignoring.
06:43.977: Attempted to load a non-existing mod 'ddra-classic reversed brightness' for the Player. Ignoring.
06:43.981: Attempted to load a non-existing mod 'dsdr 9 note' for the Player. Ignoring.
06:43.981: Attempted to load a non-existing mod 'extreme plus' for the Player. Ignoring.
06:43.983: Attempted to load a non-existing mod 'hp3 note' for the Player. Ignoring.
06:43.983: Attempted to load a non-existing mod 'jelly with eyes' for the Player. Ignoring.
06:43.984: Attempted to load a non-existing mod 'kawaii cel' for the Player. Ignoring.
06:43.984: Attempted to load a non-existing mod 'kawaii note' for the Player. Ignoring.
06:43.986: Attempted to load a non-existing mod 'midi-solo (2)' for the Player. Ignoring.
06:43.988: Attempted to load a non-existing mod 'pastel note' for the Player. Ignoring.
06:43.988: Attempted to load a non-existing mod 'pastel rainbow' for the Player. Ignoring.
06:43.988: Attempted to load a non-existing mod 'pastel vivid' for the Player. Ignoring.
06:43.993: Attempted to load a non-existing mod 'reflec arrow' for the Player. Ignoring.
06:43.993: Attempted to load a non-existing mod 'reflec note blue' for the Player. Ignoring.
06:43.998: Attempted to load a non-existing mod 'starlight 2010' for the Player. Ignoring.

**Comment by JoseVarelaP** [comment]
All of these errors have a thing in common. Spaces. Noteskins **cannot** have spaces. You need to rename the noteskins to be all a single string, like replacing the spaces with dashes.

Example.
`hp3-note`
`pastel-note`
`reflec-arrow`
