### ISSUE TITLE
[BUG] Some scores are not displayed ingame

### ISSUE THREAD

**Issue by Kaede573** [TeamRizu/OutFox#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### Game Version

4.16.0HF

### Game Mode

dance

### Theme

Noticed the bug on Simply Love, but it happens with OutFox default theme just the same.

### Describe the problem

The game seems to ignores certain scores in Stats.xml.

For the song "Tempura Dance", it displays my 56.13% score even though I have a better 78.48% score.
I have attached my full profile folder and the song (I have removed the .ogg file because copyright). I could repro the issue using a clean 4.16.0HF install, pasting the profile data and just that one song.

The scores were performed using OutFox + Simply Love. The 56.13% score was performed on 4.16.0HF. The 78.48% probably on an older release, I'm not too sure. Most scores are older - this profile is old, I have kept it but have upgraded OutFox multiple times.

[00000001.zip](https://github.com/TeamRizu/OutFox/files/9578175/00000001.zip)
[Skittles Steps Fo(u)rth (9ms).zip](https://github.com/TeamRizu/OutFox/files/9578179/Skittles.Steps.Fo.u.rth.9ms.zip)

**Comment by Kaede573** [comment]
As advised by Cube on Discord, I have removed the 'OnlineHash' attributes, but it doesn't seem to cut it. The oldest, inferior score still gets displayed (at least for "Tempura Dance", the song I've been checking).

**Comment by concubidated** [comment]
The scores are keyed by the following.

`<Steps Difficulty='Challenge' OnlineDescription='Chief Skittles' OnlineHash='16777215' StepsType='dance-single'>`
(which contains a score of 56.13) and is the correct hash
`<Steps Difficulty='Challenge' OnlineDescription='Chief Skittles' OnlineHash='805969952' StepsType='dance-single'>`
(which contains a score of 78.48) and is the wrong hash.

You must have had an intermediate Outfox version which caused this weirdness. I'll try to fix up your profile for you, Send me your latest one on discord when you get a chance

**Comment by Kaede573** [comment]
Thanks for the offer, sent you files through Discord. They are just my own personal profiles so I am totally fine with the idea of throwing them into the bin instead and starting fresh in the worst case (new profiles), no worries ! :)

**Comment by Kaede573** [comment]
Also, since no fix/modification to OutFox is required and we moved this to Discord I think I may as well close this issue now !

**Comment by concubidated** [comment]
For anyone else who runs into this in the future. Script to fix your Stats.xml file

https://gist.github.com/concubidated/9e5a7c95aad79fc230b313d569a18c35
