### ISSUE TITLE
[BUG] Game "hangs" for a few seconds after playing a song

### ISSUE THREAD

**Issue by Kaede573** [TeamRizu/OutFox#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### CPU

i5-12600KF

### GPU

Radeon RX 6700 XT

### Storage

WD_BLACK SN770 NVMe

### Game Version

4.16.0HF

### Game Mode

dance

### Theme

Simply Love v5.1.2 (latest) 

### Describe the problem

Oftentimes after clearing a song I get 3-4 seconds (or longer) pauses when leaving the gameplay screen. It doesn't happen 100% of the time but it is frequent. I haven't reproduced the issue with the default theme yet (but I have given it just a few tries, I never use default).
I _think_ this is an old problem. It happened to me back in 2021-09-04 (using latest OutFox release at that time), but maybe less frequent at that time (smaller Stats.xml ?).

I have attached logs I copied just after the freeze happened.
I have checked the "theme errors" (that can be displayed using the debug menu, "Show recent errors") but nothing was shown there.

[Logs.zip](https://github.com/TeamRizu/OutFox/files/9591425/Logs.zip)

### Describe what should happen

The game shouldn't hang

**Comment by Kaede573** [comment]
Please note that I am using Dropbox to keep my scores synced and backuped. I got to think about it some more, and I'm strongly suspecting OF is trying to acquire a lock after Dropbox has put a lock on the file (for uploading after last change). Since duplicates appeared in my Stats.xml at some point and it grew huge (10MB), it would explain why I am starting to notice these delays more and more. Sorry for the useless bug report if this theory is true. I will try to confirm it.

**Comment by Scraticus** [comment]
We cannot write to a file that is locked, so the main thread will hang until the lock is released. 

You should turn off Dropbox when playing as it can cause dual entries and corruption.
