### ISSUE TITLE
[Game Crash] Program just keeps crashing 

### ISSUE THREAD

**Issue by BonsaiBoom** [TeamRizu/OutFox#607]
### Describe the crash

1. I was adding some additional custom characters to the game with the starlight theme, and all of a sudden it just kept crashing nonstop. I tried getting rid of all the custom characters, but still, nothing changed it just kept crashing.
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/9596271/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/9596272/log.txt)

### How can you reproduce the error?

1. I just start the game with the starlight theme mod and then I press options during music select which just makes me crash

### Screenshots/Videos

![Screenshot](https://user-images.githubusercontent.com/113878225/190953654-6a81bcbb-7906-4d0e-a459-9b6eb7ef6370.png)
Then from here I just press "select" for the options menu and it instantly crashes.

### Game Mode

dance

**Comment by JoseVarelaP** [comment]
```
OptionsList.cpp:315 Assertion 'bAllowFail' failed
```

It seems that Options menu you're opening is requesting an option, and failing to get a default value (as it wasn't able to find the appropriate option), thus hitting this assert.

**Comment by BonsaiBoom** [comment]
Is there any way to restore the default value?

**Comment by Scraticus** [comment]
can you try the pre-release to see if you do not have this issue anymore

**Comment by Scraticus** [comment]
Fixed in 4.18
