### ISSUE TITLE
[BUG] #NAME in DWI files is stripping first nonstandard character.

### ISSUE THREAD

**Issue by TheT113** [TeamRizu/OutFox#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows

### Game Version

4.18.0

### Game Mode

dance

### Theme

Tested in both default and Starlight.

### Describe the problem

The first non-standard character, like parentheses, dashes, etc. in the #NAME field of DWI files (not SM or any other files, only DWI), is being stripped out and ignored. For example, "Song Name (Outfox Mix)" renders as "Song Name Outfox Mix)". Tossing an arbitrary extra symbol in there, ie "Song-Name (Outfox Mix)" will render as "Song Name (Outfox Mix)" (suggesting it is replacing the first instance of the character with a space).

### Describe what should happen

The #NAME field should display the NAME as entered.

**Comment by TheT113** [comment]
This issue occurs in the latest release of Alpha V as well.

**Comment by Jousway** [comment]
fixed, will be in next release :)
