### ISSUE TITLE
[Game Crash] Entering options before gameplay has loaded at least once crashes the game if many noteskins are installed

### ISSUE THREAD

**Issue by Buic** [TeamRizu/OutFox#615]
### Describe the crash

This only occurs when a large number of noteskins are installed for the current gamemode.
It seems like the game is unable to render noteskins in the options menu if none have been rendered in gameplay beforehand.
I've testing this with a freshly installed build, with the only change being adding around 80 noteskins for the same gamemode.
The number of noteskins at which this starts is inconsistent and sometimes occurs with less than 80.
Which noteskins are used doesn't effect the outcome from what I can tell.

Log files abruptly end without any indication of an error, and are identical to a fresh install otherwise. 

### How can you reproduce the error?

Install a large number of noteskins for the same gamemode.
Select a song and enter the options menu. 
If no gameplay screen has been loaded before doing so, and enough noteskins are present, the game crashes.
Loading into gameplay without entering options will prevent this crash until the game is re-launched. 

### Game Mode

dance

**Comment by Jousway** [comment]
can I has logs?

**Comment by Buic** [comment]
For some odd reason it stopped happening on the test install when I went back to get logs, nothing had changed.
Re-installed again, dumped in the same noteskins, and now it's back to crashing.

[ProjectOutfox.MainLog.2022-10-27--06.51.36.log](https://github.com/TeamRizu/OutFox/files/9878659/ProjectOutfox.MainLog.2022-10-27--06.51.36.log)
[ProjectOutfox-default.ThemeLua.2022-10-27--06.51.36.log](https://github.com/TeamRizu/OutFox/files/9878660/ProjectOutfox-default.ThemeLua.2022-10-27--06.51.36.log)

(crash log generated was completely empty)

**Comment by Jousway** [comment]
hm no crash log, das wierd, let me try this locally thanks for report :+1:

**Comment by Jousway** [comment]
I cant replicate this myself, so I think its one of your noteskins, can you send me all your installed skins or test every skin yourself, whats easier for you?

**Comment by Buic** [comment]
I can do that on my own time.
Tho it did happen with copy-pasting the defaults repeatedly as well.

**Comment by Buic** [comment]
At some point during testing this, it stopped happening on clean installs. It's still happening on my main install. I thought it could have been load order, since isolating individual skins for testing might have altered that, but re-installing everything the same way I did originally didn't seem to effect anything.

I haven't the faintest idea what else could be influencing it, so I'm just gonna close this until I find a more consistent setup.
At least it's easy to avoid.
