### ISSUE TITLE
[BUG] Notefield zoom and rotation reset after the first song in a course

### ISSUE THREAD

**Issue by Buic** [TeamRizu/OutFox#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### Storage

External HDD

### Game Version

4.18.0

### Game Mode

dance

### Theme

Default, latest

### Describe the problem

Exactly what the title says.
I've tested this with a fresh install and it behaves the same.
This starting happening after #569 was resolved, though I forgot to bring it up till now.

### Describe what should happen

Self explanatory 

### Relevant Log output

Nothing in the logs is any different from playing without zoom and rotation set.

**Comment by Jousway** [comment]
I prob need to use basezoom for the notefield zoom as mods overwrite zoom, thanks for reporting!

**Comment by Jousway** [comment]
fixed, will be in next release :)
