### ISSUE TITLE
[Unexpected Behavior] Audio distortion when the same sound effect is overlayed.

### ISSUE THREAD

**Issue by MrThatKid** [TeamRizu/OutFox#62]
**What you're using**
This is done on an indev version of OutFox.

When having a sound constantly overlap itself (usually through repetitively making the sound play.), it distorts that sound effect. Sometimes, it makes popping sounds, other times it may affect the rate (sounds like double rate).

**Expected behavior**

I'd expect them to overlap and have nothing odd happen.

Here's an example I took while on the profile select screen: 
[2020-08-03_00-10-23.mkv](https://cdn.discordapp.com/attachments/703665138942869594/739742280088420440/2020-08-03_00-10-23.mkv)

**Comment by Scraticus** [comment]
Can you test this with 4.8.2 when it is released?

**Comment by Scraticus** [comment]
Fixed in 4.8.2
