### ISSUE TITLE
[FIXED] [BUG] LASTSECONDHINT doesn't work on some modes

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 11

### CPU

i7

### GPU

Intel UHD Graphics 630

### Storage

lots

### Game Version

4.18.1

### Game Mode

dance

### Theme

default theme

### Describe the problem

I have a stepfile I am trying to write where the last few beats don't really have danceable steps, but I don't want to cut them short, so I am trying to use #LASTBEATHINT  However, the music ends a couple beats after the last step anyway, leaving the song unfinished.  I already made an excessively long hold to try to cover most of the tail, but thought #LASTBEATHINT would be better than having the user stand there for several seconds.

Of course, now that I file the bug, I see a different tag #LASTSECONDHINT show up a couple times in other issues.  So maybe #LASTBEATHINT isn't even a thing that is supposed to exist.

### Describe what should happen

Stopping at max(last beat in step chart, LASTBEATHINT) would be a nice touch.  Even if the feature doesn't currently exist, I suppose.  A few other step charts I found on the web to use that tag.

Logs aren't really relevant, but I can easily submit the simfile if that helps.

**Comment by concubidated** [comment]
LASTBEATHINT is for SMA files, Doesn't look like something SM/SSC supports.  LASTSECONDHINT is likely what you want.

**Comment by Scraticus** [comment]
Indeed, LastSecondHint is what you need, but we have adjusted the parser so this one is fixed, even though it was for a different issue you initially put up

**Comment by AngledLuffa** [comment]
Excellent, thanks!

**Comment by Scraticus** [comment]
fixed in 042
