### ISSUE TITLE
[Feature Request] OutFox and 1:1 / 3:4 aspect ratios

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#63]
**Is your feature request related to a problem? Please describe.**

I find it frustrating that, despite being the default OutFox theme, SoundWaves doesn't look right at the square and vertical aspect ratios offered by the OutFox engine (1:1 and 3:4).

In addition, I find the offered resolutions for 1:1 and 3:4 to be idiosyncratic.

3:4 - Instead of offering rotated versions of the 4:3 resolutions, it does some weird stuff. I understand 810x1080 (3:4 *that fits in* 1080p, although 3:4 *at* 1080p is 1080x1440), but what even are 608x810, 456x608, and 342x456? I don't think they fit existing screens.

1:1 - Square versions of the same sequence.

Also, it would be nice if, in the future, OutFox supported more vertical aspect ratios like 9:16 (COUGH smartphone build COUGH).

**Additional context**

Song select at 3:4 aspect ratio
![](https://cdn.discordapp.com/attachments/655220422111002635/743806534667993168/unknown.png)

Song results at 1:1 aspect ratio
![](https://media.discordapp.net/attachments/655220422111002635/743808170899538001/unknown.png?width=547&height=547)

[Video](https://cdn.discordapp.com/attachments/527732010714923019/743807288191746149/4KG8YOHOgk.mp4): Notefield appears upside down when using 3:4 aspect ratio.

**Comment by JapanYoshi** [comment]
Image: notefield appears upside down at 3:4 aspect ratio
![image](https://user-images.githubusercontent.com/8707990/90250973-561ad280-de80-11ea-85b8-7df0ee639be9.png)

Image: notefield appears tiny at 1:1 aspect ratio
![image](https://user-images.githubusercontent.com/8707990/90251670-7dbe6a80-de81-11ea-890f-9e8a5c65d19b.png)

Both are taken with no Attacks, 0% Mini, Overhead

**Comment by Roujo** [comment]
I have just run into this issue while testing out the Simply-Love-Vertical theme on Outfox. This was using the default profile, so no special player options were active.

![image](https://user-images.githubusercontent.com/706916/97117534-c47add00-16da-11eb-92cd-f9974bdf1f70.png)

**Comment by Scraticus** [comment]
The notefield issue has been fixed, and the resolutions will be added to the next build.

Expect theme support in time, as we get round to them however!

**Comment by Roujo** [comment]
Cool, thank you! Looking forward to trying it out.
