### ISSUE TITLE
[FIXED - Implemented][Feature Request] Add 51 Miss Fail [FIXED] [BUG] Default fail type are not saved properly [Pump] [Infinitesimal]

### ISSUE THREAD

**Issue by notnola** [TeamRizu/OutFox#631]
### Game Mode

pump

### Give an example of what is wrong

I am running 0.4.18.1 with Pump mode and the theme Infinitesimal

"Default Fail Type" settings are not working properly. 

For instance, setting it to off, should result in a pass, even if the lifebar has been depleted 

### Give an example of what it should look like

This might be contested, but IMO the options should work like this 

Immediate should fail and quit back to eval when life bar depletes
Delayed should fail and quit back to to eval after 51 miss combo
End Of Song should result in a fail at the end of the song, if the life bar was depleted at any point in the song.
Off should make it impossible for a fail to happen

**Comment by Scraticus** [comment]
These are implemented and solved in Alpha V. A backport is not possible, so I've moved this as solved due to the new fixes we've done working with the pump bros these past few weeks. :)

**Comment by Scraticus** [comment]
fixed in 042
