### ISSUE TITLE
[BUG] Marathon length songs with a lua drawfunction can get caught in the Detailed Stats NPS masking quads

### ISSUE THREAD

**Issue by KyDash** [TeamRizu/OutFox#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### CPU

AMD Ryzen 5 3600

### GPU

NVIDIA GeForce RTX 3070

### Storage

Samsung SSD 980 PRO 2TB

### Game Version

4.18.1

### Game Mode

dance

### Theme

Soundwaves (OF 0.4.18)

### Describe the problem

When playing a song of marathon length with Detailed Stats enabled, if the chart is using a drawfunction within FGChanges (as such making actors draw above Overlay theme elements), certain actors overlapping the quads masking the extended NPS graph get caught within the mask and do not get drawn.

### Describe what should happen

An additional transparent Quad with `clearzbuffer` enabled should be drawn after theme Overlay items so any user content drawn in the overlay doesn't get captured by masks set from the theme.

### Relevant Log output

Offending lines are found in `BGAnimations/ScreenGameplay overlay/DetailedStats.lua` at lines 176
```lua
s:halign(0):xy( maxwidth/2, UserOptions.scattery ):MaskSource()
```
and 186
```lua
s:halign(1):xy( -maxwidth/2, UserOptions.scattery ):MaskSource()
```
![image](https://user-images.githubusercontent.com/13700883/208999235-f71e0853-65ed-432c-a08e-82b5af83dde0.png)
[Relay New World (minimum reproducable case).zip](https://github.com/TeamRizu/OutFox/files/10281431/Relay.New.World.minimum.reproducable.case.zip)

**Comment by MrThatKid** [comment]
Pushed a fix for this by adding clearzbuffer noeffect quads, should no longer be an issue in default for alphav 043 (pre-14 onwards)
