### ISSUE TITLE
[FIXED] [BUG] StepF2 BPM-based "warps" don't treat notes as fakes, can cause erraneous misses

### ISSUE THREAD

**Issue by dj505** [TeamRizu/OutFox#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows and Linux

### CPU

AMD Ryzen 5 4500U (Windows), Intel Core 2 Duo E7600 (Linux)

### GPU

Radeon integrated graphics (Windows), GeForce 210 (Linux)

### Storage

NVMe SSD (Windows), SATA SSD (Linux)

### Game Version

4.18.1

### Game Mode

pump

### Theme

Tested with the latest versions of Infinitesimal and Soundwaves

### Describe the problem

This one is difficult to narrow down because of how bizarrely the gimmicks and effects are recreated in StepF2 official simfiles, but as far as I'm able to tell, notes within StepF2/StepP1 style "warps" (sections where the BPM is set to 100000000.000 instead of using actual real warps) are not treated as fake notes which can cause the player's health bar to immediately drain and fail them out. Can provide the SSC if needed.

Example (at 1:28 in case the timestamped link doesn't work): https://youtu.be/1BwgnzSIqmE?t=88

### Describe what should happen

The intended behavior is as follows, with the section in question starting at 1:22 in case the timestamp in the link doesn't work (the misses were my fault, each note is completely possible to hit properly)
https://youtu.be/dl7bQSc6Z1M?t=82

### Relevant Log output

[ProjectOutfox.MainLog.2022-12-27--15.15.54.log](https://github.com/TeamRizu/OutFox/files/10310952/ProjectOutfox.MainLog.2022-12-27--15.15.54.log)
[ProjectOutfox-Infinitesimal-rewrite.ThemeLua.2022-12-27--15.15.56.log](https://github.com/TeamRizu/OutFox/files/10310953/ProjectOutfox-Infinitesimal-rewrite.ThemeLua.2022-12-27--15.15.56.log)
[ProjectOutfox.Crash.2022-12-27--15.15.54.log](https://github.com/TeamRizu/OutFox/files/10310954/ProjectOutfox.Crash.2022-12-27--15.15.54.log)  
SSC:  
[1676 - Siromaru + Cranky - Conflict.zip](https://github.com/TeamRizu/OutFox/files/10311214/1676.-.Siromaru.%2B.Cranky.-.Conflict.zip)

**Comment by Scraticus** [comment]
This _should_ be fixed in a21, do confirm for me bro

**Comment by Scraticus** [comment]
fixed in 042
