### ISSUE TITLE
[FIXED - Implemented][Feature Request] Asymmetrical timing for pump/piu

### ISSUE THREAD

**Issue by dj505** [TeamRizu/OutFox#636]
### Please Select the game mode your feature request is about.

pump

### Is your feature request related to a problem?

Timing in official PIU games is asymmetrical, with judgments biased towards late hits. There's currently no way of doing this in OutFox, which can be a deal breaker for some players.

### Describe the solution you'd like

The ability to freely configure timing windows to be either symmetrical or asymmetrical in pump/piu mode. 

### Describe alternatives you've considered

N/A

### Additional context

The following is a graphical representation of the asymmetrical PIU timing windows:  
![image](https://user-images.githubusercontent.com/7433694/209735494-287a56e9-52d0-42bf-b164-932259d4f703.png)

**Comment by Scraticus** [comment]
This is in game, but we need to give you an example of this so you can implement.

**Comment by Scraticus** [comment]
Fixed in Lua -
