### ISSUE TITLE
[FIXED] [BUG] Tap notes overlapping hold heads in pump can cause erraneous misses

### ISSUE THREAD

**Issue by dj505** [TeamRizu/OutFox#637]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows and Linux

### CPU

AMD Ryzen 5 4500U (Windows), Intel Core 2 Duo E7600 (Linux)

### GPU

Radeon integrated graphics (Windows), GeForce 210 (Linux)

### Storage

NVMe SSD (Windows), SATA SSD (Linux)

### Game Version

4.18.1

### Game Mode

pump

### Theme

Tested with the latest versions of Infinitesimal and Soundwaves, issue persists across all themes

### Describe the problem

Some StepF2 charts (i.e. Brown Sky S24) have sections where the BPM is increased to 100000000.000 on the same beat as a tap note, and then decreased back to the song's typical tempo on the same beat as a hold note, which results in what looks like a hold note but with a head that needs to be hit accurately, unlike a regular hold note which always registers as a Perfect regardless of when it's hit. This causes the notes to be unusually difficult to hit, requiring higher than normal accuracy otherwise the hold seems to trigger misses where it shouldn't. It's difficult for me to narrow this one down any further without further knowledge about the engine.

Tap notes closely followed by holds without any tempo changes, particularly very small/short holds, are also prone to this issue.

### Describe what should happen

The tap note should not affect the timing window for the hold note. If the tap note is missed, it should register as a miss, unless properly hit within the tap note's timing window. The hold note should still register as a hit if the button is being held when it reaches the receptor, regardless of whether the tap note has been hit yet.

### Relevant Log output

Example of the effects used in Brown Sky S24:  
![image](https://user-images.githubusercontent.com/7433694/209731437-0f5a0f04-2dfb-413e-9b62-caef665de918.png)  
SSC:  
[16B3 - [Remix] Brown Sky.zip](https://github.com/TeamRizu/OutFox/files/10311212/16B3.-.Remix.Brown.Sky.zip)

**Comment by Scraticus** [comment]
this is solved in a21, there was a row offset in place due to the math being off, so these notes were not treated correctly. confirm with me when i've finished building you a legacy linux build.

**Comment by Scraticus** [comment]
fixed in 042, confirm for me though
