### ISSUE TITLE
[FIXED] [Game Crash] Practice Mode Crash

### ISSUE THREAD

**Issue by DDRMASTERM** [TeamRizu/OutFox#639]
### Describe the crash

Was doing practice mode, and as I exited the mode the game crashed.
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/10327725/crashinfo.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/10327726/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/10327727/log.txt)

### How can you reproduce the error?

1: Start the game
2: Select Edit/Share
3: Select Practice Songs/Steps
4: Select any song
5: Exit mode
6: Crash may happen, if not repeat steps until it does.

### Screenshots/Videos

https://user-images.githubusercontent.com/45612281/210151415-5a1f000c-7627-4e13-89b0-b26c38150b1d.mov

### Game Mode

None

### Additional Information

I use the 2020 M1 Macbook Air

**Comment by Scraticus** [comment]
Fixed on 042
