### ISSUE TITLE
[BUG] StageAward is incorrected awarded for FullComboW3 in Stats.xml

### ISSUE THREAD

**Issue by bwaggone** [TeamRizu/OutFox#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows

### Game Version

4.18.1

### Game Mode

dance

### Theme

Simply Love release branch as of 1/1/2023

### Describe the problem

Compared to a vanilla ITGMania stats.xml, outfox seems to treat the "StageAward" value differently. See the following stats.xml for ITGMania,

<details>
  <summary>ITGMania Stats</summary>

```<HighScoreList>
<NumTimesPlayed>1</NumTimesPlayed>
<LastPlayed>2023-01-16</LastPlayed>
<HighGrade>Tier07</HighGrade>
<HighScore>
<Name>EVNT</Name>
<Grade>Tier07</Grade>
<Score>190997045</Score>
<PercentDP>0.919300</PercentDP>
<SurviveSeconds>149.020355</SurviveSeconds>
<MaxCombo>146</MaxCombo>
<StageAward></StageAward>
<PeakComboAward></PeakComboAward>
<Modifiers>2.5x, Overhead</Modifiers>
<DateTime>2023-01-16 16:45:02</DateTime>
<PlayerGuid></PlayerGuid>
<MachineGuid>0671473336b32a27</MachineGuid>
<ProductID>1</ProductID>
<TapNoteScores>
<HitMine>0</HitMine>
<AvoidMine>0</AvoidMine>
<CheckpointMiss>0</CheckpointMiss>
<Miss>2</Miss>
<W5>1</W5>
<W4>0</W4>
<W3>13</W3>
<W2>62</W2>
<W1>245</W1>
<CheckpointHit>0</CheckpointHit>
</TapNoteScores>
<HoldNoteScores>
<LetGo>0</LetGo>
<Held>39</Held>
<MissedHold>0</MissedHold>
</HoldNoteScores>
...
```
</details>

Compared to a similar stats.xml generated from outfox.

<details>
  <summary>Outfox stats.xml</summary>

```
<HighScoreList>
<NumTimesPlayed>1</NumTimesPlayed>
<LastPlayed>2023-01-16</LastPlayed>
<HighGrade>Tier06</HighGrade>
<HighScore>
<Name>BWAG</Name>
<Grade>Tier06</Grade>
<Score>191331583</Score>
<PercentDP>0.925900</PercentDP>
<SurviveSeconds>149.221069</SurviveSeconds>
<MaxCombo>189</MaxCombo>
<StageAward>FullComboW3</StageAward>
<PeakComboAward>1000</PeakComboAward>
<Modifiers>2.5x, FailImmediate, Overhead, Exactv2, Speed</Modifiers>
<DateTime>2023-01-16 16:34:28</DateTime>
<PlayerGuid>e043b14cf2bf6347</PlayerGuid>
<MachineGuid>01e059a7e189ac1f</MachineGuid>
<ProductID>1</ProductID>
<TapNoteScores>
<HitMine>0</HitMine>
<AvoidMine>0</AvoidMine>
<CheckpointMiss>0</CheckpointMiss>
<Miss>1</Miss>
<W5>0</W5>
<W4>0</W4>
<W3>17</W3>
<W2>66</W2>
<W1>239</W1>
<ProW5>0</ProW5>
<ProW4>0</ProW4>
<ProW3>0</ProW3>
<ProW2>0</ProW2>
<ProW1>0</ProW1>
<MaxScore>0</MaxScore>
<CheckpointHit>0</CheckpointHit>
</TapNoteScores>
<HoldNoteScores>
<LetGo>0</LetGo>
<Held>39</Held>
<MissedHold>0</MissedHold>
</HoldNoteScores>
...
```
</details>

Note, the ITGMania stats.xml correctly populates stageaward as empty for a non-full combo--whereas OutFox gives the player FullComboW3, which is incorrect. See here for more information,
https://itgmania.github.io/lua-for-itgmania/LuaAPI#Enums-StageAward

I came across this while debugging a new feature being added to SimplyLove:
https://github.com/Simply-Love/Simply-Love-SM5/pull/434

### Describe what should happen

When a full combo is missed, "StageAward" should be set to empty--not FullComboW3.

**Comment by JoseVarelaP** [comment]
Finally figured out where this bug came from. Just fixed it.

![Captura de pantalla 3](https://github.com/TeamRizu/OutFox/assets/23246027/2177acce-0ed2-4ec3-8bef-f2f02cf0b537)
