### ISSUE TITLE
[Game Crash] Outfox 0.4.19 LTS test build still crashes on Ventura

### ISSUE THREAD

**Issue by stclairdaniel** [TeamRizu/OutFox#644]
### Describe the crash

1. The game crashed to the desktop immediately when pressing Enter in the song wheel (same as the last few builds)

Logs here - hopefully these are the right ones. The logs mentioned in this template do not exist.

[ProjectOutfox.MainLog.2023-01-17--09.21.49.log](https://github.com/TeamRizu/OutFox/files/10437899/ProjectOutfox.MainLog.2023-01-17--09.21.49.log)
[ProjectOutfox.Crash.2023-01-17--09.21.49.log](https://github.com/TeamRizu/OutFox/files/10437900/ProjectOutfox.Crash.2023-01-17--09.21.49.log)
[ProjectOutfox-default.ThemeLua.2023-01-17--09.21.50.log](https://github.com/TeamRizu/OutFox/files/10437901/ProjectOutfox-default.ThemeLua.2023-01-17--09.21.50.log)
[ProjectOutfox.MainLog.2023-01-17--08.52.14.log](https://github.com/TeamRizu/OutFox/files/10437902/ProjectOutfox.MainLog.2023-01-17--08.52.14.log)
[ProjectOutfox.Crash.2023-01-17--08.52.14.log](https://github.com/TeamRizu/OutFox/files/10437903/ProjectOutfox.Crash.2023-01-17--08.52.14.log)

### How can you reproduce the error?

1. Start the game
2. Go to song wheel
3. Select a song
4. Sometimes it will crash here (usually within 2-3 songs)

### Game Mode

dance

### Additional Information

Macbook Air 2022, M2, Ventura 13.1

**Comment by Scraticus** [comment]
Fixed in 4.19
