### ISSUE TITLE
[Feature Request] Allow ScreenSelectMusic to set a global 'preview' song to hide that a song has more than one sound source

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows10 Pro

### CPU

i5-7500 3.4GHz

### GPU

GeForce GTX 1060 6GB

### Storage

SSD

### Game Version

4.18.1

### Game Mode

dance

### Theme

Default(Soundwaves)

### Describe the problem

If a piece has a different sound source for each difficulty level, it is reflected in the preview when the difficulty level is switched on the song selection screen
StepMania5 previews globally configured sound sources, so the behavior is different from Project OutFox
Most of the music I own is treated as a hidden element with different sound sources for different difficulty levels, so it would be a spoiler if it were reflected in ScreenSelectMusic
If this is the intended behavior, it would be great to be able to change the behavior to be similar to StepMania5 in the theme settings!

`SSC File where the phenomenon occurs`
```
#VERSION:0.83;
#TITLE:Song Title;
#SUBTITLE:;
#ARTIST:Artist;
...
#CDTITLE:;
#MUSIC:global.ogg;
...
//---------------dance-single - ----------------
#NOTEDATA:;
#CHARTNAME:;
#STEPSTYPE:dance-single;
#DESCRIPTION:;
#CHARTSTYLE:;
#DIFFICULTY:Easy;
#METER:1;
#MUSIC:easy.ogg;
...

//---------------dance-single - ----------------
#NOTEDATA:;
#CHARTNAME:;
#STEPSTYPE:dance-single;
#DESCRIPTION:;
#CHARTSTYLE:;
#DIFFICULTY:Medium;
#METER:5;
#MUSIC:medium.ogg;
...
```

`StepMania5`
- Select Easy -> Played `global.ogg`
- Select Medium -> Played `global.ogg`

`Project OutFox`
- Select Easy -> Played `easy.ogg`
- Select Medium -> Played `medium.ogg`

**Comment by Scraticus** [comment]
As far as i'm aware, not many people use this feature on SM5, but we'll add an option or metric for it, and let you know.

Thanks for reporting!

**Comment by JoseVarelaP** [comment]
Currently looking at this. I have an implementation made that performs this with a ThemeMetric of the following name:
```ini
[ScreenSelectMusic]
PlayChartPreviewMusic=true
```

This could also be a Preference, so it can apply to all themes at once.

https://github.com/TeamRizu/OutFox/assets/23246027/ee40c280-03a1-408e-8828-d539a22e3f9f
