### ISSUE TITLE
[FIXED] [BUG] Pressing the Effect UP/DOWN key in ScreenGameplay changes the speed of the song

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows10 Pro

### CPU

i5-7500 3.4GHz

### GPU

GeForce GTX 1060 6GB

### Storage

SSD

### Game Version

4.18.1

### Game Mode

dance

### Theme

Default(Soundwaves)
[WAIEI CitMin](https://sm.waiei.net/citmin/)

### Describe the problem

When I press the key set to Effect UP in ScreenGameplay, the song accelerates and when I press the Effect DOWN key, it decelerates
If this behavior is only in the default theme, then it is not a problem, but this phenomenon occurs in all themes
Even if this is a feature implemented for debugging purposes, it is still unusual behavior for the long note display to be corrupted as shown in the attached image
I would like the behavior of the Effect UP/DOWN keys during the game to be configurable on the theme side
<br>
![effect_up_down_long_notes](https://user-images.githubusercontent.com/8708955/215013917-627d68f9-deb2-4a2a-a419-76602cd19516.jpg)

### Describe what should happen

The fix I am hoping for is to allow the behavior of the Effect UP/DOWN keys to be controlled by the theme
As for the long note display being corrupted, either is fine

**Comment by JoseVarelaP** [comment]
Ah yes, this is more of a result oversight of the rate mod fix. [This effect was introduced in upstream for the SoundEffect mod](https://github.com/stepmania/stepmania/blob/984dc8668f1fedacf553f279a828acdebffc5625/src/SoundEffectControl.cpp), which would use these buttons to slow/speed up the song and zoom in/out holds respectively.

I'll take this one to fix.
