### ISSUE TITLE
[FIXED] [BUG] CombobreakOnImmediateHoldLetGo is not working

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows10 Pro

### CPU

i5-7500 3.4GHz

### GPU

GeForce GTX 1060 6GB

### Storage

SSD

### Game Version

4.18.1

### Game Mode

dance

### Theme

Themes inheriting from fallback

`metrics.ini`
```ini
[Global]
FallbackTheme=_fallback

[Player]
ComboBreakOnImmediateHoldLetGo=true
```

### Describe the problem

Even if I set CombobreakOnImmediateHoldLetGo to true, it is not reflected and there is no way to disconnect the combo when it is NG on Hold/Roll

It was working in Alpha 4.6.0, so it seems to have stopped working in some later version

(Was Long mine implemented after that? My guess is that it stopped working when Long mine was implemented)

I have an issue that may be slightly related to this, so I'll need to check that out as well
#594

### Describe what should happen

When ComboBreakOnImmediateHoldLetGo is true, if Hold/Roll is NG, the combo is disconnected

**Comment by JoseVarelaP** [comment]
Seems this feature was commented out because it was colliding with pump functionality. Would need to do testing to see if it doesn't break that mode when bringing it back.
