### ISSUE TITLE
[Unexpected Behavior] Disabling "loop music on select music" doesn't work

### ISSUE THREAD

**Issue by SHRMP0** [TeamRizu/OutFox#65]
**What you're using**

The experimental setting for disabling the preview audio isn't working.

**Expected behavior**

No looping on music selection screens.

**Comment by SHRMP0** [comment]
Here's my logs in advance, they might be also useful for issue #66 
[Logs.zip](https://github.com/TeamRizu/OutFox/files/5078305/Logs.zip)

**Comment by Scraticus** [comment]
This is likely an overlooked theme issue in the engine, thanks for reporting!

**Comment by Scraticus** [comment]
Please test this when we get 4.8.0, i _think_ we've fixed this, but please confirm on your machine

**Comment by SHRMP0** [comment]
Still happening on 4.8.2, unfortunately.

**Comment by SHRMP0** [comment]
Still present on 4.8.5

**Comment by JoseVarelaP** [comment]
Made a fix for the next version.
