### ISSUE TITLE
[FIXED] [BUG] Demonstration can't find steps

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows10 Pro

### CPU

i5-7500 3.4GHz

### GPU

GeForce GTX 1060 6GB

### Storage

SSD

### Game Version

4.18.1

### Game Mode

I was using the editor!

### Theme

Themes inheriting from fallback

`metrics.ini`
```ini
[Global]
FallbackTheme=_fallback

[ScreenInit]
NextScreen="ScreenDemonstration"

[ScreenDemonstration]
NextScreen="ScreenInit"
TimerSeconds=5
AllowStyleTypes="OnePlayerOneSide"
```

### Describe the problem

Even when a song is present, ScreenDemonstration gives "No matching steps found." (ja: 条件に適合する譜面が見つかりませんでした。) and the demo is skipped
I have confirmed that this phenomenon occurs in both 4.18.1 and 4.19 (test version)

### Describe what should happen

If the game mode is Dance, a 4-panel steps is selected

### Relevant Log output

[ProjectOutfox.Crash.2023-01-29--21.24.13.log](https://github.com/TeamRizu/OutFox/files/10529797/ProjectOutfox.Crash.2023-01-29--21.24.13.log)
[ProjectOutfox.MainLog.2023-01-29--21.24.13.log](https://github.com/TeamRizu/OutFox/files/10529798/ProjectOutfox.MainLog.2023-01-29--21.24.13.log)
[ProjectOutfox-sample.ThemeLua.2023-01-29--21.24.14.log](https://github.com/TeamRizu/OutFox/files/10529799/ProjectOutfox-sample.ThemeLua.2023-01-29--21.24.14.log)

**Comment by JoseVarelaP** [comment]
Probably related with #625. The demonstration screen would present this situation of non-available steps.

**Comment by Scraticus** [comment]
Fixed in 042
