### ISSUE TITLE
[Game Crash] Crash on Title Screen view

### ISSUE THREAD

**Issue by asc6** [TeamRizu/OutFox#652]
### Describe the crash

When booting up the OutFox and viewing the outfox into with the demo songs, if it is left playing for about 3 hours then it will crash unexpectedly. 
This is on a new installation of OutFox-0.4.18.1LTS on Raspbian 11 (Bullseye) on aarch64.

CoinMode is set to Free Play if that matters. No mods or themes are used outside of what is standard in the latest release.
Any help would be greatly appreciated.

### How can you reproduce the error?

1. Start the game
2. Don't do anything
3. Wait about 3 hours
4. Crash

### Screenshots/Videos

[ProjectOutfox-default.ThemeLua.2023-02-03--14.06.33.log](https://github.com/TeamRizu/OutFox/files/10590563/ProjectOutfox-default.ThemeLua.2023-02-03--14.06.33.log)
[ProjectOutfox.Crash.2023-02-03--14.06.30.log](https://github.com/TeamRizu/OutFox/files/10590587/ProjectOutfox.Crash.2023-02-03--14.06.30.log)
[ProjectOutfox.MainLog.2023-02-03--14.06.30.log](https://github.com/TeamRizu/OutFox/files/10590589/ProjectOutfox.MainLog.2023-02-03--14.06.30.log)

### Game Mode

None

### Additional Information

The notable log line from the crash seems to be: 
`2023/02/03 17:21:03 969807	FATAL [global.cpp->void sm_crash(const char*):16]	
*******	 EXIT trigger caused by LOG(FATAL) entry: 
"[Project Outfox] Crash Reason: unimplemented
`

**Comment by Scraticus** [comment]
how much memory you running on your pi?
