### ISSUE TITLE
[Feature Request] Send keystrokes to Kafka

### ISSUE THREAD

**Issue by sderosiaux** [TeamRizu/OutFox#653]
### Please Select the game mode your feature request is about.

dance

### Is your feature request related to a problem?

I'd love to analyze my keystrokes in real-time :)

### Describe the solution you'd like

This is a bit off topic, but I thought I'd ask.

I've been a big fan of Stepmania for 15 years, and now Outfox on macOS. As an engineer, I'm also a big fan of Apache Kafka. I'd like to reconcile both worlds and be able to configure Outfox to have a Kafka sink (a Kafka topic) to send all keystrokes in realtime and "status" (status, accuracy, etc.) to do some processing and blogging for fun (I run a company). Is this even conceivable?

**Comment by Sudospective** [comment]
i think this might interfere with being able to sign macos builds, sounds like a hook and afaik apple doesnt allow that under a license agreement?

**Comment by Scraticus** [comment]
yea, we cannot do this one as it would be basically keylogging, and that's against the Apple ToS. Gatekeeper is a fickle thing as it is.
