### ISSUE TITLE
Raspi 4 2GB: libusb-0.1.so.4: internal error

### ISSUE THREAD

**Issue by Geriatric6883** [TeamRizu/OutFox#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Arch Linux ARM

### CPU

ARM Cortex-A72

### Game Version

4.18.1

### Game Mode

dance

### Theme

default

### Describe the problem

`./OutFox: error while loading shared libraries: /home/fam/OutFox-alpha-0.4.18.1-arm32v7-date-20221101/./libusb-0.1.so.4: internal error`

I've used this on ALARM32 (and Raspbian) successfully somewhat recently, ~last summer. The aarch64 version is working on my other Pi 4 running ALARM64.

`ldd OutFox` from the OutFox dir shows the same error. I have `usbutils` and `libusb-compat` installed. I tried with/without those packages installed, and replacing OutFox's libusb-0.1.so.4 with a symlink to my /usr/lib/libusb file (keeping the 01s04 name). Tried both the arm32 LTS and legacy versions.

Any idea what might be going wrong here?

**Comment by Scraticus** [comment]
fixed in 4.19, which should be uploaded within the hour.
