### ISSUE TITLE
[BUG] No audio at all

### ISSUE THREAD

**Issue by EvieUwU** [TeamRizu/OutFox#658]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### CPU

Ryzen 7 5800X

### GPU

RTX 2060

### Storage

Samsung 860 EVO 1TB SSD

### Game Version

4.18.1

### Game Mode

dance

### Describe the problem

There is no audio at all, in menus, while playing songs etc.
Could possibly be a specific issue with my system, my audio device is a Corsair VOID Pro Wireless. ICue could also be an issue, as I've heard from other games that it can mess with some stuff.

### Describe what should happen

Audio should play.

### Relevant Log output

[ProjectOutfox.Crash.2023-03-10--07.56.50.log](https://github.com/TeamRizu/OutFox/files/10939824/ProjectOutfox.Crash.2023-03-10--07.56.50.log)
[ProjectOutfox.MainLog.2023-03-10--07.45.42.log](https://github.com/TeamRizu/OutFox/files/10939825/ProjectOutfox.MainLog.2023-03-10--07.45.42.log)
[ProjectOutfox.MainLog.2023-03-10--07.48.51.log](https://github.com/TeamRizu/OutFox/files/10939827/ProjectOutfox.MainLog.2023-03-10--07.48.51.log)
[ProjectOutfox.MainLog.2023-03-10--07.56.50.log](https://github.com/TeamRizu/OutFox/files/10939828/ProjectOutfox.MainLog.2023-03-10--07.56.50.log)
[ProjectOutfox-default.ThemeLua.2023-03-10--07.45.43.log](https://github.com/TeamRizu/OutFox/files/10939829/ProjectOutfox-default.ThemeLua.2023-03-10--07.45.43.log)
[ProjectOutfox-default.ThemeLua.2023-03-10--07.48.52.log](https://github.com/TeamRizu/OutFox/files/10939830/ProjectOutfox-default.ThemeLua.2023-03-10--07.48.52.log)
[ProjectOutfox-default.ThemeLua.2023-03-10--07.56.50.log](https://github.com/TeamRizu/OutFox/files/10939831/ProjectOutfox-default.ThemeLua.2023-03-10--07.56.50.log)
[ProjectOutfox.Crash.2023-03-10--07.44.41.log](https://github.com/TeamRizu/OutFox/files/10939832/ProjectOutfox.Crash.2023-03-10--07.44.41.log)
[ProjectOutfox.Crash.2023-03-10--07.45.20.log](https://github.com/TeamRizu/OutFox/files/10939833/ProjectOutfox.Crash.2023-03-10--07.45.20.log)
[ProjectOutfox.Crash.2023-03-10--07.45.42.log](https://github.com/TeamRizu/OutFox/files/10939834/ProjectOutfox.Crash.2023-03-10--07.45.42.log)
[ProjectOutfox.Crash.2023-03-10--07.48.51.log](https://github.com/TeamRizu/OutFox/files/10939835/ProjectOutfox.Crash.2023-03-10--07.48.51.log)

**Comment by Scraticus** [comment]
can you go into your preference file and change the 'debuglevel' to 0 and run again and post the 'mainlog' again

I think your system is requesting things it shouldn't, but i need to be sure

**Comment by EvieUwU** [comment]
Is this /Save/Preferences.ini or a different preferences file? If i set debuglevel=0 in /Save/Preferences.ini, it gets removed on startup.

**Comment by Scraticus** [comment]
its the save/preferences yea, is the game closed when you edit the prefs file? it uses an old fashioned way to edit so can overwrite it

**Comment by EvieUwU** [comment]
The game is closed when I edit it, once I open the game then it gets removed. The file gets updated once the main menu is opened.

I don't think it's changed, but heres the log file once its been run with debuglevel=0
[ProjectOutfox.MainLog.2023-03-11--13.03.22.log](https://github.com/TeamRizu/OutFox/files/10948575/ProjectOutfox.MainLog.2023-03-11--13.03.22.log)

**Comment by Scraticus** [comment]
how many sound cards do you have on your system?

**Comment by EvieUwU** [comment]
I've only got one audio device, the rest are disabled.

**Comment by EvieUwU** [comment]
I believe I only have one sound card, as my headset uses a USB dongle to connect.

**Comment by EvieUwU** [comment]
Even with a regular wired speaker, no audio is outputted despite OutFox showing up in the volume mixer.

**Comment by Scraticus** [comment]
could you set the 'SoundDevice=' to 1 and see if you get audio through your headphones when they are plugged in? 

We may need you to come into the discord so we can give some technical assistance in the voice channel to help you out

**Comment by EvieUwU** [comment]
Still no audio, I'm in the discord already: @EvieUwO#6483

**Comment by EvieUwU** [comment]
This was fixed by using SoundDevice=0, Windows was offering the correct Device ID, had a chat with squirrel.

**Comment by Scraticus** [comment]
Marking this one as solved
