### ISSUE TITLE
[Unexpected Behavior] #SAMPLESTART #SAMPLELENGTH values being ignored

### ISSUE THREAD

**Issue by SHRMP0** [TeamRizu/OutFox#66]
**What you're using**

The #SAMPLESTART and #SAMPLELENGTH values are not being used in some simfiles, which results the preview to always play from beginning of the audio file when the experimental setting "sample mode" is set to "normal", "last song" or "continuous" (it works as intended in "screen music").

**Expected behavior**

Use the values set in #SAMPLESTART and #SAMPLELENGTH on all simfiles.

**Comment by SHRMP0** [comment]
Also, as noticed by Omicron on Discord, charts affected by this issue always have their graphs for "Complexity" and "Flow" maxed out while "Jumps/Hands" to be working fine:

![2020-08-15_021257](https://user-images.githubusercontent.com/61925574/90305843-347c1400-de9d-11ea-8fe6-1c93780e69a5.png)
(for reference, this is a pump chart)

**Comment by SHRMP0** [comment]
BTW, judging from a quick look I took at my logs, it seems like the affected simfiles are mentioned in some errors during loading (however, except for the preview bug, they play just fine), so this one might be related to #68

**Comment by SHRMP0** [comment]
Looks like it's fixed on 4.8.2

**Comment by Scraticus** [comment]
Can you confirm if this is solved ?

**Comment by SHRMP0** [comment]
Everything's working as intended now, thanks!
