### ISSUE TITLE
[FIXED - Implemented][Feature Request] Add empty screen class with OptionsList (ScreenWithOptionsList)

### ISSUE THREAD

**Issue by SheepyChris** [TeamRizu/OutFox#661]
### Please Select the game mode your feature request is about.

All Game Modes

### Is your feature request related to a problem?

I'm unable to utilize the OptionsList menu system outside of ScreenSelectMusic, which brings issues when using a custom Lua music wheel in a theme.

### Describe the solution you'd like

Essentially the title for this request, would be similar in nature to ScreenWithMenuElements but with the addition of OptionsList.

**Comment by Scraticus** [comment]
The def.Optionslist is available from 042, but we'll work with you to ensure it properly functions before releasing 042. Thanks for the idea!

**Comment by Scraticus** [comment]
Fixed in 042
