### ISSUE TITLE
[Nitpick] taiko playfield not looking like the original game

### ISSUE THREAD

**Issue by freshleaf1095** [TeamRizu/OutFox#664]
### Game Mode

taiko

### Give an example of what is wrong

The taiko playfield is being flipped vertically, with notes scrolling upward
<img width="722" alt="Screenshot 2023-03-29 at 0 14 28 PM" src="https://user-images.githubusercontent.com/70712987/228433250-641f4e52-4384-448a-aabf-d78aaa3b87c3.png">

### Give an example of what it should look like

It should be modified to be horizontal, with notes scrolling to the left
<img width="896" alt="Screenshot 2023-03-29 at 0 18 11 PM" src="https://user-images.githubusercontent.com/70712987/228433804-694f6f3d-482d-4471-8c05-d6b262b6ae61.png">

**Comment by JustMoneko** [comment]
This is a known issue with LTS4.18, that has been fixed in newer test builds. For now you can try using a different theme or get a test build from Discord.

**Comment by Scraticus** [comment]
Fixed in 4.19 / Alpha V, thanks for reporting!
