### ISSUE TITLE
[FIXED] [Feature Request] Adjust GetNoteData to return correct note type with holds

### ISSUE THREAD

**Issue by Sudospective** [TeamRizu/OutFox#666]
### Please Select the game mode your feature request is about.

All Game Modes

### Is your feature request related to a problem?

Currently, when using notedata, all holds return "TapNoteSubType_Hold". There is no way to access information about the type of tail a hold or roll has. This information is potentially useful for themes, noteskins, and modfiles.

### Describe the solution you'd like

Adjusting the way GetNoteData returns the notedata table to account for newer hold and roll types is an ideal solution.

**Comment by JoseVarelaP** [comment]
Giving a shot at this, currently I have the output to show this:
```lua
return {
	{4.000000,1,"TapNoteSubType::TapNoteSubType_Hold","TapNote_4th",group = "TapNoteGroupType_Normal",length = 4.000000},
	{8.000000,2,"TapNoteSubType::TapNoteSubType_Hold","TapNote_4th",group = "TapNoteGroupType_Mine",length = 4.000000},
	{12.000000,3,"TapNoteSubType::TapNoteSubType_Hold","TapNote_4th",group = "TapNoteGroupType_Normal",length = 4.000000},
	{16.000000,3,"TapNoteType::TapNoteType_LongNoteTail","TapNote_4th",group = "TapNoteGroupType_Lift"},
}
```

The way it works is that the `group` item for this data set is present for all the items. However, the change here is that if there is a **Lift Hold** present, the lift note itself will be added to the table of items as a separate entity to ease parsing.

However, I'm open for suggestions about this implementation.

**Comment by Sudospective** [comment]
this looks straightforward to me, and it seems like it keeps in line with previous specs, i agree with it
