### ISSUE TITLE
[BUG] GLAD renderer breaks certain themes

### ISSUE THREAD

**Issue by dude98** [TeamRizu/OutFox#667]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### Game Version

4.18.1

### Game Mode

dance

### Theme

ITG3-encore latest

### Describe the problem

using GLAD renderer and beating a song completely breaks rendering, muddling up textures, camera angles, and doesn't fix until it hits the USB Profiles attract screen, temp fixing it.
nothing shows up related to this in the logs.
Note: any version of outfox does this, alpha 5's steam and non-steams do it too.

### Describe what should happen

GLAD or openGL shouldn't matter, i should be able to play with either one without problem.

**Comment by JoseVarelaP** [comment]
We just found out what the bug is. This is old bug in SM 3.x which affects Multitexture and it using old D3D texture mapping which cause the processing of drawing a model to break itself.

**Comment by Scraticus** [comment]
Fixed in 4.19 /Alpha V 0.5.0-pre041 (when it gets pushed next week)
