### ISSUE TITLE
[FIXED] [BUG] Song:GetBGChanges() does not work

### ISSUE THREAD

**Issue by waiei** [TeamRizu/OutFox#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 11 Pro

### CPU

i5-12400F

### GPU

GeForce RTX 3060

### Storage

SSD

### Game Version

4.18.1

### Game Mode

dance

### Theme

WAIEI CitMin / Soundwaves

### Describe the problem

The version was not listed, so "4.18.1" was specified, but the correct version is "4.19"

The return value of GetBGChanges in Song Class is always an empty table

Example: `ScreenGameplay overlay/default.lua`
```lua
OnCommand = function(self)
    SCREENMAN:SystemMessage(Serialize(GAMESTATE:GetCurrentSong():GetBGChanges()))
end
```

`5.1 / OutFox 4.18.1`
![image](https://user-images.githubusercontent.com/8708955/232264487-e77a4c7b-f817-435f-8290-0ddf85ef5eeb.png)

`4.19`
![image](https://user-images.githubusercontent.com/8708955/232264500-9f03176d-a7e2-4d78-8e4f-dd96e750bebb.png)

**Comment by Scraticus** [comment]
Fixed in 042
