### ISSUE TITLE
[BUG] Nested AFTs scale actors in odd ways.

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#669]
This has been an issue I've seen for some time but wasn't sure if should report it.
I'm currently on latest Steam release. (20230307)

Context: bitEye is a library I made to preview BGA's and backgrounds and have quick access on ScreenEdit for charters. It previews backgrounds creating an AFT texture and works fine until the scripts of a BGA contain AFTs (like beat4sprite scripts). So it becomes a case of an AFT within an AFT and it ends up scaling the actors in unexpected ways.

Pay attention to the green overlay. 
https://i.imgur.com/FD8At99.png (when the AFT texture is invisible or alpha 0)
https://i.imgur.com/tIRR5yR.png (when the AFT texture is visible)

**Comment by EngineMachiner** [comment]
> do you have the code for this library? how does it set up the aft?

https://github.com/EngineMachiner/bitEye

**Comment by EngineMachiner** [comment]
I have run some tests and I have noticed that it has to do with the main AFT having different dimensions / size compared to the nested ones.

**Comment by EngineMachiner** [comment]
Ok it seems fine until the resolution of the first AFT is bigger than the screen size, comparing SCREEN_WIDTH * 2, SCREEN_HEIGHT * 2 to SCREEN_WIDTH and SCREEN_HEIGHT.

**Comment by Sudospective** [comment]
to me that sounds like the aft context is bigger than the sprite its displaying on, which sounds like its doing what i would expect it to do, it may not be a bug if this is the case

**Comment by EngineMachiner** [comment]
Indeed, I just put the BUG tag because I wasn't sure. I basically am using the same screen size for these cases so I don't have to deal with the offset but I wanted to report it to check up the intended behaviour or what alternatives there are.

**Comment by Scraticus** [comment]
Can you confirm this is still an issue for me?

**Comment by EngineMachiner** [comment]
I just did the tests on latest test build and the green overlay of the pics I posted doesn't seem to be offset or scaled anymore and the actors seem to be positioned according to their own AFT. Good job. We can close this now.
