### ISSUE TITLE
Unable to Run 4.8.1 in Catalina 

### ISSUE THREAD

**Issue by ajsteadm** [TeamRizu/OutFox#67]
(This is PianoGal from Discord, but I'm rarely there.)

I am unable to run the new build (4.8.1) on either of my MacBooks, both running Catalina 10.15.6.

After install and security bypass, app gave noteskin error, so I ran xattr as directed in wiki (this has been successful for me for 4.6.0 on both machines). 

After this: 
On my newer machine (2020 MBP), app shows Stepmania in menu bar briefly but never opens.
log.txt reads:
00:00.013: StepMania5.3-git-24199dfb28
00:00.013: Compiled 20200814 @ 17:29:15 (build 24199dfb28)
00:00.013: Log starting 2020-08-14 22:36:56
00:00.013:  
00:00.013: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.014: Reading 'Data/Static.ini' failed: No such file or directory
00:00.014: Reading 'Data/Static.ini' failed: No such file or directory
00:00.221: Outfox Engine: SDL Subsystem Initialised.
00:00.221: OutFox Engine: Initializing Discord SDK
00:00.223: OutFox Engine: Core Creation Returned: Failed With Error:  4
/////////////////////////////////////////
00:00.223: WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting
/////////////////////////////////////////
00:00.239: Loading window: win32

On my older machine (2014 MBAir), app initially crashed and gave the Mac crash log pasted below, so I attempted to fix by reinstalling libpng as described here: https://github.com/trevorsandy/lpub3d/issues/57

After which app behaves exactly like it does on my newer Mac, menus in the menu bar very briefly, but does not open.
log.txt from older machine:
00:00.029: StepMania5.3-git-24199dfb28
00:00.029: Compiled 20200814 @ 17:29:15 (build 24199dfb28)
00:00.030: Log starting 2020-08-14 22:29:25
00:00.030:  
00:00.030: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.031: Reading 'Data/Static.ini' failed: No such file or directory
00:00.031: Reading 'Data/Static.ini' failed: No such file or directory
00:00.269: Outfox Engine: SDL Subsystem Initialised.
00:00.269: OutFox Engine: Initializing Discord SDK
00:00.270: OutFox Engine: Core Creation Returned: Failed With Error:  4
/////////////////////////////////////////
00:00.270: WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting
/////////////////////////////////////////
00:00.307: Loading window: win32

Mac Diagnostic Report:
Process:               StepMania [3971]
Path:                  /Volumes/VOLUME/*/StepMania.app/Contents/MacOS/StepMania
Identifier:            com.StepMania-5
Version:               5.3.0 (5.3.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           StepMania [3971]
User ID:               501

Date/Time:             2020-08-14 18:10:48.586 -0400
OS Version:            Mac OS X 10.15.6 (19G73)
Report Version:        12
Anonymous UUID:        E1E5C232-F7DF-332D-8B17-CD228DECD359

Sleep/Wake UUID:       229324AA-9E5A-4D83-90A9-5BDCC4B39E9F

Time Awake Since Boot: 23000 seconds
Time Since Wake:       3700 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/X11/*/libpng16.16.dylib
  Referenced from: /Volumes/VOLUME/*/StepMania.app/Contents/MacOS/StepMania
  Reason: image not found

Binary Images:
       0x108c9a000 -        0x109664ff7 +com.StepMania-5 (5.3.0 - 5.3.0) <DBF3560E-C091-3CF8-BE7C-29F126368C1F> /var/folders/*/StepMania.app/Contents/MacOS/StepMania
       0x109bc4000 -        0x109c8dfff +libswscale.5.dylib (0) <CBA2EABF-34B8-3DC1-9A72-522CE683329D> /var/folders/*/StepMania.app/Contents/Libs/libswscale.5.dylib
       0x109c9e000 -        0x10bbf5f87 +libavcodec.58.dylib (0) <93C40761-BCD4-3556-8C81-4553C6F454C6> /var/folders/*/StepMania.app/Contents/Libs/libavcodec.58.dylib
       0x10c564000 -        0x10cd2bfcf +libavformat.58.dylib (0) <A0CA606C-DF46-3F0C-9AE8-FF1A22C6894F> /var/folders/*/StepMania.app/Contents/Libs/libavformat.58.dylib
       0x10cd9c000 -        0x10ce00fff +libavutil.56.dylib (0) <054B115C-AD12-3B67-9F67-7E79DD323FD3> /var/folders/*/StepMania.app/Contents/Libs/libavutil.56.dylib
       0x10d255000 -        0x10d2e6f47  dyld (750.6) <34A11073-9E4C-38C3-9293-7D566ABAE8B6> /usr/lib/dyld
    0x7fff28ad6000 -     0x7fff28cd1ff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff28ebe000 -     0x7fff28ebefff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff2b62c000 -     0x7fff2b70dffa  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <6BD0970D-7FD8-341D-8D82-0B3BBB565462> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2b70f000 -     0x7fff2b70ffff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <C8F9CC56-F7CF-3E77-B6FC-BD8E1D19FA92> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff2beb1000 -     0x7fff2beb1fff  com.apple.Carbon (160 - 162) <FB72FB7D-5985-3D9C-82DB-A729FCA1249A> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff2c395000 -     0x7fff2c395fff  com.apple.Cocoa (6.11 - 23) <2F5C8ABA-711F-316C-BB97-921122AEE4DF> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff2c784000 -     0x7fff2cc8dffb  com.apple.audio.CoreAudio (5.0 - 5.0) <F816D92C-9408-3279-90BC-C23B69DC75AE> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff2d237000 -     0x7fff2d6b6feb  com.apple.CoreFoundation (6.9 - 1677.104) <C0D70026-EDBE-3CBD-B317-367CF4F1C92F> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff2e457000 -     0x7fff2e532ffc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff2e61f000 -     0x7fff2e61ffff  com.apple.CoreServices (1069.24 - 1069.24) <AA140158-E909-34C2-B2F5-20EBC93E0056> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff2f24a000 -     0x7fff2f28effb  com.apple.CoreVideo (1.8 - 344.3) <2F1DC859-A2E4-3983-8047-97BC0E8C55CE> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff2f8f1000 -     0x7fff2f8f3ff3  com.apple.ForceFeedback (1.0.6 - 1.0.6) <8A03B5DC-258F-3321-82A7-0B6AA8BEF484> /System/Library/Frameworks/ForceFeedback.framework/Versions/A/ForceFeedback
    0x7fff2f8f4000 -     0x7fff2fcb9fff  com.apple.Foundation (6.9 - 1677.104) <2EF4C4DA-423B-3AFE-ACD1-7DAE64E47603> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3002d000 -     0x7fff300d1ff3  com.apple.framework.IOKit (2.0.2 - 1726.140.1) <31CA30A9-B32D-37A8-B5C8-20999D5D51BF> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff327ae000 -     0x7fff32878fff  com.apple.Metal (212.8 - 212.8) <7A496C57-4ECE-337F-96D4-09F24C033913> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff37db9000 -     0x7fff37dc8ff7  com.apple.opengl (17.10.22 - 17.10.22) <E75C69AE-61EA-32D5-B58D-30022D68CC66> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff38d86000 -     0x7fff39009ffb  com.apple.QuartzCore (1.11 - 841.4) <FE927B0E-BD49-32CC-8A55-90F553C86C15> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff39b8a000 -     0x7fff39ed3ff1  com.apple.security (7.0 - 59306.140.5) <EB9E9E2A-B53B-36EE-B9CE-EEB99B603CB1> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff3af35000 -     0x7fff3b2b8ff4  com.apple.VideoToolbox (1.0 - 2625.9) <6CF18E28-A7A8-3952-8171-7E4FF4FB37FA> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff6430a000 -     0x7fff6430bfff  libSystem.B.dylib (1281.100.1) <001B3B7F-D02C-31D3-B961-1ED445D5A266> /usr/lib/libSystem.B.dylib
    0x7fff645e3000 -     0x7fff645effff  libbz2.1.0.dylib (44) <14CC4988-B6D4-3879-AFC2-9A0DDC6388DE> /usr/lib/libbz2.1.0.dylib
    0x7fff650e3000 -     0x7fff651d3fff  libiconv.2.dylib (59) <18311A67-E4EF-3CC7-95B3-C0EDEE3A282F> /usr/lib/libiconv.2.dylib

Model: MacBookAir6,2, BootROM 122.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 1.4 GHz, 4 GB, SMC 2.13f15
Graphics: kHW_IntelHD5000Item, Intel HD Graphics 5000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x02FE, 0x45424A3230554638454455302D474E2D4620
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x02FE, 0x45424A3230554638454455302D474E2D4620
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.1)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD0128F, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

**Comment by Scraticus** [comment]
Hiya Piano, we are looking into this one, as we don't actually use libpng anymore in the game. I would try to redownload and see if that fixes it, as we have quite a few players on catalina and big sur that loaded this build ok. I will leave this open for @JoseVarelaP to look into

**Comment by ajsteadm** [comment]
Thanks, I tried a reinstall today after uninstalling and deleting all the library/preference files I could find. It's giving me the same behavior on my old machine (haven't tried the new one yet today).

log.txt: 
00:00.017: StepMania5.3-git-24199dfb28
00:00.018: Compiled 20200814 @ 17:29:15 (build 24199dfb28)
00:00.018: Log starting 2020-08-15 11:33:31
00:00.018:  
00:00.018: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.018: Reading 'Save/Preferences.ini' failed: No such file or directory
00:00.018: Reading 'Save/Preferences.ini' failed: No such file or directory
00:00.018: Reading 'Data/Static.ini' failed: No such file or directory
00:00.205: Outfox Engine: SDL Subsystem Initialised.
00:00.205: OutFox Engine: Initializing Discord SDK
00:00.207: OutFox Engine: Core Creation Returned: Failed With Error:  4
/////////////////////////////////////////
00:00.207: WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting
/////////////////////////////////////////
00:00.235: Loading window: win32

Is there an uninstall guide for MacOS somewhere, maybe there's something I'm missing that's tripping up my new install?

**Comment by garfieldnate** [comment]
I'm also having this issue. The way I install is to create a new directory in the Applications directory and copy all of the dmg contents in there; not sure if that's the recommended way, but that's the only way I could figure out.

**Comment by garfieldnate** [comment]
4.8.0 is also broken; 4.6.0 works fine, though.

**Comment by Scraticus** [comment]
Fixed in 4.8.0 thanks for the report guys

**Comment by nicolasguary01** [comment]
What a pity, I have just had this exact same error, as ajsteadm and garfielnate. Also I installed the same way as garfieldnate.

The error is : 

nico@MacBook-Pro-de-MBP MacOS % ./StepMania        
StepMania5.3-git-26c3f027e8
Compiled 20201031 @ 14:53:35 (build 26c3f027e8)
Log starting 2020-11-18 03:55:26
/////////////////////////////////////////
WARNING: OutFox Engine: Failed to initialise Discord SDK Core! - Exiting
/////////////////////////////////////////
Loading window: sdl
Fatal: crash from within the crash signal handler

Hardware/software in use :

Mac book pro macOS Catalina 10.15.7

So, it seems it is not a file corruption problem at download?
Good luck and thank you.
