### ISSUE TITLE
[BUG] NoteCrossMessageCommands falsely counts end of hold as a step

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10 Home 64-bit (22H2)

### CPU

AMD Ryzen 5 5600

### GPU

AMD Radeon RX 6600

### Storage

256GB M.2 NVMe & 2+4TB WD Black HDD

### Game Version

4.19.0

### Game Mode

dance

### Theme

itg3encore (or whichever other theme uses those MessageCommands)

### Describe the problem

In OutFox, both on 0.4.19 (20230414) and PlayTest (20230307), the end of a hold (potentially even a roll) is being counted as a step in both [NoteCrossed] & [NoteWillCross].
If there is a normal note AND the end of a hold at that point, it counts as a jump in [NoteCrossedJump].

### Describe what should happen

In SM5.1 & ITGMania, the above mentioned problem doesn't occur.
A video recording has been provided down below in "Relevant Log output".
The same theme was used everywhere (via mklink), making this an engine issue.

### Relevant Log output

https://www.youtube.com/watch?v=X1mTdCCutTk

**Comment by Scraticus** [comment]
Hiya!

Thanks for the report! It seems the dance code is not checking correctly for the ends as this is a feature in other modes (lift-hold/lift-roll etc). We'll add the check and fix this in the 4.19.1 build coming shortly, well spotted.

**Comment by JoseVarelaP** [comment]
Added the check.

https://user-images.githubusercontent.com/23246027/235785216-c27bc26b-fff1-49d9-985d-4eff90ea9a9d.mp4
