### ISSUE TITLE
[FIXED - Implemented][Feature Request] Native MetaData Tags for ParaPara Mode

### ISSUE THREAD

**Issue by SilentTempest83** [TeamRizu/OutFox#672]
### Please Select the game mode your feature request is about.

para

### Is your feature request related to a problem?

Additional MetaData is useful for parapara files to credit music sources, video sources, choreography source, dancers etc. that are not normally credited as part of a simfile for other modes.

Charts created for EKS-D ParaMania currently utilize #ORIGIN to credit the source parapara video, and #CREDIT to credit the music source.

### Describe the solution you'd like

Please add native MetaData tags to credit parapara dancers and choreography source.  Something like: #PARADANCERS and #PARACHOREO

Tags can then be referenced by individual themes that wish to display this meta data

### Describe alternatives you've considered

EKS-D ParaMania currently stores this information in an external INI file within the individual song folders

**Comment by Scraticus** [comment]
We have added a new #Metadata tag for SSC for this, i'll explain more when Alpha V 042 comes out, but thanks for your report!

**Comment by Scraticus** [comment]
Fixed, Added a new metadata tag, will be in new release out today
