### ISSUE TITLE
[FIXED] [BUG] halt and slow debug options did not respect the master game clock and were non-functioning

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10 Home 64-bit (22H2)

### CPU

AMD Ryzen 5 5600

### GPU

AMD Radeon RX 6600

### Storage

256GB M.2 NVMe & 2+4TB WD Black HDD

### Game Version

5.0.0-041

### Game Mode

dance

### Theme

everything since engine

### Describe the problem

The title is pretty much self-explanatory since the game does this (F3+F5+3) literally while everything in the background still reacts (in sounds only | no screen transitions in the background, though).

### Describe what should happen

It says "halt" not "freeze the whole game".
The visual halting might have been put at the wrong position inside the code, maybe?

### Relevant Log output

The log actually registers whenever its back to "DEBUG: Halt - off" again, but nothing else changes/everything is still visually halted.
I also noticed this when I first got access to the Steam Playtest but waited for an update (on a4/aIV not a5/aV).

**Comment by Scraticus** [comment]
So what are you asking for here?

"Halt" halts what exactly in your vision of this?

I haven't checked if the codebase has been changed, but I can say this hasn't function been touched at this time, so does SM do this as well? Something else may have broken it, which is entirely possible of course!

Thanks for reporting, let me know what it should be doing in a bit more detail, 'self-explanatory' means nothing when the context isn't given, you need to describe it so we do not spent ages trying to understand your point of view. It's much easier to us if you spend a few lines explaining it, so we can then check and marry up the differences, and then fix the issue if there is a problem.

Happy to keep recieving bug reports, but try to include more detail, i'll await your reply before allocating this one.

**Comment by DarkBahamut162** [comment]
Sorry for the inconclusive bug report. I might have been a bit too frustrated with certain things at that time.
But doing this now correctly only made things worse:

StepMania included certain debug functionalities for testing purposes (for various things for various reasons).
This include the [Slow] and [Halt] function, probably for slowing and stopping any and all animations currently taking place.
For some reason, OutFox screws those up, especially on Alpha V (which takes [Halt] a bit too literally).
I even did a video showing off what should happen (the NotFox half) as well as what had happened (the OutFox half).
One will even see why I say "worse" once it gets to the OutFox section because it doesn't even slow properly if not at all.

https://www.youtube.com/watch?v=cTeZ1MsMZqM
I only used the non-steam version of 0.5 but that shouldn't matter since both act the same (in terms of what's shown in the video)

Also: The functions themselves may not have been changed, but what they are calling outside of it most likely might. How else would this not be a bug then?
I really do hope this suffices since I'm unable to pull one entire essay about this ouf of nothing.

**Comment by Scraticus** [comment]
I never said it wasn't a bug, clearly something isn't acting as it should here, so your video is a much clearer representation of what is broken. 

Thanks for taking the time to record a video, we'll get on fixing this

**Comment by Scraticus** [comment]
Had a quick look, you're right, we skip the check in the gameloop since we optimised the clocks. We'll add a similar system that behaves as this to match the old behaviour.

Thanks a lot for being thorough mate.

**Comment by Scraticus** [comment]
This is now fixed, I didn't rehook the functions to the master game clock so they were pretty much ignored by the game.

Will be out in 042 final

Thanks for reporting.

**Comment by Scraticus** [comment]
Fixed in 042 released later today, thanks for reporting
