### ISSUE TITLE
[FIXED] [BUG] OutFox-AlphaV-0.5.0-pre041 Enciso0720 graphics glitch

### ISSUE THREAD

**Issue by makoflagkk** [TeamRizu/OutFox#676]
### Is there an existing issue for this?

- [x] I have searched the existing issues and none matched.

### Operating System

Windows 11

### Game Version

5.0.0-041

### Game Mode

I was using the editor!

### Theme

Curling's DDR A3 Theme & DDR  XX -starlight- Custom Mix

### Describe the problem

When I use dancestages and it has a bgvideo to it, the dancestages becomes very dark and the graphics glitch. This will also effect the characters model being used. Very dark and the textures become distorted too.

### Describe what should happen

This should be patched in the next release.

**Comment by Scraticus** [comment]
There was a rendering issue which made some of the sources black when used with this theme. We have fixed that part of it, but will not be coding support as this system has been changed in favour of the more aligned model list moving forward.

**Comment by makoflagkk** [comment]
👍
