### ISSUE TITLE
[Fixed?] [BUG] Game doesnt start after setting display mode to a secondary monitor (OpenGL legacy cannot start a buffer bigger than 1080p on a secondary monitor)

### ISSUE THREAD

**Issue by NaGeL182** [TeamRizu/OutFox#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### CPU

12th Gen Intel Core i9-12900K

### GPU

NVIDIA GeForce RTX 3080 Ti

### Storage

WDC WDS100T2B0C-00PXH0

### Game Version

5.0.0-041

### Game Mode

dance

### Theme

Default

### Describe the problem

I changed the graphic settings here, from this:
![OutFox_9bJe0hfujt](https://github.com/TeamRizu/OutFox/assets/598533/4ce97a77-4aaf-4b9c-9d12-62a9cd482610)
to this:
![OutFox_V2BGOiyZqy](https://github.com/TeamRizu/OutFox/assets/598533/6e1773fe-2bb7-4151-aee3-92bc46c584cf)
and it works when I set it like that:
![OutFox_xGz0ieOjVT](https://github.com/TeamRizu/OutFox/assets/598533/7ffe4f44-ff56-4b32-9529-1fadb6bbb7c8)
![OutFox_HtgQgmUEe4](https://github.com/TeamRizu/OutFox/assets/598533/8d725b1e-5098-4592-872e-e46837e85b31)

but as soon as I exit and start it again it just hangs up and never starts...
![dwm_3G9JPANqC6](https://github.com/TeamRizu/OutFox/assets/598533/666bed68-82dd-4c73-9c87-2403227f1b6e)

and until I delete the prefrences.ini it wont start.

### Describe what should happen

the program starts as norrmal

### Relevant Log output

[ProjectOutfox.Crash.2023-05-13--20.46.10.log](https://github.com/TeamRizu/OutFox/files/11470354/ProjectOutfox.Crash.2023-05-13--20.46.10.log)
[ProjectOutfox.Crash.2023-05-13--20.49.05.log](https://github.com/TeamRizu/OutFox/files/11470355/ProjectOutfox.Crash.2023-05-13--20.49.05.log)
[ProjectOutfox.MainLog.2023-05-13--20.46.10.log](https://github.com/TeamRizu/OutFox/files/11470356/ProjectOutfox.MainLog.2023-05-13--20.46.10.log)
[ProjectOutfox.MainLog.2023-05-13--20.49.05.log](https://github.com/TeamRizu/OutFox/files/11470357/ProjectOutfox.MainLog.2023-05-13--20.49.05.log)
[ProjectOutfox.Network.2023-05-13--20.46.11.log](https://github.com/TeamRizu/OutFox/files/11470358/ProjectOutfox.Network.2023-05-13--20.46.11.log)
[ProjectOutfox.Network.2023-05-13--20.49.06.log](https://github.com/TeamRizu/OutFox/files/11470359/ProjectOutfox.Network.2023-05-13--20.49.06.log)
[ProjectOutfox-default.ThemeLua.2023-05-13--20.46.11.log](https://github.com/TeamRizu/OutFox/files/11470360/ProjectOutfox-default.ThemeLua.2023-05-13--20.46.11.log)
[ProjectOutfox-default.ThemeLua.2023-05-13--20.49.06.log](https://github.com/TeamRizu/OutFox/files/11470361/ProjectOutfox-default.ThemeLua.2023-05-13--20.49.06.log)

**Comment by Scraticus** [comment]
could you go into your preferences.ini and set 'LogLevel=0' and run through this again so we get the detailed log outputs, I am not sure why this would cause a problem, but thanks for reporting it, and i'll definitely look into it when you post the detailed logs, 

Thanks so much

**Comment by NaGeL182** [comment]
[ProjectOutfox.Crash.2023-05-13--22.55.55.log](https://github.com/TeamRizu/OutFox/files/11470559/ProjectOutfox.Crash.2023-05-13--22.55.55.log)
[ProjectOutfox.MainLog.2023-05-13--22.55.55.log](https://github.co
[ProjectOutfox.Network.2023-05-13--22.55.56.log](https://github.com/TeamRizu/OutFox/files/11470561/ProjectOutfox.Network.2023-05-13--22.55.56.log)
m/TeamRizu/OutFox/files/11470560/ProjectOutfox.MainLog.2023-05-13--22.55.55.log)
[ProjectOutfox-default.ThemeLua.2023-05-13--22.55.56.log](https://github.com/TeamRizu/OutFox/files/11470562/ProjectOutfox-default.ThemeLua.2023-05-13--22.55.56.log)

the thing is the same thing happens with the 0.4.1 version that I candoenload from the site.

**Comment by Scraticus** [comment]
can you check your post? i cannot grab any of these mate

**Comment by NaGeL182** [comment]
Sorry fixed it.

**Comment by Scraticus** [comment]
thanks

**Comment by Scraticus** [comment]
Sorry for the delay on replying about this one, it looks like your system needs to use the GLAD renderer over the opengl (legacy) one, and you may need to use the drivers from nvidia's site instead of the crap ones microsoft installs for you. If you need further help, pop into the discord, and we can walk you through what needs to be done if needed :) you can just look for 'squirrel' in there.

I've fixed some things for newer GPU's in newer test builds of outfox alpha V, which makes things a bit better for windows users, but if you can try a test build in the server, that would be ace as well to know your issue is solved.

**Comment by Scraticus** [comment]
i'll keep this open for now, but let me know if you can test or not :)

**Comment by Scraticus** [comment]
Fixed in 042, use glad, it'll sort you. Reopen if you have issues! :)
