### ISSUE TITLE
[BUG] "Not an executable", RPi400, v20230501

### ISSUE THREAD

**Issue by artofthesmart** [TeamRizu/OutFox#680]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Raspbian for Raspberry Pi400

### Storage

SSD

### Game Version

5.0.0-041

### Game Mode

I was using the editor!

### Describe the problem

Spent a couple hours trying to get this working and I can't figure it, so I think there might be a bug here.

---
- Raspberry Pi 400
- `uname -a`: Linux raspberrypi 6.1.21-v8+ aarch64 GNU/Linux
---

Steps to reproduce:
1.  Create raspberry pi SSD with Pi Imager v1.7.4 using `other` > `Raspberry Pi OS (64-bit)`.
2.  Boot with that SSD allow disk to resize, and run `update` and `upgrade`.
3.  Download Outfox for Linux/Pi ([Here](https://github.com/TeamRizu/OutFox/releases/download/OF5.0.0-041/OutFox-AlphaV-0.5.0.0-pre041-Linux-amd64-modern-date-20230501.tar.gz))
4.  Untar and rename directory to `outfox`.
5.  Move from downloads folder to `/home/user` directory.
6.  Open a terminal and `cd outfox; ./outfox`.

!FAILS!
Output:
> bash: ./outfox: cannot execute binary file: Exec format error.

7.  Try running `ldd outfox` on the executable.

!FAILS!
Output:
> "not a dynamic executable"

### Describe what should happen

Should launch the application.

**Comment by Scraticus** [comment]
https://github.com/TeamRizu/OutFox/releases/download/OF5.0.0-041/OutFox-AlphaV-0.5.0.0-pre041-Linux-amd64-modern-date-20230501.tar.gz <-- AMD64 is for intel and arm chips, you want the one which has armv8 on it, which... i have not built yet.


Use the LTS version until 42, I completely forgot to build the arm builds, my bad
