### ISSUE TITLE
[FIXED][NOTABUG] Badly encoded Background videos play earlier than expected, due to modern FFMPEG not respecting B Frame H264 in AVI Flags

### ISSUE THREAD

**Issue by jerrymxy** [TeamRizu/OutFox#682]
### Is there an existing issue for this?

- [x] I have searched the existing issues and none matched.

### Operating System

Windows 11 Pro 22H2 64bit

### CPU

Intel Core i7-12700H

### GPU

NVIDIA GeForce RTX3060 Laptop

### Storage

40GB DDR5 Memory + 1TB internal SSD + 2TB external SSD

### Game Version

5.0.0-041

### Game Mode

dance

### Theme

SoundWaves-default

### Describe the problem

Some background videos and music don't start playing at the same time. Videos play a bit earlier than normal. Happens in both 0.4.19 LTS (2023-04-15) and 0.5.0-pre041.
This issue doesn't happen in StepMania 5.1.

Here are some links to the simfiles that will cause the issue (They are from the same song pack and I don't have the same problem in other packs):
https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=51745
https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=56914
https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=53156

**Comment by Scraticus** [comment]
right, so i actually added an episode from the bluray to check this simfile as the video seemed really off, and the BGCHANGES vs the actual anime is around 4seconds out.

![image](https://github.com/TeamRizu/OutFox/assets/11047768/4407f351-42df-4289-94f5-2ab2ef5d9f7f)

however, giving the video a re-encode so it has the proper timing included, fixes the issue.

![image](https://github.com/TeamRizu/OutFox/assets/11047768/27b0039b-d9a4-4e32-9b24-07b0e83527e1)

A simple open in avidemux, let it reconstruct, resave, solves the video issue, as i cannot obviously upload videos on this platform.

Sadly not everyone encodes their BGAs equally, so if we cannot get a proper timing segment, it won't load. We do not use the same FFMPEG as 5.1, (it uses FFMPEG 2.x where we're on 4.x).

Hope that helps and apologies we can't do anything more.

**Comment by Scraticus** [comment]
Closed in 042
