### ISSUE TITLE
[FIXED][BUG] Bad #LASTBEATHINT values from legacy versions of StepMania3 to 3.5 were causing the song to automatically end and jump to the result page on alphav

### ISSUE THREAD

**Issue by jerrymxy** [TeamRizu/OutFox#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 11 Pro 22H2 64bit

### CPU

Intel Core i7-12700H

### GPU

NVIDIA GeForce RTX3060 Laptop

### Storage

40GB DDR5 Memory + 1TB internal SSD + 2TB external SSD

### Game Version

5.0.0-041

### Game Mode

dance

### Theme

alphav-dance

### Describe the problem

After entering gameplay, it automatically jumps to the result page without pressing any key. Only happens in alphav-dance theme. They works fine in StepMania 5.1 and SoundWaves theme.

Some simfiles in [issue#682](https://github.com/TeamRizu/OutFox/issues/682) will cause this problem, for example:
Redirect to result page in a few seconds:
https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=56914
Redirect immediately:
https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=51745

I can't tell if these two issues are caused by the same reason so I open a new issue.

**Comment by Scraticus** [comment]
good catch, these charts have bad coded #LASTBEATHINT entries which is a throwback from 3.9's editor, which we have added back support for in other game modes, so we'll need to fix them

**Comment by Scraticus** [comment]
Fixed in 042, i've put a check in to see if #LASTBEATHINT is under 20 seconds, it'll not write it to the cache, so the song should play properly. It seems there was a bug way back in SM3's days that had a weird way of filling that tag. Since 3.9, it has not been used, so with OutFox adding support for it again these bugs have come to light.

Thanks for reporting!

**Comment by Scraticus** [comment]
Fixed in 042 which is released today
