### ISSUE TITLE
[FIXED] [BUG] classic negative-bpm warps don't work

### ISSUE THREAD

**Issue by jummy0** [TeamRizu/OutFox#688]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

windows 10

### CPU

Intel Core i7-7500U @ 2.7 GHz

### GPU

Radeon R7 M445

### Storage

1 TB HDD (WDC WD10JPVX-75JC3T0)

### Game Version

5.0.0-041

### Game Mode

dance

### Theme

default

### Describe the problem

old-style warps using negative bpm are either ignored or treated as positive (unsure which).  noticed on "Romeo and Cinderella" charted by Gpop, on "Vocaloid Project Pad Pack 3rd".

an excerpt from the sm file:
`#BPMS:0.000=170.000,190.000=-170.001,194.000=170.000;`
this is expected to play normally until beat 190, instantly skip 4 beats forward, then continue from beat 194.
what really happens is that an 8 beat gap gets inserted at beat 190. the song continues and the notes end 8 beats after the audio.

logs:
[info.txt](https://github.com/TeamRizu/OutFox/files/11990657/info.txt)
[ProjectOutfox.Crash.2023-07-08--06.24.07.log](https://github.com/TeamRizu/OutFox/files/11990658/ProjectOutfox.Crash.2023-07-08--06.24.07.log)
[ProjectOutfox.MainLog.2023-07-08--06.02.06.log](https://github.com/TeamRizu/OutFox/files/11990659/ProjectOutfox.MainLog.2023-07-08--06.02.06.log)
[ProjectOutfox.MainLog.2023-07-08--06.24.07.log](https://github.com/TeamRizu/OutFox/files/11990660/ProjectOutfox.MainLog.2023-07-08--06.24.07.log)
[ProjectOutfox.Network.2023-07-08--06.02.12.log](https://github.com/TeamRizu/OutFox/files/11990661/ProjectOutfox.Network.2023-07-08--06.02.12.log)
[ProjectOutfox.Network.2023-07-08--06.24.10.log](https://github.com/TeamRizu/OutFox/files/11990662/ProjectOutfox.Network.2023-07-08--06.24.10.log)
[ProjectOutfox-default.ThemeLua.2023-07-08--06.02.12.log](https://github.com/TeamRizu/OutFox/files/11990663/ProjectOutfox-default.ThemeLua.2023-07-08--06.02.12.log)
[ProjectOutfox-default.ThemeLua.2023-07-08--06.24.10.log](https://github.com/TeamRizu/OutFox/files/11990664/ProjectOutfox-default.ThemeLua.2023-07-08--06.24.10.log)

**Comment by Scraticus** [comment]
These are fixed in a21 of Alpha V's next 042 release (if you want to pretest, then use the alpha5-test-builds in the discord)

Also be wary when re-rating old SM files, as a lot of the older warping/gimmicks may not be saved as expected from really old charts.

**Comment by Scraticus** [comment]
fixed in 042
