### ISSUE TITLE
[Unexpected Behavior] The new loading window isn't registered by the windows manager ?

### ISSUE THREAD

**Issue by KaeMame** [TeamRizu/OutFox#69]
My windows manager (I think that's Gnome (gdm3)) on Ubuntu doesn't "keep track" of the new loading window. If I switch focus I can't find the window back (not sure if it makes sense. To put it otherwise, I can't ALT-tab to it, it isn't shown in the list).

Pretty minor issue but I doubt it is on purpose so I thought I should report it.

Latest release (Stepmania-Outfox-Alpha-4.8.1-amd64-date-20200814)
Ubuntu 20.04.1 LTS (uname -a says `Linux blah 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`)

On Windows 10 things work as expected (from the very beginning it is possible to ALT-tab to it, and a few seconds later I could see it registered in the taskbar). The window is not responsive, though (Windows says "Not Responding", also it is actually not responding even after a minute of loading many songs), I think that's because I ALT-tabbed out of it.

**Comment by Scraticus** [comment]
The loading window is actually classified by the windows manager as a 'utility window' so doesn't really show on the task bar for this reason. The lockup is due to the MP3 driver, which i've just fixed, so thank you for this bug report. Closes #68 and this issue.
