### ISSUE TITLE
[FIXED] [BUG] [PUMP] Long Note Heads count as Tap Notes instead of CheckpointsHit

### ISSUE THREAD

**Issue by thedaryen** [TeamRizu/OutFox#691]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 11

### CPU

i5 12600k

### GPU

RTX 3070

### Storage

1TB GAMMIX NVME SSD

### Game Version

5.0.0-041

### Game Mode

pump

### Theme

Infinitesimal

### Describe the problem

Outfox is inaccurate when counting notes on [pump] mode. Basically, it counts the very beginning of each long note as a Tap Note instead of a Checkpoint Hit. This makes it so that calculating grades and displaying number of notes to the user returns innacurate results.

A good way to test this behavior is by creating a chart comprised only of long notes. If you FC it, the TapNoteScore_CheckpointHit should return the exact number of perfects you have. However, that's not what happens. Instead TapNoteScore_CheckpointHit returns the number of Perfects minus the number of long note heads, since these are being counted as taps.

### Describe what should happen

When [pump] game mode is selected, Long notes should always count 100% as CheckpointsHit and never as tap notes. When FCing a chart comprised 100% of long notes, it should return a count of 100% CheckpointsHit and 0 Tap Notes. 

P.S.: Also, as a minor adjustment, when previewing number of notes of a chart in Pump Mode, Holds should return the total number of possible CheckpointsHit. 
Edit.: Actually, looking at Pump it Up Infinity, which is Stepmania based, when previewing chart stats, it also seems to count Holds once per Hold regardless of the number of perfects they give. Since K-Pump doesn't ever give chart stats, for display purposes that's really a design choice more than anything. But when it comes to score calculations, It'd be VERY useful to have a variable counting exactly how many "long note perfects" the user got.

**Comment by Scraticus** [comment]
Fixed in 042
