### ISSUE TITLE
[FIXED - Implemented] [Feature request] Add support for pump-style behavior for Miss Combo (Miss Combo resets on any non-miss judgement)

### ISSUE THREAD

**Issue by thedaryen** [TeamRizu/OutFox#693]
### Please Select the game mode your feature request is about.

pump

### Is your feature request related to a problem?

On Pump it Up, Goods (SM "Decents") will work like Decents on Hit Combos, maintaining the combo without adding to it, but on Miss Combos they will break them. Bads work like "Way-Offs" in the sense that they break your Hit Combo, but instead of keeping a Miss Combo going they also break those.

Misses combos on Pump it Up are comprised exclusively of misses and will reset to 0 on any judgement different from a miss.

Currently, this unsupported on Outfox (alpha V build from 05-08-2023)

### Describe the solution you'd like

When pump gamemode is active, just follow the Pump standard and make it so that any judgement different from TapNoteScore_Miss resets a Miss Combo Count to 0, while also allowing the lowest tier of judgement ("Bad") to break an active Hit Combo and the second-to-lowest ("Good") to maintain an active Hit Combo.

### Describe alternatives you've considered

I tried changing various combinations of 'TapNoteScore_' on the following attributes on metrics.ini for testing purposes, but couldn't get it to work like pump does. The defaults from _fallback are as follows:

MinScoreToContinueCombo=ComboContinue()
MinScoreToMaintainCombo=ComboMaintain()
MaxScoreToIncrementMissCombo='TapNoteScore_Miss'

It seems that whatever you set as the MinScoreToMaintainCombo will affect both Misses Combos and Hit Combos.

So you either have tiers breaking both types of combos, or maintaining both. It'd be nice to have an option to change said behavior.

**Comment by andreycout** [comment]
Tested it and it's fixed in alpha-V: build a15 (11-08-2023). Goods and Bads now reset the Misses Combo if playing Pump Gamemode and using a Pump Timing Mode.

**Comment by Scraticus** [comment]
Fixed in 042
