### ISSUE TITLE
[FIXED] [Feature Request] Favorite Songs

### ISSUE THREAD

**Issue by Scraticus** [TeamRizu/OutFox#699]
### Discussed in https://github.com/TeamRizu/OutFox/discussions/235

<div type='discussions-op-text'>

<sup>Originally posted by **fabb** January 11, 2021</sup>
**Is your feature request related to a problem? Please describe.**

I have a large library and would like to find my favorite songs quickly.

**Describe the solution you'd like**

It would be cool if songs could be marked as favorite, and later quickly be found with a filter.

**Describe alternatives you've considered**

Currently it's just possible to copy favorite songs to a custom group with a file manager, but that's impractical when playing the game with dance pads in front of the TV.
</div>

**Comment by Scraticus** [comment]
Added to Game

**Comment by Scraticus** [comment]
fixed in 042 coming out today

**Comment by CZyMfnIPC** [comment]
@Scraticus how do you favorite?

**Comment by Joehuu** [comment]
Not them, but here (you press select (`/`) in song select):
![Kapture 2023-12-27 at 11 02 24](https://github.com/TeamRizu/OutFox/assets/35318437/c61090af-6f00-4051-ab18-31959146e7fb)

![Kapture 2023-12-27 at 11 04 27](https://github.com/TeamRizu/OutFox/assets/35318437/e63d3c8a-1e4a-444b-9907-fc74e81699d6)

**Comment by CZyMfnIPC** [comment]
> Not them, but here (you press select (`/`) in song select)

Thank you!!! I never knew about song select!
