### ISSUE TITLE
[Unexpected Behavior] Controller mappings are lost on exit (for some controllers only)

### ISSUE THREAD

**Issue by Kaede573** [TeamRizu/OutFox#70]
Test setup:
Stepmania 5.3-git-24199dfb28 (latest at the time of writing this)
Ubuntu 20.04.1 LTS
L-Tek dance pad (4k USB dance pad)

To reproduce:
- plug USB dance pad. Start Stepmania
- map the pad (and configure Key/Joy mappings for testing...). Check it works as expected ingame.
- restart Stepmania (exit completely and relaunch). Start any song. Test input.
- => inputs do not work, mappings were lost

To try to further delimit the problem I have done some additional testing:
a) Tested 100% clean installs (no profiles, portable installs (Portable.ini)) of 4.6 (Stepmania 5.3-git-7d67243eaa) vs 4.8 (Stepmania 5.3-git-24199dfb28).
=> it looks like I cannot reproduce the issue on 4.6, the mappings are never lost.
b) Tested with another controller (Logitech game pad F310 (also Xinput))
=> the mappings for that controller are not lost - so this seems to be controller-specific ?
c) Tried to create and use profiles
=> doesn't change anything.

I can test this on Windows 10 if needed.

EDIT: will attach a log later today

**Comment by ScottBrenner** [comment]
Kind of related - I've just updated to the latest version on Windows 10 and it seems I need to unplug/plugin my L-TEK pad each time I open the game for inputs/mappings to work.

**Comment by Scraticus** [comment]
This looks like lua is not storing some key records correctly. I'll check and report back, we do need the log so i can see what the input system is doing though. @ScottBrenner you can post your log here if you wish

**Comment by KaeMame** [comment]
I'd provide a log but I cannot seem to map the L-Tek pad anymore (on latest), now I get a crash every time I exit the mapping screen, after configuration. I have try to download fresh binaries (100% clean install / no profiles, etc.), it still happens. The only thing I haven't tried is restarting my OS.

**Comment by Scraticus** [comment]
@Kaede573 can you confirm if this is fixed on the pre-alpha you're testing?

**Comment by Kaede573** [comment]
Yes it is: controller working out of the box, no crashes on exiting mapping screen, also if I do remap to specific virtual pad button (for instance Button X) it is saved on exit/restart. Thanks !

**Comment by Scraticus** [comment]
Fixed in 4.8.0, thanks for reporting!
