### ISSUE TITLE
[FIXED] [BUG] StepF2 simfile parsing missing effects

### ISSUE THREAD

**Issue by SheepyChris** [TeamRizu/OutFox#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

MX Linux 23

### Game Version

5.0.0-041

### Game Mode

pump

### Theme

Infinitesimal on alpha-v branch (commit dbbedc6)

### Describe the problem

The Single 20 chart on GOODBOUNCE (file attached below) has a couple of high BPM changes (100000000.000000 to be exact) that are supposed to act like warps, however the behavior is currently ignored and causes bad parsing/unwanted arrows.

[GOODBOUNCE.zip](https://github.com/TeamRizu/OutFox/files/12388521/GOODBOUNCE.zip)

Video demonstration here: https://cdn.discordapp.com/attachments/925893137157718066/1142840974058475721/2023-08-20_11-21-01.mp4

### Describe what should happen

The effect should be parsed so that the extra notes aren't affecting gameplay nor the charting sequence should be interrupted.

### Relevant Log output

[ProjectOutfox.MainLog.2023-08-20--11.03.25.log](https://github.com/TeamRizu/OutFox/files/12388528/ProjectOutfox.MainLog.2023-08-20--11.03.25.log)

**Comment by Scraticus** [comment]
Fixed in 042
