### ISSUE TITLE
[FIXED][BUG] On Pump, holding one note of a longnote chord stops Miss Combos from progressing

### ISSUE THREAD

**Issue by thedaryen** [TeamRizu/OutFox#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 11

### CPU

i5 12600k

### GPU

RTX 3070

### Storage

1TB GAMMIX NVME SSD

### Game Version

5.0.0-041

### Game Mode

pump

### Theme

Infinitesimal and Soundwaves

### Describe the problem

Pump Long Notes on OutFox have innacurate behavior when it comes to "chords" (long notes comprised of multiple arrows). 

Pump correct behavior: When multiple buttons need to be held on Pump, failing to hold even one of them will have the exact same result as failing to hold all of them: you'll start comboing misses. Visually you'll see which ones you're holding correctly (the arrow receptors picks them up), but the judgement will not give you any perfect, positive score or life for doing so if you're not getting all of them.

OutFox current behavior: it seems that holding one of the notes of the chord will stop the Miss Combo from progressing. You'll still be hit with multiple misses, but it seems that the game is awarding you with a Checkpoint Hit and resetting the Miss Combo every tick because of the one button you're getting correctly. Also, on Infinitesimal, you might get some perfects by holding just one of the notes (couldn't reproduce this bit on Soundwaves because that theme doesn't count each long note tick as a real perfect for evaluation purposes like Infinitesimal does)

### Describe what should happen

Holding one note of a longnote chord shouldn't give the player any benefit in Pump. You're either holding all the notes and getting perfects, or you're missing at least one and getting misses.

### Relevant Log output

To better illustrate the situation, I'll leave a video I recorded comparing the behavior between StepP1 (which has accurate long note behavior) and Infinitesimal. it's not the same chart on both videos mind you, I just quick edited on each one so the notecount doesn't match but you can get the idea.

https://www.youtube.com/watch?v=C1fbZxIC_nk

Also will leave you with that very poor edit I made for quick testing purposes (just a long note chord and the song ends lol)

https://drive.google.com/file/d/1kpmXiMZZHWVp5JWrLyyVzz4yiR-bAaYU/view?usp=sharing

**Comment by JoseVarelaP** [comment]
Fixed.
(This recording is from a previous iteration which didn't calculate the misses from the notes, which has already been addressed too)

https://github.com/TeamRizu/OutFox/assets/23246027/6f5e2d94-582c-41a6-863f-f6ad070ba730

**Comment by Scraticus** [comment]
fixed in 043
