### ISSUE TITLE
[BUG] Mute Actions key has no debounce

### ISSUE THREAD

**Issue by JustMoneko** [TeamRizu/OutFox#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Win11

### CPU

AMD

### GPU

RTX3050L

### Storage

ssd

### Game Version

5.0.0-041

### Game Mode

dance

### Theme

Every theme I think

### Describe the problem

Pressing the Pause key on the keyboard mutes the actions and then instantly unmutes them.
Seems like it has no debounce, as it will toggle on/off when held.

### Describe what should happen

Pressing Pause once should toggle Mute Actions once

**Comment by JoseVarelaP** [comment]
Yes, can confirm. The mute actions button doesn't have a check to only change when its the first press, so it'll always change it while held.
