### ISSUE TITLE
[BUG] Taiko Mode -- Red notes can't be hit

### ISSUE THREAD

**Issue by AstralDreamZ** [TeamRizu/OutFox#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### CPU

Intel Core i-5 10400F CPU @2.90GHz

### GPU

NVidia GeForce GTX 1660 Super

### Storage

1TB Hard Drive running everything for OutFox

### Game Version

5.0.0-041

### Game Mode

taiko

### Theme

Theme -- Infinitesimal

Theme Version -- 1.3

### Describe the problem

Plain and simple -- When playing Taiko, red (Don) notes can't be hit. I hit on beat, and they never get hit. I always miss them

Blue notes (Ka) work as they should, only the reds aren't functioning correctly

### Describe what should happen

When I hit the red notes, they should disappear upon being hit, like the blue notes do.

### Relevant Log output

[ProjectOutfox.MainLog.2023-10-30--13.08.42.log](https://github.com/TeamRizu/OutFox/files/13206460/ProjectOutfox.MainLog.2023-10-30--13.08.42.log)
[ProjectOutfox.MainLog.2023-10-30--14.34.37.log](https://github.com/TeamRizu/OutFox/files/13206462/ProjectOutfox.MainLog.2023-10-30--14.34.37.log)
[ProjectOutfox.Network.2023-10-30--13.04.48.log](https://github.com/TeamRizu/OutFox/files/13206463/ProjectOutfox.Network.2023-10-30--13.04.48.log)
[ProjectOutfox.Network.2023-10-30--13.08.42.log](https://github.com/TeamRizu/OutFox/files/13206464/ProjectOutfox.Network.2023-10-30--13.08.42.log)
[ProjectOutfox.Network.2023-10-30--14.34.40.log](https://github.com/TeamRizu/OutFox/files/13206465/ProjectOutfox.Network.2023-10-30--14.34.40.log)
[ProjectOutfox-default.ThemeLua.2023-10-30--00.23.52.log](https://github.com/TeamRizu/OutFox/files/13206466/ProjectOutfox-default.ThemeLua.2023-10-30--00.23.52.log)
[ProjectOutfox-Infinitesimal-13.ThemeLua.2023-10-30--13.08.42.log](https://github.com/TeamRizu/OutFox/files/13206467/ProjectOutfox-Infinitesimal-13.ThemeLua.2023-10-30--13.08.42.log)
[ProjectOutfox-Infinitesimal-13.ThemeLua.2023-10-30--14.34.40.log](https://github.com/TeamRizu/OutFox/files/13206468/ProjectOutfox-Infinitesimal-13.ThemeLua.2023-10-30--14.34.40.log)
[info.txt](https://github.com/TeamRizu/OutFox/files/13206469/info.txt)
[ProjectOutfox.Crash.2023-10-30--00.23.51.log](https://github.com/TeamRizu/OutFox/files/13206470/ProjectOutfox.Crash.2023-10-30--00.23.51.log)
[ProjectOutfox.Crash.2023-10-30--12.54.46.log](https://github.com/TeamRizu/OutFox/files/13206471/ProjectOutfox.Crash.2023-10-30--12.54.46.log)
[ProjectOutfox.Crash.2023-10-30--13.04.47.log](https://github.com/TeamRizu/OutFox/files/13206472/ProjectOutfox.Crash.2023-10-30--13.04.47.log)
[ProjectOutfox.Crash.2023-10-30--13.08.42.log](https://github.com/TeamRizu/OutFox/files/13206473/ProjectOutfox.Crash.2023-10-30--13.08.42.log)
[ProjectOutfox.Crash.2023-10-30--14.34.37.log](https://github.com/TeamRizu/OutFox/files/13206474/ProjectOutfox.Crash.2023-10-30--14.34.37.log)
[ProjectOutfox.MainLog.2023-10-30--13.04.47.log](https://github.com/TeamRizu/OutFox/files/13206475/ProjectOutfox.MainLog.2023-10-30--13.04.47.log)

**Comment by Scraticus** [comment]
Infinitessimal doesn't support taiko and never will lol, i don't think this is something that can be fixed
