### ISSUE TITLE
[BUG] 4 simultaneous inputs not supported, even during 2 player mode

### ISSUE THREAD

**Issue by GamerOn117** [TeamRizu/OutFox#713]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 11

### Game Version

5.0.0-041

### Game Mode

dance

### Describe the problem

I wanted to try my two hands playing the default chart at the same time, but when it came time for both players to do a jump, both players got misses. This may have something to do with an internal limit on the number of inputs registering at a time.

### Describe what should happen

The game should be continuously looking at all inputs and not cap out at seeing two of them.

**Comment by Scraticus** [comment]
what are you playing on? membrane keyboards can sometimes exhibit this behaviour, can you confirm the button pressing by going to the Options -> input -> test input and press a number of keys and see if you see more than 4+ being shown on the screen

**Comment by Jousway** [comment]
most laptop keyboards dont have nkro its a hardware limit on your end

**Comment by Scraticus** [comment]
You will need to get a USB keyboard, or use controllers i'm afraid, you have a laptop with the bad keyboard controller which blocks buttons on multiple presses. The page here has more information on it.

https://www.keyboardco.com/blog/index.php/2016/03/what-is-nkro-our-guide-to-rollover-anti-ghosting-and-choosing-the-right-keyboard/
