### ISSUE TITLE
[Nitpick] noshowcourse mod doesn't function properly for .crs scripts in OutFox (Soundwaves).

### ISSUE THREAD

**Issue by Gordo10776** [TeamRizu/OutFox#715]
### Game Mode

dance

### Give an example of what is wrong

If you clear the Course cache and add the "noshowcourse" mod for a song slot then load the application, the songs in the course select screen are not hidden, yet the difficulty level is hidden with a question mark.

[RANDOM ALL]

1: SONG: [Song 1] ----- DIFFICULTY: [?]
2: SONG: [Song 2] ----- DIFFICULTY: [?]
3: SONG: [Song 3] ----- DIFFICULTY: [?]
4: SONG: [Song 4] ----- DIFFICULTY: [?]

### Give an example of what it should look like

[RANDOM ALL]

1: SONG: [?????] ----- DIFFICULTY: [?]
2: SONG: [?????] ----- DIFFICULTY: [?]
3: SONG: [?????] ----- DIFFICULTY: [?]
4: SONG: [?????] ----- DIFFICULTY: [?]

**Comment by Scraticus** [comment]
which build is this for?

**Comment by Gordo10776** [comment]
> which build is this for?

3adeb80e48 a37HF11 (20231224)
![image](https://github.com/TeamRizu/OutFox/assets/130807641/fae5a9e6-e7e7-4824-97ea-69d8f5a5de03)

Here's a screenshot. The first 2 song slots have "noshowcourse", the last 2 don't.
![image](https://github.com/TeamRizu/OutFox/assets/130807641/722d99ca-5575-40f8-bcac-39ca64bcaf0e)

**Comment by JoseVarelaP** [comment]
Fixed.

<img width="1728" alt="Captura de pantalla 2024-01-26 a la(s) 11 18 09 p m" src="https://github.com/TeamRizu/OutFox/assets/23246027/a3750904-0dd8-4a94-be02-6825719f0ce0">
