### ISSUE TITLE
[FIXED] [BUG] save/upload XML files overwritten

### ISSUE THREAD

**Issue by teleshoes** [TeamRizu/OutFox#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Linux

### Game Version

5.0.0-042

### Game Mode

dance

### Theme

default

### Describe the problem

1) play a song, hit at least one note (any non-miss judgment), fail or pass the song
1) ensure XML upload file created: `Save/Upload/YYYY-MM-DD 00000.xml`
1) checksum this file
1) play a song, and do not hit ANY notes, fail or pass the song
1) a mostly-empty XML file **OVERWRITES** the just-created file `Save/Upload/YYYY-MM-DD 00000.xml`

### Describe what should happen

step (5) above should create a **NEW* mostly-empty XML file called `Save/Upload/YYYY-MM-DD 00001.xml`, and not overwrite the existing. it works this way on outfox alpha4 (and on stepmania 3.9/5.0/5.1-new/etc), and appears to be a regression in alpha5.

**Comment by Scraticus** [comment]
Confirmed, working on a fix, will be out in 043 in a week or so mate, thanks for reporting!

**Comment by Scraticus** [comment]
This is now fixed, the prealpha for this is on the discord server, as we're testing the input systems atm, so the release is delayed a touch. let me know in the discord which linux build you need and i'll build it for ya :)

**Comment by teleshoes** [comment]
awesome, thanks!

**Comment by Scraticus** [comment]
closing for 043 prep, thanks so much for reporting
