### ISSUE TITLE
[FIXED][Nitpick] TestInitialScreen=ScreenSelectMusic stopped working in 0.5

### ISSUE THREAD

**Issue by teleshoes** [TeamRizu/OutFox#719]
### Game Mode

dance

### Give an example of what is wrong

in 0.4.19, TestInitialScreen still works fine. this option has existed since before sm5.0b1, and i find it a very convenient setting.

in particular, setting the option `TestInitialScreen=ScreenSelectMusic` starts the game at the song select screen, without having to load the startup menu, select start, select game type, and select mode, which saves 6.2s for me on 0.4.19.

another use case is `ScreenTestInput`. i have a keyboard shortcut that sets this option and opens sm, handy for when im working on hardware and want to quickly test.

in 0.5 pre042, this option no longer has any effect.

### Give an example of what it should look like

it would be great if this option was restored, or replaced with user-friendly config options like `SkipMainMenu=true` or with a CLI like `./OutFox --test-input`

**Comment by Jousway** [comment]
I tested the TestInitialScreen feature in preference folder and it seems to just work, I did notice that setting it to TestInitialScreen=ScreenSelectMusic crashes the game, I've patched those crashes and it should not crash anymore.

**Comment by Scraticus** [comment]
Fixed in 043, and the latest test builds.
