### ISSUE TITLE
[FIXED] [BUG] OutFox uses windows style CRLF line breaks in Preferences.ini even on Linux systems

### ISSUE THREAD

**Issue by julianandrews** [TeamRizu/OutFox#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Linux, Mac likely also affected

### Game Version

5.0.0-042

### Game Mode

dance

### Describe the problem

When writing out `Preferences.ini` OutFox consistently uses windows-style CRLF line breaks. I'm guessing this problem also affects Macs, and likely affects any other config files written by OutFox.

While the CRLF line breaks don't outright break anything, they do make it a little obnoxious to use automated tools to manage config files since changes written with standard line breaks will get overwritten the next time OutFox runs.

It's also just a bit of a weird surprise to have a file with CRLF line breaks on a Linux system - it makes me feel like I'm back in the 90s!

I'm guessing this is a pretty simple fix. If the project were open source I'd be looking to put together a PR rather than reporting a bug.

### Describe what should happen

OutFox should use the standard line breaks for whatever platform it's running on (CRLF on windows, and LF on Mac/Linux).

**Comment by Jousway** [comment]
sadly the whole game (stepmania) is written to do \r\n and replacing that to just \n is gonna be quite annoying, we will prob do it but its not a simple replace sadly.

**Comment by bonimy** [comment]
I'm guessing std::stringstream is the approach, but the challenge will be that there are possibly thousands of strings that would need to deal with this?

**Comment by Scraticus** [comment]
This output is fixed in 043, but do check and confirm we are outputting correctly, 043 will be out in the next 2 weeks, there are test builds available in our discord as well, many thanks for reporting this.
