### ISSUE TITLE
[FIXED][BUG] Alpha V always uses Save folder in program directory for settings files, which causes issues when that directory is read-only

### ISSUE THREAD

**Issue by Maxwell-lt** [TeamRizu/OutFox#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Linux

### Game Version

5.0.0-042

### Game Mode

dance

### Describe the problem

When the OutFox install directory is read-only, the game tries and fails to create settings files in its install directory. This leads to a number of issues, such as the default theme not working correctly and an inability to make changes in the settings screen.

If the default settings files from a working OutFox install are copied into the user's `~/.project-outfox/Save` folder, the theme will no longer be broken, and it will be possible to switch themes, but there will still be issues. For example, when trying to change the timing windows from the song wheel settings menu in the Alpha V Dance theme, pressing up, down, or ESC to navigate away from that option after pressing left or right to change it will cause it to revert to the default. Many other settings will either apply only until the game is next launched, or will not apply at all.

This issue is not present on the latest Alpha 4 release (0.4.18).

### Reproduction steps:
1. Boot into some form of Linux distribution that is compatible with OutFox. A live USB environment works fine.
2. Download Alpha V 042 from the GitHub releases page.
3. Unpack the archive and set ownership to root.
```bash
$ cd /opt
$ sudo tar xvf ~/Downloads/OutFox-alpha-0.5.0-pre042-Linux-22.04-amd64-current-date-20231224.tar.gz
$ sudo mv OutFox-alpha-0.5.0-pre042-Linux-22.04-amd64-current-date-20231224 OutFox
$ sudo chown -R root:root OutFox
```
4. Launch OutFox
```bash
$ OutFox/OutFox
```

### Describe what should happen

When the game is running in non-portable mode (no `Portable.ini` file present in the program directory), all settings files including Preferences.ini and OutFoxPrefs.ini should be stored in and read from the user directory `~/.project-outfox`. The game should not attempt to create and use a Save folder inside the program directory.

### Relevant Log output

Broken theme visible on the songwheel
![image](https://github.com/TeamRizu/OutFox/assets/17859747/ad650fd5-1aa8-4abd-af43-f0695aa1ef85)

**Comment by Scraticus** [comment]
confrimed, we'll look into this one and get on fixing it

**Comment by Scraticus** [comment]
Fixed now in the pre-test builds, but can you grab one and test?

Would appreciate this being confirmed as resolved before we release.

**Comment by Maxwell-lt** [comment]
Confirmed working on 0.5.0-pre043-a13, thanks for the fix!
