### ISSUE TITLE
[FIXED][BUG] Wayland Support is broken on Linux

### ISSUE THREAD

**Issue by AstralPhnx** [TeamRizu/OutFox#729]
### Please Select the game mode your feature request is about.

All Game Modes

### Is your feature request related to a problem?

As stated in the title, some time needs to be spent developing proper Wayland support of some kind. Yes it can run under XWayland but this is far from ideal as it completely falls over when Wayland Fractional Scaling is involved making XWayland applications unable to see the full resolution of the monitor. 

With X11 slowly on the way out, I'd say it's about time Wayland support is considered.

### Describe the solution you'd like

Pretty much just proper Wayland session support that doesn't rely on XWayland. Afaik the Stepmania Project uses SDL2 to some extent and that DOES allow for spinning things up in a Wayland session seemingly but I have been unable to get this to work as of yet with the usual command switches like SDL_VIDEODRIVER=wayland. Presumably more work needs to be done for this to work out.

### Describe alternatives you've considered

Running under XWayland does work but it's far from ideal and with X11 on the way out, a proper move to supporting native Wayland sessions should be high on the priority list I believe with regards to future proofing the project.

**Comment by Scraticus** [comment]
Will get on this asap, it is about time we made the system wayland compliant.

**Comment by AstralPhnx** [comment]
> Will get on this asap, it is about time we made the system wayland compliant.

Hopefully with SDL it should make things a lot easier.

**Comment by Scraticus** [comment]
yes, i will need to remove all the ancient X11 calls in the engine and replace them with wayland aware code. we are different from mainline in this regard as we do not use a raw X11 window any longer

**Comment by AstralPhnx** [comment]
> yes, i will need to remove all the ancient X11 calls in the engine and replace them with wayland aware code. we are different from mainline in this regard as we do not use a raw X11 window any longer

Sounds like it shouldn't be AS hard to get going then. The Linux userbase will much appreciate this

**Comment by Scraticus** [comment]
I have added the preliminary support overnight tonight, and will begin testing it shortly. it will be added to a prebuild on our discord server if you wish to join it to help the effort. The game is now Wayland and XWayland aware, and i've added a better version of the kmsdrm driver for headless operations. we can get some testing down and then it can be added to the next release.

**Comment by Scraticus** [comment]
This is now actioned. You won't need to use the "SDL_VideoDriver=Wayland" switch. We have made the game Wayland aware. We also fixed kmsdrm support at the same time.

Thanks for your bug report and for supporting the project.

**Comment by Scraticus** [comment]
I'm happy to report the wayland system code has been finalised, and tested, we work fine with wayland now. 043 will be released within the next two weeks.

Thanks for your report and for getting me to get off my backside to get it done. Appreciate it.
