### ISSUE TITLE
[BUG] Crash after deleting default noteskin and then entering edit mode

### ISSUE THREAD

**Issue by bonimy** [TeamRizu/OutFox#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### CPU

Intel

### GPU

gefore 3080 ti

### Storage

2TB SSD

### Game Version

5.0.0-042

### Game Mode

I was using the editor!

### Theme

default theme

### Describe the problem

I deleted the default noteskin and added my own skins (none of which are named `default`). When I enter edit mode, the game immediately quits. The crash log does not properly mention that lack of default noteskin was the error. A warning _does_ pop up that no noteskin was found, which was a nice hint, but it does not say that this was the reason for the crash, and that the default noteskin specifically was the cause.

### Describe what should happen

Outfox should remember the last noteskin used in edit mode. If said noteskin is gone, and default noteskin is gone, it should use the first available skin. A setting in the options as to which skin to use in edit mode would be a nice-to-have

### Relevant Log output

Crash log
```
created log at: Wed May 01 09:33:04 2024
Compiled 20230414 @ 22:13:28 (build 4411ed50a9) (OS Win 10 64Bit)
2024/05/01 09:33:38 398397

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 24144

*******	STACKDUMP *******
stack dump [0]	 NoteField::Init
stack dump [1]	 ScreenEdit::Init
stack dump [2]	 ScreenEdit::CreateEditorMessage
stack dump [3]	 ScreenManager::MakeNewScreen
stack dump [4]	 ScreenManager::PrepareScreen
stack dump [5]	 ScreenManager::LoadDelayedScreen
stack dump [6]	 ScreenManager::Update
stack dump [7]	 GameLoop::RunGameLoop
stack dump [8]	 SDL_main
stack dump [9]	 main
stack dump [10]	 __scrt_common_main_seh
stack dump [11]	 BaseThreadInitThunk
stack dump [12]	 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink


FileSink shutdown at: 09:33:38 398789
```

Main log:
```
...
09:33:38	TRACE		Main Thread	Loading /Appearance/Themes/default/Sounds/Common Cancel.ogg, type FileType_Sound
09:33:38	WARNING		Main Thread	Someone set a noteskin  that doesn't exist.  Good job.
09:33:38	WARNING		Main Thread	Someone set a noteskin  that doesn't exist.  Good job.
09:33:38	WARNING		Main Thread	Someone set a noteskin  that doesn't exist.  Good job.
09:33:38	WARNING		Main Thread	Someone set a noteskin  that doesn't exist.  Good job.
09:33:38	WARNING		Main Thread	Someone set a noteskin  that doesn't exist.  Good job.
FileSink shutdown at: 09:33:38 398922
```

**Comment by Scraticus** [comment]
default is required as a subset of the way StepMania was built, you cannot sadly delete them and expect the game to run. We have yet to remove this dependency, so closing this for now as it's as the engine was designed back in 2002, and we cannot remove it unless we want to break 24 years of support for themes and suchlike.

**Comment by bonimy** [comment]
@Scraticus how about a better error message in the future then? Something for users who may not be aware of that fact.
