### ISSUE TITLE
[BUG] Default NoteSkin isn't really doing anything

### ISSUE THREAD

**Issue by KisanoWasTaken** [TeamRizu/OutFox#733]
### Is there an existing issue for this?

- [x] I have searched the existing issues and none matched.

### Operating System

Windows 10

### Storage

In the blue, but pretty full.

### Game Version

4.19.0

### Game Mode

dance

### Theme

First, Simply Love 4.9, then bare metal.

### Describe the problem

Currently, I have already set a default note skin for the game to abide by, but for some reason, it shows a completley different skin. At first, I thought it was Simply Love being quirky (please understand that 1. i've only just installed outfox 2. i've never themed or skinned before), but then, I started to realise that there was problem with the game itself.

### Describe what should happen

It should have given the same skin I gave it in Arcade Options
[ProjectOutfox.Crash.2024-05-04--19.04.06.log](https://github.com/TeamRizu/OutFox/files/15211543/ProjectOutfox.Crash.2024-05-04--19.04.06.log)
[ProjectOutfox.Crash.2024-05-04--19.12.13.log](https://github.com/TeamRizu/OutFox/files/15211544/ProjectOutfox.Crash.2024-05-04--19.12.13.log)
[ProjectOutfox.Crash.2024-05-05--02.36.36.log](https://github.com/TeamRizu/OutFox/files/15211545/ProjectOutfox.Crash.2024-05-05--02.36.36.log)
[ProjectOutfox.Crash.2024-05-05--03.01.24.log](https://github.com/TeamRizu/OutFox/files/15211546/ProjectOutfox.Crash.2024-05-05--03.01.24.log)
[ProjectOutfox.MainLog.2024-05-04--19.12.13.log](https://github.com/TeamRizu/OutFox/files/15211547/ProjectOutfox.MainLog.2024-05-04--19.12.13.log)
[ProjectOutfox.MainLog.2024-05-05--02.36.36.log](https://github.com/TeamRizu/OutFox/files/15211548/ProjectOutfox.MainLog.2024-05-05--02.36.36.log)
[ProjectOutfox.MainLog.2024-05-05--03.01.24.log](https://github.com/TeamRizu/OutFox/files/15211549/ProjectOutfox.MainLog.2024-05-05--03.01.24.log)
[ProjectOutfox.Network.2024-05-04--19.12.14.log](https://github.com/TeamRizu/OutFox/files/15211550/ProjectOutfox.Network.2024-05-04--19.12.14.log)
[ProjectOutfox.Network.2024-05-05--02.36.38.log](https://github.com/TeamRizu/OutFox/files/15211551/ProjectOutfox.Network.2024-05-05--02.36.38.log)
[ProjectOutfox.Network.2024-05-05--03.01.26.log](https://github.com/TeamRizu/OutFox/files/15211552/ProjectOutfox.Network.2024-05-05--03.01.26.log)
[ProjectOutfox-default.ThemeLua.2024-05-04--19.04.11.log](https://github.com/TeamRizu/OutFox/files/15211553/ProjectOutfox-default.ThemeLua.2024-05-04--19.04.11.log)
[ProjectOutfox-default.ThemeLua.2024-05-04--19.12.14.log](https://github.com/TeamRizu/OutFox/files/15211554/ProjectOutfox-default.ThemeLua.2024-05-04--19.12.14.log)
[ProjectOutfox-default.ThemeLua.2024-05-05--03.01.26.log](https://github.com/TeamRizu/OutFox/files/15211555/ProjectOutfox-default.ThemeLua.2024-05-05--03.01.26.log)
[info.txt](https://github.com/TeamRizu/OutFox/files/15211557/info.txt)
[ProjectOutfox.Crash.2024-04-27--21.00.45.log](https://github.com/TeamRizu/OutFox/files/15211558/ProjectOutfox.Crash.2024-04-27--21.00.45.log)

**Comment by Sudospective** [comment]
do you have a reference as to the noteskin you expect to see and what you actually see? im not sure anyone can help with this issue without a screenshot or something to go off of visually.

**Comment by KisanoWasTaken** [comment]
Nvm, I think the problem might have fixed itself (first time doing anything other than just playing random charts and making crappy ones). Gonna try and investigate further tho.

**Comment by KisanoWasTaken** [comment]
https://github.com/TeamRizu/OutFox/assets/166316583/d5880ffb-f27b-4e79-bfee-38fb63df576f

Here's some footage of me booting up the game again, if it might be of any use.
