### ISSUE TITLE
[Feature Request] Beatmania III (3) Gamemode

### ISSUE THREAD

**Issue by ChristopherEccleston2024** [TeamRizu/OutFox#735]
### Please Select the game mode your feature request is about.

be-mu

### Is your feature request related to a problem?

My Arcade recently don't have beatmania III (3) in Japan These days It's a rhythm game that it's inactive for a while ago in 2002
and certainly I don't have Photos To Show You

### Describe the solution you'd like

please consider making a game mode that mimics beatmania III (3)

**Comment by Jousway** [comment]
already added support 22 months ago
