### ISSUE TITLE
[Game Crash] Game crashes on startup, after loading songs and courses

### ISSUE THREAD

**Issue by Areldyb** [TeamRizu/OutFox#74]
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5081190/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5081191/log.txt)

Worth noting: This issue has existed in previous builds, but was intermittent (sometimes it would crash at this point, and sometimes it wouldn't and the game would run just fine). It may still be an intermittent issue, although this build of the game has crashed every time so far. The reason why it sometimes works is not clear to me.

**Comment by Scraticus** [comment]
Can you clear your cache (by deleting the contents of the /cache folder), and remove your preference.ini so the game can generate a new one?

Please post a new log when that is done, many thanks

**Comment by Areldyb** [comment]
[log-aftercacheclear.txt](https://github.com/TeamRizu/OutFox/files/5081296/log-aftercacheclear.txt)

Thanks, works now! Is this something I should expect to do if I run into this issue again?

**Comment by Scraticus** [comment]
Awesome. We have changed the cache since the last time you pushed an update, so this was invalid on this version. We will usually notify on the change log if there is a need to delete cache/preferences in future. Glad we could help!
