### ISSUE TITLE
[Game Crash] The Day The Music Died (Redux) - Simultaneous MP3 playback crashes Outfox

### ISSUE THREAD

**Issue by LightningSkunk** [TeamRizu/OutFox#75]
Version: 4.8.2pre21, 4.8.2

I am fairly certain that this is related to issue 71 that I could not reproduce a 3rd time in the way I experienced it for some reason. If the root cause is the same, I think this is a reliable way to reproduce the problem in a different way. 

I did confirm that Discord sounds are mp3!

How to Reproduce: 
- Toasties set to on AND are using Jousway Toasty (MP3)
- AND you have it set to NOT reset full combo after end of song
- AND you have FCd a song with more than 250 steps.
- Starting to play MP3 songs will reliably disappear crash the game (MP3 Toasty sound triggered at the same time as MP3 song play?).

Some examples:

Crash (MP3):
-Boing Boom Tsachk 
-1 2 Step (DDR Cut) (ZIV 2020 summer contest)
-Snow Storm (ZIV 2020 summer contest)
-(Aikyoku & Jubo) PARADOX (Rikei ga Koi ni Ochita no de Shoumei shitemita.) (Jubo)

No Crash (ogg):
-Hot Summer (ZIV 2020 summer contest)
-Red Sun (ZIV 2020 summer contest)

There is no crashlog.txt because Outfox just disappears.

[info.txt](https://github.com/TeamRizu/OutFox/files/5086347/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5086348/log.txt)

**Comment by LightningSkunk** [comment]
Still present in 4.8.2

[info.txt](https://github.com/TeamRizu/OutFox/files/5097333/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5097334/log.txt)

**Comment by Scraticus** [comment]
Fixed in 4.8.3
