### ISSUE TITLE
"I'm an Idiot." Well, so is the loader if it's not giving me any notes in return!

### ISSUE THREAD

**Issue by PCBoyGames** [TeamRizu/OutFox#76]
Mind not the weird title, but it did just that. There's a backstory to this one as well, not too unlike a few other issues I have made on GitHub over the years. It started earlier today when I extracted the files from Mungyodance 3 and ported them over from .md files to .sm format. When I loaded them up into 5.3, everything seemed normal at first, but it wouldn't be that way for too long. 

Some of my MGD series favorites were not properly playable. To name a few, I'm an Idiot, Plunging Hornets, and The Daeva Suite. [You can get them here.](https://drive.google.com/drive/folders/135WDWEI6pkIEI6yFWWzJLU6zTXOTMfVW?usp=sharing) Each of them had one thing in common when I looked: a single "empty" difficulty. However, I could load them into ArrowVortex no problem, and use of AV disproved the loader that while there are numbers of notes shown, the notes themselves actually do exist.

Here's my question to you: is there anything stopping the loader from certain charts?

**Comment by PCBoyGames** [comment]
Further investigation has proved the difficulty detection is possibly incorrect here. The chart is loaded as Hard. How does this happen, I have no possible idea other than the word Insane for the difficulty level name being detected wrongly for the simfiles. Changing this to a valid difficulty name (such as Edit) does make it work, but 5.3 loads a non-existing HD chart if I leave this as Insane. Perhaps a conflict with some other gamemode is causing this?

**Comment by JoseVarelaP** [comment]
From what I can tell, the game doesn't actually have any checks for these kinds of files, as SM simfiles are always following the Beginner, Easy, Medium, Hard, Challenge and Edit formats.

Still looking why is it picking Hard however, as there's no mention of "Insane" at all for a difficulty conversion in any of the NoteLoaders.

**Comment by Scraticus** [comment]
I think it's time to allow for more names / equivalents in this parser.

I have just had a chat with the pump folks and this is also not done correctly in piu either.

I think adding more difficulties so parsers can parse effectively may be the solution here.

**Comment by Scraticus** [comment]
Fixed in 4.8.3
