### ISSUE TITLE
[Game Crash] Crash at startup

### ISSUE THREAD

**Issue by connorpumilia** [TeamRizu/OutFox#77]
**Describe how it crashed by giving us those informations:**

1. What you were doing before it crashed and what action made the game to crash.
-just trying to start up the game. I've tried this with the past 5 versions of stepmania 5.3 that have come out and the game crashes at startup everytime. It has no problem loading the songs during the initialization window, but once it has finished loading the songs and tries to start the actual game it crashes.

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5104705/crashinfo.txt)

[log.txt](https://github.com/TeamRizu/OutFox/files/5104701/log.txt)

**Explain how we can reproduce the error**

1. Start the game
2. Game crashed

**Sreenshots/Videos**

If possible, take screenshots or record the crash happening.

**Additional information**
I am using windows 8.1 and not sure if this would be a software issue or anything on my end, as I was able to play the game yesterday morning normally with no issues

If there's any information that you think would help us.

**Comment by Scraticus** [comment]
The game is trying to use a card that is 'Microsoft Basic Video Adaptor' which is unsupported, due to it missing drivers. Can you confirm what GPU(s) you have for me please?

Cheers.

**Comment by connorpumilia** [comment]
I've been able to change the card the game was trying to use and now it works fine! Thank you for the push in the right direction
