### ISSUE TITLE
[Unexpected Behavior] Gamepad works in Firefox, but not in OutFox

### ISSUE THREAD

**Issue by omgitsraven** [TeamRizu/OutFox#79]
no pun intended ;)

**What you're using**

Outfox Alpha 4.8.2 20200819, on MacOS 10.15.6, on an Early 2014 MacBook Air
A PSX DDR mat, connected through a PSX -> USB adapter (of old and vague provenance; there's a logo that says "dragon" on it?)

I'm using an (admittedly rather old) PSX->USB adapter, but **when I visit https://gamepad-tester.com in Firefox on this same machine, all of the axes and buttons respond there perfectly**... but when I launch OutFox, none of the 'Input & Calibration' screens respond to it, including the 'Test Input' screen (which doesn't acknowledge that a gamepad is connected at all).

**Expected behavior**

The adapter can clearly communicate with the OS in a way that applications can correctly interpret as gamepad input, so I would expect OutFox to be able to as well

**Comment by omgitsraven** [comment]
I dug around a bit more, and found a mention of the "old joystick mapping" setting under "experimental settings" -- that fixes it for me!

I'll leave this issue open though, because I'm not sure whether that's going to remain an option going forward...

**Comment by Scraticus** [comment]
Thanks for your report!

I'm glad the other mode of input works for you!

**Comment by Scraticus** [comment]
Sorry for the delay in responding, we have been swamped a bit this past week.
