### ISSUE TITLE
Issue when loading external song folder

### ISSUE THREAD

**Issue by TheUnknownPerson** [TeamRizu/OutFox#8]
Hello, I'd like to report a crash issue when loading an external song folder other than the local one where StepMania 5.3 is installed. The crash log is the following:

StepMania5.3-git-c3092fe12d crash report (build c3092fe12d, 20200531 @ 20:47:04)
--------------------------------------

Crash reason: Unhandled Microsoft C++ Exception

Thread: main
        RageFileDriverDirectHelpers.cpp:229 D:/Juegos/StepMania 5.3 Outfox Alpha/Appearance/Themes/default/Other/*
        RageFileDriverDirectHelpers.cpp:229 D:/Juegos/StepMania 5.3 Outfox Alpha/Appearance/Themes/_fallback/Other/*
        RageFileDriverDirectHelpers.cpp:229 D:/Juegos/StepMania 5.3 Outfox Alpha/Data/Shaders/*
        RageFileDriverDirectHelpers.cpp:229 D:/Juegos/StepMania 5.3 Outfox Alpha/Data/Shaders/GLSL/*
        RageFileDriverDirectHelpers.cpp:229 D:/Juegos/StepMania 5.3 Outfox Alpha/Data/Shaders/*
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
778a4402: KERNELBASE!RaiseException [77790000+1143a0+62]
778a4402: KERNELBASE!RaiseException [77790000+1143a0+62]
01181ffa: StepMania!SDL_wcsstr [00b30000+4fb6a0+15695a]
011638d1: StepMania!SDL_wcsstr [00b30000+4fb6a0+138231]
011608ff: StepMania!SDL_wcsstr [00b30000+4fb6a0+13525f]
00ed30b1: StepMania!00b30000
55f883d3: ig9icd32!RegisterProcTableCallback [55cf0000+50fb0+247423]
00ed09ae: StepMania!00b30000
77c6ae8e: ntdll!RtlAllocateHeap [77c30000+3ae50+3e]
01186be5: StepMania!SDL_wcsstr [00b30000+4fb6a0+15b545]
00bbd08c: StepMania!00b30000
00ed4d65: StepMania!00b30000
01161fae: StepMania!SDL_wcsstr [00b30000+4fb6a0+13690e]
00bbec7a: StepMania!00b30000
00ed44a2: StepMania!00b30000
01170adb: StepMania!SDL_wcsstr [00b30000+4fb6a0+14543b]
00ed64d1: StepMania!00b30000
77c6b135: ntdll!RtlAllocateHeap [77c30000+3ae50+2e5]
7788f066: KERNELBASE!WaitForSingleObjectEx [77790000+fefb0+b6]
00eae76e: StepMania!00b30000
77c6ae8e: ntdll!RtlAllocateHeap [77c30000+3ae50+3e]
77c6ae8e: ntdll!RtlAllocateHeap [77c30000+3ae50+3e]
01186be5: StepMania!SDL_wcsstr [00b30000+4fb6a0+15b545]
00bbd08c: StepMania!00b30000
00ed351f: StepMania!00b30000
75574b9a: USER32!CallWindowProcW [75550000+244d0+6ca]
00d65475: StepMania!00b30000
77c6ae8e: ntdll!RtlAllocateHeap [77c30000+3ae50+3e]
77c6ae8e: ntdll!RtlAllocateHeap [77c30000+3ae50+3e]
77c6ae8e: ntdll!RtlAllocateHeap [77c30000+3ae50+3e]
01186be5: StepMania!SDL_wcsstr [00b30000+4fb6a0+15b545]
01161fae: StepMania!SDL_wcsstr [00b30000+4fb6a0+13690e]
00bbec7a: StepMania!00b30000
00ed72f1: StepMania!00b30000
00ecf746: StepMania!00b30000
00ecf782: StepMania!00b30000
00bc146a: StepMania!00b30000
75574b9a: USER32!CallWindowProcW [75550000+244d0+6ca]
01186b8f: StepMania!SDL_wcsstr [00b30000+4fb6a0+15b4ef]
00d6460c: StepMania!00b30000
00bc7873: StepMania!00b30000
77c6dcb6: ntdll!RtlFreeHeap [77c30000+3dc70+46]
77885263: KERNELBASE!LocalFree [77790000+f5210+53]
01195a95: StepMania!SDL_wcsstr [00b30000+4fb6a0+16a3f5]
011959e5: StepMania!SDL_wcsstr [00b30000+4fb6a0+16a345]
011632c9: StepMania!SDL_wcsstr [00b30000+4fb6a0+137c29]
77c97bf4: ntdll!RtlGetAppContainerNamedObjectPath [77c30000+67b40+b4]

Static log:
StepMania5.3-git-c3092fe12d
Compiled 20200531 @ 20:47:04 (build c3092fe12d)
Log starting 2020-06-11 12:18:12
Loading window: win32
Windows 10
Memory: 2047mb total, 4095mb swap (4095mb swap avail)
Video driver: Intel(R) HD Graphics 630 [Intel Corporation]
              26.20.100.7985, 3-9-2020 [PCI\VEN_8086&DEV_591B]
Drive: "WDC     WD10SPZX-21Z10T002.0" Driver: iaStorAC DMA: N/A
Drive: "NVMe    INTEL SSDPEKKW51004C" Driver: IaNVMe DMA: N/A
Sound device 0: Altavoces (Realtek High Definit, 10.0, MID 1, PID 100 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
WARNING: Main title or music file for '/AdditionalSongs/Braeden's Megapack v2/DIAVOLO/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/AdditionalSongs/Chilean Keyboard Megapack 3/(AMR) #56/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/AdditionalSongs/Touhou Gouyoukyou ~ Touhou Pad Pack/Wouldn't Cucumber-Flavored Beer Be Nice to Drink!_ - Everyone Can Know! This Technology Solves Every Problem -/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/AdditionalSongs/Touhou Kousaikai ~ Scarlet Festival Gathering/#Fairy_dancing_in_lake [CondorTalon]/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/AdditionalSongs/Touhou Kousaikai ~ Scarlet Festival Gathering/#FairyJoke [CondorTalon]/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/AdditionalSongs/Z-I-v Summer Contest 2018/[Starts with Vowels] - A Dumb Idea I Had When I Was Playing Mario Kart With Tim, and He Made Me Make It/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Video renderer list has been changed from 'opengl,glad' to 'glad,opengl,gles2'
Video renderers: 'glad,opengl,gles2'
Language: es
Current renderer: OpenGL
Theme: default

Partial log:
00:09.928: Renderer Found By SDL: opengles2
00:09.928: Renderer Found By SDL: software
00:10.289: Outfox SDL Reported Variables:
00:10.289: Outfox Engine: SDL compiled version: 2.0.12
00:10.289: Outfox Engine: SDL linked version: 2.0.12
00:10.289: Outfox Engine: GL_VENDOR   : Intel
00:10.289: Outfox Engine: GL_RENDERER : Intel(R) HD Graphics 630
00:10.289: Outfox Engine: GL_VERSION  : 4.6.0 - Build 26.20.100.7985
00:10.289: Outfox Engine: GLSL version: 4.60 - Build 26.20.100.7985
00:10.291: Compiling shader Data/Shaders/GLSL/Texture matrix scaling.vert

-- End of report

**Comment by moruzerinho6** [comment]
That happens everytime you load the game?

**Comment by moruzerinho6** [comment]
Ok, this issue is already know and a version with a fix will be coming this weekend.

**Comment by Scraticus** [comment]
This issue is fixed and will be pushed this weekend. Thanks for reporting!

**Comment by TheUnknownPerson** [comment]
Sorry for the late response. Yes, it happens everytime I load the game.

**Comment by Scraticus** [comment]
The new alpha will be out tomorrow, which will fix your issue, thanks for taking the time to follow up.

**Comment by moruzerinho6** [comment]
Hello @TheUnknownPerson. 

Project Moondance Discord Moderator here, a while ago we created a bug hunter system, users who make issue on this repository gain points and can be rewarded in our discord, so I'm here to ask, are you in Project Moondance discord?

If not, you can join using this link: https://discord.gg/3DgsbSg

If you don't wish to join, that's okay. Please be sure to contact any moderator if you join.
