### ISSUE TITLE
[Unexpected Behavior] MIDI input not functioning properly

### ISSUE THREAD

**Issue by Sudospective** [TeamRizu/OutFox#80]
**StepMania 5.3-git-09ae1e4e29**
20200819

Explain what function you're using and what arguments you're giving.

**Using MIDI input on "Test Input" screen:**
- MIDI note-on data
- MIDI CC data

Explain what you expected to happen or the function to return

**Expected Return:**
- Note-on and corresponding note-off received
- CC received

**Actual Return:**
- Note-on data received, no corresponding note-off for release
- No CC data receieved

**Additional Info:**
![image](https://user-images.githubusercontent.com/11000739/90945543-12c5e400-e3eb-11ea-9e11-8d42ca4833f4.png)

**Comment by Jousway** [comment]
this was fixed.
