### ISSUE TITLE
[Unexpected Behavior] Timing windows dont act as they should

### ISSUE THREAD

**Issue by neowzeo** [TeamRizu/OutFox#81]
**5.3 Alpha 4.6 Rc3**

i think that there are 2 bugs related with the timing.

the first one is that for example  i want to use ITG JudgeLVL 7 the usable timing stays like lvl 4 tbh i dont know why this happens but it seen that if I increase the Judge it just use the default value (lvl4) and not the one that its supposed to use.
![2020-08-23_000051](https://user-images.githubusercontent.com/70078691/90971380-4846fc00-e4d5-11ea-8865-3b738da24c1f.jpg)
ITG Judge lvl 7.

the second issue is that if I use an advance timing window like itg Advanced or ECFA the score dont goes from 0 to 100% but from 0 to 200% i dont know if that is intended but if i play any song on any advanced timing and save the score them i wont be able to compare it with a regular timing because the score and the ratings are diferent 

![2020-08-23_000440](https://user-images.githubusercontent.com/70078691/90971399-7d534e80-e4d5-11ea-9ea3-8563cf8b2db5.jpg)
![2020-08-23_000509](https://user-images.githubusercontent.com/70078691/90971401-7e847b80-e4d5-11ea-9245-e0ab803ae0f8.jpg)

i hope that you are able to understand what im trying to say since english is not my first language

**Comment by Scraticus** [comment]
Thanks for the report! 

We will look into the lua Error with the timing, and the 'extra' levels going to 200% is as designed. Sorry for the delay in responding

**Comment by JoseVarelaP** [comment]
The timing scaling was fixed on Alpha 4.8, so I would suggest upgrading to that version or above.

**Comment by Scraticus** [comment]
Fixed in 4.8.3
