### ISSUE TITLE
[Unexpected Behavior] InputHandler(event) callback doesn't provide realtime data

### ISSUE THREAD

**Issue by Sudospective** [TeamRizu/OutFox#82]
**Build Used**
OutFox Alpha 4.3-pre14

**Steps to Reproduce**
1. Create modfile with the following included:
```
local function InputHandler(event)
    if not event.PlayerNumber return end
    lua.ReportScriptError(tostring(event.DeviceInput.level))
end
```
2. Test modfile with analog input

**Expected Behavior**
Error log reports current, realtime analog input level.

**Actual Behavior**
Error log reports initial level, then reports level of 1 for repeat until input release.

Tested with Akai Professional MPD218 via MIDI input, observed sending realtime analog input level in ScreenTestInput.

**Comment by Sudospective** [comment]
This bug was revealed to me after receiving a test build that fixed issue #80 to correct MIDI behavior.

**Comment by Jousway** [comment]
we have added proper analog support in lua, I could add another .analoglevel to the input handler but I consider it unesseasry, also I wouldnt change the way .level works because it will break backward compatibility

**Comment by Sudospective** [comment]
Definitely important to keep compatibility, but I'm not partial to any specific implementation. having a `.analog` or similar key-value would work for me. Not sure my feedback on how it's implemented is completely necessary, but I'm glad I'm given the opportunity at giving my input.

**Comment by Scraticus** [comment]
Thanks for replying, we'll revisit midi when the linux driver is added.
