### ISSUE TITLE
[Feature Request] Add proper analog support

### ISSUE THREAD

**Issue by Sudospective** [TeamRizu/OutFox#83]
**Is your feature request related to a problem? Please describe.**

Currently, there is no analog support available in OutFox 4.8.2. With the release of TaroNuke's "Hardware Bullshit Tournament" providing support for pressure-sensitive input and button lighting output within gameplay, custom analog pads that support an input protocol only required for this specific modpack has indefinitely postponed its release.

**Describe the solution you'd like**

With proper analog support, ridding need of this custom protocol in favor for analog support for standard protocols like Xinput and MIDI would be a possibility, and could lead to the long-awaited release of this modpack.

**Describe alternatives you've considered**

Considered alternatives:
- Building custom pads to support the HBT input handler protocol
- Using a pipeline to simulate HBT input and output using MIDI

**Additional context**

I've been testing analog input extensively this past week. Full analog support seems to be halfway there.

**Comment by Jousway** [comment]
@Sudospective how would you like this to work, we already got values inside of sm for presssure sensetive pad and we worked on the midi stuff to make it work and it has sensetivity suppot, should I just pass it to a lua function that people can call with a float between 0.0 to 1.0?

**Comment by Sudospective** [comment]
Yeah, that sounds good. Having some sort of Lua function to grab the player's input sensitivity would work for me, and it might even be useful for other stuff along the road, whatever that may be.

**Comment by Scraticus** [comment]
Fixed in 4.9.1!
