### ISSUE TITLE
[Unexpected Behavior] Random Backgrounds option doesn't work the right way

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#84]
Using 4.8.2. I might have mistaken this before (probably) with songs that have BGChanges but I tested it again and it seemed like there wasn't a fix at all.

**Actual behaviour**

The option Random Backgrounds at Song Options now sets some sort of pattern with the same Backgrounds for any song that has the option.

**Expected behavior**

There shouldn't be a pattern. Any song with the option should have random backgrounds.

**Comment by Scraticus** [comment]
Fixed in 4.8.3!
