### ISSUE TITLE
[Game Crash] OutFox decode doesn't like mpeg formats. (Memory leak?)

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#85]
**How it crashed:**

1. Before the crash I was testing a feature that respawns many times videos, the format was mpeg.
2. [http://www.mediafire.com/file/nsyxhz5bly498ho/crashinfo.txt/file](url)

**Explain how we can reproduce the error**

1. Reload mpeg videos quickly.
3. Game crashed

**Screenshots/Videos**

https://i.imgur.com/Sx1nFHX.mp4

**Additional information**

Notice the stats on the video, the upper right corner. I don't know if it's a possible leak. Avi format increased the memory use too but less than mpeg.

**Comment by ListenerJubatus** [comment]
_Thank you for submitting a bug report, We will get back to you as soon as possible._

**Comment by MrThatKid** [comment]
Okay, looking at your log, it seems the warnings at the start are because your scripts appear to run before the Def. table is created (which is in `02 ActorDef.lua`)

Try having the folder named such that it would come after `02 ActorDef.lua`. (So, maybe have it start with `03` and not `_`?)

**Comment by EngineMachiner** [comment]
> Okay, looking at your log, it seems the warnings at the start are because your scripts appear to run before the Def. table is created (which is in `02 ActorDef.lua`)
> 
> Try having the folder named such that it would come after `02 ActorDef.lua`. (So, maybe have it start with `03` and not `_`?)

Rename the Scripts folder or the `02 ActorDef.lua` file? I didn't understand. Also shouldn't that appear on top with the errors before it crashes?

**Comment by MrThatKid** [comment]
Rename your `_editmode-tool` folder that's in `Scripts`.

Right now, I'm seeing if your crash is because of the script-related errors.

If that doesn't fix it, then I'd like you to upload the mpeg that causes that huge memory spike.

Oh, and sidenote, your links don't work. (They just redirect to `https://github.com/TeamRizu/OutFox/issues/url`)

**Comment by EngineMachiner** [comment]
> Rename your `_editmode-tool` folder that's in `Scripts`.
Did it. Nothing changed, same crash.
Here are some examples of the mpegs. http://www.mediafire.com/file/5uapybuzxklfy3i/RandomMovies.rar/file

> Oh, and sidenote, your links don't work. (They just redirect to `https://github.com/TeamRizu/OutFox/issues/url`)
Whoops. Sorry about the link. It should be ok now.

**Comment by MrThatKid** [comment]
Hm. Alright, we'll have to take a look at those mpeg files, then.

**Comment by Scraticus** [comment]
@EngineMachiner Can you do this behaviour on 5.1/5.0.12 and see what happens?

If you try to open 20 mpeg files on even a video player you are going to cause massive problems. 

If this does not crash 5.0.12, or 5.1, we will continue investigating it, as we have fixed 1 memory leak that _did_ occur in this code, but you shouldn't be trying to load this many at once, we are not a video player, so the process of initialisation is very different.

Let us know, thanks

**Comment by EngineMachiner** [comment]
> @EngineMachiner Can you do this behaviour on 5.1/5.0.12 and see what happens?
> 

https://i.imgur.com/uuxDJPE.mp4
Interesting, 5.1 won't crash. FPS are affected but not to the point of crash and it gets stable if it stops for a moment. Also I noticed that when it gets to the limit of the choices (first or last video in the OptionRow) it doesn't start blinking like in 5.3. 

> If you try to open 20 mpeg files on even a video player you are going to cause massive problems.
> 

I understand. Too many videos will be heavy. That's why I'm writing in my code something to hide or delete the videos if the scrolling gets going past a few seconds. But still with it, it goes to the crash.

**Comment by Scraticus** [comment]
We have found the cause of the issue and will plan how to solve it for Alpha 5. 

So far this seems to be only affecting mpg/mpeg files, and some early .mov encoded files. 

Thanks for taking the time to report this.

**Comment by EngineMachiner** [comment]
I tested position() for mpgs trying to compare with avis, and position() seems to be broken with mpgs only making available a few frames of the video while in avi format you can specify which frame. Not so sure about other video formats but that might be a hint for possible uncompatible formats.

**Comment by Scraticus** [comment]
Open a new request if seeking is wrong on the next alpha. 

This one behaves better now, there is still a small issue, but it's nothing that should crash the game anymore.
