### ISSUE TITLE
[Unexpected Behavior] Splash screen freezes - version 4.8.2

### ISSUE THREAD

**Issue by AngledLuffa** [TeamRizu/OutFox#87]
**What you're using**

If you click on the splash screen while it's loading a lot of songs, the screen freezes and the progress counter stops counting.

**Expected behavior**

Expected behavior is to be able to reposition the window without it freezing and for the counter to continue incrementing.  The game does eventually load even though it is frozen, so it is still processing in the background.

**Comment by AngledLuffa** [comment]
This is on Windows 10

**Comment by Scraticus** [comment]
I'm just having our Alpha testers check this is fixed, but it will be done for 4.8.3

**Comment by Scraticus** [comment]
This is fixed in the upcoming 4.8.3. Thanks for reporting!
