### ISSUE TITLE
[Game Crash] Too many open files

### ISSUE THREAD

**Issue by Level99OCR** [TeamRizu/OutFox#92]
**Describe how it crashed by giving us those informations:**

1. Just loaded the game up for the second time after a clean install. First run was with default files (no additional songs). Second run, when it crashes, is after I moved my song library into the directory.
2. No crashlog generated.
3. 
[info.txt](https://github.com/TeamRizu/OutFox/files/5150012/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5150013/log.txt)

**Explain how we can reproduce the error**

1. Start the game

**Sreenshots/Videos**

![image](https://user-images.githubusercontent.com/6171738/91715434-a5892000-eb5b-11ea-8858-268600932fba.png)

**Additional information**

I have an extremely large song library. It opens fine in Stepmania 5.1 Beta 2 (after disabling all image caches), it loads fine in my own compiled from source Stepmania 64-bit from the git, and it also loads fine in the latest release of Etterna. Typically if it were an error with the 32-bit limitations I would have seen the ram reach the 1.8gb range, however this fatal error happened before it got to 1gb of ram usage, so I am doubtful a 64-bit executable would be the remedy here.

**Comment by Scraticus** [comment]
We have been investigating this bug, thanks for reporting it. It's due to things not closing correctly with the 'unicodedoupper' function. We have almost fixed it in our current pre-alpha, so I'm hoping it will be omitted completely for 4.8.3 which will be out this weekend.

**Comment by Scraticus** [comment]
Fixed in alpha 4.8.3
