### ISSUE TITLE
[Unexpected Behavior] Character's bones are broken

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#94]
Using 4.8.2.

**What you're using**

Using any kind of character. Characters bones go crazy. And can make the game crash if they try to load the dancepad.
https://i.imgur.com/1iJsT0e.png

**Expected behavior**

Normal bones and no dancepad crash.

**Comment by ListenerJubatus** [comment]
Thanks for the bug report; that definitely _does not_ look right.

@JoseVarelaP

**Comment by JoseVarelaP** [comment]
Fixed for 4.8.5.
