### ISSUE TITLE
[Feature Request] OptionRow change of choice externally.

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#96]
**Is your feature request related to a problem? Please describe.**

Context...
I made a previewer for RandomMovies and coded BGAnimations at ScreenMiniMenuBackgroundChange and ScreenEdit.
This way there's no need to play each time you edit a BGChange, making it faster and easier to see when creating step charts with custom backgrounds.

I want to access the OptionRow at ScreenMiniMenuBackgroundChange and change/force the choice externally.

**Describe the solution you'd like**

Maybe a function that changes the choice of the OptionRow only when the value (the input or variable) in the function exists in the choices table and are the same.

**Describe alternatives you've considered**

I'm not sure. I made a search feature to look up RandomMovies and BGAnimations but can't tell how else to push these to the ScreenEdit.

**Additional context**

https://github.com/EngineMachiner/BGA-RM-Tool
Search box can appear with Ctrl at ScreenMiniMenuBackgroundChange.

**Comment by JoseVarelaP** [comment]
Added a function for 4.8.3, can confirm it works but needs external testing.

**Comment by JoseVarelaP** [comment]
Finished testing, and it is now fully functional!
