### ISSUE TITLE
[Game Crash] when taking screenshot in borderless full screen

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#99]
**Describe how it crashed by giving us those informations:**

1. What you were doing before it crashed and what action made the game to crash.
2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
3. Upload the info.txt and log.txt (GameFolder/Logs)

**Explain how we can reproduce the error**

1. Start the game
2. Press Print Screen (or Shift + Print Screen) to take a screenshot
3. Game crashed

**Screenshots/Videos**

None, because it crashed before I could take one.
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5198803/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5198808/log.txt)
[info.txt](https://github.com/TeamRizu/OutFox/files/5198809/info.txt)

**Comment by Scraticus** [comment]
This is a debug assert from a test build, and is fixed in 4.8.3. The message command was being copied incorrectly and it triggered a bad opengl call.
